// Advanced Interaction Analytics — sourced from Advanced_Analytics_Matrix.xlsx
// 52 vendors | 7 scoring dimensions | Score out of 42 | 6 platform categories
// Scale: High=6, Med-High=5, Med=4, Low-Med=3, Low=2

const S = { "High": 6, "Med-High": 5, "Med": 4, "Low-Med": 3, "Low": 2, "Low*": 2 };

export const analyticsVendors = [
  // ═══ A: CCaaS PLATFORMS ═══
  { name: "NICE CXone", slug: "nice-analytics", score: 39, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 6, autoQA: 6, opsWF: 5, wfm: 6, prodIns: 4, intData: 6, scaleGov: 6, summary: "The analytics benchmark. Strongest combined interaction analytics, auto-QA, and WEM alignment in the CCaaS market. Enlighten AI sets the standard for automated quality evaluation." },
  { name: "Genesys Cloud CX", slug: "genesys-analytics", score: 38, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 5, autoQA: 4, opsWF: 6, wfm: 6, prodIns: 4, intData: 6, scaleGov: 6, summary: "Strongest operational workflow score in the entire matrix. Deep WFM alignment and integration depth. Auto-QA trails NICE but overall analytics breadth is elite." },
  { name: "Five9", slug: "five9-analytics", score: 30, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 4, autoQA: 4, opsWF: 4, wfm: 4, prodIns: 3, intData: 6, scaleGov: 6, summary: "Solid mid-tier analytics within the CCaaS category. Strong integration and scalability, but intelligence and auto-QA depth lag the top two leaders." },
  { name: "Talkdesk", slug: "talkdesk-analytics", score: 30, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 4, autoQA: 4, opsWF: 4, wfm: 4, prodIns: 3, intData: 4, scaleGov: 6, summary: "Analytics capability is growing but integration depth trails Five9 and the top-tier leaders. Scalability and governance are strong." },
  { name: "Amazon Connect", slug: "connect-analytics", score: 28, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 4, autoQA: 3, opsWF: 3, wfm: 6, prodIns: 2, intData: 6, scaleGov: 6, summary: "Strong WFM alignment and integration depth through AWS services (Contact Lens). Weak in product insights and auto-QA — analytics requires custom build." },
  { name: "Cisco Webex CC", slug: "cisco-analytics", score: 24, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 4, autoQA: 2, opsWF: 3, wfm: 4, prodIns: 2, intData: 4, scaleGov: 6, summary: "Scalability is strong but analytics depth is limited. Auto-QA and product insights are weak. Enterprise governance compensates." },
  { name: "Avaya Experience Platform", slug: "avaya-analytics", score: 21, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 3, autoQA: 2, opsWF: 2, wfm: 4, prodIns: 2, intData: 4, scaleGov: 6, summary: "Legacy analytics capability. WFM alignment and governance are adequate but intelligence, auto-QA, and operational workflow are weak." },
  { name: "Zoom Contact Center", slug: "zoom-analytics", score: 18, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 3, autoQA: 2, opsWF: 3, wfm: 2, prodIns: 2, intData: 4, scaleGov: 4, summary: "Early-stage analytics. WFM alignment and product insights are minimal. Growing but significant gaps remain versus established analytics leaders." },
  { name: "RingCentral CC", slug: "ringcentral-analytics", score: 18, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 4, autoQA: 3, opsWF: 2, wfm: 2, prodIns: 2, intData: 4, scaleGov: 4, summary: "Basic analytics with some intelligence capability. Operational workflow, WFM alignment, and product insights are weak." },
  { name: "Vonage CC", slug: "vonage-analytics", score: 16, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 4, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 2, intData: 4, scaleGov: 4, summary: "Minimal analytics depth. Some intelligence capability through communications APIs but lacks substance across most dimensions." },
  { name: "Mitel / Unify", slug: "mitel-analytics", score: 14, cat: "A", catLabel: "CCaaS Platforms", segment: "CCaaS", intel: 2, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 2, intData: 4, scaleGov: 6, summary: "Legacy analytics with minimal modern capability. Governance and scalability from enterprise heritage, but analytics substance is absent." },

  // ═══ B: AI-NATIVE INTERACTION ANALYTICS ═══
  { name: "CallMiner", slug: "callminer-analytics", score: 38, cat: "B", catLabel: "AI-Native Analytics", segment: "AI-Native", intel: 6, autoQA: 5, opsWF: 4, wfm: 4, prodIns: 6, intData: 6, scaleGov: 6, summary: "The strongest product insights score in the entire matrix (6/6). Deep interaction analytics with broad enterprise integration. The benchmark for conversation mining and topic analysis." },
  { name: "Observe.AI", slug: "observeai-analytics", score: 37, cat: "B", catLabel: "AI-Native Analytics", segment: "AI-Native", intel: 6, autoQA: 6, opsWF: 6, wfm: 4, prodIns: 4, intData: 6, scaleGov: 5, summary: "Tied with Level AI for the strongest auto-QA and operational workflow combination in the AI-native segment. Hybrid LLM + ASR stack purpose-built for CX." },
  { name: "Level AI", slug: "levelai-analytics", score: 37, cat: "B", catLabel: "AI-Native Analytics", segment: "AI-Native", intel: 6, autoQA: 6, opsWF: 6, wfm: 4, prodIns: 4, intData: 6, scaleGov: 5, summary: "The most accurate subjective QA scoring in the market. Excels at coachability insights, outlier detection, and automated quality evaluation at scale." },
  { name: "Verint Speech Analytics", slug: "verint-analytics", score: 36, cat: "B", catLabel: "AI-Native Analytics", segment: "AI-Native", intel: 6, autoQA: 4, opsWF: 4, wfm: 6, prodIns: 4, intData: 6, scaleGov: 6, summary: "The strongest WFM alignment in the AI-native segment (tied at 6/6). Deep enterprise scale and governance. Auto-QA depth trails Observe.AI and Level AI." },
  { name: "Cresta", slug: "cresta-analytics", score: 34, cat: "B", catLabel: "AI-Native Analytics", segment: "AI-Native", intel: 6, autoQA: 4, opsWF: 6, wfm: 4, prodIns: 4, intData: 5, scaleGov: 4, summary: "Real-time behavioral AI with live guidance. Strong in operational workflow and coaching-driven analytics. Integration depth is growing." },
  { name: "ASAPP", slug: "asapp-analytics", score: 33, cat: "B", catLabel: "AI-Native Analytics", segment: "AI-Native", intel: 6, autoQA: 4, opsWF: 6, wfm: 4, prodIns: 4, intData: 4, scaleGov: 4, summary: "Strong intelligence and operational workflow depth. Scalability and integration are mid-tier. Growing enterprise presence." },
  { name: "Kore.ai", slug: "koreai-analytics", score: 33, cat: "B", catLabel: "AI-Native Analytics", segment: "Conversational AI", intel: 5, autoQA: 4, opsWF: 4, wfm: 4, prodIns: 5, intData: 5, scaleGov: 5, summary: "Analytics capabilities embedded in the broader conversational AI platform. Balanced scores across all dimensions — strongest product insights in the AI-native tier." },
  { name: "Uniphore", slug: "uniphore-analytics", score: 29, cat: "B", catLabel: "AI-Native Analytics", segment: "AI-Native", intel: 6, autoQA: 4, opsWF: 6, wfm: 3, prodIns: 3, intData: 4, scaleGov: 4, summary: "Acoustic emotion detection and agent soft-skill coaching. Strong intelligence and workflow, but WFM alignment and product insights lag." },
  { name: "Balto", slug: "balto-analytics", score: 28, cat: "B", catLabel: "AI-Native Analytics", segment: "AI-Native", intel: 4, autoQA: 2, opsWF: 6, wfm: 2, prodIns: 2, intData: 4, scaleGov: 4, summary: "Real-time guidance specialist with strong operational workflow score. Analytics depth outside of live guidance is limited." },
  { name: "Gong", slug: "gong-analytics", score: 26, cat: "B", catLabel: "AI-Native Analytics", segment: "Revenue Intelligence", intel: 6, autoQA: 2, opsWF: 4, wfm: 2, prodIns: 4, intData: 4, scaleGov: 6, summary: "Revenue intelligence leader with strong conversation analytics for sales. Limited relevance for service-center analytics and QA workflows." },

  // ═══ C: WEM / QA / QM PLATFORMS ═══
  { name: "Verint WFO", slug: "verint-wfo", score: 35, cat: "C", catLabel: "WEM / QA / QM", segment: "WEM/QM", intel: 5, autoQA: 4, opsWF: 4, wfm: 6, prodIns: 3, intData: 6, scaleGov: 6, summary: "Enterprise WFO suite with deep WFM alignment and integration. Analytics are embedded within the broader workforce optimization platform." },
  { name: "NICE WEM", slug: "nice-wem", score: 35, cat: "C", catLabel: "WEM / QA / QM", segment: "WEM/QM", intel: 5, autoQA: 4, opsWF: 4, wfm: 6, prodIns: 2, intData: 6, scaleGov: 6, summary: "Analytics capabilities within the WEM suite. Strong WFM and integration depth. Product insights are limited compared to the standalone CXone analytics offering." },
  { name: "Calabrio", slug: "calabrio-analytics", score: 28, cat: "C", catLabel: "WEM / QA / QM", segment: "WEM/QM", intel: 4, autoQA: 4, opsWF: 4, wfm: 6, prodIns: 2, intData: 4, scaleGov: 6, summary: "WEM-embedded analytics with the strongest WFM alignment in its class. Intelligence and integration depth trail the top WEM players." },
  { name: "Playvox", slug: "playvox-analytics", score: 26, cat: "C", catLabel: "WEM / QA / QM", segment: "WEM/QM", intel: 4, autoQA: 4, opsWF: 4, wfm: 4, prodIns: 2, intData: 4, scaleGov: 6, summary: "QA and workforce analytics for mid-market. Solid governance and scalability but intelligence and product insights are limited." },

  // ═══ D: LLM / SPEECH / AI INFRASTRUCTURE ═══
  { name: "OpenAI (Whisper + LLM)", slug: "openai-analytics", score: 22, cat: "D", catLabel: "LLM / Speech / AI Infra", segment: "LLM Infra", intel: 6, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 2, intData: 6, scaleGov: 6, summary: "Foundational AI infrastructure. Intelligence and integration are strong, but analytics application requires custom build. These are building blocks — the analytics layer sits above them." },
  { name: "Anthropic Claude", slug: "claude-analytics", score: 22, cat: "D", catLabel: "LLM / Speech / AI Infra", segment: "LLM Infra", intel: 6, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 2, intData: 6, scaleGov: 6, summary: "LLM infrastructure with strong reasoning capability. Relevant as an analytics engine layer but requires application-level tooling for CX analytics use cases." },
  { name: "Deepgram", slug: "deepgram-analytics", score: 22, cat: "D", catLabel: "LLM / Speech / AI Infra", segment: "Speech AI", intel: 6, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 2, intData: 6, scaleGov: 6, summary: "Speech-to-text infrastructure with enterprise-grade accuracy and speed. Building block for analytics applications, strong API and integration posture." },
  { name: "AssemblyAI", slug: "assemblyai-analytics", score: 22, cat: "D", catLabel: "LLM / Speech / AI Infra", segment: "Speech AI", intel: 6, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 2, intData: 6, scaleGov: 6, summary: "Speech AI platform with strong transcription accuracy. Similar positioning to Deepgram — infrastructure for analytics applications, strong API layer." },
  { name: "Google Speech + Vertex", slug: "google-analytics", score: 20, cat: "D", catLabel: "LLM / Speech / AI Infra", segment: "Cloud AI", intel: 5, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 2, intData: 6, scaleGov: 6, summary: "Google Cloud speech and AI services. Enterprise-grade infrastructure with strong governance. Application-level analytics requires partner or custom build." },
  { name: "AWS Transcribe + Bedrock", slug: "aws-analytics", score: 20, cat: "D", catLabel: "LLM / Speech / AI Infra", segment: "Cloud AI", intel: 5, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 2, intData: 6, scaleGov: 6, summary: "AWS speech and AI services integrated with Connect and the broader AWS ecosystem. Strong for builder-led analytics architectures." },
  { name: "Azure Cognitive + OpenAI", slug: "azure-analytics", score: 20, cat: "D", catLabel: "LLM / Speech / AI Infra", segment: "Cloud AI", intel: 5, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 2, intData: 6, scaleGov: 6, summary: "Microsoft Azure AI services with OpenAI integration. Relevant for Microsoft-standardized enterprises building custom analytics layers." },

  // ═══ E: AGENT ASSIST / KNOWLEDGE AI ═══
  { name: "Forethought", slug: "forethought-analytics", score: 29, cat: "E", catLabel: "Agent Assist / Knowledge AI", segment: "Agent Assist", intel: 4, autoQA: 2, opsWF: 4, wfm: 2, prodIns: 4, intData: 4, scaleGov: 4, summary: "Support automation with embedded analytics. Useful for ticket resolution insights and knowledge gap identification. Limited QA and WFM depth." },
  { name: "Ada", slug: "ada-analytics", score: 29, cat: "E", catLabel: "Agent Assist / Knowledge AI", segment: "Agent Assist", intel: 4, autoQA: 2, opsWF: 4, wfm: 2, prodIns: 4, intData: 4, scaleGov: 4, summary: "Digital-first support automation with conversation analytics. Strong for containment insights. Limited voice analytics and workforce alignment." },
  { name: "Zendesk AI", slug: "zendesk-analytics", score: 29, cat: "E", catLabel: "Agent Assist / Knowledge AI", segment: "Agent Assist", intel: 4, autoQA: 2, opsWF: 4, wfm: 2, prodIns: 4, intData: 4, scaleGov: 6, summary: "AI-enhanced support analytics embedded in the Zendesk platform. Strongest governance score in the Agent Assist segment. Limited depth in QA and WFM." },
  { name: "Salesforce Einstein CI", slug: "einstein-analytics", score: 29, cat: "E", catLabel: "Agent Assist / Knowledge AI", segment: "CRM AI", intel: 4, autoQA: 2, opsWF: 4, wfm: 2, prodIns: 5, intData: 6, scaleGov: 6, summary: "CRM-embedded conversation intelligence. Strongest integration and governance scores in segment. Limited auto-QA depth but strong product insights through CRM data." },

  // ═══ F: PRODUCT & JOURNEY ANALYTICS ═══
  { name: "FullStory", slug: "fullstory-analytics", score: 32, cat: "F", catLabel: "Product & Journey Analytics", segment: "Product Analytics", intel: 5, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 6, intData: 4, scaleGov: 6, summary: "Digital experience analytics with session replay and journey analysis. The strongest product insights capability in this segment. Adjacent to CX analytics rather than core interaction analytics." },
  { name: "Glassbox", slug: "glassbox-analytics", score: 32, cat: "F", catLabel: "Product & Journey Analytics", segment: "Product Analytics", intel: 5, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 6, intData: 5, scaleGov: 6, summary: "Digital experience intelligence with strong session capture and journey analytics. Stronger integration depth than FullStory. Useful as CX journey layer alongside core interaction analytics." },
  { name: "Pendo", slug: "pendo-analytics", score: 31, cat: "F", catLabel: "Product & Journey Analytics", segment: "Product Analytics", intel: 4, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 6, intData: 4, scaleGov: 6, summary: "Product analytics and in-app guidance platform. Strong product insights but limited CX interaction analytics depth. Useful for digital self-service journey analysis." },
  { name: "Heap", slug: "heap-analytics", score: 31, cat: "F", catLabel: "Product & Journey Analytics", segment: "Product Analytics", intel: 4, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 6, intData: 4, scaleGov: 6, summary: "Auto-capture digital analytics. Strong product insights for web and app journeys. Limited relevance for voice or contact center interaction analytics." },
  { name: "Amplitude", slug: "amplitude-analytics", score: 31, cat: "F", catLabel: "Product & Journey Analytics", segment: "Product Analytics", intel: 4, autoQA: 2, opsWF: 2, wfm: 2, prodIns: 6, intData: 4, scaleGov: 6, summary: "Digital analytics platform with strong product insights and experimentation capability. Strongest in digital product analytics, adjacent to core CX interaction analytics." },
];

export const getAllAnalytics = () => analyticsVendors;
export const getAnalyticsByCategory = (cat) => analyticsVendors.filter(v => v.cat === cat);

export const analyticsCats = [
  { id: "A", name: "CCaaS Platforms", color: "#0088DD", desc: "Interaction analytics embedded within full-suite CCaaS platforms. Depth varies dramatically — from NICE's best-in-class Enlighten to basic reporting." },
  { id: "B", name: "AI-Native Interaction Analytics", color: "#10B981", desc: "Purpose-built analytics platforms focused on conversation intelligence, auto-QA, and operational insights. The deepest analytics capabilities in the market." },
  { id: "C", name: "WEM / QA / QM Platforms", color: "#F59E0B", desc: "Analytics embedded within workforce engagement and quality management suites. Strong WFM alignment, variable analytics depth." },
  { id: "D", name: "LLM / Speech / AI Infrastructure", color: "#7C3AED", desc: "Foundational AI and speech services. These are building blocks for analytics applications — strong intelligence and integration, but require custom application-level tooling." },
  { id: "E", name: "Agent Assist / Knowledge AI", color: "#EC4899", desc: "Analytics capabilities embedded in agent assist and knowledge platforms. Useful for containment and resolution insights, limited QA and workforce depth." },
  { id: "F", name: "Product & Journey Analytics", color: "#14B8A6", desc: "Digital experience and product analytics platforms. Strong product insights for web/app journeys, adjacent to core CX interaction analytics." },
];

export const analyticsDimensions = [
  { abbr: "INT", name: "Intelligence", desc: "Depth of speech/text analytics, NLU, sentiment, topic modeling, and conversation understanding." },
  { abbr: "AQA", name: "Auto-QA", desc: "Automated quality evaluation, compliance scoring, and behavioral assessment at scale." },
  { abbr: "OPS", name: "Ops Workflow", desc: "Integration with operational workflows — coaching, alerts, escalation triggers, and action-oriented analytics." },
  { abbr: "WFM", name: "WFM Alignment", desc: "Connection to workforce management — forecasting inputs, schedule optimization, and capacity planning analytics." },
  { abbr: "PRD", name: "Product Insights", desc: "Ability to surface product, journey, and experience-level insights from interaction data." },
  { abbr: "IDT", name: "Integration / Data", desc: "Data accessibility, API depth, warehouse connectivity, and ecosystem integration maturity." },
  { abbr: "SGV", name: "Scale / Governance", desc: "Enterprise scalability, data governance, security, compliance, and multi-region capability." },
];
