export const educationSubVerticals = {
  "undergrad-admissions": {
    name: "Undergraduate Admissions & Enrollment", parent: "Education",
    tagline: "Inquiry management, application support, yield campaigns, and enrollment onboarding.",
    intro: "Admissions contact centers sit inside the enrollment funnel. Every stage, from inquiry to application to admit to deposit, loses a share of prospects, and response speed at each handoff moves yield. The operating challenge is working that funnel as a revenue system: fast first response, clean handoffs to counselors, and outreach timed to the decisions students are actually making.",
    kpis: [
      { metric: "AHT", avg: "[[edu.sv.undergrad-admissions.aht]]", note: "Inquiry calls are short; application help runs longer" },
      { metric: "FCR", avg: "[[edu.sv.undergrad-admissions.fcr]]", note: "Driven by how often an admissions question needs a counselor or another office" },
      { metric: "Speed to Lead", avg: "[[edu.sv.undergrad-admissions.lead]]", note: "Driven by inquiry routing and counselor coverage; measure time from inquiry to first live contact" },
      { metric: "Yield Rate", avg: "[[edu.sv.undergrad-admissions.yield]]", note: "Share of admitted students who enroll; driven by aid offers, visits and outreach during yield season" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Inquiry-to-enrollment funnel analytics by source, program, and demographic","Speed-to-lead tracking measuring first contact time for new inquiries","Yield campaign effectiveness: which outreach drives deposits","Application completion rate analytics identifying abandonment points","Competitive loss analysis: where admitted students chose to enroll instead"], vendors: "Slate, Salesforce Education, EAB, NICE", risk: "Admitted students melting (choosing another school) without understanding why",
        stack: [{ name: "Slate (Technolutions)", role: "Admissions CRM", why: "Admissions CRM. Inquiry tracking, application management, communication workflows, and yield analytics. The platform that measures whether the contact center is converting inquiries to enrolled students.", href: "/vendors" }, { name: "EAB", role: "Enrollment Intelligence", why: "Predictive enrollment analytics and student success. Identifies which admitted students are most likely to melt and which interventions prevent it.", href: "/vendors" }],
        pitfall: "Many admissions offices count inquiries and applications without measuring what the contact center adds to conversion. If the contact center handles a large share of the conversations between inquiry and application, it owns a matching share of the conversion result. Build attribution that connects contact center interactions to enrollment outcomes, not just satisfaction scores."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Inquiry source routing: web, college fair, campus visit, referral","Admitted student priority routing during yield season","Geographic routing matching prospective students to regional counselors","Transfer student routing to specialized transfer advisors","Parent routing separating parent inquiries from student inquiries"], vendors: "NICE CXone, Five9, 8x8", risk: "Admitted student calling during yield season reaching voicemail",
        stack: [{ name: "Five9", role: "CCaaS", why: "Blended inbound/outbound for admissions. Inbound inquiry handling combined with outbound yield campaigns. Salesforce integration for institutions using Education Cloud. Sized for small and mid-size admissions teams.", href: "/vendors/five9" }],
        pitfall: "Yield season, the weeks before your deposit deadline, decides the entering class. An admitted student who calls then is usually weighing you against another school, and one who reaches voicemail may call the other school next. Size yield season staffing from last year's yield-season volume, not an average month, and route admitted students to experienced counselors."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Personalized yield communications via email, text, and phone","Virtual campus tour scheduling and follow-up","Application checklist notifications with missing document alerts","Admitted student portal with financial aid, housing, and orientation links","Parent communication channel with FERPA-appropriate information"], vendors: "Slate, Salesforce, EAB, Mongoose", risk: "Yield communications feeling generic instead of personalized to the student's interests",
        stack: [{ name: "Slate", role: "Communications Hub", why: "Automated communication workflows triggered by funnel stage: inquiry acknowledgment, application receipt, missing documents, admission notification, yield outreach, and enrollment confirmation. The orchestration layer for the entire admissions lifecycle.", href: "/vendors" }, { name: "Mongoose (Cadence)", role: "Student Texting", why: "Two-way texting for admissions outreach, a channel many students answer sooner than email. Built with opt-in/opt-out management.", href: "/vendors" }],
        pitfall: "Yield messages need more than a first name in the greeting. An admitted student interested in marine biology learns little from a generic congratulations; a note about the marine biology lab and how first-year students join its research speaks to the reason they applied. Connect the interests captured in the CRM to the content of each message."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Application status bots with checklist and missing document alerts","Campus visit scheduling bots with calendar integration","Financial aid estimator bots providing preliminary aid calculations","Program and major exploration bots based on student interests","FAQ bots covering deadlines, requirements, and campus life"], vendors: "Ocelot (Anthology), Ada, Ivy.ai", risk: "Bot providing incorrect deadline that causes a student to miss application",
        stack: [{ name: "Ocelot (Anthology)", role: "Education AI", why: "Purpose-built for higher education. Pre-trained on admissions, financial aid, and student services intents. Integrates with Ellucian Banner and Colleague SIS. Trained on the vocabulary of admissions and financial aid.", href: "/vendors/iva" }],
        pitfall: "Admissions bots must handle parents and students differently. Once a student attends a college, FERPA rights belong to the student, not the parents ([[edu.ferpa.eligible]]); a parent may see records without the student's consent only under an exception, such as the student being a tax dependent, which the institution may use but need not ([[edu.ferpa.dependent]]). Many institutions set the same rule for applicants by policy. Build a check of the student's consent, or of your institution's documented exception, into every bot flow that reads student records."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FERPA compliance for prospective and admitted student records","Clery Act disclosure of campus safety statistics","ADA/Section 504 accessibility for admissions communications","TCPA compliance for outbound recruitment texts and calls","NCAA compliance for athletic recruitment communications"], vendors: "FERPA compliance, Clery Act, institutional policy", risk: "Sharing application status with a parent without FERPA authorization",
        stack: [{ name: "Institutional compliance", role: "FERPA & Title IX", why: "FERPA covers the records of a person who is or has been in attendance at the institution ([[edu.ferpa.student]]), so an applicant who never enrolls has no FERPA rights in the admissions file. Many institutions protect applicant records by policy anyway. Agents should verify identity and the student's consent before sharing application information with parents or third parties.", href: "/vendors" }],
        pitfall: "FERPA protects a student's records once the student is in attendance; admissions records of a person who has not yet attended fall to institutional policy and state privacy law. Write down what may be shared with parents during the application process and after enrollment, and train agents on both. A simple rule for agents: confirm the student's consent before sharing information with anyone other than the student."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Inquiry capture and assignment workflow from all sources","Application review and decision workflow with committee coordination","Yield outreach workflow with multi-touch, multi-channel campaigns","Enrollment deposit and intent-to-enroll processing","New student onboarding workflow: orientation, housing, advising, registration"], vendors: "Slate, Salesforce Education Cloud, Ellucian", risk: "Application review bottleneck creating late decisions that lose students to faster schools",
        stack: [{ name: "Slate", role: "Admissions Workflow", why: "End-to-end admissions workflow: inquiry capture, application processing, document management, committee review, decision release, and yield management. The operational core of the admissions office.", href: "/vendors" }],
        pitfall: "Decision timing shapes yield. A student still waiting on your decision may already be holding an offer, an aid package and a housing deadline from a faster school. Streamline committee review, use rolling admission where it fits, and tell applicants when to expect a decision."
      },
      { layer: 1, name: "Data Access", capabilities: ["Admissions CRM: inquiries, applications, decisions, and enrollment status","SIS: enrollment records, academic history (for transfers), and demographics","Financial aid system: FAFSA data, aid packages, and acceptance status","Housing and orientation systems for enrolled student onboarding","External data: College Board, ACT, clearinghouse, and high school profiles"], vendors: "Slate, Ellucian Banner/Colleague, PeopleSoft, Workday Student", risk: "Admissions CRM and SIS containing duplicate student records with conflicting data",
        stack: [{ name: "Slate", role: "Admissions CRM Data", why: "Inquiry history, application status, communication log, and yield campaign data. The source of truth for every admissions interaction.", href: "/vendors" }, { name: "Ellucian Banner/Colleague", role: "SIS", why: "Student Information System: the institutional record of enrollment, academic history, and financial aid. Admissions data must flow cleanly from Slate into Banner/Colleague at enrollment.", href: "/vendors" }],
        pitfall: "The handoff from the admissions CRM to the SIS at enrollment is one of the most data-critical transitions in education CX. If the student's name, ID, financial aid, and housing data don't transfer accurately from the admissions CRM to the SIS, the student starts their college career with incorrect records: wrong financial aid package, wrong housing assignment, wrong advisor. Test the data handoff for every enrolled student before orientation."
      },
    ],
  },

  "graduate-programs": {
    name: "Graduate & Professional Programs", parent: "Education",
    tagline: "Program inquiries, application guidance, cohort management, and career-focused advising.",
    intro: "Graduate program contact centers serve working adults making tuition decisions that can run to six figures. These prospects weigh return on investment, career outcomes, faculty credentials and program flexibility ahead of campus culture. The CX challenge is giving consultative, high-touch support to informed buyers who are comparing several programs at once.",
    kpis: [
      { metric: "AHT", avg: "[[edu.sv.graduate-programs.aht]]", note: "Driven by career-focused conversations and program comparison" },
      { metric: "FCR", avg: "[[edu.sv.graduate-programs.fcr]]", note: "Driven by prerequisite reviews and application requirements that need follow-up" },
      { metric: "Speed to Lead", avg: "[[edu.sv.graduate-programs.lead]]", note: "Prospects often inquire at several programs at once; measure time to first live contact" },
      { metric: "Enrollment Rate", avg: "[[edu.sv.graduate-programs.enroll]]", note: "Driven by selectivity, employer funding and the alternatives each prospect holds" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Inquiry-to-enrollment conversion by program, source, and counselor","Career outcome data integrated into recruitment messaging","Competitor loss analysis by program and prospect segment","Alumni engagement and referral tracking","Revenue per program analytics connecting enrollment to tuition"],
        vendors: "Salesforce Education, Slate, NICE", risk: "High-value MBA inquiries receiving the same generic response as certificate inquiries",
        stack: [{ name: "Salesforce Education Cloud", role: "Graduate CRM", why: "Relationship management for the longer, more consultative graduate enrollment cycle. Pipeline management, communication sequencing, and enrollment forecasting.", href: "/vendors/ccaas" }],
        pitfall: "Graduate programs often count inquiries without weighing them. Tuition differs widely between programs: [[edu.ex.grad-weight]]. Weight conversion metrics by program revenue so the contact center is measured on the enrollments that fund the institution."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Program-specific routing matching prospects to counselors with domain expertise","Executive/C-suite routing for executive education and custom programs","International routing with timezone and language considerations","Employer-sponsored routing for corporate partnership programs","Re-engagement routing for prospects who started but didn't complete applications"],
        vendors: "Five9, NICE CXone, 8x8", risk: "Executive education prospect reaching a counselor trained on entry-level certificates",
        stack: [{ name: "Five9", role: "CCaaS", why: "Blended inbound/outbound for graduate recruitment. Speed-to-lead automation for new inquiries combined with nurture campaign outbound for pipeline prospects.", href: "/vendors/five9" }],
        pitfall: "Graduate prospects are shopping and often request information from several programs at once. The first program to reach them with a knowledgeable, consultative response has the advantage. [[edu.ex.grad-speed]], the competitor has set the terms of the comparison before you speak."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Program comparison tools showing curriculum, outcomes, and ROI","Virtual information session scheduling and follow-up","Alumni connection facilitation for prospect conversations","Application milestone notifications with personalized next steps","Employer tuition benefit navigation assistance"],
        vendors: "Salesforce, Slate, EAB, Mongoose", risk: "Prospects feeling sold to rather than advised: trust collapse",
        stack: [{ name: "Mongoose", role: "Text Engagement", why: "Working professionals respond to text faster than email or phone. Text-based outreach for info session reminders, application updates, and deadline nudges. Respects the adult learner's schedule.", href: "/vendors" }],
        pitfall: "Graduate recruitment must be consultative, not transactional. A prospect asking 'should I get an MBA or a specialized master's?' needs career guidance: not a sales pitch for the MBA. Counselors who default to selling the most expensive program lose trust. Train graduate counselors as career advisors first and recruiters second."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Program recommendation bots based on career goals and background","Application requirement bots with prerequisite evaluation","Tuition and financial aid estimator bots","Info session and campus visit scheduling bots","FAQ bots covering GMAT/GRE waivers, transfer credits, and timelines"],
        vendors: "Ocelot, Ada, custom bots", risk: "Bot recommending a program the prospect isn't qualified for",
        stack: [{ name: "Ocelot", role: "Education AI", why: "Graduate-specific intents: program comparison, prerequisite checking, and career outcome data. Built for the detailed questions graduate prospects ask.", href: "/vendors/iva" }],
        pitfall: "Graduate bots must understand that prospects are evaluating programs, not just asking questions. A bot that answers 'what's the average GMAT score for admitted students?' factually is helpful. A bot that also says 'students with your profile have been successful in our program, would you like to schedule a conversation with an admissions counselor?' is converting. Build career-context awareness into graduate bots."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FERPA compliance for graduate student records","Accreditation disclosure requirements for program advertising","State authorization compliance for out-of-state and online programs","VA benefits and GI Bill compliance for veteran students","Title IV and FTC rules on career outcome claims"],
        vendors: "Accreditation bodies, state authorization, VA", risk: "Career outcome claims in recruitment that don't match actual placement data",
        stack: [{ name: "Institutional compliance", role: "Accreditation & outcome claims", why: "For an institution in the federal aid programs, a false or misleading statement about graduates' employability, including employment rates materially lower than those marketed, is misrepresentation ([[edu.t4.jobs]]). A placement rate a counselor quotes should match the institution's published outcome data.", href: "/vendors" }],
        pitfall: "State authorization requirements for online graduate programs vary by state, and some states require specific disclosures or approvals before enrolling their residents. A program that enrolls a resident of a state where it lacks authorization, through SARA or that state's own approval, has a compliance gap. Your contact center must verify the prospect's state of residence and confirm authorization before advancing the enrollment."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Graduate inquiry nurture workflow with multi-touch, multi-month cadence","Application review workflow with faculty committee coordination","Prerequisite evaluation workflow for conditional admission","Employer partnership enrollment workflow with corporate billing","Cohort formation workflow grouping students for program start dates"],
        vendors: "Salesforce Education, Slate, Ellucian", risk: "Application review running far longer than the prospect was told",
        stack: [{ name: "Salesforce Education Cloud", role: "Enrollment Workflow", why: "Pipeline management from inquiry through enrollment. Communication automation, application tracking, and decision workflow. Handles the longer, more complex graduate enrollment cycle.", href: "/vendors/ccaas" }],
        pitfall: "Graduate enrollment cycles can run [[edu.grad.cycle]] from first inquiry. Without a structured nurture workflow, with touchpoints spaced from the first week out to the following terms, prospects go cold. Outreach that stops after a few attempts loses prospects who were deciding on next year's start. Plan the cadence for the length of your own cycle."
      },
      { layer: 1, name: "Data Access", capabilities: ["Graduate CRM: inquiries, applications, pipeline, and enrollment","SIS: enrollment records, degree progress, and academic standing","Career services: placement data, employer connections, and outcome tracking","Alumni database: referral sources, engagement, and giving history","Financial system: tuition, billing, employer reimbursement, and scholarship"],
        vendors: "Salesforce, Slate, Ellucian, PeopleSoft", risk: "Career outcome data not accessible to counselors during recruitment conversations",
        stack: [{ name: "Salesforce Education Cloud", role: "Graduate CRM Data", why: "Full lifecycle data: from first inquiry through graduation and alumni engagement. The relationship layer that enables the consultative approach graduate recruitment requires.", href: "/vendors/ccaas" }],
        pitfall: "Graduate prospects ask 'what will this degree do for my career?', and the counselor needs data to answer credibly. Average salary increase post-graduation, employer placement by industry, and time-to-promotion data must be accessible in the agent desktop, not buried in a marketing PDF. Build career outcome dashboards that counselors can reference during prospect conversations."
      },
    ],
  },

  "financial-aid": {
    name: "Financial Aid & Student Accounts", parent: "Education",
    tagline: "FAFSA support, aid packaging, billing, payment plans, and 1098-T.",
    intro: "Financial aid contact centers handle the most consequential interactions in education: the ones that determine whether a student can afford to attend. A confusing aid package, a billing error, or an unresolved hold can prevent enrollment entirely. The CX challenge is explaining extraordinarily complex financial information to stressed families while navigating federal regulations that change annually.",
    kpis: [
      { metric: "AHT", avg: "[[edu.sv.financial-aid.aht]]", note: "Driven by FAFSA, aid offer and billing questions that need explanation" },
      { metric: "FCR", avg: "[[edu.sv.financial-aid.fcr]]", note: "Driven by verification documents, appeals and issues that cross departments" },
      { metric: "CSAT", avg: "[[edu.sv.financial-aid.csat]]", note: "Financial stress raises the stakes of every delay and handoff" },
      { metric: "Abandonment", avg: "[[edu.sv.financial-aid.abandon]]", note: "Driven by staffing against FAFSA season and term-start peaks" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["FAFSA completion rate tracking by demographic and outreach method","Verification completion rate and cycle time analytics","Aid package acceptance rate by award type and family income","Payment plan enrollment and delinquency tracking","Melt attribution: students who accepted aid but didn't enroll and why"],
        vendors: "NICE, Qualtrics, EAB", risk: "FAFSA simplification changes creating confusion that suppresses completion rates",
        stack: [{ name: "NICE CXone", role: "QA & Analytics", why: "FAFSA-season volume analytics and quality monitoring. Flags calls where agents give incorrect aid information, a serious compliance risk in education CX.", href: "/vendors/nice-cxone" }],
        pitfall: "Financial aid offices track FAFSA completion but rarely attribute it to contact center help. Count the completed FAFSAs that followed a phone or chat interaction with the aid office; the contact center earns credit for those completions, and investment in line with its enrollment impact. Build attribution from contact center interactions to FAFSA completion to enrollment."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["FAFSA season surge routing, from the FAFSA launch through state and institutional priority deadlines","Verification routing to agents trained on document collection","Billing dispute routing separating financial aid from student accounts","Appeal routing for special circumstances and professional judgment","Student accounts routing for payment plans, 1098-T, and refunds"],
        vendors: "NICE CXone, Five9, Genesys", risk: "FAFSA calls reaching billing agents who can't help with aid questions",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Financial aid seasonal routing with WEM for surge staffing. Routes FAFSA, verification, packaging, and billing to specialized agents and plans staffing for FAFSA season peaks.", href: "/vendors/nice-cxone" }],
        pitfall: "Financial aid and student accounts are different departments with different systems, but students don't know the difference. A student calling about 'my bill' might have a financial aid question (aid hasn't posted), a student accounts question (payment plan needed), or a registrar question (registration hold from unpaid balance). Build cross-department triage that classifies the issue before routing, not after."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Proactive FAFSA deadline and verification document notifications","Net price calculator accessible before and during aid packaging","Self-service payment plan enrollment portal","Aid package comparison tools showing costs across institutions","1098-T delivery and explanation communications"],
        vendors: "Slate, Salesforce, Ellucian, Ocelot", risk: "Verification document requests getting lost in email: student never sees them",
        stack: [{ name: "Ocelot", role: "Financial Aid Communications", why: "AI-powered financial aid chatbot and proactive notification system. Pre-built for FAFSA help, verification document collection, and aid package explanation. Multi-channel (chat, text, email) for the urgency that financial aid requires.", href: "/vendors" }],
        pitfall: "Verification document requests sent only by email are easy to miss. A family that does not submit verification documents does not receive an aid package, and may not enroll. Use several channels (email, text, and a phone call for non-respondents), clear deadlines and simple submission (photo upload in place of fax), and track verification completion by channel to see what works for your students."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["FAFSA filing assistance bots with step-by-step guidance","Aid package explanation bots breaking down grants, loans, and work-study","Payment plan options and enrollment bots","Verification document checklist bots with submission status","1098-T explanation bots for tax filing season"],
        vendors: "Ocelot, Ada, Ivy.ai", risk: "Bot providing incorrect financial aid information that affects enrollment decisions",
        stack: [{ name: "Ocelot", role: "Financial Aid AI", why: "Purpose-built for financial aid. Understands Pell Grant, subsidized/unsubsidized loans, work-study, institutional grants, and the difference between cost of attendance and net price. A general-purpose bot needs this vocabulary built in.", href: "/vendors/iva" }],
        pitfall: "Financial aid bots must distinguish between 'cost of attendance' (sticker price) and 'net price' (what the student actually pays after aid). A bot that answers 'how much does it cost?' with the cost of attendance instead of the net price scares away low-income students who would receive significant aid. Always present both numbers, with net price prominent and labelled as an estimate: \"[[edu.ex.netprice]]\""
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Title IV federal financial aid compliance for all aid communications","FERPA compliance for financial information sharing","GLBA (Gramm-Leach-Bliley) compliance for student financial data","State financial aid program compliance requirements","Satisfactory Academic Progress (SAP) policy enforcement"],
        vendors: "Federal Title IV compliance, FERPA, GLBA", risk: "Agent providing incorrect aid eligibility information violating Title IV",
        stack: [{ name: "Federal compliance", role: "Title IV", why: "Federal student aid is governed by Title IV of the Higher Education Act. A false, erroneous or misleading statement about the availability, amount or nature of financial aid is misrepresentation ([[edu.t4.aid]]), whether made in person, by phone, in chat or by a bot, and substantial misrepresentation can cost the institution its participation in federal aid programs ([[edu.t4.sanction]]).", href: "/vendors" }],
        pitfall: "An agent who promises a grant amount before the aid package is final gives the family a figure the institution may not deliver, and a misleading statement about aid is a Title IV misrepresentation risk. Train agents to use conditional language: 'Based on current information, your estimated aid package would include about this amount, pending verification.' Estimates labelled as estimates protect the family and the institution."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["FAFSA processing workflow with ISIRs, verification, and packaging","Verification document collection workflow with status tracking","Aid package delivery and acceptance workflow","Payment plan enrollment and installment tracking workflow","Refund processing workflow for excess aid disbursement"],
        vendors: "Ellucian Banner/Colleague, PeopleSoft, Workday Student", risk: "Verification workflow running for weeks while enrollment deadlines approach",
        stack: [{ name: "Ellucian Banner", role: "Financial Aid System", why: "Federal aid processing: ISIRs, verification, packaging, and disbursement. The system that determines what the student receives and when. Contact center agents need Banner access to answer any aid question.", href: "/vendors" }],
        pitfall: "Verification is a common enrollment bottleneck. A student selected for verification must submit documents such as household information before aid can be packaged. If verification runs for weeks, the student may not know their real cost before the enrollment deadline, and may choose a school that already packaged their aid. Shorten it with document imaging, the tax data the FAFSA now pulls directly from the IRS, and parallel processing."
      },
      { layer: 1, name: "Data Access", capabilities: ["Financial aid system: ISIR data, awards, disbursements, and SAP status","Student accounts/bursar: billing, payments, holds, and refunds","SIS: enrollment, registration, and academic standing","NSLDS (National Student Loan Data System): federal loan history","Payment processor: installment plans, credit card payments, and e-checks"],
        vendors: "Ellucian Banner/Colleague, PeopleSoft, Workday, TouchNet", risk: "Financial aid data in one system and billing data in another with no reconciliation",
        stack: [{ name: "Ellucian Banner", role: "Financial Aid Data", why: "Federal aid data, institutional aid, and disbursement records. Every financial aid question starts with Banner: what was awarded, what was accepted, what was disbursed, and what's pending.", href: "/vendors" }, { name: "TouchNet", role: "Student Payments", why: "Payment processing, payment plans, and e-billing for student accounts. When a student asks 'why do I still owe money if I have financial aid?' the answer spans both Banner (aid) and TouchNet (billing).", href: "/vendors" }],
        pitfall: "A frequent financial aid contact center frustration: the student's bill shows a balance due, but their financial aid has not disbursed yet. The aid office says 'your aid will post before the payment deadline.' The billing office says 'you owe this amount by Friday.' The student panics. Build a unified view that shows pending aid alongside the current balance: \"[[edu.ex.balance]]\" This one data integration answers the question before the student has to call."
      },
    ],
  },

  "student-services": {
    name: "Student Services & Campus Life", parent: "Education",
    tagline: "Housing, dining, health services, accessibility, counseling, and Title IX.",
    intro: "Student services contact centers support enrolled students across the full campus experience, housing, dining, health, counseling, accessibility, student conduct, and campus safety. The CX challenge is breadth: a single contact center may field questions about meal plan changes, housing maintenance, disability accommodations, and mental health crises in the same hour.",
    kpis: [
      { metric: "AHT", avg: "[[edu.sv.student-services.aht]]", note: "Housing and dining questions are short; accessibility and conduct take longer" },
      { metric: "FCR", avg: "[[edu.sv.student-services.fcr]]", note: "Driven by requests that need coordination with other departments" },
      { metric: "CSAT", avg: "[[edu.sv.student-services.csat]]", note: "Driven by reachability and follow-through across service areas" },
      { metric: "Containment", avg: "[[edu.sv.student-services.containment]]", note: "Basic information can be automated; accommodations and counseling referrals need people" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Student satisfaction by service area, housing, dining, health, accessibility","Service request resolution time by department and request type","Retention correlation: do students who use services persist at higher rates?","Accessibility accommodation request volume and fulfillment time","Mental health referral tracking with follow-up completion"], vendors: "NICE, Qualtrics, Maxient", risk: "Retention signals in service data not connected to retention interventions",
        stack: [{ name: "Qualtrics", role: "Student Experience", why: "Multi-touchpoint student satisfaction across housing, dining, health, and campus services. Identifies which service areas drive retention and which create friction.", href: "/vendors" }],
        pitfall: "Student services data contains retention signals that most retention offices never see. A student who keeps requesting housing changes, visits the counseling center, and files a dining complaint is showing disengagement patterns visible across service touchpoints, but invisible when each department tracks interactions in isolation. Build a cross-service student engagement dashboard visible to the retention team."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Service-area routing: housing, dining, health, accessibility, conduct","Crisis routing for mental health, Title IX, and safety emergencies","Accessibility routing to trained ADA/504 coordinators","Parent routing with FERPA verification for enrolled student inquiries","After-hours routing for residential emergencies and safety"], vendors: "NICE CXone, Five9, 8x8", risk: "Student in mental health crisis reaching a housing agent",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Multi-service routing with crisis detection. Keyword identification for mental health, safety, and Title IX language routes to trained responders immediately.", href: "/vendors/nice-cxone" }],
        pitfall: "Student services calls that start as one issue can reveal another. A student calling about a housing change may mention that their roommate is threatening them, which becomes a Title IX or student conduct issue. A student asking about withdrawing from a class may express suicidal ideation. Train every student services agent to recognize crisis indicators and build one-button escalation to the counseling center, Title IX office, or campus safety."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Student portal for housing, dining, and service requests","Mental health resource information with crisis hotline integration","Accessibility accommodation request portal","Residential life communication for hall events and maintenance","Parent and family communication channels with FERPA controls"], vendors: "StarRez, Maxient, Salesforce, custom portals", risk: "Crisis resources not prominently visible on every student communication channel",
        stack: [{ name: "StarRez", role: "Housing Management", why: "Student housing: room selection, roommate matching, maintenance requests, and meal plan management. The operational system behind many student services calls.", href: "/vendors" }],
        pitfall: "Every student-facing digital channel, portal, chatbot, email, app, must prominently display crisis resources: 988 Suicide & Crisis Lifeline, campus counseling center, and campus safety. A student who navigates to the student services portal looking for help and can't find crisis resources may not navigate further. Crisis access must be zero-click visible, not buried in a FAQ."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Housing information bots: availability, meal plans, and maintenance requests","Dining plan comparison and change bots","Campus event and recreation information bots","Health services appointment scheduling bots","FAQ bots covering parking, ID cards, and campus policies"], vendors: "Ocelot, Ada, custom bots", risk: "Bot handling mental health inquiry instead of immediately connecting to counselor",
        stack: [{ name: "Ocelot", role: "Student Services AI", why: "Campus services chatbot with built-in crisis detection. Handles housing, dining, and campus FAQ while routing mental health, safety, and conduct concerns to human responders immediately.", href: "/vendors/iva" }],
        pitfall: "Student services bots must have an absolute rule: any language indicating mental health distress, self-harm, suicidal ideation, or safety threat immediately exits the bot flow and connects to a trained human, campus counseling, 988, or campus safety. A bot that says 'I'm sorry you're feeling that way. Can I help you with a dining plan question?' in response to 'I don't want to be here anymore' is a failure with potentially fatal consequences. Test crisis detection weekly."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FERPA compliance for all enrolled student interactions","Title IX reporting and response protocols","ADA/Section 504 accommodation compliance","Clery Act crime reporting and notification requirements","Student conduct process confidentiality controls"], vendors: "FERPA, Title IX, ADA/504, Clery Act", risk: "Title IX mandatory report not filed because agent didn't recognize the disclosure",
        stack: [{ name: "Maxient", role: "Student Conduct & Title IX", why: "Student conduct case management and Title IX tracking. When a student services agent receives a Title IX disclosure, Maxient is where the report is filed and tracked.", href: "/vendors" }],
        pitfall: "Title IX requires institutions to respond to reports of sexual harassment and assault. Student services agents are often the first people to hear a disclosure, during a housing change request, a class withdrawal call, or a vague 'I'm having problems with someone on campus.' Train every agent on your institution's Title IX reporting policy, including whether staff are designated reporters, how to receive a disclosure with care, and how to reach the Title IX Coordinator."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Housing selection and roommate matching workflow","Dining plan change and accommodation workflow","Accessibility accommodation request and implementation workflow","Student conduct case management workflow","Health services appointment and referral workflow"], vendors: "StarRez, Maxient, Ellucian, Salesforce", risk: "Accessibility accommodation approved but not implemented before classes start",
        stack: [{ name: "StarRez", role: "Housing Operations", why: "Room assignment, roommate matching, housing changes, and residential maintenance. The workflow engine for residential life.", href: "/vendors" }, { name: "Maxient", role: "Conduct & Care", why: "Student conduct, CARE team case management, and behavioral intervention tracking. Connects the contact center to the intervention teams that support students in distress.", href: "/vendors" }],
        pitfall: "Accessibility accommodations must be implemented before the student needs them, not after they file a complaint. If a student with a mobility disability is assigned to a third-floor room without an elevator, the contact center will receive the call, but the failure happened in the housing assignment workflow. Build accommodation flags that the housing system checks before assignment, not after."
      },
      { layer: 1, name: "Data Access", capabilities: ["SIS: enrollment, registration, and academic standing","Housing management: room assignments, meal plans, and maintenance","Student conduct database: cases, sanctions, and behavioral alerts","Health and counseling: appointments, referrals, and crisis contacts","Accessibility services: accommodation letters, requests, and implementation status"], vendors: "Ellucian, StarRez, Maxient, Titanium (health), Accommodate", risk: "Agent unable to see a student's accommodation letter during a service interaction",
        stack: [{ name: "Ellucian Banner/Colleague", role: "SIS", why: "Enrollment status, class schedule, and academic standing. The foundation for every student services interaction, is this person currently enrolled?", href: "/vendors" }, { name: "Accommodate (Symplicity)", role: "Accessibility Data", why: "Accommodation requests, approved accommodations, and implementation tracking. When a student calls about exam accommodations not being provided, the agent needs this data.", href: "/vendors" }],
        pitfall: "Student services data spans many systems (SIS, housing, dining, health, conduct, and accessibility), often without integration. An agent helping a student with a housing concern can't see their accessibility accommodations (different system), their conduct history (different system), or their counseling referral status (different system). Without a unified student view, every interaction starts from zero and the agent misses critical context."
      },
    ],
  },

  "it-helpdesk": {
    name: "IT Help Desk & Learning Technology", parent: "Education",
    tagline: "LMS support, WiFi, account access, device troubleshooting, and classroom technology.",
    intro: "University IT help desks support students, faculty, and staff across a technology landscape that includes LMS platforms, campus WiFi, email, lab computers, classroom AV, research computing, and personal device support. The CX challenge is seasonal intensity: the first week of classes, midterms, and finals create surge volume that dwarfs normal operations.",
    kpis: [
      { metric: "AHT", avg: "[[edu.sv.it-helpdesk.aht]]", note: "Password resets are short; LMS and research computing take longer" },
      { metric: "FCR", avg: "[[edu.sv.it-helpdesk.fcr]]", note: "Access issues resolve on contact; integration and LMS issues need follow-up" },
      { metric: "CSAT", avg: "[[edu.sv.it-helpdesk.csat]]", note: "Students compare institutional IT with consumer tech support" },
      { metric: "Containment", avg: "[[edu.sv.it-helpdesk.containment]]", note: "Driven by self-service password reset and basic troubleshooting" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Ticket volume trending by system, building, and time of semester","LMS uptime and performance correlated with help desk volume","Faculty vs student vs staff satisfaction by service category","Knowledge base effectiveness: which articles deflect tickets","SLA compliance by priority level and service category"],
        vendors: "ServiceNow, NICE, Qualtrics", risk: "LMS performance degradation invisible until a whole class cannot submit assignments",
        stack: [{ name: "ServiceNow ITSM", role: "IT Service Management", why: "IT service management used in university IT operations. Incident, problem, change, and knowledge management. Connects the help desk to infrastructure teams and application support.", href: "/vendors" }],
        pitfall: "University IT help desks measure ticket volume and resolution time but rarely measure academic impact. An LMS outage during finals week that blocks submissions across campus has a different urgency than a WiFi issue in a lounge. Build academic-calendar-aware priority classification: system issues during exams and registration get automatic escalation."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Tier 1/2/3 routing by issue complexity and system affected","LMS-specific routing to learning technology specialists","Faculty priority routing during class preparation and exam periods","Research computing routing to HPC and data services specialists","Classroom technology emergency routing for active class disruptions"],
        vendors: "ServiceNow, NICE CXone, Cisco", risk: "Faculty with a classroom projector failure during a lecture waiting in the general queue",
        stack: [{ name: "ServiceNow + CCaaS", role: "Integrated ITSM", why: "ServiceNow for ticket management and knowledge base; CCaaS (NICE, Genesys) for phone/chat routing and WEM. The integration between ITSM and CCaaS determines whether the agent has ticket context when the caller reaches them.", href: "/vendors" }],
        pitfall: "Classroom technology failures during active classes are time-critical: a professor with a full lecture hall and a dead projector cannot wait in a general queue. Build an 'active class' emergency line with a short, stated dispatch target for AV support. It is a small investment against a visible failure."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Self-service password reset and MFA enrollment","LMS help resources integrated into the LMS interface itself","Proactive system status notifications during outages and maintenance","Device setup guides for campus WiFi, email, and VPN","Knowledge base with searchable troubleshooting articles"],
        vendors: "ServiceNow, Confluence, custom portals", risk: "System outage during registration or exams without proactive communication",
        stack: [{ name: "ServiceNow Knowledge + Portal", role: "Self-Service", why: "Student-facing knowledge base and service request portal. Password reset, WiFi troubleshooting, and software access: requests that should rarely need a human agent.", href: "/vendors" }],
        pitfall: "Password resets are a large, repetitive share of help desk tickets; count yours. Automated self-service password reset with MFA verification takes most of them out of the queue. Some universities still require students to call or visit in person to reset a password. Self-service reset is usually the first improvement to make."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Password reset and account unlock bots with identity verification","WiFi and network troubleshooting bots with device-specific instructions","LMS FAQ bots (submission, grading, discussion, video uploads)","Software access and installation guide bots","System status bots with real-time outage information"],
        vendors: "ServiceNow Virtual Agent, Ada, custom bots", risk: "Bot resolving a password reset without proper identity verification",
        stack: [{ name: "ServiceNow Virtual Agent", role: "IT Chatbot", why: "Native ServiceNow chatbot with ITSM integration. Handles password resets, ticket creation, knowledge search, and status updates. Pre-integrated with the ticket system: no separate bot-to-ITSM integration required.", href: "/vendors" }],
        pitfall: "IT help desk bots must verify identity before performing any account action. A bot that resets a password based on a student ID and email address alone, without MFA or security question verification, is a social engineering vulnerability. Students' ID numbers and emails are easily guessable or obtainable. Require MFA or secondary verification for all account actions through bots."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FERPA compliance for student data in IT systems","HIPAA compliance for health center IT systems","CJIS compliance for campus police systems","PCI DSS compliance for payment processing systems","Data classification and handling policies for research data"],
        vendors: "NIST frameworks, institutional policy", risk: "Help desk agent accessing student records in a system they shouldn't have access to",
        stack: [{ name: "NIST/institutional security", role: "IT Compliance", why: "University IT touches FERPA (student records), HIPAA (health center), CJIS (campus police), PCI (payments), and research compliance (export control, IRB). Help desk agents need role-based access that limits what they can see based on the system they're supporting.", href: "/vendors" }],
        pitfall: "University IT help desks often have broad system access for troubleshooting, which means a student worker staffing the help desk might have access to grade systems, financial records, or health center databases. Implement role-based access that gives help desk agents the minimum access needed for their tier. Tier 1 student workers should be able to reset passwords and check system status, not browse the registrar's database."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Incident management workflow: detect, triage, assign, resolve, close","Service request workflow: software access, account creation, equipment loan","Change management workflow for system updates and maintenance windows","Major incident workflow for campus-wide outages and security events","Onboarding workflow for new student, faculty, and staff account provisioning"],
        vendors: "ServiceNow, Jira Service Management, Freshservice", risk: "Major LMS outage during finals with no incident command workflow",
        stack: [{ name: "ServiceNow ITSM", role: "Workflow Engine", why: "ITIL-aligned incident, problem, change, and request management. The workflow core for university IT operations, used by small and large help desks.", href: "/vendors" }, { name: "Jira Service Management", role: "Alternative ITSM", why: "Used in universities with agile-oriented IT teams. Strong integration with development tools. Better for IT organizations that blend support with software development.", href: "/vendors" }],
        pitfall: "Start-of-semester IT help desk volume is predictable and steep: account activations, WiFi setup, LMS access, and email configuration all arrive in the first days of term. Build a 'Welcome Week' IT support model: extended hours, walk-up support in residence halls, peer tech support volunteers, and setup guides sent with orientation materials. The goal is to resolve most new-student IT issues before classes start."
      },
      { layer: 1, name: "Data Access", capabilities: ["ITSM: tickets, knowledge base, asset inventory, and SLA tracking","Identity management: Active Directory, SSO, MFA enrollment","LMS: Canvas, Blackboard, Moodle user accounts and course data","Network management: WiFi performance, device registration, bandwidth","Asset management: lab computers, classroom technology, and loaner equipment"],
        vendors: "ServiceNow, Canvas/Blackboard, Cisco (network), Active Directory", risk: "Agent unable to see which systems the student is having trouble with",
        stack: [{ name: "ServiceNow CMDB", role: "IT Asset Data", why: "Configuration items: every system, server, network device, and application. When a student reports 'the system is down,' CMDB tells the agent which system, its current status, and known issues.", href: "/vendors" }, { name: "Canvas / Blackboard", role: "LMS Data", why: "Learning Management System user data and course information. When a student says 'I can't submit my assignment,' the agent needs to see the student's course enrollment, assignment status, and any system errors in the LMS.", href: "/vendors" }],
        pitfall: "LMS issues are the most emotionally charged IT help desk calls, because they affect grades. A student who can't submit an assignment before the deadline due to a technical issue needs both IT resolution AND communication with the instructor. Build a workflow that resolves the technical issue AND generates an automated notification to the instructor documenting the system error and timeline. Without this, the student must persuade the professor that 'the system was down', a claim instructors hear often and cannot check."
      },
    ],
  },

  "online-education": {
    name: "Online & Continuing Education", parent: "Education",
    tagline: "Enrollment, technical support, proctor scheduling, credentials, and corporate partnerships.",
    intro: "Online education contact centers serve adult learners who chose online for convenience and may leave when it stops being convenient. Every service friction point is a possible reason to stop out. The CX challenge is giving responsive, empathetic support at the hours these students study, which are often late in the evening.",
    kpis: [
      { metric: "AHT", avg: "[[edu.sv.online-education.aht]]", note: "Driven by the mix of technical and enrollment questions" },
      { metric: "FCR", avg: "[[edu.sv.online-education.fcr]]", note: "Driven by a narrower service scope than a residential campus" },
      { metric: "CSAT", avg: "[[edu.sv.online-education.csat]]", note: "Moves with technical frustration and how connected students feel" },
      { metric: "Retention", avg: "[[edu.sv.online-education.retention]]", note: "Share of students who continue to the next term; measure yours by program and start date" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Course completion and dropout prediction by student profile and engagement","LMS engagement analytics correlated with support contact patterns","Student satisfaction by program, modality, and support channel","Technical issue trending by platform, browser, and device type","ROI analytics for corporate and employer-sponsored students"],
        vendors: "NICE, Qualtrics, EAB, LMS analytics", risk: "Dropout signals visible in data but no intervention triggered",
        stack: [{ name: "EAB", role: "Student Success Analytics", why: "Predictive analytics identifying online students at risk of dropping out. Engagement signals (missed assignments, login decline, support contacts) trigger proactive outreach before the student disappears.", href: "/vendors" }],
        pitfall: "Online student dropout is often gradual: a missed assignment, then a missed week, then formal withdrawal or quiet disappearance. LMS engagement data shows the pattern as it happens, but many institutions do not connect LMS data to intervention workflows. Build automated alerts: when a student misses consecutive assignments, trigger a call from a success coach, which reaches the student more directly than an email."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["24/7 technical support routing for students studying at all hours","Enrollment and registration routing for new and continuing students","Proctor scheduling and exam support routing","Corporate partnership routing for employer-sponsored students","Re-engagement routing for at-risk and recently inactive students"],
        vendors: "NICE CXone, Five9, 8x8", risk: "Student studying late at night unable to reach support until morning",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "24/7 coverage with WEM that manages evening and weekend staffing efficiently. Online students study during non-business hours: support must be available when they study.", href: "/vendors/nice-cxone" }],
        pitfall: "Online education sells convenience, and that includes support hours. If students can open courses at any hour but support runs only on weekday business hours, the institution has built a convenience gap. At minimum, provide round-the-clock technical support (LMS, login, submission issues). For enrollment and financial aid, evening and Saturday hours reach adult learners when they are free."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Proactive engagement for disengaged students before they drop","Technical support accessible within the LMS interface","Proctor scheduling and exam preparation communications","Onboarding communications for new online students with tech setup guides","Community-building communications reducing online student isolation"],
        vendors: "Canvas, Salesforce, Ocelot, Mongoose", risk: "Online students feeling isolated with no community connection to the institution",
        stack: [{ name: "Canvas (Instructure)", role: "LMS + Support", why: "Embedding support resources directly in the LMS reduces friction: the student doesn't leave Canvas to get help. Canvas's built-in help menu can route to the help desk, knowledge base, and chatbot.", href: "/vendors" }],
        pitfall: "Isolation can push online students out, and support can reach them. In a randomized experiment, students assigned a personal coach who contacted them regularly were [[edu.coach.rct]] and more likely to still be enrolled a year after coaching ended. Assign online students to named success coaches who check in on a set schedule. A short call from someone who knows the student's name and program is the intervention to test first."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["LMS troubleshooting bots for submission, grading, and access issues","Enrollment and registration bots for course selection and scheduling","Exam proctoring setup and troubleshooting bots","Academic calendar and deadline reminder bots","Financial aid and payment bots for continuing students"],
        vendors: "Ocelot, Ada, ServiceNow Virtual Agent", risk: "Bot unable to resolve a proctoring issue during a timed exam",
        stack: [{ name: "Ocelot", role: "Online Student AI", why: "24/7 chatbot for the questions online students ask at midnight: 'how do I submit my assignment?', 'when is my exam?', 'how do I set up proctoring?' Purpose-built for higher education, not generic tech support.", href: "/vendors/iva" }],
        pitfall: "Proctoring issues during timed exams are among the most urgent online education support calls: the student has a fixed exam window, the proctoring software isn't working, and the clock is ticking. Build a dedicated exam support line active during all exam windows with agents trained specifically on proctoring software (ProctorU, Examity, Honorlock). These calls cannot wait in a general queue."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FERPA compliance for online student records across state lines","State authorization compliance for enrolling students in specific states","Accessibility compliance for online course content and platforms","Academic integrity policies for online assessment and proctoring","SARA (State Authorization Reciprocity Agreement) compliance"],
        vendors: "FERPA, SARA, accessibility standards", risk: "Enrolling students in states where the institution lacks authorization",
        stack: [{ name: "SARA / state authorization", role: "Regulatory", why: "Online programs enrolling students across state lines must comply with SARA or individual state authorization requirements. The contact center must verify student state of residence and confirm authorization before enrollment.", href: "/vendors" }],
        pitfall: "Online proctoring creates unique accessibility challenges: students with disabilities may not be able to use standard proctoring software (screen readers, alternative input devices, extended time). Build alternative assessment pathways for accommodated students and ensure the contact center can connect disabled students to accommodation coordinators during exam windows, not after."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Online student onboarding workflow with technology setup and orientation","Proctor scheduling workflow with technology verification","Course registration workflow with prerequisite validation","Student success intervention workflow triggered by engagement decline","Credential and certificate delivery workflow for completers"],
        vendors: "Ellucian, Canvas, Salesforce Education, custom platforms", risk: "Onboarding workflow not verifying student technology readiness before classes start",
        stack: [{ name: "Canvas + Salesforce", role: "Online Operations", why: "Canvas for the learning platform; Salesforce Education Cloud for the student relationship. Together they handle the enrollment-to-completion lifecycle for online programs.", href: "/vendors" }],
        pitfall: "Online student onboarding must include technology readiness verification: browser compatibility, internet speed, webcam/microphone for proctoring, and LMS navigation proficiency. A student who discovers on day 1 that their Chromebook can't run the proctoring software is already behind and frustrated. Send a technology readiness checklist with automatic checks well before classes start."
      },
      { layer: 1, name: "Data Access", capabilities: ["LMS: course enrollment, engagement data, grades, and submissions","SIS: enrollment status, academic standing, and degree progress","CRM: student communication history, advisor notes, and intervention records","Proctoring platform: exam schedules, technical requirements, and results","Corporate partnership database: employer agreements, tuition benefits, and billing"],
        vendors: "Canvas, Ellucian, Salesforce, ProctorU/Examity", risk: "LMS engagement data not accessible to student success team for intervention",
        stack: [{ name: "Canvas Data", role: "LMS Analytics", why: "Login frequency, assignment submission timing, discussion participation, and grade trends. The early warning system for dropout risk: visible in Canvas data weeks before the student formally withdraws.", href: "/vendors" }, { name: "Salesforce Education Cloud", role: "Student CRM", why: "Communication history, advisor interactions, and intervention tracking. When a success coach calls a disengaged student, they need the full picture, not just LMS data, but financial aid status, previous interactions, and support contacts.", href: "/vendors/ccaas" }],
        pitfall: "A high-value data integration in online education: connecting LMS engagement (Canvas) to the student success CRM (Salesforce). When Canvas shows a student has not logged in for longer than the threshold you set from your own data, that alert should create a task in Salesforce for the success coach to call. Without this integration, LMS data sits in Canvas dashboards that nobody checks, and students disappear silently."
      },
    ],
  },
};

export const getEducationSubVertical = (slug) => (Object.prototype.hasOwnProperty.call(educationSubVerticals, slug) ? educationSubVerticals[slug] : undefined);
export const getAllEducationSubVerticalSlugs = () => Object.keys(educationSubVerticals);
