// Financial Services Sub-Vertical CX Stack Frameworks
// Each sub-vertical maps all 7 orchestration layers with specific capabilities, vendors, and maturity checkpoints

export const fsSubVerticals = {
  "retail-banking": {
    name: "Retail Banking",
    parent: "Financial Services",
    tagline: "Account servicing, fraud alerts, card disputes, loan inquiries, and branch-to-digital migration.",
    intro: "Retail banking contact centers handle the broadest channel mix and highest volume of any financial services sub-vertical. The CX challenge is balancing transactional speed (balance checks, card activations) with consultative depth (mortgage inquiries, wealth referrals) while maintaining compliance across every interaction.",
    kpis: [
      { metric: "AHT", avg: "5:40", note: "Driven down by transactional volume; complex inquiries skew higher" },
      { metric: "FCR", avg: "72%", note: "Authentication and multi-system lookups reduce first-contact resolution" },
      { metric: "CSAT", avg: "79%", note: "Higher than healthcare but below retail; trust expectations are demanding" },
      { metric: "Containment", avg: "28%", note: "Balance checks and card activations are highly automatable" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: [
        "CSAT and NPS tracking segmented by product line (deposits, lending, cards)",
        "Compliance recording with automated audit trail for regulatory review",
        "Agent quality scoring calibrated for transactional vs consultative interactions",
        "Fraud interaction analytics — pattern detection across channels",
        "Branch-to-digital handoff tracking and attribution",
      ], vendors: "NICE Nexidia, Verint, CallMiner, Qualtrics", risk: "Regulatory audit failures if recording and QA gaps exist" },
      { layer: 6, name: "Routing & Orchestration", capabilities: [
        "Intent-based routing separating fraud, service, sales, and retention",
        "VIP and relationship-tier routing for wealth referrals and priority clients",
        "Skills-based routing for licensed representatives (Series 6/7, insurance)",
        "Overflow logic for branch closures and storm events",
        "Callback and scheduled appointment routing for complex consultations",
      ], vendors: "Genesys, NICE CXone, Five9, Talkdesk FS", risk: "Fraud and service sharing a queue creates response time risk" },
      { layer: 5, name: "Conversation Management", capabilities: [
        "Secure messaging for account-sensitive communications (statements, disputes)",
        "Co-browsing for online banking navigation and application assistance",
        "Chat with PII redaction for card numbers and SSN",
        "Video banking for advisory consultations and complex product discussions",
        "Proactive notifications for fraud alerts, payment reminders, and rate changes",
      ], vendors: "Glia, Unblu, LivePerson, Ada", risk: "Unsecured chat channels for sensitive banking data" },
      { layer: 4, name: "Reasoning & Planning", capabilities: [
        "Balance inquiry and transaction lookup bots with real-time core banking data",
        "Card activation, replacement, and PIN reset automation",
        "Loan application status bots with document checklist logic",
        "Product recommendation AI based on account profile and life events",
        "Fraud alert response bots with immediate card freeze capability",
      ], vendors: "Kasisto, Cognigy, Kore.ai, Google CCAI", risk: "AI handling financial advice without licensed-representative guardrails" },
      { layer: 3, name: "Policy & Guardrails", capabilities: [
        "KYC/AML identity verification integrated into every interaction",
        "PCI DSS compliance for card data in voice and digital channels",
        "Reg E dispute handling with required disclosure and timeline tracking",
        "TCPA consent management for outbound communications",
        "State-specific licensing validation for product recommendations",
      ], vendors: "Pindrop, BioCatch, LexisNexis Risk, Nuance", risk: "Non-compliant disclosures creating regulatory exposure" },
      { layer: 2, name: "Workflow Execution", capabilities: [
        "Account opening workflow with identity verification and funding steps",
        "Dispute intake and resolution workflow with Reg E timeline enforcement",
        "Address/profile change workflow with fraud verification triggers",
        "Loan modification workflow with document collection and status updates",
        "Cross-sell referral workflow routing qualified leads to specialists",
      ], vendors: "Pega, MuleSoft, Workato, UiPath", risk: "Manual handoffs between workflows creating data loss" },
      { layer: 1, name: "Data Access", capabilities: [
        "Core banking system integration (real-time balance, transactions, holds)",
        "Card management system access (status, limits, fraud flags)",
        "Loan origination system connectivity (application status, documents)",
        "CRM with full relationship view (all products, interactions, lifetime value)",
        "Knowledge base with product terms, policies, and regulatory requirements",
      ], vendors: "FIS, Fiserv, Jack Henry, Temenos, Salesforce FSC", risk: "Agent desktop requiring 3+ separate logins to serve one customer" },
    ],
  },
  "credit-unions": {
    name: "Credit Unions",
    parent: "Financial Services",
    tagline: "Member-centric service with relationship depth. Smaller operations but higher trust expectations.",
    intro: "Credit union contact centers serve members who chose a relationship-first institution over a megabank. The CX expectation is personal, empathetic, and community-aware. The operational challenge is delivering that experience with smaller teams, tighter budgets, and the same regulatory requirements as banks ten times their size.",
    kpis: [
      { metric: "AHT", avg: "6:20", note: "Longer than retail banking — members expect relationship-depth conversations" },
      { metric: "FCR", avg: "75%", note: "Higher than banks — smaller product set and deeper member knowledge" },
      { metric: "CSAT", avg: "84%", note: "Consistently higher than banks — member loyalty drives satisfaction" },
      { metric: "Containment", avg: "18%", note: "Lower than banks — members prefer human interaction for trust" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Member satisfaction tracking tied to retention and share-of-wallet", "Regulatory compliance recording meeting NCUA examination requirements", "Quality scoring that values relationship depth alongside efficiency", "Member lifecycle analytics — onboarding, engagement, and attrition signals", "Peer credit union benchmarking for service level comparison"], vendors: "NICE, Verint, Qualtrics", risk: "Over-optimizing for efficiency at the cost of member relationship quality" },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Relationship-aware routing matching members to their preferred representative", "Small-team queue management balancing coverage with personalization", "After-hours routing to shared service cooperatives or answering services", "Escalation paths that keep members within the credit union ecosystem", "Branch-to-contact-center warm transfer with full context"], vendors: "Genesys, NICE CXone, Cisco, 8x8", risk: "Small team size creating single-point-of-failure for specialized queries" },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure messaging for loan applications and account servicing", "Video banking connecting remote members with in-branch specialists", "Community-aware chat reflecting credit union brand voice and values", "Mobile app messaging integrated with online banking platform", "Proactive outreach for rate changes, dividend notices, and community events"], vendors: "Glia, Unblu, POPi/o, Ada", risk: "Digital channels feeling impersonal in a relationship-first institution" },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Balance and transaction bots sized for credit union core banking systems", "Loan pre-qualification AI with member-specific rate calculation", "Payment and transfer automation with share account logic", "FAQ bots covering credit union-specific products (share certificates, SEGs)", "After-hours self-service for card management and basic inquiries"], vendors: "Kasisto, Cognigy, Google CCAI", risk: "Bot interactions undermining the personal touch members expect" },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["NCUA regulatory compliance controls and examination readiness", "BSA/AML monitoring integration for suspicious activity reporting", "Member authentication meeting FFIEC guidance for digital channels", "TCPA compliance for outbound member communications", "Share insurance disclosure requirements in automated interactions"], vendors: "Pindrop, LexisNexis, Verafin", risk: "Regulatory gaps due to smaller compliance teams" },
      { layer: 2, name: "Workflow Execution", capabilities: ["New member onboarding workflow with account funding and card issuance", "Loan application workflow sized for credit union approval processes", "Dispute resolution workflow meeting NCUA timeline requirements", "Membership eligibility verification workflow for SEG-based credit unions", "Deceased member account handling with required notifications"], vendors: "Symitar workflows, MuleSoft, UiPath", risk: "Manual processes surviving because 'we've always done it this way'" },
      { layer: 1, name: "Data Access", capabilities: ["Core system integration (Symitar, Corelation, DNA, CU*BASE)", "Card processing system connectivity (PSCU, CO-OP, Visa DPS)", "Loan origination system access for application status and decisions", "Online/mobile banking platform integration for session continuity", "Member relationship view spanning all share and loan accounts"], vendors: "Symitar (Jack Henry), Corelation, CU*Answers, CUNA Mutual", risk: "Legacy core systems with limited API capability" },
    ],
  },
  "insurance": {
    name: "Insurance (P&C, Life, Health)",
    parent: "Financial Services",
    tagline: "Claims, policy servicing, renewals, FNOL, underwriting support, and high-emotion journeys.",
    intro: "Insurance contact centers operate at the intersection of complex policy logic, emotionally charged claims interactions, and regulatory compliance that varies by state and line of business. The CX challenge is guiding policyholders through processes they rarely understand, at moments when they are often distressed, while maintaining the accuracy that prevents E&O exposure.",
    kpis: [
      { metric: "AHT", avg: "9:00", note: "Longest in FS — claims and policy changes require detailed documentation" },
      { metric: "FCR", avg: "65%", note: "Below average — multi-party coordination (adjuster, provider, agent) prevents single-call resolution" },
      { metric: "CSAT", avg: "77%", note: "Driven by claims experience — fast FNOL and transparent status improve satisfaction" },
      { metric: "Containment", avg: "12%", note: "Very low — policy complexity and emotional stakes limit automation suitability" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Claims cycle time analytics by line of business and adjuster", "Policyholder sentiment tracking across the claims lifecycle", "State-specific compliance monitoring for disclosures and timelines", "Agent E&O risk scoring based on interaction quality audits", "Retention analytics linking service quality to policy renewal rates"], vendors: "NICE, Verint, Qualtrics, Medallia", risk: "Claims handling errors creating E&O exposure and regulatory action" },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["FNOL priority routing with catastrophe-event surge protocols", "Line-of-business routing (P&C, life, health, commercial)", "Licensed agent routing for policy binding and coverage advice", "Catastrophe event routing with geographic and peril-based triage", "Adjuster-to-policyholder callback scheduling and warm transfer"], vendors: "Genesys, NICE CXone, Talkdesk Insurance", risk: "Catastrophe events overwhelming capacity without surge routing" },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure document upload for claims photos, receipts, and police reports", "Video damage assessment for property and auto claims", "Proactive claims status notifications at each milestone", "Empathy-scripted messaging for total loss and denial communications", "Agent-to-adjuster collaboration tools within the interaction"], vendors: "Glia, LivePerson, Sprinklr, Unblu", risk: "Impersonal automated messages during high-emotion claims moments" },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["FNOL intake bots collecting required information by peril type", "Policy lookup and coverage verification automation", "Claims status bots with adjuster assignment and timeline visibility", "Premium payment and billing inquiry automation", "Renewal quote comparison bots for retention offers"], vendors: "Cognigy, Kore.ai, EIS AI, Duck Creek AI", risk: "Bot handling coverage questions without licensed-agent oversight" },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["State DOI compliance controls for claims handling timelines", "Unfair claims practices act adherence monitoring", "Recorded statement protocols with required disclosures", "Anti-fraud detection integrated into FNOL and claims workflows", "E&O risk controls requiring supervisor review for coverage determinations"], vendors: "Verisk, LexisNexis, SAS, Shift Technology", risk: "State-specific timeline violations triggering regulatory penalties" },
      { layer: 2, name: "Workflow Execution", capabilities: ["FNOL workflow with peril-specific data collection requirements", "Claims assignment workflow routing to available adjuster by specialization", "Subrogation tracking workflow with third-party coordination", "Policy endorsement workflow with premium recalculation triggers", "Renewal retention workflow with competitive rate comparison and save offers"], vendors: "Guidewire, Duck Creek, Majesco, Pega", risk: "Paper-based processes surviving in a digital-first expectation environment" },
      { layer: 1, name: "Data Access", capabilities: ["Policy administration system integration (coverage, endorsements, billing)", "Claims management system connectivity (FNOL, reserves, payments)", "Agent/broker portal integration for producer-initiated service", "Document management system for claims files and correspondence", "Actuarial and underwriting data for real-time eligibility decisions"], vendors: "Guidewire, Duck Creek, Majesco, Sapiens, Socotra", risk: "Legacy policy admin systems with batch-only data updates" },
    ],
  },
  "wealth-management": {
    name: "Wealth Management & Advisory",
    parent: "Financial Services",
    tagline: "Portfolio inquiries, advisor scheduling, compliance-sensitive communications, and high-value retention.",
    intro: "Wealth management contact centers serve clients whose relationship value can exceed seven figures. Every interaction carries revenue risk. The CX challenge is providing white-glove service with institutional-grade compliance — personalized enough to feel bespoke, governed enough to satisfy regulators.",
    kpis: [
      { metric: "AHT", avg: "11:00", note: "Longest sub-vertical — complex portfolio discussions and compliance requirements" },
      { metric: "FCR", avg: "78%", note: "Higher than insurance — dedicated advisors reduce handoff friction" },
      { metric: "CSAT", avg: "85%", note: "Highest in FS — high-touch service model with relationship continuity" },
      { metric: "Containment", avg: "8%", note: "Lowest in FS — clients expect human interaction for financial decisions" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Client satisfaction tracking tied to AUM retention and wallet share", "Compliance surveillance for suitability and best-interest obligations", "Advisor performance analytics with client outcome correlation", "Client lifecycle analytics — onboarding, engagement, and attrition risk", "Regulatory examination readiness dashboards"], vendors: "NICE, Verint, Smarsh, Global Relay", risk: "Surveillance gaps creating SEC/FINRA examination exposure" },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Named-advisor routing connecting clients to their dedicated relationship manager", "Licensed representative routing for trading, options, and margin inquiries", "Escalation to compliance for complex suitability questions", "After-hours routing to qualified backup advisors with client context", "Priority routing for high-AUM clients and significant market events"], vendors: "Genesys, NICE CXone, Cisco", risk: "Client reaching an unlicensed representative for investment questions" },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure client portal messaging with document sharing and e-signature", "Video conferencing for portfolio reviews and financial planning sessions", "Screen sharing for platform navigation and trade execution guidance", "Compliant SMS and messaging with archival and supervision", "Proactive market event communications and portfolio impact notifications"], vendors: "Glia, Unblu, Zoom, Symphony", risk: "Unarchived communications creating compliance violations" },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Account balance and position lookup bots with real-time market data", "Transfer and money movement automation with compliance checks", "Tax document request and delivery automation (1099, K-1)", "Appointment scheduling bots for advisor consultations", "Basic market data and research access bots"], vendors: "Kasisto, Cognigy, Salesforce Einstein", risk: "AI providing investment guidance without suitability controls" },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["SEC/FINRA compliance controls for all client communications", "Suitability and best-interest obligation enforcement at interaction level", "Anti-money laundering and suspicious activity reporting integration", "Communication archival meeting SEC 17a-4 and FINRA 3110 requirements", "Restricted trading list enforcement during client interactions"], vendors: "Smarsh, Global Relay, NICE Actimize, Verint", risk: "Compliance violations from unmonitored communication channels" },
      { layer: 2, name: "Workflow Execution", capabilities: ["New account opening workflow with KYC, suitability, and funding", "Account transfer (ACAT) workflow with timeline tracking and status", "Beneficiary change workflow with proper documentation and verification", "Required minimum distribution (RMD) workflow with tax implications", "Client review preparation workflow aggregating performance and holdings"], vendors: "Salesforce WM, SS&C, Pega, Appian", risk: "Manual processes creating delays in time-sensitive transfers" },
      { layer: 1, name: "Data Access", capabilities: ["Portfolio management system integration (holdings, performance, allocations)", "Custodial platform connectivity (Schwab, Fidelity, Pershing)", "Financial planning software integration (eMoney, MoneyGuidePro)", "CRM with complete relationship view and interaction history", "Market data feeds for real-time portfolio context during interactions"], vendors: "SS&C Advent, Orion, Black Diamond, Salesforce WM, Wealthbox", risk: "Advisor and service team seeing different client data" },
    ],
  },
  "lending-mortgage": {
    name: "Lending & Mortgage",
    parent: "Financial Services",
    tagline: "Application status, document collection, rate inquiries, closing coordination, and servicing.",
    intro: "Lending and mortgage contact centers manage the most complex, longest-duration customer journeys in financial services. A single mortgage interaction can span 45-90 days from application to close, involving multiple parties, document exchanges, and regulatory milestones. The CX challenge is maintaining borrower confidence through a process most consumers find opaque and stressful.",
    kpis: [
      { metric: "AHT", avg: "8:30", note: "Long — rate explanations, document requirements, and status updates are inherently complex" },
      { metric: "FCR", avg: "58%", note: "Very low — multi-party coordination and document dependencies prevent single-call resolution" },
      { metric: "CSAT", avg: "74%", note: "Below FS average — process opacity and timeline uncertainty suppress satisfaction" },
      { metric: "Containment", avg: "15%", note: "Low — borrowers want human confirmation for high-stakes financial decisions" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Pipeline conversion analytics from application to close", "Borrower satisfaction tracking at each milestone (application, UW, closing)", "TRID and RESPA compliance monitoring for disclosure timelines", "Agent quality scoring for rate lock explanations and fee transparency", "Fall-through analysis identifying where borrowers abandon the process"], vendors: "NICE, Verint, Qualtrics", risk: "TRID timing violations creating regulatory and rescission risk" },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Pipeline-stage routing connecting borrowers to their assigned loan officer", "Rate lock urgency routing during volatile market conditions", "Closing coordination routing connecting borrowers with title, escrow, and settlement", "Retention routing for borrowers exploring refinance with competitors", "After-hours routing for rate inquiries during evening and weekend research"], vendors: "Genesys, NICE CXone, Five9", risk: "Borrower reaching a generic agent during a rate-lock-critical window" },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure document upload portal for income, asset, and property documentation", "Co-browsing for online application assistance and document review", "Proactive milestone notifications (application received, UW decision, clear-to-close)", "Video for complex rate comparison and closing disclosure review", "SMS alerts for document requests and deadline reminders"], vendors: "Glia, Blend, LivePerson", risk: "Borrower receiving conflicting rate information across channels" },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Application status bots with pipeline stage and next-step guidance", "Document checklist bots tracking what's been received and what's outstanding", "Rate quote bots with real-time pricing engine integration", "Payment calculator bots with taxes, insurance, and PMI estimates", "Pre-qualification bots collecting initial borrower information"], vendors: "Kasisto, Cognigy, Blend AI", risk: "AI quoting rates without proper disclosures and licensing" },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["TRID compliance automation for Loan Estimate and Closing Disclosure timelines", "ECOA and fair lending monitoring across all interaction channels", "RESPA controls for settlement service referrals and fee disclosures", "NMLS licensing verification for agents providing rate and product advice", "State-specific disclosure requirements automated by borrower location"], vendors: "Wolters Kluwer, Black Knight Compliance, ICE", risk: "Fair lending violations from inconsistent rate communication" },
      { layer: 2, name: "Workflow Execution", capabilities: ["Loan application intake workflow with automated AUS submission", "Document collection workflow with intelligent follow-up sequencing", "Underwriting condition clearance workflow with borrower notification", "Closing scheduling workflow coordinating title, settlement, and notary", "Post-close onboarding workflow with servicing transfer communication"], vendors: "Encompass (ICE), Blend, MuleSoft, Byte", risk: "Manual document chasing creating timeline delays and borrower frustration" },
      { layer: 1, name: "Data Access", capabilities: ["Loan origination system integration (Encompass, Byte, Calyx)", "Pricing engine connectivity for real-time rate and fee calculation", "AUS integration (DU, LPA) for automated underwriting decisions", "Title and settlement system connectivity for closing coordination", "Servicing platform integration for post-close inquiries and payments"], vendors: "ICE (Encompass), Black Knight, Sagent, FICS", risk: "Disconnected origination and servicing systems creating post-close confusion" },
    ],
  },
  "fintech-neobanks": {
    name: "Fintech & Neobanks",
    parent: "Financial Services",
    tagline: "Digital-native service models with app-first support and instant resolution expectations.",
    intro: "Fintech and neobank contact centers are born digital. Customers chose these institutions specifically because they promise faster, simpler, and more transparent financial experiences. The CX bar is set by the app experience, and the contact center must match that speed and simplicity — or the customer leaves for the next fintech with a better onboarding flow.",
    kpis: [
      { metric: "AHT", avg: "4:00", note: "Fastest in FS — digital-native customers expect speed and chat-first resolution" },
      { metric: "FCR", avg: "78%", note: "Above average — simpler product sets and integrated systems reduce handoffs" },
      { metric: "CSAT", avg: "82%", note: "High — digital-native users value speed and self-service availability" },
      { metric: "Containment", avg: "40%", note: "Highest in FS — app-native self-service and chat bots handle most transactional queries" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Real-time app experience monitoring with support trigger correlation", "CSAT embedded in app post-interaction with one-tap feedback", "Support volume analytics correlated to product releases and outages", "Agent productivity tracking across chat, email, and in-app messaging", "Regulatory compliance dashboards meeting charter/license requirements"], vendors: "NICE, Amplitude, Mixpanel, Qualtrics", risk: "Scaling support without losing the speed that defines the brand" },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["In-app support routing with full session context and user journey data", "Priority routing based on account value, tenure, and issue severity", "Fraud alert routing with immediate account freeze capability", "Engineering escalation routing for product bugs surfaced through support", "Queue-less routing — chat-first with callback as overflow only"], vendors: "Intercom, Zendesk, Genesys", risk: "Growing call volume undermining the digital-first brand promise" },
      { layer: 5, name: "Conversation Management", capabilities: ["In-app messaging as the primary support channel", "Async chat allowing customers to continue conversations across sessions", "Push notification support for proactive updates and resolutions", "Screen recording and co-browsing for app navigation assistance", "Community forums and help center as first line of self-service"], vendors: "Intercom, Zendesk, Ada, Kustomer", risk: "Forcing customers to call when the entire brand is built on not calling" },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Transaction dispute bots with instant provisional credit logic", "Card management bots (freeze, unfreeze, replace, set limits)", "Account verification and KYC completion bots", "Spending insights and budgeting tool support bots", "Fee explanation and waiver bots with policy-based decisioning"], vendors: "Ada, Forethought, Intercom Fin, Cognigy", risk: "Bot limitations frustrating users who expect everything to work in-app" },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Charter/license compliance appropriate to entity type (bank, money transmitter)", "BSA/AML controls meeting regulatory expectations for digital-only institutions", "Strong customer authentication for account changes and high-value transfers", "Dispute resolution compliance meeting Reg E timelines", "Data privacy controls meeting state-by-state requirements"], vendors: "Alloy, Sardine, Unit21, Plaid", risk: "Regulatory scrutiny increasing as fintechs grow beyond startup scale" },
      { layer: 2, name: "Workflow Execution", capabilities: ["Instant account opening workflow with real-time identity verification", "Dispute resolution workflow with automated provisional credit and investigation", "Account closure workflow with balance transfer and regulatory holds", "Referral and reward redemption workflow with real-time tracking", "Compliance case management workflow for suspicious activity"], vendors: "Alloy, Plaid, Unit, Treasury Prime", risk: "Speed-first culture creating compliance shortcuts" },
      { layer: 1, name: "Data Access", capabilities: ["Banking-as-a-service platform integration (Unit, Treasury Prime, Synapse)", "Payment processor connectivity (Marqeta, Galileo, i2c)", "Identity verification platform integration (Alloy, Plaid Identity)", "Product analytics platform integration for user context during support", "Internal knowledge base with product release notes and known issues"], vendors: "Unit, Treasury Prime, Marqeta, Galileo, Plaid", risk: "Third-party dependency on BaaS providers for real-time data access" },
    ],
  },
  "payments-processing": {
    name: "Payments & Processing",
    parent: "Financial Services",
    tagline: "Merchant support, transaction disputes, terminal troubleshooting, and settlement inquiries.",
    intro: "Payments and processing contact centers serve two distinct audiences — merchants (B2B) and cardholders (B2C) — often from the same operation. The CX challenge is maintaining technical depth for merchant terminal and integration support while delivering consumer-grade experience for cardholder disputes and transaction inquiries. Every minute of downtime for a merchant is lost revenue.",
    kpis: [
      { metric: "AHT", avg: "7:30", note: "Mixed — consumer inquiries are fast, merchant technical support is long" },
      { metric: "FCR", avg: "70%", note: "Average — merchant issues often require escalation to technical or risk teams" },
      { metric: "CSAT", avg: "76%", note: "Below average — merchant frustration with hold times and technical complexity" },
      { metric: "Containment", avg: "22%", note: "Transaction lookups are automatable; terminal troubleshooting requires humans" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Merchant satisfaction tracking segmented by volume tier and industry", "Transaction dispute analytics with chargeback ratio monitoring", "PCI compliance audit readiness across all interaction channels", "Technical support resolution analytics by terminal type and issue category", "Settlement discrepancy tracking and root cause analysis"], vendors: "NICE, Verint, Qualtrics", risk: "Chargeback ratios exceeding card network thresholds" },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["B2B vs B2C routing separating merchant and cardholder queues", "Merchant tier routing prioritizing high-volume and enterprise accounts", "Technical support routing by terminal type, gateway, and integration method", "Risk and fraud routing for suspicious transaction patterns", "Settlement and funding urgency routing for merchant cash flow issues"], vendors: "Genesys, NICE CXone, Five9", risk: "High-value merchants waiting in general queue during outages" },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure merchant portal with case management and knowledge base", "Screen sharing for terminal configuration and gateway troubleshooting", "Proactive outreach for settlement delays and processing changes", "Developer support chat for API integration and webhook issues", "Cardholder dispute intake with required documentation collection"], vendors: "Zendesk, Intercom, Freshdesk, Salesforce Service", risk: "Developer support quality not matching the technical depth required" },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Transaction lookup bots with real-time authorization and settlement data", "Cardholder dispute intake bots collecting required Reg E information", "Merchant statement and fee explanation bots", "Terminal activation and basic troubleshooting bots", "Settlement status and funding timeline bots"], vendors: "Ada, Cognigy, Forethought", risk: "Bot mishandling dispute intake and missing required data fields" },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["PCI DSS Level 1 compliance across all interaction channels", "Card network (Visa, Mastercard) dispute handling rule compliance", "Reg E and Reg Z compliance for consumer transaction disputes", "Merchant underwriting and risk monitoring integration", "Anti-money laundering controls for suspicious merchant activity"], vendors: "Verisk, Ethoca, NICE Actimize", risk: "PCI scope creep as channels expand beyond voice" },
      { layer: 2, name: "Workflow Execution", capabilities: ["Merchant onboarding workflow with underwriting and terminal provisioning", "Chargeback response workflow with evidence collection and network deadlines", "Terminal replacement and shipping workflow with configuration migration", "Rate review and repricing workflow for merchant retention", "Merchant account closure workflow with reserve hold and settlement"], vendors: "Salesforce, Pega, MuleSoft", risk: "Chargeback response deadlines missed due to manual evidence collection" },
      { layer: 1, name: "Data Access", capabilities: ["Payment gateway integration (real-time authorization, settlement, batch data)", "Terminal management system connectivity (deployment, configuration, firmware)", "Merchant portfolio system (pricing, statements, risk flags)", "Card network portals (Visa Resolve Online, Mastercard Connect)", "Cardholder account data for dispute resolution and fraud investigation"], vendors: "Adyen, Stripe, Worldpay, Fiserv, Global Payments", risk: "Fragmented data across acquirer, processor, and gateway systems" },
    ],
  },
};

export const getSubVertical = (slug) => fsSubVerticals[slug];
export const getAllSubVerticalSlugs = () => Object.keys(fsSubVerticals);
