export const governmentSubVerticals = {
  "federal": {
    name: "Federal Government", parent: "Government & Public Sector",
    tagline: "Agency citizen services, benefits, immigration, tax, and veterans affairs.",
    intro: "Federal contact centers operate at a scale and under constraints that no private sector operation faces. The IRS handles 200+ million calls per year. SSA serves 70 million beneficiaries. VA supports 9 million veterans. The CX challenge is delivering responsive, accessible, equitable service across massive populations with legacy technology, unionized workforces, and procurement cycles that take 12-18 months.",
    kpis: [
      { metric: "AHT", avg: "10:00", note: "Long — complex eligibility, multi-system lookups, and interpretation services" },
      { metric: "FCR", avg: "50%", note: "Very low — inter-agency referrals and system limitations prevent resolution" },
      { metric: "CSAT", avg: "69.7", note: "ACSI score — improving but still lowest across sectors" },
      { metric: "Containment", avg: "22%", note: "Below average — citizens often need human guidance for complex processes" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["OMB Circular A-11 citizen satisfaction measurement and reporting","Service level compliance against agency-specific targets","Language access monitoring ensuring Title VI compliance","Accessibility compliance tracking for Section 508","Congressional/constituent inquiry tracking and resolution"], vendors: "NICE, Verint, Qualtrics, Medallia", risk: "OMB reporting gaps creating congressional scrutiny",
        stack: [{ name: "Medallia", role: "Citizen Experience", why: "Used by multiple federal agencies for OMB A-11 required satisfaction measurement. Connects citizen feedback to service delivery improvements with mandated reporting.", href: "/vendors/analytics" }, { name: "NICE CXone", role: "QA & Compliance", why: "FedRAMP authorized. Compliance-scored QA for federal interactions. Monitors language access, accessibility, and service equity across populations.", href: "/vendors/nice-cxone" }],
        pitfall: "OMB Circular A-11 Section 280 requires High Impact Service Providers (HISPs) to measure and report citizen satisfaction. But most agencies measure satisfaction after the interaction rather than satisfaction with the outcome. A citizen who reaches an agent quickly, gets treated politely, and is told 'your application is still pending after 6 months' will rate the interaction positively — but their experience with the service is terrible. Measure outcome satisfaction, not just interaction satisfaction."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Multi-program routing across agency service lines","Language-based routing supporting 200+ languages via interpretation","TTY/video relay routing for deaf and hard-of-hearing citizens","Veterans priority routing meeting VA PACT Act requirements","Disaster response routing for FEMA and emergency benefit programs"], vendors: "Genesys, NICE CXone, Amazon Connect, Cisco", risk: "Non-English-speaking citizen unable to reach language-appropriate service",
        stack: [{ name: "Amazon Connect", role: "CCaaS", why: "AWS GovCloud with FedRAMP High authorization. Pay-per-use pricing aligns with federal budget constraints. AI capabilities (Lex, Contact Lens) for citizen self-service. Growing federal adoption.", href: "/vendors/amazon-connect" }, { name: "Genesys Cloud", role: "CCaaS", why: "FedRAMP authorized with federal deployment experience. Handles the routing complexity of multi-program agencies serving diverse populations.", href: "/vendors/genesys" }],
        pitfall: "Federal language access is not optional — Title VI requires meaningful access for Limited English Proficiency (LEP) individuals. This means the contact center must provide interpretation in 200+ languages — not just Spanish. Most agencies contract with Language Line or similar over-the-phone interpretation services, but the handoff adds 2-3 minutes per call and creates a three-way conversation that frustrates all parties. Invest in bilingual agents for top-volume languages and streamline the interpretation handoff for others."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Citizen portal integration (Login.gov, agency-specific portals)","Proactive notifications for benefit status, deadlines, and policy changes","Accessible digital channels meeting WCAG 2.1 AA standards","Secure document upload for benefit applications and supporting evidence","Multi-channel communication respecting citizen channel preferences"], vendors: "Granicus, Adobe Experience, Salesforce Gov Cloud", risk: "Digital channels not meeting Section 508 accessibility standards",
        stack: [{ name: "Granicus", role: "Government Communications", why: "Purpose-built government communications platform. Email, SMS, and web notifications for government agencies. Accessible by design. Used by thousands of federal, state, and local agencies.", href: "/vendors" }, { name: "Adobe Experience Manager", role: "Digital Experience", why: "Federal-approved content management powering accessible citizen-facing websites and portals. Strong Section 508 compliance tooling.", href: "/vendors" }],
        pitfall: "Government digital channels must be accessible from day one — not retrofitted after launch. Section 508 requires that all electronic and information technology be accessible to people with disabilities. A chatbot that can't be navigated by screen reader, a portal that lacks keyboard navigation, or a form that doesn't support assistive technology isn't just bad CX — it's a legal violation. Test with actual assistive technology users before deployment."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Benefits eligibility screening bots with program-specific criteria","Case status bots across agency programs","FAQ bots covering hundreds of federal programs and services","Appointment scheduling bots for in-person service delivery","Document requirement guidance bots for applications and renewals"], vendors: "Amazon Lex, Google CCAI, Ada (via integrator)", risk: "Bot providing incorrect eligibility information that the citizen relies on",
        stack: [{ name: "Amazon Lex", role: "Conversational AI", why: "Native to AWS GovCloud. FedRAMP authorized. Handles citizen self-service for benefit status, appointment scheduling, and FAQ. Integrates with Connect for seamless bot-to-agent handoff.", href: "/vendors/iva" }, { name: "Google CCAI", role: "AI Platform", why: "FedRAMP authorized Dialogflow and Agent Assist. Strong NLU for complex government program terminology. Virtual agent and agent assist capabilities.", href: "/vendors/iva" }],
        pitfall: "Federal benefit eligibility is extraordinarily complex — SNAP eligibility alone involves income, household size, work requirements, immigration status, and state-specific rules. A bot that says 'you may be eligible' when the citizen isn't (or 'you're not eligible' when they are) creates real harm — missed benefits or wasted application effort. Either build comprehensive eligibility logic (expensive) or limit the bot to 'based on what you've told me, here's how to apply — the agency will determine eligibility.' Never give a definitive eligibility answer from a bot."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FedRAMP authorization for all cloud services","FISMA compliance for information security","Section 508 accessibility for all citizen-facing technology","Title VI language access for LEP populations","PII protection under the Privacy Act and E-Government Act"], vendors: "FedRAMP-certified vendors only", risk: "Non-FedRAMP system processing citizen PII creating security and compliance violation",
        stack: [{ name: "FedRAMP-authorized platforms", role: "Security Compliance", why: "Every cloud service touching federal data must have FedRAMP authorization — Moderate for most agencies, High for sensitive data. This eliminates many commercial CX vendors from consideration. Check the FedRAMP marketplace before evaluating.", href: "/vendors" }],
        pitfall: "FedRAMP authorization takes 6-18 months and costs vendors $500K-$2M. This means the innovative startup with the best CX technology often can't sell to federal agencies because they haven't completed FedRAMP. Federal CX leaders must balance innovation desire with security compliance reality. Work with vendors who have FedRAMP authorization or are actively in process — don't select a vendor and then discover they can't get authorized."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Benefits application and enrollment workflow with eligibility determination","Case management workflow spanning intake, investigation, and resolution","FOIA request processing workflow with document review and redaction","Congressional inquiry workflow with tracking and response timeline","Disaster benefit application workflow for emergency programs"], vendors: "Salesforce Government Cloud, Pega, Appian, ServiceNow", risk: "Benefits processing backlog creating citizen hardship without proactive communication",
        stack: [{ name: "Salesforce Government Cloud", role: "Case Management", why: "FedRAMP authorized CRM and case management. Used by multiple federal agencies for citizen relationship management, case tracking, and service delivery workflow.", href: "/vendors/ccaas" }, { name: "Pega", role: "Process Orchestration", why: "Government-grade case management and decisioning. Handles the complex eligibility rules and multi-step workflows federal benefits programs require.", href: "/vendors" }],
        pitfall: "Federal benefits processing backlogs are the #1 citizen CX failure — and the contact center absorbs the frustration. When Social Security disability applications take 6-12 months, every applicant calls monthly for status. The agent can only say 'it's still processing.' Build proactive milestone notifications: application received, assigned to reviewer, additional documentation needed, decision pending, decision issued. Each notification prevents a status call."
      },
      { layer: 1, name: "Data Access", capabilities: ["Agency case management systems (often legacy mainframe)","Identity verification (Login.gov, ID.me)","Inter-agency data sharing (where authorized)","Financial systems for benefit payments and accounting","Document management for applications, evidence, and correspondence"], vendors: "Legacy mainframes, Oracle, SAP, Salesforce, Login.gov", risk: "COBOL mainframe limiting real-time data access for contact center agents",
        stack: [{ name: "Login.gov", role: "Identity", why: "Federal identity verification platform providing secure citizen authentication across agencies. Single sign-on for government services. The identity layer that enables multi-agency citizen service.", href: "/vendors" }, { name: "Salesforce Government Cloud", role: "CRM", why: "Modern CRM layer on top of legacy systems. Provides the agent-friendly interface that legacy mainframes can't offer while connecting to existing systems of record.", href: "/vendors/ccaas" }],
        pitfall: "The fundamental federal CX technology challenge: critical benefit data lives in COBOL mainframes from the 1970s-1990s that can't expose real-time APIs. SSA, IRS, and VA all run on legacy systems that process in batch. The contact center agent queries the mainframe terminal, waits for a response, and translates green-screen data into citizen-friendly language. Modernization is a decade-long effort. In the meantime, build middleware (MuleSoft, Boomi) that provides near-real-time access through API wrappers around mainframe queries."
      },
    ],
  },

  "state": {
    name: "State Government", parent: "Government & Public Sector",
    tagline: "DMV, unemployment, Medicaid, licensing, and tax — the most interaction-intensive government level.",
    intro: "State government contact centers handle the interactions citizens encounter most frequently — driver's licenses, unemployment benefits, Medicaid enrollment, professional licensing, and state taxes. The CX challenge is breadth: a single state government may operate 30+ separate contact centers across different agencies with different systems, different cultures, and different funding models.",
    kpis: [
      { metric: "AHT", avg: "8:30", note: "Long — DMV, unemployment, and Medicaid are complex multi-step processes" },
      { metric: "FCR", avg: "52%", note: "Low — inter-agency referrals and eligibility complexity prevent resolution" },
      { metric: "CSAT", avg: "65", note: "Lowest government level — DMV and unemployment drive down scores" },
      { metric: "Containment", avg: "20%", note: "Low — eligibility questions and document requirements need human guidance" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Agency-specific satisfaction tracking across 10+ service lines","Unemployment claim processing time and citizen communication analytics","DMV wait time and transaction completion analytics","Medicaid enrollment success rate and abandonment tracking","Legislative reporting on service levels and citizen complaints"], vendors: "NICE, Verint, Qualtrics", risk: "Governor's office receiving citizen complaints without agency performance context",
        stack: [{ name: "NICE CXone", role: "QA & Analytics", why: "Multi-agency analytics on one platform. Allows state CIO offices to benchmark agency performance against each other and identify which agencies need investment.", href: "/vendors/nice-cxone" }],
        pitfall: "State governments run 20-40 separate contact centers across agencies — each with different technology, metrics, and management. The citizen sees one state government; the state operates as disconnected silos. A statewide CX dashboard that aggregates satisfaction, wait time, and FCR across agencies gives the Governor's office and legislature visibility into which agencies are performing and which need help."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Multi-agency routing — citizens often call the wrong agency first","Unemployment surge routing during economic downturns","DMV appointment scheduling and walk-in queue management","Medicaid enrollment routing with eligibility pre-screening","Tax season routing with dedicated teams for filing assistance"], vendors: "Genesys, NICE CXone, Amazon Connect, Cisco", risk: "Citizen transferred between 3 agencies before reaching the right one",
        stack: [{ name: "Amazon Connect", role: "CCaaS", why: "StateRAMP authorized with pay-per-use pricing that fits state budget cycles. Multiple state agencies have standardized on Connect for cost control and cloud modernization.", href: "/vendors/amazon-connect" }, { name: "Genesys Cloud", role: "CCaaS", why: "Multi-agency routing connecting citizens to the right agency on the first call. Handles the complexity of 30+ service lines with different SLAs and staffing models.", href: "/vendors/genesys" }],
        pitfall: "The #1 state government CX failure: a citizen calls about unemployment, gets transferred to the tax department, gets transferred to workforce development, and finally reaches unemployment — after 45 minutes. Build a state-level front door (IVR or bot) that accurately classifies the citizen's need and routes to the right agency on the first attempt. Cross-agency routing eliminates 20-30% of transfers."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Citizen portal integration for self-service across state agencies","Proactive notifications for benefit status, deadlines, and renewals","Multilingual communication for diverse state populations","Accessible channels meeting state accessibility requirements","Appointment scheduling for DMV, licensing, and in-person services"], vendors: "Granicus, Adobe, Salesforce, custom portals", risk: "Benefit renewal deadlines missed because notifications didn't reach the citizen",
        stack: [{ name: "Granicus", role: "Government Communications", why: "Proactive notifications for benefit renewals, tax deadlines, and service changes. Multi-channel delivery. Used by thousands of state and local agencies.", href: "/vendors" }],
        pitfall: "Medicaid continuous enrollment unwound in 2023-2024, causing millions of beneficiaries to lose coverage — many because they didn't receive or understand renewal notices. Proactive, multi-channel renewal notifications (mail + email + SMS + phone) with clear deadlines and simple response paths prevent coverage gaps. The cost of one hospitalization for an uninsured person who should have been covered exceeds the cost of 10,000 renewal notifications."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Benefits eligibility screening bots for Medicaid, SNAP, and TANF","DMV transaction bots for registration renewal and appointment scheduling","Unemployment claim status bots with real-time case data","Tax filing status and refund tracking bots","Professional licensing renewal and status bots"], vendors: "Amazon Lex, Google CCAI, Cognigy, Ada", risk: "Bot incorrectly screening Medicaid eligibility and deterring eligible citizens from applying",
        stack: [{ name: "Amazon Lex", role: "Conversational AI", why: "Native to AWS. StateRAMP alignment. Handles DMV appointment scheduling, benefit status, and tax FAQ. Growing state government adoption alongside Connect.", href: "/vendors/iva" }],
        pitfall: "State benefit eligibility bots face a high-stakes accuracy challenge: incorrectly telling an eligible citizen they're 'not eligible' denies them benefits they're entitled to. Incorrectly telling an ineligible citizen they 'are eligible' creates a wasted application and disappointment. The safest bot approach for eligibility: 'Based on your answers, you may qualify — here's how to apply.' Never give a definitive yes or no from a bot on eligibility."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["StateRAMP or equivalent cloud security requirements","State-specific accessibility and language access mandates","Unemployment fraud detection and identity verification","Medicaid enrollment and renewal compliance (CMS requirements)","State privacy laws (varying by state — some stricter than federal)"], vendors: "StateRAMP-certified vendors, ID.me, LexisNexis", risk: "Unemployment fraud from identity verification failures in the contact center",
        stack: [{ name: "ID.me", role: "Identity Verification", why: "Identity verification for state government services. Used by 30+ state unemployment agencies and multiple state tax departments. Balances fraud prevention with citizen accessibility.", href: "/vendors" }],
        pitfall: "Unemployment fraud cost states $60B+ during COVID — primarily through identity theft. The contact center is both a fraud vector (social engineering to access accounts) and a fraud detection tool (agents noticing inconsistencies). Implement identity verification (ID.me) before granting account access, and train agents to recognize social engineering patterns. The balance between security and accessibility is the core tension."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Unemployment claim filing and weekly certification workflow","Medicaid application and renewal workflow with CMS compliance","DMV transaction workflow — licenses, registration, titles","Professional licensing application and renewal workflow","Tax filing assistance and refund tracking workflow"], vendors: "Salesforce Gov Cloud, Pega, Appian, Deloitte/Accenture custom", risk: "Unemployment claim processing taking 8+ weeks while citizens exhaust savings",
        stack: [{ name: "Salesforce Government Cloud", role: "Case Management", why: "Multi-agency case management standardizing citizen service across state programs. Growing state government adoption for Medicaid, unemployment, and licensing.", href: "/vendors/ccaas" }, { name: "Pega", role: "Process Automation", why: "Complex eligibility determination and case management. Handles the rules engine that Medicaid and unemployment require — income thresholds, work requirements, household composition.", href: "/vendors" }],
        pitfall: "State unemployment systems were designed for 5% unemployment rates. During recessions and pandemics, they face 15-25% rates — a 3-5x surge that collapses processing timelines. The contact center becomes the pressure release valve for a broken backend system. Build surge capacity into both the processing system and the contact center simultaneously — scaling one without the other just moves the bottleneck."
      },
      { layer: 1, name: "Data Access", capabilities: ["Benefits eligibility systems (Medicaid, SNAP, TANF, unemployment)","DMV systems — driver records, vehicle registration, titles","State tax systems — filing status, refund processing, audit","Professional licensing databases across 50+ license types","Inter-agency data sharing for integrated eligibility determination"], vendors: "Deloitte, Accenture, CGI custom systems, IBM mainframes", risk: "Legacy eligibility systems unable to provide real-time data to the contact center",
        stack: [{ name: "Custom/legacy systems", role: "State Operations", why: "Most state benefit systems are custom-built by Deloitte, Accenture, or CGI on contracts spanning 5-15 years. The contact center integrates with whatever the SI built — which varies dramatically by state.", href: "/vendors" }, { name: "Salesforce Government Cloud", role: "Modern CRM Layer", why: "Provides the modern agent desktop on top of legacy systems. Agents interact with Salesforce; Salesforce queries the legacy system via middleware. Faster than replacing the legacy system.", href: "/vendors/ccaas" }],
        pitfall: "State government IT is defined by system integrator (SI) contracts. The Medicaid system was built by Deloitte, the unemployment system by Accenture, and the DMV system by CGI — each on different technology, different timelines, and different data models. Cross-agency citizen service requires cross-system integration that these contracts weren't designed for. The CX layer (Salesforce, contact center) must bridge systems that were never meant to talk to each other."
      },
    ],
  },

  "local-municipal": {
    name: "Local & Municipal Government", parent: "Government & Public Sector",
    tagline: "311 services, permits, code enforcement, parks, public works, and constituent services.",
    intro: "Local government contact centers — typically 311 centers — are the front door for community services. They handle everything from potholes to park reservations to building permits to elected official constituent inquiries. The CX challenge is routing across dozens of city departments while providing the community-level accountability that citizens expect from their local government.",
    kpis: [
      { metric: "AHT", avg: "5:00", note: "Shorter — many 311 calls are simple reports and routing" },
      { metric: "FCR", avg: "60%", note: "Moderate — many requests require field dispatch or inter-department routing" },
      { metric: "CSAT", avg: "72", note: "Moderate — citizens appreciate responsiveness but frustrated by follow-through" },
      { metric: "Containment", avg: "25%", note: "Service requests and info queries automatable; complaints need humans" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Service request resolution time by department and request type","311 call reason analytics identifying top community issues","Council district performance comparison for equity monitoring","Citizen satisfaction by service type, neighborhood, and channel","Seasonal volume tracking for budget and staffing planning"], vendors: "NICE, Qualtrics, CRM analytics", risk: "Council members surprised by constituent complaints they weren't tracking",
        stack: [{ name: "NICE CXone", role: "311 Analytics", why: "Call reason tracking, wait time monitoring, and QA for 311 operations. Identifies which departments create the most citizen friction. Right-sized for 20-100 agent municipal operations.", href: "/vendors/nice-cxone" }],
        pitfall: "311 analytics must track not just call volume but resolution closure. A city that receives 500 pothole reports and closes 400 service requests sounds effective — until you discover that 200 of those closures were 'unable to locate' or 'no action required.' Track actual resolution (pothole filled, code violation corrected, permit issued), not just ticket closure."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Multi-department routing across 30+ city services","Elected official constituent inquiry priority routing","Emergency vs non-emergency classification","Geographic routing based on caller location and council district","Language routing for community demographic needs"], vendors: "Genesys, NICE CXone, Cisco, 8x8", risk: "Citizen calling about a gas leak reaching the parks department",
        stack: [{ name: "Genesys Cloud / NICE CXone", role: "311 CCaaS", why: "Multi-department routing connecting citizens to the right service area. Classification AI can determine whether 'water in my street' is a public works issue (broken main), a utility issue (meter leak), or a drainage issue (storm sewer) before routing.", href: "/vendors/genesys" }],
        pitfall: "311 routing requires local knowledge that standard IVR menus can't capture. A citizen calling about 'a tree blocking the road' might need: Public Works (if it's a city tree on a city road), Parks (if it's in a park), the utility (if it brought down a power line), or Emergency Management (if it's blocking an evacuation route). Intent classification for 311 must account for the city's specific department structure and service boundaries."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["311 mobile app with photo-based service request submission","Proactive city service notifications (road closures, water advisories, events)","Constituent inquiry tracking for elected officials","Self-service permit application and status portal","Community engagement communications for public meetings and budgets"], vendors: "SeeClickFix, Granicus, custom 311 apps", risk: "Citizens submitting the same pothole report 5 times because they can't see existing reports",
        stack: [{ name: "SeeClickFix", role: "311 Citizen Engagement", why: "Mobile 311 app with photo submission, real-time tracking, and community visibility. Citizens see existing reports in their area — reducing duplicate submissions. The standard for modern 311 digital engagement.", href: "/vendors" }, { name: "Granicus", role: "Government Communications", why: "City notifications, public meeting management, and citizen engagement. Multi-channel delivery for service alerts and community information.", href: "/vendors" }],
        pitfall: "The biggest 311 CX failure: citizens submit a service request and never hear back. 'Thank you for your report' followed by silence for 30 days is worse than no digital channel at all. Build automated status updates: request received → assigned to department → crew scheduled → work completed. Even if the update is 'your request is in queue,' it's better than silence."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["311 service request classification bots for routing","City services FAQ bots covering hours, locations, and procedures","Permit requirement and application status bots","Event and recreation program information bots","Utility payment and billing inquiry bots (for municipal utilities)"], vendors: "Ada, Amazon Lex, Google CCAI", risk: "Bot misclassifying a service request and routing to the wrong department",
        stack: [{ name: "Ada", role: "311 AI", why: "Handles FAQ, service request intake, and permit status. Routes complex constituent complaints to human agents. Good for cities adding digital self-service alongside phone 311.", href: "/vendors/iva" }],
        pitfall: "311 bots must handle an extremely broad service domain — every city department, every service type, every neighborhood-specific nuance. A bot that can answer 'when is bulk trash pickup in my neighborhood?' needs to know the city's specific pickup schedule by area. This data changes frequently and varies by location. Build a dynamic knowledge base that city departments update directly — not a static FAQ that goes stale in 60 days."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["ADA accessibility for citizen communications and self-service","Open records/FOIA compliance for recorded calls and citizen data","Language access requirements based on community demographics","EEO and equity compliance ensuring all communities receive equal service","Records retention requirements for citizen interactions"], vendors: "Municipal compliance, ADA", risk: "311 service levels varying by neighborhood creating equity concerns",
        stack: [{ name: "Municipal compliance", role: "Policy", why: "Local government compliance varies by municipality — some cities have specific accessibility ordinances, language access plans, and equity mandates that exceed state/federal requirements. Map your city's specific obligations.", href: "/vendors" }],
        pitfall: "311 service equity is increasingly measured and scrutinized — are affluent neighborhoods getting faster service request resolution than underserved communities? Geographic analytics showing response time by neighborhood, district, and demographic can reveal systemic inequity that the city needs to address. If the west side gets potholes fixed in 3 days and the east side waits 14 days, that's a policy problem the contact center data reveals."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Service request intake and routing to city departments","Permit application workflow from submission through inspection to issuance","Code enforcement complaint workflow with investigation and follow-up","Constituent inquiry workflow tracking elected official requests","Emergency notification workflow for weather, water, and safety events"], vendors: "Salesforce Gov Cloud, CityWorks, Tyler Technologies, Accela", risk: "Service requests assigned to departments but never picked up for action",
        stack: [{ name: "CityWorks", role: "Asset & Work Management", why: "Public works and infrastructure management. Service request routing to field crews with GPS tracking and work order completion. Connects 311 intake to physical service delivery.", href: "/vendors" }, { name: "Tyler Technologies", role: "Government ERP", why: "Comprehensive local government platform — finance, HR, permitting, courts, and utilities. The operational backbone for many municipal 311 operations.", href: "/vendors" }, { name: "Accela", role: "Permitting & Licensing", why: "Building permits, business licenses, and code enforcement. The system agents query when a citizen asks 'what's the status of my building permit?'", href: "/vendors" }],
        pitfall: "311 service requests create accountability when they're tracked end-to-end. If the contact center creates the request but the receiving department doesn't have a system to track it, the request disappears into email or paper. Implement a city-wide work management system (CityWorks, Cartegraph) that tracks every service request from intake through completion — with citizen-visible status updates."
      },
      { layer: 1, name: "Data Access", capabilities: ["CRM with citizen interaction history across all city services","Work management system for service requests and field operations","GIS for location-based service routing and geographic analytics","Permitting and licensing databases for application status","Financial system for payments, fees, and account balances"], vendors: "Tyler Technologies, CityWorks, ESRI, Accela, Salesforce", risk: "Agent unable to see a citizen's history across departments — every call starts from zero",
        stack: [{ name: "Tyler Technologies (Munis/EnerGov)", role: "Municipal ERP", why: "Financial, permitting, and utility billing data. The source of truth for 'how much is my water bill?' and 'what's the status of my permit?' Widely deployed in municipal government.", href: "/vendors" }, { name: "ESRI (ArcGIS)", role: "GIS", why: "Location intelligence for routing service requests to the right department and crew. Maps citizen-reported issues to city infrastructure. Powers outage maps, snow plow tracking, and service request visualization.", href: "/vendors" }],
        pitfall: "Municipal data is fragmented by department — public works has one system, utilities has another, permitting has a third. A citizen calling about their property might have a water bill, a building permit, a code violation, and a sidewalk repair request — in four different systems. The 311 agent needs a unified citizen view. Salesforce Government Cloud or a custom CRM layer can provide this, but the integration work across municipal systems is significant."
      },
    ],
  },

  "courts-justice": {
    name: "Courts & Justice", parent: "Government & Public Sector",
    tagline: "Case status, jury duty, fines, filing procedures, and victim services.",
    intro: "Court contact centers serve citizens navigating the most intimidating government institution. Litigants, jurors, witnesses, victims, and attorneys all call with different needs, different urgency, and different knowledge levels. The CX challenge is providing helpful guidance without providing legal advice — a line that's legally significant and operationally difficult to maintain.",
    kpis: [
      { metric: "AHT", avg: "6:00", note: "Moderate — case status is quick; filing procedures are complex" },
      { metric: "FCR", avg: "58%", note: "Low — many inquiries require clerk review or case-specific research" },
      { metric: "CSAT", avg: "68", note: "Below average — citizens are often stressed, confused, and frustrated" },
      { metric: "Containment", avg: "20%", note: "Case status and jury info automatable; filing questions need humans" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Case processing time analytics by case type and division","Juror satisfaction and compliance tracking","Fine payment collection rate and delinquency analytics","Language access monitoring for court proceedings and phone support","Self-help resource utilization and effectiveness tracking"], vendors: "NICE, custom analytics", risk: "Case processing delays invisible until backlog creates public concern",
        stack: [{ name: "NICE CXone", role: "QA & Analytics", why: "Monitors agent interactions for unauthorized legal advice — the most critical compliance requirement in court contact centers.", href: "/vendors/nice-cxone" }],
        pitfall: "Court contact center QA must specifically monitor for agents crossing the line from information (allowed) to legal advice (prohibited). 'You need to file a motion to continue' is legal advice. 'The form for requesting a continuance is available on our website' is information. Train agents on this distinction and build QA scoring that detects when agents cross the line."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Case type routing — criminal, civil, family, probate, traffic","Juror call-in routing with automated reporting instructions","Attorney vs self-represented litigant routing with different service models","Victim services routing to trained advocates","Fine payment and collection routing to financial services"], vendors: "Genesys, NICE CXone, Cisco", risk: "Domestic violence victim reaching general clerk instead of victim advocate",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Case-type routing with sensitivity-based classification. Routes victim services, domestic violence, and protective order inquiries to trained staff with appropriate handling protocols.", href: "/vendors/nice-cxone" }],
        pitfall: "Court calls involving domestic violence, child custody, and protective orders require trained staff who understand safety protocols — not general clerks. A victim calling about a protective order needs an agent who can explain the process without minimizing the urgency and who knows not to share case details with someone claiming to be 'the other party.' Build a victim services routing path with certified advocates."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Case status portal accessible to parties and attorneys","Jury duty notification and reporting via text and email","Fine and fee payment portal with payment plan options","Self-help resources for self-represented litigants","Court date reminder notifications via SMS and email"], vendors: "Tyler Technologies, Journal Technologies, custom portals", risk: "Self-represented litigants missing court dates due to notification failures",
        stack: [{ name: "Tyler Technologies (Odyssey)", role: "Court Case Management", why: "Dominant court case management system. Case status, calendaring, and document management. The data source for every case-related inquiry.", href: "/vendors" }],
        pitfall: "Court date reminders save millions in failure-to-appear warrants and rescheduling costs. A simple SMS reminder ('You have a court appearance on Tuesday, March 15 at 9:00 AM in Room 301') reduces failure-to-appear by 25-35%. Yet most courts still rely on mailed notices that arrive 2-3 weeks before the hearing. Implement SMS reminders 7 days and 1 day before every scheduled appearance."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Case status bots with hearing dates and next steps","Juror reporting bots with call-in instructions","Fine balance and payment plan bots","Filing requirement bots with form identification","Court hours, location, and parking information bots"], vendors: "Ada, custom IVR", risk: "Bot providing filing guidance that constitutes unauthorized legal advice",
        stack: [{ name: "Ada / custom IVR", role: "Court Self-Service", why: "Case status, jury duty reporting, and fine payment are ideal automation candidates. Must be carefully configured to provide information without legal advice.", href: "/vendors/iva" }],
        pitfall: "Court bots must be designed by people who understand the legal information vs legal advice distinction. A bot that says 'you should file a motion to dismiss' is practicing law. A bot that says 'information about motions to dismiss can be found on our self-help page' is providing information. Every bot response must be reviewed by court administration (not just IT) for legal advice risk. One unauthorized-practice-of-law complaint can shut down a court's entire digital program."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Unauthorized practice of law prevention in all citizen interactions","CJIS compliance for criminal justice information systems","Victim privacy protections under VAWA and state victim rights laws","ADA accessibility for court services and communications","Records sealing and expungement compliance"], vendors: "CJIS compliance, court rules", risk: "Agent providing legal advice creating unauthorized practice of law liability",
        stack: [{ name: "CJIS compliance", role: "Criminal Justice Security", why: "Criminal justice information systems (case data, warrants, booking records) are governed by FBI CJIS Security Policy. Any contact center system touching this data must meet CJIS requirements — background checks for all personnel with access.", href: "/vendors" }],
        pitfall: "CJIS compliance requires that every person with access to criminal justice information passes a fingerprint-based background check. This includes contact center agents who can view case status in criminal matters. If your court contact center agents can see criminal case data, they must be CJIS-cleared — including temporary and contractor staff. This affects BPO viability for court support."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Case filing workflow with document requirements and fee calculation","Fine payment workflow with payment plan options and compliance tracking","Jury summons response workflow with qualification and deferral processing","Protective order application workflow with safety protocols","Interpreter request workflow for non-English court proceedings"], vendors: "Tyler Odyssey, Journal Technologies, custom", risk: "Protective order application delayed by workflow bottleneck during safety emergency",
        stack: [{ name: "Tyler Technologies (Odyssey)", role: "Court Management", why: "End-to-end court case management — filing, calendaring, hearing management, and disposition. Workflow automation for filing, payment processing, and jury management.", href: "/vendors" }],
        pitfall: "Protective order applications are time-sensitive safety matters. A victim applying for a protective order and told 'you'll hear back in 5-7 business days' may be in danger tonight. Build an expedited workflow for protective orders that prioritizes intake, notifies the judge immediately, and provides the applicant with safety resources and a timeline measured in hours, not days."
      },
      { layer: 1, name: "Data Access", capabilities: ["Case management system — filings, hearings, parties, and disposition","Financial system — fines, fees, payments, and restitution","Juror management system — summons, qualification, and service records","Document management for filed documents and court orders","Warrant and protective order databases"], vendors: "Tyler Odyssey, Journal Technologies, NCSC standards", risk: "Case data in the case management system not matching what the clerk sees",
        stack: [{ name: "Tyler Technologies (Odyssey)", role: "Case Data", why: "The case management system is the source of truth for every court contact center interaction. Case status, next hearing, parties, attorneys, and disposition — all from Odyssey or equivalent CMS.", href: "/vendors" }, { name: "Journal Technologies (eCourt)", role: "Case Management", why: "Alternative to Tyler used by many state and local courts. Case management, calendaring, and e-filing. The integration target for court contact center operations.", href: "/vendors" }],
        pitfall: "Court case data is legally sensitive and access-controlled. Not all case information is public — sealed records, juvenile cases, and certain family law matters have restricted access. Your contact center system must enforce these access controls: an agent should never be able to see or share information from a sealed case, even if the caller claims to be a party. Build role-based access controls into the agent desktop that mirror the court's access rules."
      },
    ],
  },

  "public-safety": {
    name: "Public Safety & 911", parent: "Government & Public Sector",
    tagline: "Emergency dispatch, non-emergency reporting, community outreach, and crisis intervention.",
    intro: "Public safety contact centers include 911 PSAPs (Public Safety Answering Points) and non-emergency police, fire, and EMS communication centers. The CX framework applies differently here — 'customer satisfaction' is secondary to 'caller survival.' The operational challenge is life-safety call handling with zero tolerance for failure, alongside non-emergency community service that increasingly includes mental health crisis and social services.",
    kpis: [
      { metric: "Answer Time", avg: "10 sec", note: "NENA standard: 90% of 911 calls answered within 15 seconds" },
      { metric: "Dispatch Time", avg: "60 sec", note: "Time from answer to unit dispatched — the critical life-safety metric" },
      { metric: "Abandonment", avg: "2%", note: "Near-zero tolerance — an abandoned 911 call could be a dying caller" },
      { metric: "Accuracy", avg: "99%+", note: "Address and nature-of-call accuracy directly affects response" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Call answer time compliance against NENA/NFPA standards","Dispatch accuracy and response time correlation","Call-type analytics — emergency vs non-emergency vs crisis vs information","Text-to-911 usage and response time tracking","Critical incident review and quality improvement"], vendors: "NICE (NiceInContact Public Safety), Hexagon, Zetron", risk: "Answer time degradation during major incidents",
        stack: [{ name: "NICE Public Safety", role: "Recording & QA", why: "Purpose-built for PSAP quality assurance. Incident reconstruction, call replay, and protocol compliance scoring. Legal-grade recording for evidence and liability.", href: "/vendors/nice-cxone" }],
        pitfall: "Public safety QA is life-safety QA. A 911 call taker who doesn't ask the right questions, misclassifies the call type, or provides incorrect pre-arrival instructions may contribute to a death. QA scoring must be performed by trained public safety professionals — not generic contact center QA analysts. Every cardiac arrest, shooting, and structure fire call should be reviewed for protocol compliance."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["911 call routing based on caller location (wireline ALI, wireless Phase II)","Priority dispatch protocols (medical, fire, police) with pre-arrival instructions","Text-to-911 routing and processing","Mental health crisis routing to co-responder or crisis teams","Non-emergency to emergency escalation when call nature changes"], vendors: "Intrado (Lumen), Zetron, Hexagon, Motorola", risk: "Wireless 911 call routed to wrong PSAP based on cell tower location",
        stack: [{ name: "Intrado (Lumen)", role: "911 Infrastructure", why: "Core 911 call routing infrastructure serving the majority of US PSAPs. ANI/ALI delivery, selective routing, and backup routing for 911 calls.", href: "/vendors" }, { name: "Hexagon Safety", role: "CAD/Dispatch", why: "Computer-Aided Dispatch integrating 911 call data with unit dispatch, GPS tracking, and incident management. The system that turns a 911 call into a response.", href: "/vendors" }],
        pitfall: "NG911 (Next Generation 911) is the transition from analog to IP-based 911 infrastructure. This transition enables text-to-911, video, and real-time data sharing — but many PSAPs are mid-transition with incomplete NG911 deployment. Your PSAP must handle both legacy and NG911 calls simultaneously. Plan for the transition period, not just the end state."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Text-to-911 for deaf, hard-of-hearing, and unsafe-to-talk callers","Real-time language interpretation for non-English 911 callers","Pre-arrival instructions (CPR, bleeding control, childbirth)","Crisis intervention communication for mental health emergencies","Community notification for active threats and natural disasters"], vendors: "Intrado, RapidSOS, Motorola, Zetron", risk: "Deaf caller unable to reach 911 via text in a jurisdiction that hasn't deployed text-to-911",
        stack: [{ name: "RapidSOS", role: "Emergency Data", why: "Real-time emergency data platform connecting 911 PSAPs with device-based location, health data, and crash detection. When a smartphone detects a car crash, RapidSOS delivers location and telematics data to the PSAP before the caller can speak.", href: "/vendors" }],
        pitfall: "Pre-arrival instructions (PAI) save lives — CPR guidance from the dispatcher while EMS is en route can double cardiac arrest survival rates. But PAI requires trained dispatchers following exact protocols (MPDS, FPDS, PPDS). If your PSAP doesn't use standardized dispatch protocols with PAI, callers in cardiac arrest are waiting in silence while help drives to them. Implement protocol-based dispatch with PAI as a life-safety obligation."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Automated location verification for wireless and VoIP 911 calls","Call-type classification AI assisting dispatcher triage","Non-emergency report intake bots for crime reporting and noise complaints","Community safety FAQ bots for non-emergency information","Crisis line bots for initial screening before counselor connection"], vendors: "RapidSOS, Carbyne, Mark43 AI", risk: "AI misclassifying a life-threatening call as non-emergency",
        stack: [{ name: "Carbyne", role: "Emergency Communications", why: "Cloud-native 911 platform with real-time caller location, video streaming from the caller's phone, and AI-assisted dispatch classification. Modernizes PSAP operations.", href: "/vendors" }],
        pitfall: "AI in 911 must augment, never replace, human judgment. An AI that classifies a call as 'non-emergency' when the caller is whispering because an intruder is in the house could cost a life. AI should provide recommendations (suggested call type, location confidence, risk indicators) but the dispatcher must make every classification and dispatch decision. The liability of an AI-dispatched wrong response is not survivable for any public safety agency."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["NENA NG911 standards compliance","HIPAA compliance for medical dispatch information","CJIS compliance for law enforcement data access","Kari's Law and RAY BAUM'S Act compliance for enterprise 911","State and local 911 governance and funding compliance"], vendors: "NENA standards, FCC regulations", risk: "Enterprise buildings not compliant with Kari's Law direct-dial 911 requirements",
        stack: [{ name: "NENA / FCC compliance", role: "911 Standards", why: "NENA i3 standard defines NG911 architecture. FCC mandates (Kari's Law, RAY BAUM'S Act) require direct 911 dialing and dispatchable location from enterprise phone systems. Non-compliance creates legal liability.", href: "/vendors" }],
        pitfall: "Kari's Law requires that any multi-line telephone system (enterprise PBX, hotel phone system) allow direct dialing of 911 without a prefix (no '9-1-1'). RAY BAUM'S Act requires that these systems provide a dispatchable location (floor, room number) to the PSAP. Non-compliant enterprises create a life-safety risk — and the 911 center receives the complaint calls when 911 doesn't work from a hotel room or office building."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Emergency call processing workflow — answer, triage, dispatch, pre-arrival instructions","Non-emergency report intake workflow with case number assignment","Mental health crisis workflow with co-responder or mobile crisis team dispatch","Community notification workflow for active threats and evacuations","Mutual aid coordination workflow for multi-agency incidents"], vendors: "Hexagon, Motorola Solutions, Tyler New World, Mark43", risk: "Mental health crisis dispatching police response when crisis team is needed",
        stack: [{ name: "Hexagon (Intergraph CAD)", role: "Dispatch", why: "Computer-Aided Dispatch — the operational system that converts 911 calls into dispatched units. Unit tracking, incident management, and response coordination.", href: "/vendors" }, { name: "Mark43", role: "Modern Public Safety", why: "Cloud-native public safety platform — CAD, records management, and analytics. Modern alternative to legacy on-premise CAD systems. Growing in mid-size agencies.", href: "/vendors" }],
        pitfall: "Mental health crisis calls are the fastest-growing category in public safety — and the most poorly handled. Dispatching armed officers to a person in psychiatric crisis often escalates rather than resolves the situation. Build a mental health dispatch pathway: 988 Suicide & Crisis Lifeline routing, mobile crisis team dispatch, co-responder (officer + clinician) protocols, and follow-up wellness checks. The technology is dispatch logic; the transformation is cultural."
      },
      { layer: 1, name: "Data Access", capabilities: ["ALI/ANI — caller location and phone number for 911","CAD — active incidents, unit status, and dispatch history","RMS — records management for crime reports and case data","GIS — caller location mapping, response zones, and hazard data","RapidSOS — real-time device data (location, health, crash detection)"], vendors: "Intrado, RapidSOS, Hexagon, Motorola, Mark43", risk: "Wireless 911 location accuracy insufficient for interior response (apartment, floor)",
        stack: [{ name: "RapidSOS", role: "Emergency Data", why: "Aggregates device-sourced data — precise location from smartphones, connected car crash data, medical alert device information, and smart home sensor data. Provides data PSAPs need but couldn't access from traditional 911 infrastructure.", href: "/vendors" }, { name: "Intrado", role: "911 Network", why: "Core 911 selective routing and ALI database. The network infrastructure that delivers 911 calls to the right PSAP with caller information.", href: "/vendors" }],
        pitfall: "Wireless 911 location accuracy has improved dramatically (RapidSOS device-based location, z-axis for floor level) but the PSAP's CAD system must be configured to receive and display this data. Many PSAPs have RapidSOS data available but their CAD doesn't render it in a useful way — the dispatcher sees coordinates instead of an address, or the floor information isn't displayed. CAD integration with modern location data is the current gap."
      },
    ],
  },

  "social-services": {
    name: "Social Services & Benefits", parent: "Government & Public Sector",
    tagline: "SNAP, Medicaid, TANF, housing, child protective services, and disability benefits.",
    intro: "Social services contact centers serve the most vulnerable populations in government — families in poverty, individuals with disabilities, children in unsafe situations, and people experiencing homelessness. The CX challenge is providing empathetic, thorough service to people who are often in crisis, while navigating the most complex eligibility systems in government and managing the emotional toll on agents who hear hardship stories every day.",
    kpis: [
      { metric: "AHT", avg: "12:00", note: "Longest in government — complex eligibility, document requirements, and crisis situations" },
      { metric: "FCR", avg: "42%", note: "Lowest in government — multi-program enrollment and document requirements prevent resolution" },
      { metric: "CSAT", avg: "62", note: "Lowest in government — citizens interacting with social services are already in distress" },
      { metric: "Containment", avg: "12%", note: "Very low — vulnerable populations need human empathy and guidance" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Benefits enrollment success rate by program and population segment","Churn analytics — citizens who apply but don't complete enrollment","Wait time impact on enrollment abandonment","Agent wellbeing monitoring for secondary trauma exposure","Equity analytics ensuring all demographics receive equal service quality"], vendors: "NICE, Verint, Qualtrics", risk: "Eligible citizens abandoning enrollment due to process friction without visibility",
        stack: [{ name: "NICE CXone", role: "QA & Agent Wellbeing", why: "Empathy-scored QA for social services interactions. Monitors agent emotional load and identifies burnout signals. Critical for a workforce handling crisis calls daily.", href: "/vendors/nice-cxone" }],
        pitfall: "Social services contact centers have the highest agent burnout rate in government — agents hear stories of poverty, abuse, and desperation every shift. Standard contact center wellness programs (pizza parties, appreciation weeks) are insufficient. Implement structured resilience programs: secondary trauma training, regular debriefing sessions, access to counseling, and call rotation that limits consecutive high-intensity interactions."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Crisis routing for child abuse, domestic violence, and suicide risk","Multi-program routing covering 10+ benefit programs","Language routing for immigrant and refugee populations","Accessibility routing for elderly and disabled callers","Re-engagement routing for citizens who started but didn't complete applications"], vendors: "Genesys, NICE CXone, Amazon Connect", risk: "Child abuse report reaching a benefits enrollment agent instead of trained investigator",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Crisis detection and routing for the most sensitive government calls. Identifies child abuse reporting language, domestic violence indicators, and suicidal ideation for immediate specialist routing.", href: "/vendors/genesys" }],
        pitfall: "Social services calls that start as benefit inquiries can reveal crisis situations — a parent calling about SNAP eligibility mentions that her partner hit her child last night. The agent must recognize this as a mandatory reporting situation, not a benefits question. Train every social services agent as a mandatory reporter and build a one-button crisis escalation that connects to child protective services or law enforcement immediately."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Simplified application portals with plain-language instructions","Proactive renewal notifications preventing benefit gaps","Document upload alternatives (photo capture, in-person submission)","Community partner referral communications (food banks, shelters, legal aid)","Crisis hotline integration for immediate safety concerns"], vendors: "Granicus, custom portals, 211 integration", risk: "Benefit renewal notices written in legal language that recipients can't understand",
        stack: [{ name: "211 Integration", role: "Community Resources", why: "211 is the national community services helpline. Integration connects social services contact centers with local food banks, shelters, utility assistance, and legal aid — resources the caller needs beyond government benefits.", href: "/vendors" }],
        pitfall: "Government benefit communications are written by lawyers and policy staff — not by the people who receive them. A Medicaid renewal notice that says 'Failure to respond by the specified date will result in termination of eligibility as per Section 1902(e)(14)' is unintelligible to most recipients. Rewrite all citizen-facing communications in plain language at a 6th-grade reading level. Test with actual recipients. The cost of one preventable coverage lapse exceeds the cost of rewriting every form."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Multi-program eligibility screening bots (SNAP + Medicaid + TANF + LIHEAP)","Application status bots with document requirement tracking","Appointment scheduling bots for in-person interviews","Community resource referral bots connecting to 211 services","Renewal deadline reminder bots with simplified response options"], vendors: "Amazon Lex, Ada, Google CCAI", risk: "Bot screening out an eligible family because it can't handle their complex situation",
        stack: [{ name: "Amazon Lex / Ada", role: "Benefits AI", why: "Application status, appointment scheduling, and renewal reminders. Routes all eligibility questions and crisis situations to human agents. Never determines eligibility — only guides the citizen to the application.", href: "/vendors/iva" }],
        pitfall: "Social services bots face a fundamental tension: the populations they serve are often the least comfortable with technology — elderly, disabled, non-English-speaking, and low-literacy. A bot that says 'please describe your situation' to a 78-year-old caller who doesn't understand what a chatbot is creates frustration, not efficiency. Deploy bots for simple tasks (status check, appointment scheduling) and ensure the path to a human agent is immediate and obvious — one press, not a menu tree."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Eligibility determination compliance (federal and state program rules)","Mandatory reporting protocols for child abuse and vulnerable adult abuse","Privacy protections for sensitive personal and family information","Civil rights compliance ensuring equal access regardless of demographics","Immigration-sensitive communication protocols (public charge concerns)"], vendors: "Federal/state compliance, CPS protocols", risk: "Mandatory report not filed because the agent didn't recognize the indicators",
        stack: [{ name: "State compliance systems", role: "Benefits Compliance", why: "SNAP, Medicaid, and TANF are governed by federal rules administered by states — each state has different income thresholds, work requirements, and eligibility criteria. Your compliance framework must match your state's specific program rules.", href: "/vendors" }],
        pitfall: "Immigration status sensitivity is a critical CX issue in social services. Immigrant families may be eligible for benefits (especially children who are citizens) but avoid applying due to public charge concerns. Agents must be trained to provide accurate information about which programs affect immigration status and which don't — without providing legal advice. Incorrect information in either direction (falsely discouraging or falsely encouraging) creates real harm."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Integrated benefits application workflow spanning multiple programs","Document collection workflow with alternative submission methods","Eligibility determination workflow with automated rules and human review","Case assignment workflow for ongoing case management","Community resource referral workflow connecting to local partners"], vendors: "Deloitte/Accenture custom, Salesforce Gov Cloud, Pega, Cúram (Merative)", risk: "Integrated application promised but programs still requiring separate applications",
        stack: [{ name: "Cúram (Merative/IBM)", role: "Social Program Management", why: "Integrated eligibility determination for SNAP, Medicaid, TANF, and other programs. Designed for the rules-engine complexity of social programs. Used by multiple state HHS agencies.", href: "/vendors" }, { name: "Salesforce Government Cloud", role: "Case Management", why: "Citizen relationship management connecting benefits enrollment, case management, and interaction history across programs.", href: "/vendors/ccaas" }],
        pitfall: "Integrated eligibility — applying for SNAP, Medicaid, TANF, and LIHEAP in one application — has been a goal for 20 years. Most states still require separate applications or separate verification steps for each program. Every additional application form loses 15-20% of eligible citizens. True integration means one application, one interview, one set of documents, and eligibility determination across all programs simultaneously. Push for integration at the policy level, not just the technology level."
      },
      { layer: 1, name: "Data Access", capabilities: ["Integrated eligibility system (SNAP, Medicaid, TANF, LIHEAP, child care)","Case management system for ongoing service delivery","Income and employment verification databases","Immigration status verification (SAVE system)","Community resource database (211, local partners, shelters)"], vendors: "Cúram, Deloitte/Accenture custom, state HHS systems", risk: "Eligibility system down during enrollment period leaving agents without access",
        stack: [{ name: "State HHS eligibility system", role: "Benefits Data", why: "Each state runs a unique eligibility system — some are 30 years old, some are recently modernized. The agent's ability to help a citizen is entirely constrained by what this system can do. Real-time eligibility lookup, document upload, and application status are table stakes — but many legacy systems can't deliver them.", href: "/vendors" }, { name: "211/community resources", role: "Referral Data", why: "Social services callers often need more than government benefits — they need food banks, shelters, transportation, legal aid, and childcare. 211 databases and local community resource directories must be accessible to agents for warm referrals.", href: "/vendors" }],
        pitfall: "Social services is the only contact center vertical where the caller may not have a phone, an address, or identification — the very things most systems require for account lookup. Homeless callers, undocumented immigrants, and domestic violence survivors may not be able to verify identity through standard methods. Build alternative verification paths and anonymous inquiry options that don't require the caller to have what they're calling to get."
      },
    ],
  },
};

export const getGovernmentSubVertical = (slug) => governmentSubVerticals[slug];
export const getAllGovernmentSubVerticalSlugs = () => Object.keys(governmentSubVerticals);
