export const insuranceSubVerticals = {
  "personal-lines": {
    name: "Personal Lines P&C", parent: "Insurance",
    tagline: "Auto, home, renters, and umbrella — high-volume FNOL, CAT surges, and retention.",
    intro: "Personal lines P&C contact centers handle the highest volume and most emotionally charged interactions in insurance. A homeowner whose roof was destroyed by a hailstorm and an auto policyholder involved in a collision are calling at the worst moments of their lives. The CX challenge is combining empathy with efficiency — collecting FNOL data accurately while making the policyholder feel heard.",
    kpis: [
      { metric: "AHT", avg: "8:30", note: "Long — FNOL intake and coverage verification are detailed" },
      { metric: "FCR", avg: "62%", note: "Low — claims require adjuster assignment and follow-up" },
      { metric: "CSAT", avg: "78%", note: "Driven almost entirely by claims speed and communication clarity" },
      { metric: "Containment", avg: "18%", note: "Low — FNOL and claims require human empathy; billing automatable" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Claims cycle time by peril type, adjuster, and region","FNOL quality scoring — completeness, empathy, and accuracy","CAT event response analytics — volume, wait time, and resolution speed","Retention analytics correlating service quality to renewal rates","Agent E&O risk monitoring for coverage statements and claim promises"],
        vendors: "NICE Nexidia, Verint, Medallia", risk: "FNOL quality degradation during CAT surges",
        stack: [{ name: "NICE Nexidia", role: "Interaction Analytics", why: "Automated FNOL quality scoring detecting missing data fields, incorrect coverage statements, and empathy gaps. Critical for post-CAT quality review when volume overwhelms normal QA capacity.", href: "/vendors/analytics" }, { name: "Medallia", role: "CX Platform", why: "Claims journey analytics connecting FNOL experience, adjuster interaction, and settlement communication to overall policyholder satisfaction and renewal likelihood.", href: "/vendors/analytics" }],
        pitfall: "During CAT events, QA is typically suspended because 'we're in crisis mode.' This is exactly when QA matters most — undertrained surge agents handling emotional policyholders create the highest E&O exposure. Deploy automated QA (NICE Nexidia) that scores every interaction even during CAT, flagging compliance issues in real-time rather than discovering them during the post-mortem."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["FNOL priority routing with peril-type classification at first contact","CAT surge protocols activating overflow capacity within hours","Licensed adjuster routing for coverage questions and claim decisions","Retention routing for policyholders at renewal with competitive signals","After-hours FNOL routing maintaining 24/7 claim reporting capability"],
        vendors: "Genesys, NICE CXone, Talkdesk Insurance", risk: "FNOL calls waiting behind billing inquiries during CAT events",
        stack: [{ name: "Genesys Cloud", role: "Primary CCaaS", why: "CAT surge routing activates overflow agents, deploys geo-targeted IVR messaging, and prioritizes affected policyholders — all within hours of event declaration. Proven at State Farm, Allstate, and Progressive scale.", href: "/vendors/genesys" }, { name: "Talkdesk Insurance", role: "Vertical CCaaS", why: "Pre-built FNOL routing with peril classification. Separates auto, property, and liability at first contact. Faster deployment than building insurance-specific routing on a generic platform.", href: "/vendors/talkdesk" }],
        pitfall: "CAT routing must be pre-configured and tested BEFORE the event. A hurricane doesn't wait for your IT team to configure surge routing. Build CAT playbooks with pre-approved IVR changes, agent overflow activation, and geographic routing rules. Test them quarterly with simulated surge volume. The carriers that respond well to CAT events are the ones that rehearsed."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure photo and video upload for damage documentation during FNOL","Proactive claims milestone notifications via SMS and email","Two-way messaging for adjuster-policyholder communication","Self-service claims status portal reducing status-check call volume","Renewal communication with coverage review and competitive context"],
        vendors: "Hi Marley, Glia, LivePerson, Sprinklr", risk: "Policyholders waiting days for claims updates when the adjuster hasn't been assigned yet",
        stack: [{ name: "Hi Marley", role: "Insurance Messaging", why: "Purpose-built for P&C insurance. Two-way texting for FNOL follow-up, adjuster coordination, and claims updates. Built by insurance people who understand that policyholders text, they don't log into portals.", href: "/vendors/digital-engagement" }, { name: "Glia", role: "Digital CX", why: "Secure photo upload during FNOL calls — policyholder shares damage photos while on the phone with the agent. Co-browsing for policy document review.", href: "/vendors/digital-engagement" }],
        pitfall: "Claims status calls consume 25-35% of post-FNOL contact center volume. The policyholder calls because they don't know what's happening — not because something is wrong. Proactive milestone notifications (claim received, adjuster assigned, inspection scheduled, estimate completed, payment issued) eliminate 60-70% of status calls. Hi Marley or similar texting platforms make this easy. Most carriers know this but haven't implemented it because the claims and CX teams don't share a budget."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["FNOL intake bots collecting peril-specific data (auto vs property vs liability)","Claims status bots with real-time adjuster and timeline visibility","Policy coverage lookup bots verifying what's covered before the claim","Billing and payment bots for premium inquiries and payment arrangements","Renewal quote comparison bots presenting competitive retention context"],
        vendors: "Cognigy, Kore.ai, Shift Technology AI", risk: "Bot collecting incomplete FNOL data that delays adjuster assignment",
        stack: [{ name: "Cognigy", role: "Conversational AI", why: "Insurance-specific FNOL intake with peril-branching logic. Auto FNOL collects different data than property FNOL — vehicle info, other party, police report vs damage description, temporary housing needs, mitigation steps.", href: "/vendors/iva" }, { name: "Shift Technology", role: "Claims AI", why: "AI fraud detection at FNOL — analyzes claim data patterns to flag suspicious claims before adjuster assignment. Reduces fraud leakage without slowing legitimate claims.", href: "/vendors" }],
        pitfall: "FNOL bots must collect different data for different perils — an auto FNOL needs: date/time/location, vehicle info, other party details, injuries, police report number. A property FNOL needs: date of loss, damage description, temporary housing needs, emergency mitigation taken. A bot that asks the same generic questions for every peril will either miss critical data (delaying the claim) or ask irrelevant questions (frustrating the policyholder). Build peril-specific intake flows."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["State DOI compliance for claims handling timelines by jurisdiction","Unfair claims practices act monitoring across all interactions","Anti-fraud detection integrated into FNOL and claims workflows","Recorded statement protocols with required legal disclosures","E&O controls preventing agents from making coverage promises"],
        vendors: "Shift Technology, Verisk, SAS, NICE Actimize", risk: "State-specific timeline violations creating DOI complaints and penalties",
        stack: [{ name: "Shift Technology", role: "Fraud Detection", why: "AI-powered claims fraud detection analyzing FNOL data, claimant history, and external indicators in real-time. Flags suspicious claims for SIU review before payment. Deployed at top 20 global insurers.", href: "/vendors" }, { name: "Verisk", role: "Claims Data & Validation", why: "ISO ClaimSearch cross-references claims across carriers to detect duplicate or suspicious filing patterns. Property data validates damage claims against actual property characteristics.", href: "/vendors" }],
        pitfall: "Claims handling timelines are state-specific and non-negotiable. California requires acknowledgment within 15 days; New York within 15 business days; Florida within 14 days. A national carrier serving 50 states must enforce 50 different timeline rules simultaneously. Your claims workflow engine must track state-specific SLAs and escalate approaching deadlines automatically — not rely on adjusters to remember which state has which deadline."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["FNOL intake workflow with peril-specific data requirements and auto-assignment","Claims triage and adjuster assignment by peril, complexity, and geography","Subrogation identification and tracking workflow","Policy endorsement workflow with premium recalculation","Retention save workflow with competitive pricing and coverage review"],
        vendors: "Guidewire, Duck Creek, Majesco, Pega", risk: "Claims assignment bottleneck during CAT events when all adjusters are deployed",
        stack: [{ name: "Guidewire ClaimCenter", role: "Claims Management", why: "Industry standard for P&C claims. FNOL, assignment, reserving, payment, and subrogation in one platform. Cloud-native Guidewire Cloud is the modernization target for most carriers.", href: "/vendors" }, { name: "Duck Creek Claims", role: "Claims Platform", why: "SaaS-native alternative. Faster implementation for mid-market carriers. Growing API ecosystem for CX and digital integration.", href: "/vendors" }],
        pitfall: "CAT claims assignment is the operational bottleneck — 5,000 new FNOL in 48 hours but only 200 adjusters available. Automated triage that assigns simple claims (windshield, minor water damage) to fast-track adjusters while routing complex claims (structural damage, total loss) to senior adjusters prevents the backlog from growing. Without triage, every claim enters the same queue and cycle times explode uniformly."
      },
      { layer: 1, name: "Data Access", capabilities: ["Policy administration system (coverage, limits, deductibles, endorsements)","Claims management system (FNOL, reserves, payments, adjuster notes)","Billing system (premium, payment history, installment schedule)","Agent/broker portal with production and commission data","Document management for claims files, photos, and correspondence"],
        vendors: "Guidewire, Duck Creek, Majesco, Sapiens, Salesforce FSC", risk: "Agent seeing policy data but not claims data — or vice versa",
        stack: [{ name: "Guidewire InsuranceSuite", role: "Core Systems", why: "PolicyCenter + ClaimCenter + BillingCenter = the data foundation. Real-time APIs in Cloud edition. The contact center agent's capability ceiling is set by how deeply you integrate with Guidewire.", href: "/vendors" }, { name: "Salesforce Financial Services Cloud", role: "CRM", why: "Policyholder relationship view connecting policy, claims, billing, and interaction history. The CRM layer that unifies Guidewire data into an agent-friendly desktop.", href: "/vendors/ccaas" }],
        pitfall: "Most P&C carriers run separate policy, claims, and billing systems — often from different vendors or different eras. The contact center agent needs data from all three to answer a simple question like 'I had a claim last month — will my premium go up at renewal?' Without a unified view, the agent checks policy (yes, you're active), checks claims (yes, $5,000 paid), and guesses at the premium impact (because that's an actuarial calculation they can't access). Build a unified agent desktop or accept that agents will always give incomplete answers."
      },
    ],
  },

  "commercial-lines": {
    name: "Commercial Lines", parent: "Insurance",
    tagline: "Business insurance, general liability, commercial property, and fleet.",
    intro: "Commercial lines contact centers serve businesses whose insurance needs are complex, multi-policy, and broker-mediated. A manufacturing company with GL, property, auto fleet, workers' comp, and umbrella coverage across 12 states is not calling about one policy — they're calling about a business risk. The CX challenge is B2B service depth with B2C responsiveness.",
    kpis: [
      { metric: "AHT", avg: "11:00", note: "Long — multi-policy, multi-location, and broker coordination" },
      { metric: "FCR", avg: "55%", note: "Low — commercial issues span policies, locations, and coverage layers" },
      { metric: "CSAT", avg: "75%", note: "Moderate — relationship-driven but frustrated by complexity" },
      { metric: "Containment", avg: "10%", note: "Very low — commercial insurance requires human expertise" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Account profitability analytics connecting service cost to premium revenue","Broker satisfaction tracking separate from policyholder satisfaction","Claims frequency and severity trends by industry class and region","Renewal retention analytics by account size and line of business","Underwriting referral tracking from contact center to underwriting team"], vendors: "NICE, Verint, Salesforce Analytics", risk: "High-premium accounts receiving the same service as small accounts",
        stack: [{ name: "NICE CXone", role: "Analytics & QA", why: "Separate QA scorecards for direct policyholder interactions vs broker-channel interactions. Commercial service quality is measured differently than personal lines.", href: "/vendors/nice-cxone" }],
        pitfall: "Commercial lines analytics must connect service interactions to account profitability. A $500K premium account that generates 50 service calls per year is profitable. A $50K premium account that generates 50 calls is not. Track service cost per account alongside premium to understand the true cost-to-serve for your commercial book."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Named account manager routing for large commercial accounts","Broker vs direct policyholder routing with different service models","Line-of-business routing (GL, property, auto, WC, umbrella)","Certificate of insurance routing to automated or specialized teams","Claims FNOL routing with commercial complexity triage"], vendors: "Genesys, NICE CXone, Cisco", risk: "Broker reaching a personal lines agent who can't navigate commercial systems",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Named-account routing with full commercial account context. Routes broker calls separately from direct calls. Handles the multi-policy complexity of commercial accounts.", href: "/vendors/genesys" }],
        pitfall: "Certificate of insurance requests are the highest-volume, lowest-complexity interaction in commercial lines — and they consume disproportionate agent time. Automate COI generation and delivery. A contractor who needs a COI by 3pm to start a job tomorrow should be able to get it in 30 seconds from a self-service portal, not wait 45 minutes on hold."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Broker portal with real-time policy, claims, and commission data","Certificate of insurance self-service portal with digital delivery","Proactive renewal communication 90 days before expiration","Claims status portal for commercial policyholders with multi-claim view","Audit and compliance document exchange via secure channels"], vendors: "Glia, Salesforce, broker portals", risk: "Broker and carrier communicating about the same account without shared visibility",
        stack: [{ name: "Salesforce Experience Cloud", role: "Broker Portal", why: "Self-service broker portal with real-time policy data, commission statements, and claims status. Reduces broker calls to the contact center by 40-60%.", href: "/vendors/ccaas" }],
        pitfall: "Commercial renewals are complex negotiations — not automated notices. A $200K account renewal involves loss analysis, market comparison, coverage review, and premium negotiation between the broker, underwriter, and policyholder. The contact center's role is coordination and status — but most carriers don't give contact center agents visibility into the renewal pipeline. Build renewal status into the agent desktop so agents can answer 'where does my renewal stand?' without transferring to underwriting."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Certificate of insurance generation bots with automated delivery","Policy coverage verification bots for multi-policy commercial accounts","Claims status bots with multi-claim, multi-location visibility","Billing and installment management bots","Basic underwriting referral bots collecting risk information"], vendors: "Cognigy, Ada", risk: "Bot misrepresenting coverage on a multi-policy commercial account",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles COI requests, billing inquiries, and claims status. Routes complex commercial underwriting and coverage questions to human experts.", href: "/vendors/iva" }],
        pitfall: "Commercial coverage questions are dangerous for bots. A business owner asking 'does my policy cover water damage from a broken pipe?' requires analysis of the specific policy form, endorsements, exclusions, and sublimits. A bot that says 'yes' when the policy has a water damage exclusion creates E&O liability. Restrict bots to administrative tasks and route all coverage questions to licensed agents."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Multi-state compliance for commercial operations across jurisdictions","Surplus lines compliance for non-admitted coverage placement","E&O controls for commercial coverage representations","Anti-fraud monitoring for commercial claims patterns","Regulatory reporting for large commercial claims and market conduct"], vendors: "Verisk, ISO, NICE Actimize", risk: "Coverage misrepresentation on a multi-million-dollar commercial account",
        stack: [{ name: "Verisk / ISO", role: "Commercial Data", why: "Commercial lines rating, classification, and loss cost data. Validates that coverage is rated and classified correctly. The compliance data foundation for commercial underwriting and servicing.", href: "/vendors" }],
        pitfall: "Commercial E&O exposure is orders of magnitude larger than personal lines. Misrepresenting coverage on a $10M commercial property policy can create a $10M+ E&O claim. Every contact center interaction involving commercial coverage must be recorded, quality-scored, and reviewed for coverage accuracy. The cost of QA is trivial compared to the cost of one E&O claim."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Certificate of insurance automation with holder tracking and delivery","Commercial renewal workflow with loss analysis and market comparison","Multi-location policy change workflow with state-specific compliance","Commercial claims FNOL with business interruption assessment","Audit premium reconciliation workflow with payroll and revenue verification"], vendors: "Guidewire, Duck Creek, Pega, Salesforce", risk: "Manual COI processes consuming agent time on low-value requests",
        stack: [{ name: "Guidewire PolicyCenter", role: "Policy Admin", why: "Commercial policy administration with multi-line, multi-state complexity. The workflow engine that determines what policy changes agents can make and what requires underwriter approval.", href: "/vendors" }],
        pitfall: "Commercial audits (annual premium reconciliation based on actual payroll/revenue vs estimated) generate significant contact center volume because policyholders don't understand why they owe additional premium. Build a proactive audit communication workflow: notify the policyholder 60 days before audit, explain the process, provide documentation requirements, and offer a payment plan for any additional premium. Reactive audit notices create angry calls."
      },
      { layer: 1, name: "Data Access", capabilities: ["Policy administration with multi-line, multi-location commercial accounts","Claims management across GL, property, auto, and WC for same account","Billing with complex premium installment and audit reconciliation","Broker management system with production, commission, and correspondence","Underwriting workbench with risk data, loss history, and pricing"], vendors: "Guidewire, Duck Creek, Salesforce, Applied Epic", risk: "Agent seeing one policy line but not the full commercial account relationship",
        stack: [{ name: "Applied Epic", role: "Agency Management", why: "The dominant agency management system. Brokers use Applied Epic to manage their book. Carriers that integrate with Applied Epic give agents visibility into the broker relationship.", href: "/vendors" }, { name: "Guidewire InsuranceSuite", role: "Core Systems", why: "Policy, claims, and billing for the carrier side. The agent desktop must show the full commercial account — all policies, all claims, all billing — in one view.", href: "/vendors" }],
        pitfall: "Commercial accounts are multi-policy relationships. A manufacturing company might have: GL, commercial property, business auto (20 vehicles), workers' comp (3 states), umbrella, and cyber. If the agent desktop shows these as 6 separate policies rather than one commercial account, the agent can't understand the relationship or provide relationship-level service. Build an account-level view that shows all policies, total premium, total claims, and account profitability."
      },
    ],
  },

  "life-annuities": {
    name: "Life Insurance & Annuities", parent: "Insurance",
    tagline: "Policy servicing, beneficiary changes, premium payments, surrenders, and death claims.",
    intro: "Life insurance contact centers manage the longest customer relationships in financial services — policies that span 20-50 years. The CX challenge is maintaining relevance and accuracy across decades while handling the most emotionally sensitive interaction in all of insurance: the death claim.",
    kpis: [
      { metric: "AHT", avg: "8:00", note: "Moderate — servicing calls are routine; death claims and surrenders are long" },
      { metric: "FCR", avg: "72%", note: "Good for servicing; poor for surrenders and death claims requiring documentation" },
      { metric: "CSAT", avg: "82%", note: "Higher than P&C — fewer emotionally negative interactions outside death claims" },
      { metric: "Containment", avg: "22%", note: "Premium payments and balance inquiries automatable; beneficiary and death claims need humans" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Policyholder engagement tracking across decades-long relationships","Surrender and lapse risk prediction based on payment patterns and inquiries","Death claim processing time and family satisfaction tracking","Agent compliance scoring for illustrations, projections, and suitability","Orphan policy identification — policies without an assigned agent/advisor"], vendors: "NICE, Verint, Qualtrics", risk: "Orphan policyholders churning without any proactive engagement",
        stack: [{ name: "NICE CXone", role: "QA & Compliance", why: "Compliance-scored QA for life insurance interactions. Detects unauthorized illustrations, incorrect cash value statements, and suitability concerns. Critical for regulatory examination readiness.", href: "/vendors/nice-cxone" }],
        pitfall: "Life insurers lose policyholders not through dissatisfaction but through disengagement. A policyholder who bought a whole life policy 15 years ago and never hears from the carrier will lapse when finances get tight — because the policy feels irrelevant. Track engagement signals (login frequency, statement opens, inquiry calls) and proactively reach out to disengaged policyholders before they lapse."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Death claim priority routing with empathy-trained specialist teams","Surrender and loan request routing to retention-skilled agents","Agent/advisor routing for servicing their assigned policyholders","Compliance routing for illustration requests and replacement discussions","After-hours routing for death notification and claim initiation"], vendors: "Genesys, NICE CXone", risk: "Death claim caller reaching a general servicing agent unprepared for the conversation",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Empathy-routing for death claims — detects bereavement context and routes to trained specialists. WEM ensures death claim specialists are always available during business hours.", href: "/vendors/nice-cxone" }],
        pitfall: "Death claims are the single most important interaction in life insurance — and the most undertrained. A surviving spouse calling to report a death and file a claim needs an agent who combines empathy, procedural accuracy, and patience. Most carriers train death claim procedures but not death claim empathy. Invest in bereavement communication training and route all death calls to certified specialists."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Self-service premium payment and policy loan portal","Secure document upload for death certificates and claim forms","Proactive policy anniversary communications with value updates","Beneficiary update portal with digital verification","Life event-triggered outreach (marriage, birth, retirement)"], vendors: "Glia, Salesforce, custom portals", risk: "Death claim documentation process feeling bureaucratic during grief",
        stack: [{ name: "Glia", role: "Digital CX", why: "Secure document upload during phone calls — surviving spouse can send death certificate while speaking with the agent. Eliminates the 'mail us the documents and wait' experience.", href: "/vendors/digital-engagement" }],
        pitfall: "Death claim documentation requirements (certified death certificate, claim form, policy, claimant identification) feel bureaucratic to a grieving family. Simplify by: accepting digital copies initially while originals are in transit, pre-populating claim forms with known policy data, and providing a single point of contact for the entire claim process. The family should never have to explain the situation to a second person."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Premium payment and billing status bots","Cash value and loan availability bots with real-time calculations","Policy information bots (coverage amount, beneficiaries, riders)","Beneficiary update initiation bots with verification workflow","Address and contact information change bots"], vendors: "Ada, Cognigy", risk: "Bot providing cash value projection that differs from the actual illustration",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles premium payments, policy lookups, and basic servicing requests. Routes death claims, surrenders, and illustration requests to human agents immediately.", href: "/vendors/iva" }],
        pitfall: "Cash value bots must pull real-time data from the policy administration system — not cached or estimated values. A bot that says 'your cash value is approximately $45,000' when the actual value is $42,300 creates a reliance problem if the policyholder makes financial decisions based on that number. Either provide the exact real-time figure or say 'I can connect you with an agent who can provide your current cash value.'"
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Suitability compliance for replacement discussions and new illustrations","State-specific free look period and cancellation right disclosures","Anti-money laundering controls for large premium payments and surrenders","Privacy compliance for beneficiary and medical information","NAIC model regulation compliance for policy illustrations and projections"], vendors: "NICE Actimize, Verint, compliance systems", risk: "Replacement discussion without required comparison disclosure creating regulatory violation",
        stack: [{ name: "NICE Actimize", role: "Compliance Monitoring", why: "Detects unauthorized replacement discussions where agents recommend surrendering one policy to buy another without proper suitability analysis and disclosure. A common enforcement target for state regulators.", href: "/vendors" }],
        pitfall: "Life insurance replacement regulations (NAIC Model 613) require specific disclosures and comparison documents when a policyholder is considering replacing an existing policy with a new one. If a contact center agent discusses replacement without triggering the compliance workflow, the carrier faces regulatory action. Build replacement-detection logic that flags keywords ('cancel this policy and buy a new one,' 'better rate elsewhere') and triggers compliance review."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Death claim intake and processing workflow with document tracking","Policy loan and withdrawal workflow with tax implications notification","Beneficiary change workflow with proper verification and documentation","Surrender and lapse reinstatement workflow with retention intervention","Premium payment mode change workflow (annual to monthly, auto-pay enrollment)"], vendors: "FAST, OIPA, Sapiens, EXL", risk: "Death claim processing taking 30+ days due to documentation bottlenecks",
        stack: [{ name: "FAST (FINEOS)", role: "Life Admin", why: "Policy administration for life and annuity carriers. Premium billing, policy values, and claims processing. The workflow engine that determines death claim processing speed.", href: "/vendors" }, { name: "Sapiens", role: "Life Platform", why: "Core life insurance platform with policy admin, claims, and billing. Cloud capabilities growing. Strong in mid-market life carriers.", href: "/vendors" }],
        pitfall: "Death claim processing has a direct emotional impact that no other insurance workflow has. A family waiting 45 days for a $500K death benefit payment while managing funeral costs and lost income will never recommend the carrier. Streamline: accept digital documents, fast-track claims under $100K with simplified verification, and provide interim payments for documented funeral costs while the full claim processes."
      },
      { layer: 1, name: "Data Access", capabilities: ["Policy administration system (coverage, values, riders, beneficiaries, history)","Billing system (premium payments, frequency, grace period, lapse status)","Claims system (death claims, disability, accelerated benefits)","Agent/advisor database (assigned producer, commission, service history)","Illustration system (current values, projections, comparison reports)"], vendors: "FAST, OIPA, Sapiens, LIDP, Salesforce", risk: "Cash values calculated by the admin system not matching customer-facing illustrations",
        stack: [{ name: "OIPA (Oracle Insurance)", role: "Policy Admin", why: "High-performance life policy administration. Real-time cash value calculations, rider processing, and premium billing. Strong in large life carriers.", href: "/vendors" }, { name: "Salesforce Financial Services Cloud", role: "CRM", why: "Policyholder relationship view across all policies, beneficiaries, and interactions. Connects the servicing team to the advisor for orphan policy management.", href: "/vendors/ccaas" }],
        pitfall: "Life insurance policy admin systems calculate cash values, dividends, and loan interest using complex actuarial formulas. The contact center agent sees a 'current cash value' field but can't explain how it was calculated or why it differs from what the policyholder expected. Train agents to explain value drivers (premiums paid, interest credited, cost of insurance deducted, loan balance) or build a visual value breakdown in the agent desktop. 'Your cash value is $45,000' is less useful than 'You've paid $60,000 in premiums, earned $15,000 in interest, and $30,000 has been applied to cost of insurance, resulting in a cash value of $45,000.'"
      },
    ],
  },

  "workers-comp": {
    name: "Workers' Compensation", parent: "Insurance",
    tagline: "Injury reporting, claims management, return-to-work coordination, and employer/employee dual-audience.",
    intro: "Workers' comp contact centers serve two audiences with different needs: employers (reporting injuries, managing premiums, understanding experience mods) and injured workers (filing claims, understanding benefits, navigating medical treatment). The CX challenge is balancing employer accountability with employee advocacy — while managing the medical and legal complexity of every claim.",
    kpis: [
      { metric: "AHT", avg: "10:00", note: "Long — injury details, medical coordination, and return-to-work planning" },
      { metric: "FCR", avg: "50%", note: "Very low — claims involve medical providers, employers, and legal coordination" },
      { metric: "CSAT", avg: "72%", note: "Moderate — injured workers are frustrated; employers want cost control" },
      { metric: "Containment", avg: "10%", note: "Very low — injury claims require human judgment and empathy" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Claims cost development tracking by injury type and employer","Return-to-work timeline analytics with medical provider correlation","Employer experience modification impact forecasting","Fraud detection analytics for claim patterns and medical treatment","Injured worker satisfaction tracking through the claim lifecycle"], vendors: "NICE, Verint, custom WC analytics", risk: "Claims costs developing beyond reserves without early detection",
        stack: [{ name: "NICE CXone", role: "QA & Analytics", why: "Dual-audience QA — separate scorecards for employer interactions (accuracy, cost context) and injured worker interactions (empathy, benefits clarity, medical coordination).", href: "/vendors/nice-cxone" }],
        pitfall: "Workers' comp analytics must track claims cost development — the difference between initial reserve and ultimate paid. If contact center decisions (approving treatment, extending lost time, accepting late-reported claims) systematically increase development, the contact center is creating underwriting losses that only surface 2-3 years later. Connect contact center decisions to actuarial outcomes."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Employer vs injured worker routing with different service models","Injury severity triage routing — minor first aid vs serious injury vs fatality","Medical provider routing for treatment authorization and bill review","Return-to-work coordinator routing for transitional duty planning","Legal routing for litigated claims with attorney involvement"], vendors: "Genesys, NICE CXone", risk: "Injured worker calling about their claim reaching the employer service team",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Dual-audience routing separating employer and injured worker paths. Injury severity classification at first contact determines urgency and specialist assignment.", href: "/vendors/genesys" }],
        pitfall: "Workers' comp has a unique routing challenge: the employer and the injured worker may call about the same claim but need different information and different agents. The employer wants cost impact and return-to-work timeline; the injured worker wants benefits amount and medical treatment authorization. If they reach the same agent, the agent must switch contexts — and risk sharing employer-sensitive information with the worker or vice versa. Build separate routing paths."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure injury reporting portal for employers with photo documentation","Injured worker benefits explanation with state-specific calculation","Medical provider treatment authorization communication","Return-to-work coordination messaging between employer, worker, and carrier","Proactive claim milestone notifications to both employer and injured worker"], vendors: "Hi Marley, Glia, custom portals", risk: "Injured worker not understanding their benefits or treatment rights",
        stack: [{ name: "Hi Marley", role: "Insurance Messaging", why: "Two-way texting with injured workers for appointment reminders, benefits updates, and return-to-work coordination. Workers' comp claimants are often hourly workers who can't take phone calls during shift hours — texting is the accessible channel.", href: "/vendors/digital-engagement" }],
        pitfall: "Injured workers are often hourly employees who can't take phone calls during work hours (even if they're on light duty). Sending a voicemail that says 'call us back between 8am and 5pm' when the worker's shift is 7am to 3:30pm guarantees a missed connection. Text-based communication (Hi Marley) respects the worker's schedule and produces faster claim resolution."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["First report of injury bots collecting OSHA-required data","Claim status bots with benefits calculation and payment schedule","Medical treatment authorization status bots","Return-to-work planning bots with transitional duty options","Employer experience mod explanation bots"], vendors: "Cognigy, Ada", risk: "Bot calculating benefits incorrectly due to state-specific formula differences",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles claim status, payment schedule, and basic benefits inquiries. Routes complex medical authorization and return-to-work questions to trained adjusters.", href: "/vendors/iva" }],
        pitfall: "Workers' comp benefits are calculated using state-specific formulas — wage replacement rate, maximum weekly benefit, waiting period, and duration all vary by state. A bot that says 'you'll receive 66% of your average weekly wage' is wrong in states where the rate is 70% or where the calculation uses a different wage basis. Either build state-specific benefit calculation or restrict the bot to 'your benefits have been calculated at $X per week — here's how to reach your adjuster if you have questions.'"
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["State-specific workers' comp regulatory compliance (50 states, 50 sets of rules)","OSHA reporting requirements for workplace injuries","Medical treatment guidelines by jurisdiction (ODG, ACOEM)","Anti-fraud controls for claims investigation","Privacy compliance for medical records and injury documentation"], vendors: "ISO, NCCI, state rating bureaus", risk: "State regulatory violations from applying one state's rules to another state's claim",
        stack: [{ name: "NCCI / state bureaus", role: "Regulatory Data", why: "Class codes, experience modification, and loss cost data. The regulatory foundation that determines premium and compliance requirements. Varies by state — monopolistic states, competitive states, and NCCI states all have different rules.", href: "/vendors" }],
        pitfall: "Workers' comp is the most jurisdictionally complex line of insurance. Monopolistic states (Ohio, Washington, Wyoming, North Dakota) have state-run funds; competitive states use private carriers; and the rules for reporting, benefits, and medical treatment differ everywhere. Your contact center agents must know which state's rules apply to each claim — and the state is determined by where the injury occurred, not where the employer is headquartered."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["First report of injury workflow with employer and worker data collection","Medical treatment authorization workflow with provider communication","Return-to-work planning workflow with transitional duty matching","Subrogation identification for third-party liability recovery","Experience modification impact analysis for employer risk management"], vendors: "Guidewire, Origami Risk, Mitchell, custom WC platforms", risk: "Delayed return-to-work extending claim duration and costs",
        stack: [{ name: "Origami Risk", role: "WC Claims Platform", why: "Risk management and claims platform popular in mid-market WC. Claims administration, medical management, and return-to-work coordination. More accessible than Guidewire for smaller operations.", href: "/vendors" }, { name: "Mitchell (Enlyte)", role: "Medical Management", why: "Medical bill review, treatment authorization, and pharmacy management for WC. The medical cost containment layer that integrates with claims administration.", href: "/vendors" }],
        pitfall: "Return-to-work is the single most important claims outcome metric in workers' comp — and the contact center directly influences it. Early contact with the injured worker (within 24 hours of FNOL), proactive medical coordination, and transitional duty planning reduce average claim duration by 20-30%. Carriers that treat RTW as an adjuster responsibility without contact center support leave money and outcomes on the table."
      },
      { layer: 1, name: "Data Access", capabilities: ["Claims administration system (injury details, benefits, payments, reserves)","Medical management system (treatment authorization, provider network, bill review)","Policy and premium data (class codes, payroll, experience modification)","Employer data (locations, payroll by class, loss history)","Regulatory data (state rules, benefit rates, reporting requirements)"], vendors: "Guidewire, Origami Risk, Mitchell, NCCI", risk: "Medical and claims data in separate systems without integration",
        stack: [{ name: "Guidewire ClaimCenter", role: "Claims Admin", why: "Enterprise WC claims administration. Integrates medical management, return-to-work, and litigation tracking. The data foundation for every WC claims interaction.", href: "/vendors" }, { name: "Mitchell / Enlyte", role: "Medical Data", why: "Medical bill review data, treatment guidelines, and pharmacy management. When an injured worker asks 'is my surgery approved?' the answer is in Mitchell.", href: "/vendors" }],
        pitfall: "Workers' comp data spans claims, medical, and employer systems — and the agent needs all three. An injured worker calling about a denied treatment authorization needs: claim status (claims system), treatment details and denial reason (medical management), and employer's return-to-work options (employer portal). Three systems, three logins, three contexts. Build a unified WC agent desktop or accept 10-minute AHT on every call."
      },
    ],
  },

  "specialty-lines": {
    name: "Specialty & Surplus Lines", parent: "Insurance",
    tagline: "Cyber, E&O, D&O, marine, aviation, and excess — sophisticated policyholders and broker-driven.",
    intro: "Specialty lines contact centers serve the most sophisticated policyholders and brokers in insurance. A CFO calling about their D&O coverage limit and a CISO calling about their cyber incident response protocol expect expert-level service — not generalist agents reading from scripts. The CX challenge is staffing a contact center with the technical insurance knowledge that specialty lines demand.",
    kpis: [
      { metric: "AHT", avg: "13:00", note: "Longest in insurance — complex coverage discussions and claims coordination" },
      { metric: "FCR", avg: "60%", note: "Low — specialty claims require underwriter, legal, and broker coordination" },
      { metric: "CSAT", avg: "78%", note: "Good when expertise matches expectations; poor when it doesn't" },
      { metric: "Containment", avg: "5%", note: "Lowest in insurance — every interaction requires specialist knowledge" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Broker satisfaction by market and product line","Claims severity tracking for low-frequency, high-severity events","Underwriting referral quality from contact center to specialty underwriters","Coverage accuracy monitoring for complex policy forms","Market cycle analytics connecting pricing trends to service volume"], vendors: "NICE, custom analytics", risk: "Coverage misstatement on a $50M specialty policy creating massive E&O exposure",
        stack: [{ name: "NICE CXone", role: "QA & Compliance", why: "Compliance monitoring for specialty coverage discussions. Every statement about coverage limits, exclusions, or conditions must be accurate against the policy form. Automated detection of potential E&O statements.", href: "/vendors/nice-cxone" }],
        pitfall: "Specialty lines QA must be performed by people who understand the coverage. A generic QA analyst scoring a D&O interaction can evaluate empathy and process compliance but cannot evaluate whether the agent correctly described the insured vs insured exclusion. Staff specialty QA with insurance-trained reviewers, not generic contact center QA analysts."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Product-line routing by specialty (cyber, D&O, E&O, marine, aviation)","Broker-tier routing prioritizing high-production wholesale brokers","Claims routing to specialty adjusters by coverage type","Underwriting referral routing with risk information pre-collection","After-hours routing for cyber incident and crisis notification"], vendors: "Genesys, NICE CXone", risk: "Cyber incident notification reaching a general agent at 2am",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Specialty-specific routing matching callers to agents with product expertise. Cyber incident notifications route to breach response teams 24/7.", href: "/vendors/genesys" }],
        pitfall: "Cyber insurance policies include incident response hotlines that must be answered 24/7 by people who understand breach response protocols — not by answering services or general agents. When a CISO calls at 2am to report a ransomware attack, they need to reach a breach response coordinator within minutes, not leave a message. Staff and route the incident hotline as a critical path, separate from general servicing."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure breach notification and incident reporting portal","Broker submission portal for new business and renewals","Claims reporting with specialized intake forms by coverage type","Market update communications for pricing and capacity changes","Expert roundtable and webinar coordination for policyholder engagement"], vendors: "Glia, Salesforce, custom broker portals", risk: "Sensitive breach information transmitted through unsecured channels",
        stack: [{ name: "Salesforce Experience Cloud", role: "Broker Portal", why: "Wholesale broker portal with submission tracking, quote status, and policy management. Reduces broker calls for status updates while maintaining the relationship.", href: "/vendors/ccaas" }],
        pitfall: "Cyber insurance breach notifications contain extremely sensitive information — company name, type of breach, data compromised, ransom demanded. This information must be transmitted through encrypted, access-controlled channels — not email, not voicemail, not generic ticketing systems. Build a secure incident portal with access limited to breach response team members and encrypted end-to-end."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Policy coverage summary bots for complex specialty forms","Broker submission status bots with underwriting timeline","Claims status bots for specialty claims in progress","Certificate and evidence of insurance automation","Basic coverage FAQ bots by specialty line"], vendors: "Limited use — specialty requires human expertise", risk: "Bot attempting to explain D&O coverage exclusions incorrectly",
        stack: [{ name: "Minimal AI", role: "—", why: "Specialty insurance interactions require expert knowledge that current AI cannot reliably provide. Use AI for administrative tasks (submission status, payment processing) and route all coverage, claims, and underwriting questions to human specialists. The containment target for specialty lines should be under 10%." }],
        pitfall: "Specialty insurance is the worst use case for customer-facing AI in all of insurance. The coverage is complex, the stakes are high, and the policyholders are sophisticated enough to know when an answer is wrong. A bot that says 'your D&O policy covers regulatory investigations' when the policy has a regulatory exclusion creates E&O exposure that exceeds the entire contact center budget. Keep AI behind the scenes (agent assist, document search) and keep humans in front of the customer."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Surplus lines compliance for non-admitted placements","Broker licensing verification by state and product line","E&O controls for complex coverage representations","Sanctions and embargo screening for marine and international risks","Privacy and confidentiality controls for breach notification data"], vendors: "NICE Actimize, Verisk, custom compliance", risk: "Surplus lines tax and filing non-compliance across jurisdictions",
        stack: [{ name: "Custom compliance", role: "Specialty Compliance", why: "Surplus lines compliance (state filing, tax, broker licensing) varies by state and is too specialized for generic compliance tools. Most specialty carriers build custom compliance workflows integrated with their policy admin system.", href: "/vendors" }],
        pitfall: "Surplus lines placements require state-specific filings, taxes, and broker licensing verification that admitted carriers don't face. If your contact center processes policy changes or endorsements on surplus lines policies, the agents must understand which changes trigger re-filing requirements. A mid-term limit increase on a surplus lines policy may require a new filing and additional tax — if the agent processes it without the filing, you have a compliance gap."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Broker submission intake workflow with risk information collection","Specialty claims FNOL with coverage-specific data requirements","Breach response coordination workflow connecting insured, counsel, and forensics","Policy endorsement workflow with surplus lines compliance checks","Renewal marketing workflow with loss analysis and market comparison"], vendors: "Guidewire, Duck Creek, custom specialty platforms", risk: "Breach response coordination delays while the ransomware clock is ticking",
        stack: [{ name: "Guidewire / custom", role: "Specialty Claims", why: "Specialty claims (cyber breach, D&O investigation, marine hull loss) require claims platforms configured for low-frequency, high-severity, multi-party events. Most specialty carriers customize Guidewire or build proprietary claims platforms.", href: "/vendors" }],
        pitfall: "Cyber breach response has a golden hour — the first 60 minutes after a breach is detected determine whether containment succeeds or the attack spreads. The contact center's role is connecting the insured with breach counsel, forensic investigators, and notification vendors within that window. If the breach notification workflow takes 4 hours to activate the response team, the insured's containment window is gone. Pre-configure response teams by policy and test activation quarterly."
      },
      { layer: 1, name: "Data Access", capabilities: ["Policy administration for complex specialty forms and endorsements","Claims management for low-frequency, high-severity specialty claims","Broker management with submission pipeline and production tracking","Underwriting workbench with risk models and pricing tools","Reinsurance data for treaty and facultative placement tracking"], vendors: "Guidewire, Duck Creek, custom platforms, Salesforce", risk: "Policy form complexity exceeding what the agent desktop can display meaningfully",
        stack: [{ name: "Custom specialty platform", role: "Core Systems", why: "Many specialty carriers (Beazley, Hiscox, Markel, RLI) run custom or heavily customized policy admin platforms because standard systems don't support the complexity of specialty forms, manuscript endorsements, and multi-year policies.", href: "/vendors" }, { name: "Salesforce", role: "Broker CRM", why: "Broker relationship management, submission tracking, and market intelligence. The commercial layer connecting underwriting, marketing, and service.", href: "/vendors/ccaas" }],
        pitfall: "Specialty policy forms are often manuscript (custom-drafted) rather than standard ISO forms. This means the agent can't rely on generic coverage knowledge — they must reference the actual policy document to answer any coverage question. Build a document retrieval system that pulls the specific policy form into the agent desktop during the interaction. Without it, agents will say 'let me review your policy and call you back' for every coverage question."
      },
    ],
  },

  "insurtech": {
    name: "Insurtech & Digital Carriers", parent: "Insurance",
    tagline: "Digital-first insurance with app-native service, instant quoting, and AI-driven claims.",
    intro: "Insurtech contact centers promise what traditional carriers can't: instant quotes, one-tap claims filing, and chat-first support. Customers chose these carriers because the app experience is superior. The CX challenge is maintaining that speed and simplicity in the contact center — because when the app can't solve the problem, the expectation for human support is equally high.",
    kpis: [
      { metric: "AHT", avg: "4:30", note: "Fastest in insurance — digital-native users and simpler product sets" },
      { metric: "FCR", avg: "76%", note: "Above average — fewer product lines and integrated systems reduce handoffs" },
      { metric: "CSAT", avg: "84%", note: "Highest in insurance — self-selected digital-savvy population" },
      { metric: "Containment", avg: "40%", note: "Highest in insurance — app-native self-service handles routine queries" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["App experience monitoring with support trigger correlation","Claims AI accuracy tracking with human review audit","CSAT embedded in app with one-tap post-interaction feedback","Support volume correlation to app releases and product launches","Regulatory compliance dashboards meeting state DOI requirements"], vendors: "Amplitude, Mixpanel, NICE", risk: "Scaling support without losing the speed that defines the brand",
        stack: [{ name: "Amplitude", role: "Product Analytics", why: "Connects in-app behavior to support contacts. Shows which app screens or flows generate the most support tickets. Product fixes reduce support volume.", href: "/vendors" }],
        pitfall: "Insurtechs track product metrics (quote conversion, bind rate) and support metrics (CSAT, AHT) separately. The breakthrough insight is connecting them: if 15% of users who complete a quote but don't bind contact support within 24 hours, that's a product friction problem disguised as a support problem. Pipe support data into product analytics."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["In-app support routing with full user context and policy data","Claims routing with AI pre-triage for fast-track vs complex","Fraud detection routing flagging suspicious claims before assignment","Escalation routing for regulatory complaints and complex coverage questions","Chat-first routing with phone as overflow, not primary channel"], vendors: "Intercom, Zendesk, NICE CXone", risk: "Claims AI auto-approving a fraudulent claim without human review",
        stack: [{ name: "Intercom", role: "In-App Support", why: "In-app messaging with full user context. Agents see policy, claims history, and recent app activity. Purpose-built for product-led companies.", href: "/vendors/digital-engagement" }, { name: "Zendesk", role: "Support Platform", why: "More structured ticketing for insurtechs scaling past 50 agents. Better for managing the mix of claims, policy service, and billing.", href: "/vendors" }],
        pitfall: "Insurtechs deploy AI claims triage to auto-approve small claims (under $1K) for speed. But fraud detection must still run on auto-approved claims. An auto-approval that skips fraud screening creates an exploitable pattern — serial claimants learn the threshold and file claims just under it. Run fraud scoring on 100% of claims regardless of auto-approval status."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["In-app messaging as primary support channel","Photo and video claims documentation within the app","Proactive claims status push notifications","Self-service policy changes, endorsements, and cancellation","Chat-based FNOL with guided data collection"], vendors: "Intercom, Zendesk, Ada, Lemonade-style UX", risk: "Chat-only support frustrating customers with complex claims issues",
        stack: [{ name: "Intercom Messenger", role: "In-App Chat", why: "Native in-app messaging. Customer never leaves the app. Full policy and claims context visible to agents. Async messaging lets conversations continue across sessions.", href: "/vendors/digital-engagement" }],
        pitfall: "Insurtechs often launch chat-only and resist adding phone support. But complex claims — water damage with mold remediation, auto accident with injuries, theft with police report — generate customer anxiety that chat can't resolve. The customer needs to hear a human voice say 'we're taking care of this.' Add phone support for claims over a complexity threshold. Chat-only works for quoting and billing; it fails for serious claims."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Instant quote bots with real-time underwriting decisioning","Photo-based claims bots with AI damage assessment","Policy management bots (coverage changes, payment, cancellation)","Claims status bots with timeline and next-step guidance","FAQ bots covering coverage, deductibles, and filing claims"], vendors: "Ada, Lemonade AI Jim, custom AI", risk: "AI damage assessment undervaluing a claim and creating a dispute",
        stack: [{ name: "Custom AI / Ada", role: "Claims & Service AI", why: "Insurtechs build AI into the product, not as an add-on. Lemonade's AI Jim handles claims intake and instant payment. Root's AI assesses driving behavior. The AI IS the product — not a support tool.", href: "/vendors/iva" }],
        pitfall: "AI claims assessment (photo-based damage estimation) is powerful but imperfect. An AI that estimates $3,000 for a bumper repair when the actual cost is $5,000 creates a dispute that damages trust. Always present AI estimates as 'preliminary assessment pending adjuster review' — not as final settlement offers. The speed advantage of AI is in triage and initiation, not in final determination."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["State DOI compliance for all 50 states (or operating states)","Rate filing and form compliance for digital products","AI decisioning transparency and fair lending/pricing audit","Consumer data privacy (CCPA, state-specific) for app data","Claims handling compliance meeting traditional carrier standards"], vendors: "Custom compliance, Socotra, EIS", risk: "AI pricing or claims decisions creating fair treatment violations",
        stack: [{ name: "Socotra", role: "Modern Core", why: "API-first insurance core platform purpose-built for insurtechs. Policy admin, billing, and claims with modern APIs. Enables the digital-first experience that insurtechs promise.", href: "/vendors" }],
        pitfall: "Insurtechs face increasing regulatory scrutiny of AI decisioning — particularly pricing algorithms that may discriminate and claims AI that may systematically undervalue certain claim types. State regulators are requiring transparency in AI models. Build explainable AI from day one and maintain audit trails that demonstrate fair treatment across demographics. 'Move fast and break things' doesn't work in a regulated industry."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Instant bind workflow with real-time underwriting and payment","Photo-based claims FNOL with AI damage pre-assessment","Self-service policy modification with instant repricing","Cancellation workflow with instant refund calculation","Referral and rewards workflow for growth-driven insurtechs"], vendors: "Socotra, EIS, Majesco, custom platforms", risk: "Instant bind without adequate underwriting creating adverse selection",
        stack: [{ name: "Socotra", role: "Policy & Claims Engine", why: "Full insurance lifecycle — quote, bind, policy change, billing, and claims — on one API-first platform. Enables the one-tap experiences insurtechs promise.", href: "/vendors" }, { name: "EIS", role: "Digital Insurance Platform", why: "Cloud-native coretech platform for digital carriers. Policy admin, billing, claims, and engagement on a modern architecture.", href: "/vendors" }],
        pitfall: "Insurtechs optimize for instant everything — instant quote, instant bind, instant claim. But insurance requires accuracy alongside speed. An instant bind that doesn't verify the insured's identity, vehicle VIN, or property characteristics creates underwriting risk. An instant claim payment that doesn't verify coverage creates claims leakage. Build verification into the instant workflow — not as a separate step, but as a real-time check that runs in the background while the customer sees 'processing.'"
      },
      { layer: 1, name: "Data Access", capabilities: ["Modern core platform with real-time APIs (Socotra, EIS, Majesco Digital)","Telematics and IoT data for usage-based and behavioral pricing","Third-party data enrichment (property, vehicle, credit, claims history)","Product analytics (Amplitude, Mixpanel) for user behavior context","Payment platform for instant premium collection and claims payment"], vendors: "Socotra, EIS, Verisk, LexisNexis, Stripe", risk: "Third-party data dependency creating single points of failure",
        stack: [{ name: "Socotra / EIS", role: "Core Platform", why: "API-first means the support team accesses the same real-time data the app shows the customer. No batch delays, no stale information. The agent sees what the customer sees.", href: "/vendors" }, { name: "Verisk / LexisNexis", role: "Data Enrichment", why: "Property characteristics, claims history, vehicle data, and risk scores. Pre-fill applications and validate claims against external data. The data layer that enables instant underwriting.", href: "/vendors" }],
        pitfall: "Insurtechs build on modern core platforms (Socotra, EIS) with real-time APIs — which gives them a massive advantage over traditional carriers running batch-processing legacy systems. But this advantage only matters if the support team has the same real-time data access the customer has. If the customer's app shows a claim status of 'payment issued' but the support agent's system shows 'in review' because of a sync delay, the trust advantage evaporates. Ensure support tools and customer-facing tools read from the same real-time data source."
      },
    ],
  },
};

export const getInsuranceSubVertical = (slug) => insuranceSubVerticals[slug];
export const getAllInsuranceSubVerticalSlugs = () => Object.keys(insuranceSubVerticals);
