export const insuranceSubVerticals = {
  "personal-lines": {
    name: "Personal Lines P&C", parent: "Insurance",
    tagline: "Auto, home, renters, and umbrella. High-volume FNOL, CAT surges, and retention.",
    intro: "Personal lines P&C contact centers take some of the most emotional calls in insurance. Policyholders reach out after a collision or a destroyed roof, often during a regional catastrophe that multiplies volume overnight. The operating challenge is capturing complete FNOL data on the first contact while the policyholder feels heard, then holding that standard when CAT surges hit.",
    kpis: [
      { metric: "AHT", avg: "[[ins.sv.personal-lines.aht]]", note: "Driven by first notice of loss intake and coverage verification" },
      { metric: "FCR", avg: "[[ins.sv.personal-lines.fcr]]", note: "Claims that need adjuster assignment and follow-up hold it down" },
      { metric: "CSAT", avg: "[[ins.sv.personal-lines.csat]]", note: "Moves with claims speed and the clarity of claims communication" },
      { metric: "Containment", avg: "[[ins.sv.personal-lines.containment]]", note: "Billing automates well; first notice of loss and claims keep a person on the line" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Claims cycle time by peril type, adjuster, and region","FNOL quality scoring: completeness, empathy, and accuracy","CAT event response analytics: volume, wait time, and resolution speed","Retention analytics correlating service quality to renewal rates","Agent E&O risk monitoring for coverage statements and claim promises"],
        vendors: "NICE Nexidia, Verint, Medallia", risk: "FNOL quality degradation during CAT surges",
        stack: [{ name: "NICE Nexidia", role: "Interaction Analytics", why: "Automated FNOL quality scoring detecting missing data fields, incorrect coverage statements, and empathy gaps. Critical for post-CAT quality review when volume overwhelms normal QA capacity.", href: "/vendors/analytics" }, { name: "Medallia", role: "CX Platform", why: "Claims journey analytics connecting FNOL experience, adjuster interaction, and settlement communication to overall policyholder satisfaction and renewal likelihood.", href: "/vendors/analytics" }],
        pitfall: "Carriers often pause QA during a catastrophe because the floor is in crisis mode. That is when QA matters most: newly trained surge agents talking to distressed policyholders carry the most E&O exposure. Deploy automated QA (NICE Nexidia) that scores every interaction even during CAT, flagging compliance issues in real-time rather than discovering them during the post-mortem."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["FNOL priority routing with peril-type classification at first contact","CAT surge protocols activating overflow capacity within hours","Licensed adjuster routing for coverage questions and claim decisions","Retention routing for policyholders at renewal with competitive signals","After-hours FNOL routing maintaining 24/7 claim reporting capability"],
        vendors: "Genesys, NICE CXone, Talkdesk Insurance", risk: "FNOL calls waiting behind billing inquiries during CAT events",
        stack: [{ name: "Genesys Cloud", role: "Primary CCaaS", why: "CAT surge routing activates overflow agents, deploys geo-targeted IVR messaging, and prioritizes affected policyholders, all within hours of event declaration.", href: "/vendors/genesys" }, { name: "Talkdesk Insurance", role: "Vertical CCaaS", why: "Pre-built FNOL routing with peril classification. Separates auto, property, and liability at first contact. Faster deployment than building insurance-specific routing on a generic platform.", href: "/vendors/talkdesk" }],
        pitfall: "CAT routing must be pre-configured and tested BEFORE the event. A hurricane doesn't wait for your IT team to configure surge routing. Build CAT playbooks with pre-approved IVR changes, agent overflow activation, and geographic routing rules. Test them quarterly with simulated surge volume. The carriers that respond well to CAT events are the ones that rehearsed."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure photo and video upload for damage documentation during FNOL","Proactive claims milestone notifications via SMS and email","Two-way messaging for adjuster-policyholder communication","Self-service claims status portal reducing status-check call volume","Renewal communication with coverage review and competitive context"],
        vendors: "Hi Marley, Glia, LivePerson, Sprinklr", risk: "Policyholders waiting days for claims updates when the adjuster hasn't been assigned yet",
        stack: [{ name: "Hi Marley", role: "Insurance Messaging", why: "Purpose-built for P&C insurance. Two-way texting for FNOL follow-up, adjuster coordination, and claims updates. Built by insurance people who understand that policyholders text, they don't log into portals.", href: "/vendors/digital-engagement" }, { name: "Glia", role: "Digital CX", why: "Secure photo upload during FNOL calls: policyholder shares damage photos while on the phone with the agent. Co-browsing for policy document review.", href: "/vendors/digital-engagement" }],
        pitfall: "Claim status calls can make up [[ins.pl.status.share]] of contact volume after first notice of loss. Most of these callers have no problem with the claim; they simply cannot see where it stands. Proactive milestone messages (claim received, adjuster assigned, inspection scheduled, estimate complete, payment issued) can remove [[ins.pl.status.cut]] of status calls, and texting platforms such as Hi Marley make them straightforward to send. Where this stalls, it is often because claims and CX sit in separate budgets."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["FNOL intake bots collecting peril-specific data (auto vs property vs liability)","Claims status bots with real-time adjuster and timeline visibility","Policy coverage lookup bots verifying what's covered before the claim","Billing and payment bots for premium inquiries and payment arrangements","Renewal quote comparison bots presenting competitive retention context"],
        vendors: "Cognigy, Kore.ai, Shift Technology AI", risk: "Bot collecting incomplete FNOL data that delays adjuster assignment",
        stack: [{ name: "Cognigy", role: "Conversational AI", why: "Insurance-specific FNOL intake with peril-branching logic. Auto FNOL collects different data than property FNOL: vehicle info, other party, police report vs damage description, temporary housing needs, mitigation steps.", href: "/vendors/iva" }, { name: "Shift Technology", role: "Claims AI", why: "AI fraud detection at FNOL: analyzes claim data patterns to flag suspicious claims before adjuster assignment. Reduces fraud leakage without slowing legitimate claims.", href: "/vendors" }],
        pitfall: "FNOL bots must collect different data for different perils: an auto FNOL needs: date/time/location, vehicle info, other party details, injuries, police report number. A property FNOL needs: date of loss, damage description, temporary housing needs, emergency mitigation taken. A bot that asks the same generic questions for every peril will either miss critical data (delaying the claim) or ask irrelevant questions (frustrating the policyholder). Build peril-specific intake flows."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["State DOI compliance for claims handling timelines by jurisdiction","Unfair claims practices act monitoring across all interactions","Anti-fraud detection integrated into FNOL and claims workflows","Recorded statement protocols with required legal disclosures","E&O controls preventing agents from making coverage promises"],
        vendors: "Shift Technology, Verisk, SAS, NICE Actimize", risk: "State-specific timeline violations creating DOI complaints and penalties",
        stack: [{ name: "Shift Technology", role: "Fraud Detection", why: "AI-powered claims fraud detection analyzing FNOL data, claimant history, and external indicators in real-time. Flags suspicious claims for SIU review before payment. ", href: "/vendors" }, { name: "Verisk", role: "Claims Data & Validation", why: "ISO ClaimSearch cross-references claims across carriers to detect duplicate or suspicious filing patterns. Property data validates damage claims against actual property characteristics.", href: "/vendors" }],
        pitfall: "Claims handling deadlines are set by each state. California requires an insurer to acknowledge a notice of claim within [[ins.reg.ca.ack]]; New York within [[ins.reg.ny.ack]]; Florida within [[ins.reg.fl.ack]], and Florida also requires a property claim to be paid or denied within [[ins.reg.fl.decide]] of notice. A national carrier runs a different rule set in every state it writes. Put the state deadlines in the claims workflow engine and let it escalate claims as a deadline approaches, so no adjuster has to remember which state has which clock."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["FNOL intake workflow with peril-specific data requirements and auto-assignment","Claims triage and adjuster assignment by peril, complexity, and geography","Subrogation identification and tracking workflow","Policy endorsement workflow with premium recalculation","Retention save workflow with competitive pricing and coverage review"],
        vendors: "Guidewire, Duck Creek, Majesco, Pega", risk: "Claims assignment bottleneck during CAT events when all adjusters are deployed",
        stack: [{ name: "Guidewire ClaimCenter", role: "Claims Management", why: "Widely used for P&C claims. FNOL, assignment, reserving, payment, and subrogation in one platform. Guidewire Cloud is the modernization path many carriers are taking.", href: "/vendors" }, { name: "Duck Creek Claims", role: "Claims Platform", why: "SaaS-native alternative. Faster implementation for mid-market carriers. Growing API ecosystem for CX and digital integration.", href: "/vendors" }],
        pitfall: "Claim assignment is the bottleneck in a catastrophe: [[ins.ex.pl.cat]]. Automated triage that assigns simple claims (windshield, minor water damage) to fast-track adjusters while routing complex claims (structural damage, total loss) to senior adjusters prevents the backlog from growing. Without triage, every claim enters the same queue and cycle times explode uniformly."
      },
      { layer: 1, name: "Data Access", capabilities: ["Policy administration system (coverage, limits, deductibles, endorsements)","Claims management system (FNOL, reserves, payments, adjuster notes)","Billing system (premium, payment history, installment schedule)","Agent/broker portal with production and commission data","Document management for claims files, photos, and correspondence"],
        vendors: "Guidewire, Duck Creek, Majesco, Sapiens, Salesforce FSC", risk: "Agent seeing policy data but not claims data, or vice versa",
        stack: [{ name: "Guidewire InsuranceSuite", role: "Core Systems", why: "PolicyCenter + ClaimCenter + BillingCenter = the data foundation. Real-time APIs in Cloud edition. The contact center agent's capability ceiling is set by how deeply you integrate with Guidewire.", href: "/vendors" }, { name: "Salesforce Financial Services Cloud", role: "CRM", why: "Policyholder relationship view connecting policy, claims, billing, and interaction history. The CRM layer that unifies Guidewire data into an agent-friendly desktop.", href: "/vendors/ccaas" }],
        pitfall: "Many P&C carriers run separate policy, claims, and billing systems, often from different vendors or different eras. The contact center agent needs data from all three to answer a simple question like 'I had a claim last month, will my premium go up at renewal?' Without a unified view, the agent checks policy (yes, you're active), checks claims (yes, a payment went out), and guesses at the premium impact (because that's an actuarial calculation they can't access). Build a unified agent desktop or accept that agents will always give incomplete answers."
      },
    ],
  },

  "commercial-lines": {
    name: "Commercial Lines", parent: "Insurance",
    tagline: "Business insurance, general liability, commercial property, and fleet.",
    intro: "Commercial lines contact centers serve businesses whose insurance needs are complex, multi-policy, and broker-mediated. A manufacturer with GL, property, fleet auto, workers' comp and umbrella coverage across many states calls about a business risk that spans all of those policies. The CX challenge is B2B service depth with B2C responsiveness.",
    kpis: [
      { metric: "AHT", avg: "[[ins.sv.commercial-lines.aht]]", note: "Driven by multi-policy, multi-location accounts and broker coordination" },
      { metric: "FCR", avg: "[[ins.sv.commercial-lines.fcr]]", note: "Issues that span policies, locations and coverage layers need follow-up" },
      { metric: "CSAT", avg: "[[ins.sv.commercial-lines.csat]]", note: "Moves with relationship strength and the complexity of the account" },
      { metric: "Containment", avg: "[[ins.sv.commercial-lines.containment]]", note: "Commercial coverage questions need human expertise; certificates automate well" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Account profitability analytics connecting service cost to premium revenue","Broker satisfaction tracking separate from policyholder satisfaction","Claims frequency and severity trends by industry class and region","Renewal retention analytics by account size and line of business","Underwriting referral tracking from contact center to underwriting team"], vendors: "NICE, Verint, Salesforce Analytics", risk: "High-premium accounts receiving the same service as small accounts",
        stack: [{ name: "NICE CXone", role: "Analytics & QA", why: "Separate QA scorecards for direct policyholder interactions vs broker-channel interactions. Commercial service quality is measured differently than personal lines.", href: "/vendors/nice-cxone" }],
        pitfall: "Commercial lines analytics must connect service interactions to account profitability. [[ins.ex.cl.profit]] Track service cost per account alongside premium to understand the true cost-to-serve for your commercial book."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Named account manager routing for large commercial accounts","Broker vs direct policyholder routing with different service models","Line-of-business routing (GL, property, auto, WC, umbrella)","Certificate of insurance routing to automated or specialized teams","Claims FNOL routing with commercial complexity triage"], vendors: "Genesys, NICE CXone, Cisco", risk: "Broker reaching a personal lines agent who can't navigate commercial systems",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Named-account routing with full commercial account context. Routes broker calls separately from direct calls. Handles the multi-policy complexity of commercial accounts.", href: "/vendors/genesys" }],
        pitfall: "Certificates of insurance are frequent, simple requests that still take up agent time when handled by phone. Automate certificate generation and delivery. [[ins.ex.cl.coi]]"
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Broker portal with real-time policy, claims, and commission data","Certificate of insurance self-service portal with digital delivery","Proactive renewal communication well ahead of expiration","Claims status portal for commercial policyholders with multi-claim view","Audit and compliance document exchange via secure channels"], vendors: "Glia, Salesforce, broker portals", risk: "Broker and carrier communicating about the same account without shared visibility",
        stack: [{ name: "Salesforce Experience Cloud", role: "Broker Portal", why: "Self-service broker portal with real-time policy data, commission statements, and claims status. Gives brokers the status answers they would otherwise call for.", href: "/vendors/ccaas" }],
        pitfall: "Commercial renewals are complex negotiations, not automated notices. A large account renewal involves loss analysis, market comparison, coverage review, and premium negotiation between the broker, underwriter, and policyholder. The contact center's role is coordination and status, but many carriers don't give contact center agents visibility into the renewal pipeline. Build renewal status into the agent desktop so agents can answer 'where does my renewal stand?' without transferring to underwriting."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Certificate of insurance generation bots with automated delivery","Policy coverage verification bots for multi-policy commercial accounts","Claims status bots with multi-claim, multi-location visibility","Billing and installment management bots","Basic underwriting referral bots collecting risk information"], vendors: "Cognigy, Ada", risk: "Bot misrepresenting coverage on a multi-policy commercial account",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles COI requests, billing inquiries, and claims status. Routes complex commercial underwriting and coverage questions to human experts.", href: "/vendors/iva" }],
        pitfall: "Commercial coverage questions are dangerous for bots. A business owner asking 'does my policy cover water damage from a broken pipe?' requires analysis of the specific policy form, endorsements, exclusions, and sublimits. A bot that says 'yes' when the policy has a water damage exclusion creates E&O liability. Restrict bots to administrative tasks and route all coverage questions to licensed agents."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Multi-state compliance for commercial operations across jurisdictions","Surplus lines compliance for non-admitted coverage placement","E&O controls for commercial coverage representations","Anti-fraud monitoring for commercial claims patterns","Regulatory reporting for large commercial claims and market conduct"], vendors: "Verisk, ISO, NICE Actimize", risk: "Coverage misrepresentation on a multi-million-dollar commercial account",
        stack: [{ name: "Verisk / ISO", role: "Commercial Data", why: "Commercial lines rating, classification, and loss cost data. Validates that coverage is rated and classified correctly. The compliance data foundation for commercial underwriting and servicing.", href: "/vendors" }],
        pitfall: "Commercial E&O exposure can be far larger than in personal lines. [[ins.ex.cl.eo]] Every contact center interaction involving commercial coverage must be recorded, quality-scored, and reviewed for coverage accuracy. The cost of QA is trivial compared to the cost of one E&O claim."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Certificate of insurance automation with holder tracking and delivery","Commercial renewal workflow with loss analysis and market comparison","Multi-location policy change workflow with state-specific compliance","Commercial claims FNOL with business interruption assessment","Audit premium reconciliation workflow with payroll and revenue verification"], vendors: "Guidewire, Duck Creek, Pega, Salesforce", risk: "Manual COI processes consuming agent time on low-value requests",
        stack: [{ name: "Guidewire PolicyCenter", role: "Policy Admin", why: "Commercial policy administration with multi-line, multi-state complexity. The workflow engine that determines what policy changes agents can make and what requires underwriter approval.", href: "/vendors" }],
        pitfall: "Commercial audits (annual premium reconciliation based on actual payroll/revenue vs estimated) generate significant contact center volume because policyholders don't understand why they owe additional premium. Build a proactive audit communication workflow: notify the policyholder [[ins.cl.audit.notice]] before the audit, explain the process, provide documentation requirements, and offer a payment plan for any additional premium. Reactive audit notices create angry calls."
      },
      { layer: 1, name: "Data Access", capabilities: ["Policy administration with multi-line, multi-location commercial accounts","Claims management across GL, property, auto, and WC for same account","Billing with complex premium installment and audit reconciliation","Broker management system with production, commission, and correspondence","Underwriting workbench with risk data, loss history, and pricing"], vendors: "Guidewire, Duck Creek, Salesforce, Applied Epic", risk: "Agent seeing one policy line but not the full commercial account relationship",
        stack: [{ name: "Applied Epic", role: "Agency Management", why: "A widely used agency management system. Brokers use Applied Epic to manage their book. Carriers that integrate with Applied Epic give agents visibility into the broker relationship.", href: "/vendors" }, { name: "Guidewire InsuranceSuite", role: "Core Systems", why: "Policy, claims, and billing for the carrier side. The agent desktop must show the full commercial account, all policies, all claims, all billing, in one view.", href: "/vendors" }],
        pitfall: "Commercial accounts are multi-policy relationships. [[ins.ex.cl.account]] If the agent desktop shows these as separate policies instead of one commercial account, the agent can't understand the relationship or provide relationship-level service. Build an account-level view that shows all policies, total premium, total claims, and account profitability."
      },
    ],
  },

  "life-annuities": {
    name: "Life Insurance & Annuities", parent: "Insurance",
    tagline: "Policy servicing, beneficiary changes, premium payments, surrenders, and death claims.",
    intro: "Life insurance contact centers manage the longest customer relationships in financial services: policies that can run for decades. The CX challenge is staying relevant and accurate across that span while handling one of the hardest conversations in insurance: the death claim.",
    kpis: [
      { metric: "AHT", avg: "[[ins.sv.life-annuities.aht]]", note: "Servicing calls run short; death claims and surrenders run long" },
      { metric: "FCR", avg: "[[ins.sv.life-annuities.fcr]]", note: "Servicing resolves on the call; surrenders and death claims wait on documents" },
      { metric: "CSAT", avg: "[[ins.sv.life-annuities.csat]]", note: "Moves with how death claims and surrenders are handled" },
      { metric: "Containment", avg: "[[ins.sv.life-annuities.containment]]", note: "Premium payments and balance inquiries automate; beneficiary and death claims need people" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Policyholder engagement tracking across decades-long relationships","Surrender and lapse risk prediction based on payment patterns and inquiries","Death claim processing time and family satisfaction tracking","Agent compliance scoring for illustrations, projections, and suitability","Orphan policy identification: policies without an assigned agent/advisor"], vendors: "NICE, Verint, Qualtrics", risk: "Orphan policyholders churning without any proactive engagement",
        stack: [{ name: "NICE CXone", role: "QA & Compliance", why: "Compliance-scored QA for life insurance interactions. Detects unauthorized illustrations, incorrect cash value statements, and suitability concerns. Critical for regulatory examination readiness.", href: "/vendors/nice-cxone" }],
        pitfall: "Silence after the sale is a lapse risk. In a Capgemini and LIMRA survey, [[ins.life.rarelyhear]] of policyholders said they rarely hear from their life insurer after purchase. A policyholder who bought a whole life policy years ago and has heard nothing since may let it go when money gets tight, because it no longer feels relevant. Track engagement signals (login frequency, statement opens, inquiry calls) and proactively reach out to disengaged policyholders before they lapse."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Death claim priority routing with empathy-trained specialist teams","Surrender and loan request routing to retention-skilled agents","Agent/advisor routing for servicing their assigned policyholders","Compliance routing for illustration requests and replacement discussions","After-hours routing for death notification and claim initiation"], vendors: "Genesys, NICE CXone", risk: "Death claim caller reaching a general servicing agent unprepared for the conversation",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Empathy-routing for death claims: detects bereavement context and routes to trained specialists. WEM schedules death claim specialists across business hours.", href: "/vendors/nice-cxone" }],
        pitfall: "Death claims are among the most important interactions in life insurance, and they are often undertrained. A surviving spouse calling to report a death and file a claim needs an agent who combines empathy, procedural accuracy, and patience. Training often covers death claim procedure and stops short of how to hold the conversation. Invest in bereavement communication training and route all death calls to certified specialists."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Self-service premium payment and policy loan portal","Secure document upload for death certificates and claim forms","Proactive policy anniversary communications with value updates","Beneficiary update portal with digital verification","Life event-triggered outreach (marriage, birth, retirement)"], vendors: "Glia, Salesforce, custom portals", risk: "Death claim documentation process feeling bureaucratic during grief",
        stack: [{ name: "Glia", role: "Digital CX", why: "Secure document upload during phone calls, surviving spouse can send death certificate while speaking with the agent. Eliminates the 'mail us the documents and wait' experience.", href: "/vendors/digital-engagement" }],
        pitfall: "Death claim documentation requirements (certified death certificate, claim form, policy, claimant identification) feel bureaucratic to a grieving family. Simplify by: accepting digital copies initially while originals are in transit, pre-populating claim forms with known policy data, and providing a single point of contact for the entire claim process. The family should never have to explain the situation to a second person."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Premium payment and billing status bots","Cash value and loan availability bots with real-time calculations","Policy information bots (coverage amount, beneficiaries, riders)","Beneficiary update initiation bots with verification workflow","Address and contact information change bots"], vendors: "Ada, Cognigy", risk: "Bot providing cash value projection that differs from the actual illustration",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles premium payments, policy lookups, and basic servicing requests. Routes death claims, surrenders, and illustration requests to human agents immediately.", href: "/vendors/iva" }],
        pitfall: "Cash value bots must pull real-time data from the policy administration system, not cached or estimated values. [[ins.ex.life.bot]] creates a reliance problem if the policyholder makes financial decisions based on that number. Either provide the exact real-time figure or say 'I can connect you with an agent who can provide your current cash value.'"
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Suitability compliance for replacement discussions and new illustrations","State-specific free look period and cancellation right disclosures","Anti-money laundering controls for large premium payments and surrenders","Privacy compliance for beneficiary and medical information","NAIC model regulation compliance for policy illustrations and projections"], vendors: "NICE Actimize, Verint, compliance systems", risk: "Replacement discussion without required comparison disclosure creating regulatory violation",
        stack: [{ name: "NICE Actimize", role: "Compliance Monitoring", why: "Detects unauthorized replacement discussions where agents recommend surrendering one policy to buy another without proper suitability analysis and disclosure. A common enforcement target for state regulators.", href: "/vendors" }],
        pitfall: "Life insurance replacement rules based on the NAIC Life Insurance and Annuities Replacement Model Regulation ([[ins.naic.613]]) require specific disclosures and comparison documents when a policyholder is considering replacing an existing policy with a new one. If a contact center agent discusses replacement without triggering the compliance workflow, the carrier faces regulatory action. Build replacement-detection logic that flags keywords ('cancel this policy and buy a new one,' 'better rate elsewhere') and triggers compliance review."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Death claim intake and processing workflow with document tracking","Policy loan and withdrawal workflow with tax implications notification","Beneficiary change workflow with proper verification and documentation","Surrender and lapse reinstatement workflow with retention intervention","Premium payment mode change workflow (annual to monthly, auto-pay enrollment)"], vendors: "FAST, OIPA, Sapiens, EXL", risk: "Death claim processing stretching into weeks because of documentation bottlenecks",
        stack: [{ name: "FAST (FINEOS)", role: "Life Admin", why: "Policy administration for life and annuity carriers. Premium billing, policy values, and claims processing. The workflow engine that determines death claim processing speed.", href: "/vendors" }, { name: "Sapiens", role: "Life Platform", why: "Core life insurance platform with policy admin, claims, and billing. Cloud capabilities growing. Strong in mid-market life carriers.", href: "/vendors" }],
        pitfall: "Death claim processing has a direct emotional impact that no other insurance workflow has. [[ins.ex.life.wait]] is unlikely to recommend the carrier. Streamline: accept digital documents, fast-track smaller claims with simplified verification, and provide interim payments for documented funeral costs while the full claim processes."
      },
      { layer: 1, name: "Data Access", capabilities: ["Policy administration system (coverage, values, riders, beneficiaries, history)","Billing system (premium payments, frequency, grace period, lapse status)","Claims system (death claims, disability, accelerated benefits)","Agent/advisor database (assigned producer, commission, service history)","Illustration system (current values, projections, comparison reports)"], vendors: "FAST, OIPA, Sapiens, LIDP, Salesforce", risk: "Cash values calculated by the admin system not matching customer-facing illustrations",
        stack: [{ name: "OIPA (Oracle Insurance)", role: "Policy Admin", why: "High-performance life policy administration. Real-time cash value calculations, rider processing, and premium billing. Strong in large life carriers.", href: "/vendors" }, { name: "Salesforce Financial Services Cloud", role: "CRM", why: "Policyholder relationship view across all policies, beneficiaries, and interactions. Connects the servicing team to the advisor for orphan policy management.", href: "/vendors/ccaas" }],
        pitfall: "Life insurance policy admin systems calculate cash values, dividends, and loan interest using complex actuarial formulas. The contact center agent sees a 'current cash value' field but can't explain how it was calculated or why it differs from what the policyholder expected. Train agents to explain value drivers (premiums paid, interest credited, cost of insurance deducted, loan balance) or build a visual value breakdown in the agent desktop. [[ins.ex.life.cashvalue]]"
      },
    ],
  },

  "workers-comp": {
    name: "Workers' Compensation", parent: "Insurance",
    tagline: "Injury reporting, claims management, return-to-work coordination, and employer/employee dual-audience.",
    intro: "Workers' comp contact centers serve two audiences with different needs: employers (reporting injuries, managing premiums, understanding experience mods) and injured workers (filing claims, understanding benefits, navigating medical treatment). The CX challenge is balancing employer accountability with employee advocacy, while managing the medical and legal complexity of every claim.",
    kpis: [
      { metric: "AHT", avg: "[[ins.sv.workers-comp.aht]]", note: "Driven by injury details, medical coordination and return-to-work planning" },
      { metric: "FCR", avg: "[[ins.sv.workers-comp.fcr]]", note: "Claims involve medical providers, employers and legal coordination" },
      { metric: "CSAT", avg: "[[ins.sv.workers-comp.csat]]", note: "Injured workers and employers want different things from the same claim" },
      { metric: "Containment", avg: "[[ins.sv.workers-comp.containment]]", note: "Injury claims need human judgment and empathy" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Claims cost development tracking by injury type and employer","Return-to-work timeline analytics with medical provider correlation","Employer experience modification impact forecasting","Fraud detection analytics for claim patterns and medical treatment","Injured worker satisfaction tracking through the claim lifecycle"], vendors: "NICE, Verint, custom WC analytics", risk: "Claims costs developing beyond reserves without early detection",
        stack: [{ name: "NICE CXone", role: "QA & Analytics", why: "Dual-audience QA: separate scorecards for employer interactions (accuracy, cost context) and injured worker interactions (empathy, benefits clarity, medical coordination).", href: "/vendors/nice-cxone" }],
        pitfall: "Workers' comp analytics must track claims cost development: the difference between initial reserve and ultimate paid. If contact center decisions (approving treatment, extending lost time, accepting late-reported claims) systematically increase development, the contact center is creating underwriting losses that only surface years later. Connect contact center decisions to actuarial outcomes."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Employer vs injured worker routing with different service models","Injury severity triage routing: minor first aid vs serious injury vs fatality","Medical provider routing for treatment authorization and bill review","Return-to-work coordinator routing for transitional duty planning","Legal routing for litigated claims with attorney involvement"], vendors: "Genesys, NICE CXone", risk: "Injured worker calling about their claim reaching the employer service team",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Dual-audience routing separating employer and injured worker paths. Injury severity classification at first contact determines urgency and specialist assignment.", href: "/vendors/genesys" }],
        pitfall: "Workers' comp has a unique routing challenge: the employer and the injured worker may call about the same claim but need different information and different agents. The employer wants cost impact and return-to-work timeline; the injured worker wants benefits amount and medical treatment authorization. If they reach the same agent, the agent must switch contexts, and risk sharing employer-sensitive information with the worker or vice versa. Build separate routing paths."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure injury reporting portal for employers with photo documentation","Injured worker benefits explanation with state-specific calculation","Medical provider treatment authorization communication","Return-to-work coordination messaging between employer, worker, and carrier","Proactive claim milestone notifications to both employer and injured worker"], vendors: "Hi Marley, Glia, custom portals", risk: "Injured worker not understanding their benefits or treatment rights",
        stack: [{ name: "Hi Marley", role: "Insurance Messaging", why: "Two-way texting with injured workers for appointment reminders, benefits updates, and return-to-work coordination. Workers' comp claimants are often hourly workers who can't take phone calls during shift hours, texting is the accessible channel.", href: "/vendors/digital-engagement" }],
        pitfall: "Injured workers are often hourly employees who can't take phone calls during work hours (even if they're on light duty). [[ins.ex.wc.hours]] The two will keep missing each other. Text-based communication (Hi Marley) respects the worker's schedule and produces faster claim resolution."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["First report of injury bots collecting OSHA-required data","Claim status bots with benefits calculation and payment schedule","Medical treatment authorization status bots","Return-to-work planning bots with transitional duty options","Employer experience mod explanation bots"], vendors: "Cognigy, Ada", risk: "Bot calculating benefits incorrectly due to state-specific formula differences",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles claim status, payment schedule, and basic benefits inquiries. Routes complex medical authorization and return-to-work questions to trained adjusters.", href: "/vendors/iva" }],
        pitfall: "Workers' comp benefits are calculated using state-specific formulas: wage replacement rate, maximum weekly benefit, waiting period, and duration all vary by state. [[ins.ex.wc.rate]] Either build state-specific benefit calculation or restrict the bot to 'your benefits have been calculated at $X per week: here's how to reach your adjuster if you have questions.'"
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["State-specific workers' comp regulatory compliance (each state sets its own rules)","OSHA reporting requirements for workplace injuries","Medical treatment guidelines by jurisdiction (ODG, ACOEM)","Anti-fraud controls for claims investigation","Privacy compliance for medical records and injury documentation"], vendors: "ISO, NCCI, state rating bureaus", risk: "State regulatory violations from applying one state's rules to another state's claim",
        stack: [{ name: "NCCI / state bureaus", role: "Regulatory Data", why: "Class codes, experience modification, and loss cost data. The regulatory foundation that determines premium and compliance requirements. Varies by state: monopolistic states, competitive states, and NCCI states all have different rules.", href: "/vendors" }],
        pitfall: "Workers' comp is jurisdictionally complex. In [[ins.wc.monopolistic]] states (North Dakota, Ohio, Washington and Wyoming) an exclusive state fund writes the coverage; elsewhere private carriers compete, and the rules for reporting, benefits and medical treatment differ from state to state. Agents must know which state's rules govern each claim. That can be the state where the injury happened or the state where the worker was hired or is based, so it is not simply the employer's home state."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["First report of injury workflow with employer and worker data collection","Medical treatment authorization workflow with provider communication","Return-to-work planning workflow with transitional duty matching","Subrogation identification for third-party liability recovery","Experience modification impact analysis for employer risk management"], vendors: "Guidewire, Origami Risk, Mitchell, custom WC platforms", risk: "Delayed return-to-work extending claim duration and costs",
        stack: [{ name: "Origami Risk", role: "WC Claims Platform", why: "Risk management and claims platform popular in mid-market WC. Claims administration, medical management, and return-to-work coordination. More accessible than Guidewire for smaller operations.", href: "/vendors" }, { name: "Mitchell (Enlyte)", role: "Medical Management", why: "Medical bill review, treatment authorization, and pharmacy management for WC. The medical cost containment layer that integrates with claims administration.", href: "/vendors" }],
        pitfall: "Return to work is a central claims outcome in workers' comp, and the contact center shapes it. Early contact with the injured worker (a target of [[ins.wc.contact]] after the first report), proactive medical coordination and transitional duty planning all shorten the time off work. Leaving return to work to the adjuster alone gives up one of the contact center's most useful levers."
      },
      { layer: 1, name: "Data Access", capabilities: ["Claims administration system (injury details, benefits, payments, reserves)","Medical management system (treatment authorization, provider network, bill review)","Policy and premium data (class codes, payroll, experience modification)","Employer data (locations, payroll by class, loss history)","Regulatory data (state rules, benefit rates, reporting requirements)"], vendors: "Guidewire, Origami Risk, Mitchell, NCCI", risk: "Medical and claims data in separate systems without integration",
        stack: [{ name: "Guidewire ClaimCenter", role: "Claims Admin", why: "Enterprise WC claims administration. Integrates medical management, return-to-work, and litigation tracking. The data foundation for every WC claims interaction.", href: "/vendors" }, { name: "Mitchell / Enlyte", role: "Medical Data", why: "Medical bill review data, treatment guidelines, and pharmacy management. When an injured worker asks 'is my surgery approved?' the answer is in Mitchell.", href: "/vendors" }],
        pitfall: "Workers' comp data spans claims, medical, and employer systems, and the agent needs all three. An injured worker calling about a denied treatment authorization needs: claim status (claims system), treatment details and denial reason (medical management), and employer's return-to-work options (employer portal). Three systems, three logins, three contexts. Build a unified WC agent desktop or accept long handle times on every call."
      },
    ],
  },

  "specialty-lines": {
    name: "Specialty & Surplus Lines", parent: "Insurance",
    tagline: "Cyber, E&O, D&O, marine, aviation, and excess: sophisticated policyholders and broker-driven.",
    intro: "Specialty lines contact centers serve some of the most sophisticated policyholders and brokers in insurance. A CFO calling about their D&O coverage limit and a CISO calling about their cyber incident response protocol expect expert-level service, not generalist agents reading from scripts. The CX challenge is staffing a contact center with the technical insurance knowledge that specialty lines demand.",
    kpis: [
      { metric: "AHT", avg: "[[ins.sv.specialty-lines.aht]]", note: "Driven by complex coverage discussions and claims coordination" },
      { metric: "FCR", avg: "[[ins.sv.specialty-lines.fcr]]", note: "Claims need underwriter, legal and broker coordination" },
      { metric: "CSAT", avg: "[[ins.sv.specialty-lines.csat]]", note: "Moves with whether the agent's expertise matches the caller's" },
      { metric: "Containment", avg: "[[ins.sv.specialty-lines.containment]]", note: "Nearly every contact needs specialist knowledge" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Broker satisfaction by market and product line","Claims severity tracking for low-frequency, high-severity events","Underwriting referral quality from contact center to specialty underwriters","Coverage accuracy monitoring for complex policy forms","Market cycle analytics connecting pricing trends to service volume"], vendors: "NICE, custom analytics", risk: "Coverage misstatement on a large specialty policy creating major E&O exposure",
        stack: [{ name: "NICE CXone", role: "QA & Compliance", why: "Compliance monitoring for specialty coverage discussions. Every statement about coverage limits, exclusions, or conditions must be accurate against the policy form. Automated detection of potential E&O statements.", href: "/vendors/nice-cxone" }],
        pitfall: "Specialty lines QA must be performed by people who understand the coverage. A generic QA analyst scoring a D&O interaction can evaluate empathy and process compliance but cannot evaluate whether the agent correctly described the insured vs insured exclusion. Staff specialty QA with insurance-trained reviewers, not generic contact center QA analysts."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Product-line routing by specialty (cyber, D&O, E&O, marine, aviation)","Broker-tier routing prioritizing high-production wholesale brokers","Claims routing to specialty adjusters by coverage type","Underwriting referral routing with risk information pre-collection","After-hours routing for cyber incident and crisis notification"], vendors: "Genesys, NICE CXone", risk: "Cyber incident notification reaching a general agent overnight",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Specialty-specific routing matching callers to agents with product expertise. Cyber incident notifications route to breach response teams 24/7.", href: "/vendors/genesys" }],
        pitfall: "Cyber insurance policies include incident response hotlines that must be answered 24/7 by people who understand breach response protocols, not by answering services or general agents. When a CISO calls in the middle of the night to report a ransomware attack, they need to reach a breach response coordinator within minutes, not leave a message. Staff and route the incident hotline as a critical path, separate from general servicing."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Secure breach notification and incident reporting portal","Broker submission portal for new business and renewals","Claims reporting with specialized intake forms by coverage type","Market update communications for pricing and capacity changes","Expert roundtable and webinar coordination for policyholder engagement"], vendors: "Glia, Salesforce, custom broker portals", risk: "Sensitive breach information transmitted through unsecured channels",
        stack: [{ name: "Salesforce Experience Cloud", role: "Broker Portal", why: "Wholesale broker portal with submission tracking, quote status, and policy management. Reduces broker calls for status updates while maintaining the relationship.", href: "/vendors/ccaas" }],
        pitfall: "Cyber insurance breach notifications contain extremely sensitive information: company name, type of breach, data compromised, ransom demanded. This information must be transmitted through encrypted, access-controlled channels, not email, not voicemail, not generic ticketing systems. Build a secure incident portal with access limited to breach response team members and encrypted end-to-end."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Policy coverage summary bots for complex specialty forms","Broker submission status bots with underwriting timeline","Claims status bots for specialty claims in progress","Certificate and evidence of insurance automation","Basic coverage FAQ bots by specialty line"], vendors: "Limited use: specialty requires human expertise", risk: "Bot attempting to explain D&O coverage exclusions incorrectly",
        stack: [{ name: "Minimal AI", role: "None", why: "Specialty insurance interactions require expert knowledge that current AI cannot reliably provide. Use AI for administrative tasks (submission status, payment processing) and route all coverage, claims, and underwriting questions to human specialists. The containment target for specialty lines should be [[ins.sp.containment]]." }],
        pitfall: "Specialty insurance is a poor fit for customer-facing AI. The coverage is complex, the stakes are high, and the policyholders are sophisticated enough to know when an answer is wrong. A bot that says 'your D&O policy covers regulatory investigations' when the policy has a regulatory exclusion creates E&O exposure that exceeds the entire contact center budget. Keep AI behind the scenes (agent assist, document search) and keep humans in front of the customer."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Surplus lines compliance for non-admitted placements","Broker licensing verification by state and product line","E&O controls for complex coverage representations","Sanctions and embargo screening for marine and international risks","Privacy and confidentiality controls for breach notification data"], vendors: "NICE Actimize, Verisk, custom compliance", risk: "Surplus lines tax and filing non-compliance across jurisdictions",
        stack: [{ name: "Custom compliance", role: "Specialty Compliance", why: "Surplus lines compliance (state filing, tax, broker licensing) varies by state and is too specialized for generic compliance tools. Many specialty carriers build custom compliance workflows integrated with their policy admin system.", href: "/vendors" }],
        pitfall: "Surplus lines placements require state-specific filings, taxes, and broker licensing verification that admitted carriers don't face. If your contact center processes policy changes or endorsements on surplus lines policies, the agents must understand which changes trigger re-filing requirements. A mid-term limit increase on a surplus lines policy may require a new filing and additional tax, if the agent processes it without the filing, you have a compliance gap."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Broker submission intake workflow with risk information collection","Specialty claims FNOL with coverage-specific data requirements","Breach response coordination workflow connecting insured, counsel, and forensics","Policy endorsement workflow with surplus lines compliance checks","Renewal marketing workflow with loss analysis and market comparison"], vendors: "Guidewire, Duck Creek, custom specialty platforms", risk: "Breach response coordination delays while the ransomware clock is ticking",
        stack: [{ name: "Guidewire / custom", role: "Specialty Claims", why: "Specialty claims (cyber breach, D&O investigation, marine hull loss) require claims platforms configured for low-frequency, high-severity, multi-party events. Many specialty carriers customize Guidewire or build proprietary claims platforms.", href: "/vendors" }],
        pitfall: "In a cyber breach, the early response decides how far the attack spreads. The contact center's job is to connect the insured with breach counsel, forensic investigators and notification vendors as fast as possible. A notification workflow that takes most of a day to activate the response team hands the attacker that time. Pre-configure response teams by policy and test activation quarterly."
      },
      { layer: 1, name: "Data Access", capabilities: ["Policy administration for complex specialty forms and endorsements","Claims management for low-frequency, high-severity specialty claims","Broker management with submission pipeline and production tracking","Underwriting workbench with risk models and pricing tools","Reinsurance data for treaty and facultative placement tracking"], vendors: "Guidewire, Duck Creek, custom platforms, Salesforce", risk: "Policy form complexity exceeding what the agent desktop can display meaningfully",
        stack: [{ name: "Custom specialty platform", role: "Core Systems", why: "Many specialty carriers run custom or heavily customized policy admin platforms because standard systems don't support the complexity of specialty forms, manuscript endorsements, and multi-year policies.", href: "/vendors" }, { name: "Salesforce", role: "Broker CRM", why: "Broker relationship management, submission tracking, and market intelligence. The commercial layer connecting underwriting, marketing, and service.", href: "/vendors/ccaas" }],
        pitfall: "Specialty policy forms are often manuscript (custom-drafted) rather than standard ISO forms. This means the agent can't rely on generic coverage knowledge: they must reference the actual policy document to answer any coverage question. Build a document retrieval system that pulls the specific policy form into the agent desktop during the interaction. Without it, agents will say 'let me review your policy and call you back' for every coverage question."
      },
    ],
  },

  "insurtech": {
    name: "Insurtech & Digital Carriers", parent: "Insurance",
    tagline: "Digital-first insurance with app-native service, instant quoting, and AI-driven claims.",
    intro: "Insurtech contact centers promise what traditional carriers can't: instant quotes, one-tap claims filing, and chat-first support. Many customers chose these carriers for the app. The CX challenge is maintaining that speed and simplicity in the contact center, because when the app can't solve the problem, the expectation for human support is equally high.",
    kpis: [
      { metric: "AHT", avg: "[[ins.sv.insurtech.aht]]", note: "Driven by digital-native users and simpler product sets" },
      { metric: "FCR", avg: "[[ins.sv.insurtech.fcr]]", note: "Fewer product lines and integrated systems reduce handoffs" },
      { metric: "CSAT", avg: "[[ins.sv.insurtech.csat]]", note: "Moves with how well the app and support stay in step" },
      { metric: "Containment", avg: "[[ins.sv.insurtech.containment]]", note: "App-native self-service handles routine requests" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["App experience monitoring with support trigger correlation","Claims AI accuracy tracking with human review audit","CSAT embedded in app with one-tap post-interaction feedback","Support volume correlation to app releases and product launches","Regulatory compliance dashboards meeting state DOI requirements"], vendors: "Amplitude, Mixpanel, NICE", risk: "Scaling support without losing the speed that defines the brand",
        stack: [{ name: "Amplitude", role: "Product Analytics", why: "Connects in-app behavior to support contacts. Shows which app screens or flows generate the most support tickets. Product fixes reduce support volume.", href: "/vendors" }],
        pitfall: "Insurtechs track product metrics (quote conversion, bind rate) and support metrics (CSAT, AHT) separately. The breakthrough insight is connecting them: [[ins.ex.it.quote]], that's a product friction problem disguised as a support problem. Pipe support data into product analytics."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["In-app support routing with full user context and policy data","Claims routing with AI pre-triage for fast-track vs complex","Fraud detection routing flagging suspicious claims before assignment","Escalation routing for regulatory complaints and complex coverage questions","Chat-first routing with phone as overflow, not primary channel"], vendors: "Intercom, Zendesk, NICE CXone", risk: "Claims AI auto-approving a fraudulent claim without human review",
        stack: [{ name: "Intercom", role: "In-App Support", why: "In-app messaging with full user context. Agents see policy, claims history, and recent app activity. Purpose-built for product-led companies.", href: "/vendors/digital-engagement" }, { name: "Zendesk", role: "Support Platform", why: "More structured ticketing for insurtechs as the support team grows. Better for managing the mix of claims, policy service, and billing.", href: "/vendors" }],
        pitfall: "Insurtechs use AI claims triage to auto-approve small claims below a set amount. But fraud detection must still run on auto-approved claims. An auto-approval that skips fraud screening creates an exploitable pattern: serial claimants learn the threshold and file claims just under it. Run fraud scoring on every claim, auto-approved or not."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["In-app messaging as primary support channel","Photo and video claims documentation within the app","Proactive claims status push notifications","Self-service policy changes, endorsements, and cancellation","Chat-based FNOL with guided data collection"], vendors: "Intercom, Zendesk, Ada, Lemonade-style UX", risk: "Chat-only support frustrating customers with complex claims issues",
        stack: [{ name: "Intercom Messenger", role: "In-App Chat", why: "Native in-app messaging. Customer never leaves the app. Full policy and claims context visible to agents. Async messaging lets conversations continue across sessions.", href: "/vendors/digital-engagement" }],
        pitfall: "Insurtechs often launch chat-only and resist adding phone support. But complex claims, water damage with mold remediation, auto accident with injuries, theft with police report, generate customer anxiety that chat can't resolve. The customer needs to hear a human voice say 'we're taking care of this.' Add phone support for claims over a complexity threshold. Chat-only works for quoting and billing; it fails for serious claims."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Instant quote bots with real-time underwriting decisioning","Photo-based claims bots with AI damage assessment","Policy management bots (coverage changes, payment, cancellation)","Claims status bots with timeline and next-step guidance","FAQ bots covering coverage, deductibles, and filing claims"], vendors: "Ada, Lemonade AI Jim, custom AI", risk: "AI damage assessment undervaluing a claim and creating a dispute",
        stack: [{ name: "Custom AI / Ada", role: "Claims & Service AI", why: "Insurtechs build AI into the product, not as an add-on. Lemonade's AI Jim handles claims intake and instant payment. Root's AI assesses driving behavior. The AI IS the product, not a support tool.", href: "/vendors/iva" }],
        pitfall: "AI claims assessment (photo-based damage estimation) is powerful but imperfect. [[ins.ex.it.bumper]] creates a dispute that damages trust. Always present AI estimates as 'preliminary assessment pending adjuster review', not as final settlement offers. The speed advantage of AI is in triage and initiation, not in final determination."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["State DOI compliance in every state where the carrier writes","Rate filing and form compliance for digital products","AI decisioning transparency and fair lending/pricing audit","Consumer data privacy (CCPA, state-specific) for app data","Claims handling compliance meeting traditional carrier standards"], vendors: "Custom compliance, Socotra, EIS", risk: "AI pricing or claims decisions creating fair treatment violations",
        stack: [{ name: "Socotra", role: "Modern Core", why: "API-first insurance core platform purpose-built for insurtechs. Policy admin, billing, and claims with modern APIs. Enables the digital-first experience that insurtechs promise.", href: "/vendors" }],
        pitfall: "Insurtechs face increasing regulatory scrutiny of AI decisioning, particularly pricing algorithms that may discriminate and claims AI that may systematically undervalue certain claim types. State regulators are requiring transparency in AI models. Build explainable AI from day one and maintain audit trails that demonstrate fair treatment across demographics. 'Move fast and break things' doesn't work in a regulated industry."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Instant bind workflow with real-time underwriting and payment","Photo-based claims FNOL with AI damage pre-assessment","Self-service policy modification with instant repricing","Cancellation workflow with instant refund calculation","Referral and rewards workflow for growth-driven insurtechs"], vendors: "Socotra, EIS, Majesco, custom platforms", risk: "Instant bind without adequate underwriting creating adverse selection",
        stack: [{ name: "Socotra", role: "Policy & Claims Engine", why: "Full insurance lifecycle, quote, bind, policy change, billing, and claims, on one API-first platform. Enables the one-tap experiences insurtechs promise.", href: "/vendors" }, { name: "EIS", role: "Digital Insurance Platform", why: "Cloud-native coretech platform for digital carriers. Policy admin, billing, claims, and engagement on a modern architecture.", href: "/vendors" }],
        pitfall: "Insurtechs optimize for instant everything: instant quote, instant bind, instant claim. But insurance requires accuracy alongside speed. An instant bind that doesn't verify the insured's identity, vehicle VIN, or property characteristics creates underwriting risk. An instant claim payment that doesn't verify coverage creates claims leakage. Build verification into the instant workflow, not as a separate step, but as a real-time check that runs in the background while the customer sees 'processing.'"
      },
      { layer: 1, name: "Data Access", capabilities: ["Modern core platform with real-time APIs (Socotra, EIS, Majesco Digital)","Telematics and IoT data for usage-based and behavioral pricing","Third-party data enrichment (property, vehicle, credit, claims history)","Product analytics (Amplitude, Mixpanel) for user behavior context","Payment platform for instant premium collection and claims payment"], vendors: "Socotra, EIS, Verisk, LexisNexis, Stripe", risk: "Third-party data dependency creating single points of failure",
        stack: [{ name: "Socotra / EIS", role: "Core Platform", why: "API-first means the support team accesses the same real-time data the app shows the customer. No batch delays, no stale information. The agent sees what the customer sees.", href: "/vendors" }, { name: "Verisk / LexisNexis", role: "Data Enrichment", why: "Property characteristics, claims history, vehicle data, and risk scores. Pre-fill applications and validate claims against external data. The data layer that enables instant underwriting.", href: "/vendors" }],
        pitfall: "Insurtechs build on modern core platforms (Socotra, EIS) with real-time APIs, which gives them an advantage over traditional carriers running batch-processing legacy systems. But this advantage only matters if the support team has the same real-time data access the customer has. If the customer's app shows a claim status of 'payment issued' but the support agent's system shows 'in review' because of a sync delay, the trust advantage evaporates. Ensure support tools and customer-facing tools read from the same real-time data source."
      },
    ],
  },
};

export const getInsuranceSubVertical = (slug) => (Object.prototype.hasOwnProperty.call(insuranceSubVerticals, slug) ? insuranceSubVerticals[slug] : undefined);
export const getAllInsuranceSubVerticalSlugs = () => Object.keys(insuranceSubVerticals);
