// IVA Market Intelligence — sourced from IVA_Research.xlsx
// 50 vendors | 4 weighted dimensions (25% each) | Scored 1-5 per dimension | Total out of 100

export const ivaVendors = [
  // ═══════════════════════════════════════
  // LEADERS (90–100)
  // ═══════════════════════════════════════
  { name: "Kore.ai", slug: "kore-ai", type: "Standalone IVA", tier: "Leader", score: 100, autonomy: 5, multiChannel: 5, orchestration: 5, analytics: 5, modality: "Voice & Digital", origin: "Proprietary NLP", diff: "Deep orchestration + low-code builder", useCase: "Enterprise service automation", segment: "Enterprise", summary: "The highest-scoring IVA platform in the market. Kore.ai combines deep orchestration, low-code tooling, and strong enterprise deployment across BFSI, healthcare, retail, and public sector. Proven global scale with flexible deployment models." },
  { name: "Cognigy", slug: "cognigy", type: "Standalone IVA", tier: "Leader", score: 100, autonomy: 5, multiChannel: 5, orchestration: 5, analytics: 5, modality: "Voice & Digital", origin: "Proprietary + OpenAI", diff: "Flexible orchestration & on-prem deploy", useCase: "Regulated industries", segment: "Enterprise", summary: "Tied for the top score. Cognigy delivers flexible orchestration with strong on-premises and hybrid deployment options — critical for regulated industries. Deep enterprise capability across BFSI, public sector, and healthcare." },
  { name: "Yellow.ai", slug: "yellow-ai", type: "Standalone IVA", tier: "Leader", score: 94, autonomy: 5, multiChannel: 5, orchestration: 5, analytics: 4, modality: "Voice & Digital", origin: "Hybrid AI", diff: "Global multilingual automation", useCase: "BFSI, eCommerce", segment: "Enterprise", summary: "Strong global multilingual automation platform with proven scale in BFSI and eCommerce. Analytics depth is slightly behind the top two, but orchestration and autonomy are best-in-class." },
  { name: "LivePerson", slug: "liveperson", type: "Conversational AI Suite", tier: "Leader", score: 94, autonomy: 5, multiChannel: 5, orchestration: 5, analytics: 4, modality: "Voice & Digital", origin: "Proprietary + GPT", diff: "Conversational orchestration + agent assist", useCase: "Enterprise CX", segment: "Enterprise", summary: "Conversational AI suite combining IVA orchestration with agent assist capabilities. Strong in enterprise CX transformation with deep messaging channel expertise." },
  { name: "Interactions LLC", slug: "interactions-llc", type: "Standalone IVA", tier: "Leader", score: 94, autonomy: 5, multiChannel: 5, orchestration: 5, analytics: 4, modality: "Voice IVA", origin: "Proprietary + LLM hybrid", diff: "Human-in-the-loop NLP", useCase: "Enterprise inbound automation", segment: "Enterprise", summary: "Voice-native IVA with a unique human-in-the-loop model that improves accuracy in complex interactions. Strong enterprise inbound automation capabilities." },
  { name: "OneReach.ai", slug: "onereach-ai", type: "Standalone IVA", tier: "Leader", score: 94, autonomy: 5, multiChannel: 5, orchestration: 5, analytics: 4, modality: "Voice & Digital", origin: "Multi-AI orchestration", diff: "Highly configurable orchestration studio", useCase: "Complex workflows", segment: "Enterprise", summary: "Highly configurable multi-AI orchestration studio for complex enterprise workflows. The platform's flexibility makes it strong for organizations building differentiated conversational experiences." },
  { name: "Amelia (IPsoft)", slug: "amelia", type: "Standalone IVA", tier: "Leader", score: 93, autonomy: 5, multiChannel: 5, orchestration: 4, analytics: 4, modality: "Voice & Digital", origin: "Proprietary", diff: "Human-like conversation & process automation", useCase: "Banking, insurance", segment: "Enterprise", summary: "Enterprise IVA platform with human-like conversational depth and process automation strength. Strongest in banking, insurance, and complex enterprise service scenarios." },
  { name: "Aisera", slug: "aisera", type: "AI Service Platform", tier: "Leader", score: 91, autonomy: 5, multiChannel: 4, orchestration: 5, analytics: 4, modality: "Voice & Digital", origin: "Multi-model (LLMs + NLU)", diff: "Conversational + workflow automation", useCase: "ITSM, HR service", segment: "Enterprise", summary: "AI service platform combining conversational AI with workflow automation. Particularly strong in ITSM and HR service use cases with growing customer service capabilities." },
  { name: "Avaamo", slug: "avaamo", type: "Standalone IVA", tier: "Leader", score: 89, autonomy: 5, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice & Digital", origin: "Proprietary + LLM", diff: "Enterprise conversational platform", useCase: "Healthcare, insurance", segment: "Enterprise", summary: "Enterprise conversational AI platform with particular strength in healthcare and insurance verticals. Deep domain expertise in regulated industries." },
  { name: "Nuance (Microsoft)", slug: "nuance", type: "CCaaS-Native IVA", tier: "Leader", score: 89, autonomy: 5, multiChannel: 5, orchestration: 4, analytics: 4, modality: "Voice & Digital", origin: "Proprietary + GPT", diff: "Healthcare/voice expertise", useCase: "Healthcare & telco", segment: "Enterprise", summary: "The gold standard in healthcare voice AI, now integrated into the Microsoft ecosystem. Deep telephony expertise and regulated-industry credibility. Post-Microsoft acquisition positions it as a key enterprise voice AI player." },
  { name: "Replicant", slug: "replicant", type: "Standalone IVA", tier: "Leader", score: 89, autonomy: 5, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice IVA", origin: "Proprietary + LLM", diff: "Autonomous voice conversations", useCase: "Call automation", segment: "Enterprise", summary: "Voice-first IVA focused on autonomous call handling. Strong containment rates in production deployments with growing enterprise adoption." },

  // ═══════════════════════════════════════
  // ADVANCERS (80–89)
  // ═══════════════════════════════════════
  { name: "PolyAI", slug: "polyai", type: "Standalone IVA", tier: "Advancer", score: 88, autonomy: 5, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice IVA", origin: "Proprietary + LLM", diff: "Voice-native intent handling", useCase: "Hospitality, retail", segment: "Enterprise", summary: "Voice-native IVA with strong natural language understanding in production environments. Particularly effective in hospitality, retail, and financial services voice containment." },
  { name: "Google Dialogflow CX", slug: "google-dialogflow", type: "Conversational Platform", tier: "Advancer", score: 88, autonomy: 4, multiChannel: 5, orchestration: 4, analytics: 3, modality: "Voice & Digital", origin: "Google Cloud NLP", diff: "Strong NLU, global reach", useCase: "Dev & enterprise IVA", segment: "Enterprise", summary: "Google's enterprise conversational AI platform with strong NLU and global multilingual capabilities. Best fit for developer-led organizations building on Google Cloud." },
  { name: "Rasa", slug: "rasa", type: "Open Source IVA", tier: "Advancer", score: 86, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice & Digital", origin: "Open Source + LLM", diff: "Developer flexibility", useCase: "Developer/Enterprise", segment: "Developer", summary: "Open-source conversational AI framework offering maximum flexibility for developer-led teams. High ceiling for customization, but requires significant engineering investment." },
  { name: "Teneo.ai", slug: "teneo-ai", type: "Standalone IVA", tier: "Advancer", score: 86, autonomy: 5, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice & Digital", origin: "Proprietary", diff: "Linguistic NLU expertise", useCase: "Enterprise CX", segment: "Enterprise", summary: "Enterprise IVA platform built on deep linguistic NLU expertise. Strong conversational autonomy with proven enterprise deployment track record." },
  { name: "Kasisto", slug: "kasisto", type: "Standalone IVA", tier: "Advancer", score: 85, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice & Digital", origin: "Proprietary", diff: "Banking digital assistant", useCase: "BFSI", segment: "Enterprise", summary: "Purpose-built digital banking assistant with deep financial services domain expertise. The strongest vertical-specific IVA in banking." },
  { name: "Haptik", slug: "haptik", type: "Standalone IVA", tier: "Advancer", score: 85, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice & Digital", origin: "Proprietary", diff: "India/APAC leader in AI CX", useCase: "BFSI, eCommerce", segment: "Enterprise", summary: "Leading IVA platform in India and APAC markets with strong BFSI and eCommerce automation. Jio Platforms backing provides scale and regional depth." },
  { name: "Laiye", slug: "laiye", type: "AI Workforce Platform", tier: "Advancer", score: 85, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice & Digital", origin: "Proprietary", diff: "Automation + IVA", useCase: "Enterprise", segment: "Enterprise", summary: "AI workforce platform combining IVA with broader automation capabilities. Strong in enterprise service automation with growing conversational depth." },
  { name: "Microsoft Copilot Studio", slug: "ms-copilot-studio", type: "AI Platform", tier: "Advancer", score: 85, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 3, modality: "Voice & Digital", origin: "Azure AI + GPT", diff: "Enterprise LLM orchestration", useCase: "Enterprise, IT", segment: "Enterprise", summary: "Microsoft's low-code AI builder integrated with Teams, Dynamics, and Azure. Strongest in Microsoft-standardized enterprise environments for internal and customer service." },
  { name: "IBM watsonx Assistant", slug: "ibm-watsonx", type: "Conversational Platform", tier: "Advancer", score: 84, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice & Digital", origin: "IBM watsonx + LLM", diff: "Robust governance + analytics", useCase: "Regulated enterprise", segment: "Enterprise", summary: "Enterprise conversational AI platform with strong governance, compliance, and analytics depth. Best fit for regulated industries where auditability and model controls are essential." },
  { name: "Ultimate.ai", slug: "ultimate-ai", type: "Standalone IVA", tier: "Advancer", score: 84, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice & Digital", origin: "Proprietary", diff: "Customer service automation", useCase: "Support automation", segment: "Enterprise", summary: "Customer service automation platform with strong multilingual capabilities and CRM integration depth. Solid mid-to-enterprise IVA contender." },
  { name: "NICE Enlighten Autopilot", slug: "nice-autopilot", type: "CCaaS-Native IVA", tier: "Advancer", score: 83, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 5, modality: "Voice & Digital", origin: "NICE LLM + NLP", diff: "CX-specific IVA orchestration", useCase: "Enterprise CX", segment: "Enterprise", summary: "NICE's native IVA capability integrated with the CXone platform. Strongest analytics score in the Advancer tier (5/5) — reflecting NICE's Enlighten AI depth. Best for organizations already on CXone." },
  { name: "Five9 IVA Studio", slug: "five9-iva", type: "CCaaS-Native IVA", tier: "Advancer", score: 83, autonomy: 4, multiChannel: 5, orchestration: 4, analytics: 4, modality: "Voice & Chat", origin: "Google + Proprietary", diff: "Integrated with CCaaS routing", useCase: "Contact centers", segment: "Enterprise", summary: "Five9's native IVA integrated with the CCaaS routing engine. Strongest multi-channel score in the Advancer tier (5/5). Best for Five9 customers seeking unified self-service within their existing platform." },

  // ═══════════════════════════════════════
  // DEVELOPERS (70–79)
  // ═══════════════════════════════════════
  { name: "Amazon Lex", slug: "amazon-lex", type: "Conversational Platform", tier: "Developer", score: 82, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 3, modality: "Voice & Digital", origin: "AWS", diff: "Integrated with Connect; developer-friendly", useCase: "CCaaS IVAs", segment: "Enterprise", summary: "AWS's conversational AI platform deeply integrated with Amazon Connect. Strongest for AWS-native organizations building custom IVA experiences on cloud infrastructure." },
  { name: "Kore.ai SmartAssist", slug: "koreai-smartassist", type: "CCaaS-Native IVA", tier: "Developer", score: 82, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice & Chat", origin: "Proprietary", diff: "Hybrid agent + virtual agent", useCase: "Enterprise", segment: "Enterprise", summary: "Kore.ai's agent-assist and IVA hybrid offering. Bridges the gap between automated self-service and agent-assisted interactions." },
  { name: "Botpress", slug: "botpress", type: "Open Source IVA", tier: "Developer", score: 82, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 3, modality: "Digital", origin: "LLM + Modular NLU", diff: "Developer-centric, customizable", useCase: "Tech & startups", segment: "Developer", summary: "Open platform / modular IVA with strong developer community. Good customization path, but enterprise governance and business-admin simplicity need validation by deployment context." },
  { name: "Genesys Dialog Engine", slug: "genesys-dialog", type: "CCaaS-Native IVA", tier: "Developer", score: 81, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice & Chat", origin: "Genesys AI", diff: "Contact center automation", useCase: "Enterprise", segment: "Enterprise", summary: "Genesys's native bot and IVA capability within the Cloud CX platform. Best for organizations already invested in Genesys who want unified self-service without adding a standalone IVA vendor." },
  { name: "Moveworks", slug: "moveworks", type: "AI Platform", tier: "Developer", score: 80, autonomy: 4, multiChannel: 3, orchestration: 4, analytics: 4, modality: "Digital", origin: "LLM + Proprietary", diff: "IT/Employee-focused autonomous resolution", useCase: "Internal service automation", segment: "Enterprise", summary: "AI assistant focused on IT and employee service automation. Strong adjacent value for knowledge-led automation, but should be evaluated as employee-service AI rather than frontline customer IVA." },
  { name: "Cresta AI", slug: "cresta-ai", type: "Agent Assist Hybrid", tier: "Developer", score: 80, autonomy: 4, multiChannel: 3, orchestration: 4, analytics: 4, modality: "Voice & Chat", origin: "LLM + NLU", diff: "Real-time coaching + IVA handoff", useCase: "Sales & service", segment: "Enterprise", summary: "Agent assist platform with growing IVA capabilities. High value in coaching, assist, and optimization loops — partial fit as a direct IVA comparator." },
  { name: "Cognigy Voice Gateway", slug: "cognigy-voice", type: "CCaaS-Native IVA", tier: "Developer", score: 80, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 4, modality: "Voice", origin: "Proprietary", diff: "Voice routing orchestration", useCase: "Enterprise", segment: "Enterprise", summary: "Cognigy's voice orchestration layer for CCaaS environments. Extends Cognigy's IVA capabilities into voice-native routing and telephony integration." },
  { name: "NLX.ai", slug: "nlx-ai", type: "Voice IVA", tier: "Developer", score: 80, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 3, modality: "Voice", origin: "Proprietary", diff: "CCaaS-agnostic, conversational IVR", useCase: "Airlines, logistics", segment: "Mid-Market", summary: "CCaaS-agnostic voice IVA with strength in airlines, logistics, and conversational IVR replacement. Practical mid-market alternative for voice-first automation." },
  { name: "Conversica", slug: "conversica", type: "Standalone IVA", tier: "Developer", score: 78, autonomy: 4, multiChannel: 4, orchestration: 4, analytics: 3, modality: "Digital", origin: "Proprietary + GPT", diff: "Revenue automation + lead follow-up", useCase: "Sales/marketing", segment: "Mid-Market", summary: "Revenue automation platform using conversational AI for lead follow-up and sales engagement. Strong in sales-oriented use cases, less relevant for service-center IVA evaluation." },
  { name: "Active.Ai (Gupshup)", slug: "active-ai", type: "Standalone IVA", tier: "Developer", score: 78, autonomy: 4, multiChannel: 3, orchestration: 4, analytics: 3, modality: "Voice & Chat", origin: "Proprietary", diff: "Banking automation", useCase: "BFSI", segment: "Mid-Market", summary: "Banking automation IVA now part of Gupshup. Strong in BFSI digital banking workflows in APAC markets." },
  { name: "Forethought", slug: "forethought-iva", type: "AI Platform", tier: "Developer", score: 76, autonomy: 4, multiChannel: 3, orchestration: 3, analytics: 4, modality: "Digital", origin: "LLM", diff: "Generative ticket automation", useCase: "Support automation", segment: "Enterprise", summary: "Support automation platform using generative AI for ticket resolution and knowledge retrieval. Useful for digital support automation — should be evaluated as adjacent rather than full enterprise IVA." },

  // ═══════════════════════════════════════
  // EMERGING (≤69)
  // ═══════════════════════════════════════
  { name: "Aivo", slug: "aivo", type: "Standalone IVA", tier: "Emerging", score: 78, autonomy: 4, multiChannel: 4, orchestration: 3, analytics: 3, modality: "Voice & Digital", origin: "Proprietary", diff: "LATAM conversational AI", useCase: "Regional automation", segment: "Mid-Market", summary: "Conversational AI platform with Latin American market strength. Practical regional automation capabilities but limited enterprise-scale proof." },
  { name: "Inbenta", slug: "inbenta", type: "Standalone IVA", tier: "Emerging", score: 74, autonomy: 4, multiChannel: 3, orchestration: 3, analytics: 3, modality: "Digital", origin: "Proprietary NLU", diff: "Knowledge + chat automation", useCase: "Self-service CX", segment: "Mid-Market", summary: "Knowledge-driven chat automation platform with proprietary NLU. Useful for digital self-service but lacks the voice depth and enterprise orchestration of higher-tier vendors." },
  { name: "SoundHound AI", slug: "soundhound", type: "Voice AI", tier: "Emerging", score: 74, autonomy: 4, multiChannel: 3, orchestration: 3, analytics: 3, modality: "Voice", origin: "Proprietary ASR + NLU", diff: "Real-time speech intelligence", useCase: "Voice commerce", segment: "Enterprise", summary: "Voice AI platform with strength in automotive and retail voice commerce. Real-time speech intelligence capabilities but narrower contact center applicability." },
  { name: "e-bot7", slug: "ebot7", type: "Standalone IVA", tier: "Emerging", score: 74, autonomy: 4, multiChannel: 3, orchestration: 3, analytics: 3, modality: "Digital", origin: "Proprietary", diff: "European digital IVA", useCase: "Digital service", segment: "Mid-Market", summary: "European digital IVA platform. Practical for regional digital service automation but limited voice depth and enterprise scale." },
  { name: "Hyperscience", slug: "hyperscience", type: "Intelligent Automation", tier: "Emerging", score: 72, autonomy: 3, multiChannel: 3, orchestration: 4, analytics: 4, modality: "Digital", origin: "LLM + ML", diff: "Document understanding + AI routing", useCase: "Enterprise automation", segment: "Enterprise", summary: "Intelligent automation platform focused on document understanding and AI-driven routing. Adjacent to IVA — stronger in document processing than conversational interaction." },
  { name: "Mindsay (Laiye)", slug: "mindsay", type: "Standalone IVA", tier: "Emerging", score: 66, autonomy: 3, multiChannel: 3, orchestration: 3, analytics: 3, modality: "Digital", origin: "Proprietary", diff: "Workflow automation", useCase: "Travel, retail", segment: "Mid-Market", summary: "Digital IVA acquired by Laiye. Travel and retail focus with workflow automation capabilities. Limited scale and innovation velocity post-acquisition." },
  { name: "Cien (Zoom AI)", slug: "cien-zoom", type: "AI Platform", tier: "Emerging", score: 66, autonomy: 3, multiChannel: 3, orchestration: 3, analytics: 3, modality: "Digital", origin: "GPT-based", diff: "Generative insights + assist", useCase: "Internal AI copilot", segment: "Mid-Market", summary: "AI platform acquired by Zoom. Generative insights and internal copilot capabilities. Early stage as a contact center IVA — watch for integration into broader Zoom Contact Center." },
  { name: "Certainly.io", slug: "certainly", type: "SMB IVA", tier: "Emerging", score: 63, autonomy: 3, multiChannel: 3, orchestration: 3, analytics: 3, modality: "Digital", origin: "Proprietary", diff: "eCommerce chatbot", useCase: "SMB digital service", segment: "SMB", summary: "SMB-focused digital chatbot for eCommerce and customer support. Practical for smaller operations but limited enterprise capability." },
  { name: "Tidio", slug: "tidio", type: "SMB IVA", tier: "Emerging", score: 61, autonomy: 3, multiChannel: 3, orchestration: 3, analytics: 2, modality: "Digital", origin: "Proprietary", diff: "SMB live chat + bot", useCase: "SMB support", segment: "SMB", summary: "SMB live chat and bot platform. Easy deployment for small businesses but minimal enterprise IVA capability. Analytics depth is the weakest dimension." },
];

export const getIVAVendor = (slug) => ivaVendors.find(v => v.slug === slug) || null;
export const getIVAByTier = (tier) => ivaVendors.filter(v => v.tier === tier);
export const getAllIVA = () => ivaVendors;

export const ivaTierConfig = {
  "Leader": { color: "#10B981", range: "90–100", count: 11, desc: "Enterprise-grade orchestration and automation with proven global deployment. These platforms can anchor serious enterprise IVA programs." },
  "Advancer": { color: "#0088DD", range: "80–89", count: 11, desc: "Mature IVA or hybrid AI platforms with broad orchestration capabilities and emerging autonomy. Strong contenders with defined strengths." },
  "Developer": { color: "#F59E0B", range: "70–79", count: 12, desc: "Operational IVAs with strong core logic but more limited scale, analytics maturity, or broader channel coverage." },
  "Emerging": { color: "#EF4444", range: "≤69", count: 9, desc: "Innovators, SMB-focused IVAs, or pre-scale conversational startups. Drive creativity and vertical innovation but lack governance, LLM orchestration, or voice depth." },
};

export const ivaScoringDimensions = [
  { name: "Conversational Autonomy", weight: "25%", desc: "Ability to manage interactions end-to-end — understanding intent, resolving inquiries, escalating appropriately, and learning from feedback." },
  { name: "Multi-Channel Coverage", weight: "25%", desc: "Support across voice, chat, web, messaging, and continuity between channels. Omnichannel maturity affects journey continuity and scale." },
  { name: "Orchestration Depth", weight: "25%", desc: "Ability to trigger business actions, manage workflow steps, and coordinate backend systems. Without action execution, containment claims are inflated." },
  { name: "Analytics & Intelligence", weight: "25%", desc: "Depth of reporting, conversation analytics, intent insights, and closed-loop learning capabilities. Drives continuous improvement." },
];
