export const manufacturingSubVerticals = {
  "automotive-oem": {
    name: "Automotive OEM", parent: "Manufacturing & Automotive",
    tagline: "Recalls, warranty, connected vehicle support, EV ownership, and brand loyalty.",
    intro: "Automotive OEM contact centers manage the post-purchase relationship with millions of vehicle owners. Every recall, warranty claim, and service issue either reinforces or erodes the likelihood that the owner will buy the same brand next time. The CX challenge is managing massive recall surges, complex warranty adjudication, and an entirely new category of connected vehicle and EV support — all while the dealer remains the primary physical touchpoint.",
    kpis: [
      { metric: "AHT", avg: "9:00", note: "Long — VIN lookup, warranty verification, and recall coordination" },
      { metric: "FCR", avg: "55%", note: "Low — warranty decisions, dealer coordination, and parts availability require follow-up" },
      { metric: "CSAT", avg: "75%", note: "Driven by recall communication speed and warranty fairness perception" },
      { metric: "Containment", avg: "22%", note: "VIN recall check automatable; warranty and technical need humans" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["J.D. Power CSI and SSI tracking tied to contact center interactions","Warranty cost-per-vehicle analytics by model, year, and component","Recall completion rate tracking by campaign and geographic region","Connected vehicle complaint trending by software version and feature","Social media sentiment analysis during recall and quality events"],
        vendors: "NICE, Medallia, J.D. Power, Qualtrics", risk: "Quality trend invisible until warranty costs spike",
        stack: [{ name: "Medallia", role: "CX Analytics", why: "Connects CSI survey data to contact center interaction data. Shows which contact center experiences drive or suppress repurchase intent. OEM-specific CX benchmarking.", href: "/vendors/analytics" }, { name: "NICE Nexidia", role: "Interaction Analytics", why: "Analyzes warranty and recall calls at scale. Identifies which warranty denials create the most escalation and which recall communications reduce follow-up calls.", href: "/vendors/analytics" }],
        pitfall: "OEMs track warranty cost as a financial metric but rarely connect it to CX impact. A $200 goodwill repair that costs the OEM $200 but retains a customer worth $150,000 in lifetime purchases is the best investment in the business. Track warranty decisions against repurchase data — the correlation between warranty denial and brand defection is the most important metric most OEMs don't measure."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Recall surge routing activating overflow capacity within hours of NHTSA announcement","VIN-based routing matching callers to agents trained on their vehicle platform","Warranty escalation routing with goodwill authority tiers","Connected vehicle/EV routing to technically trained specialists","Dealer escalation routing when the customer's dealer issue requires OEM intervention"],
        vendors: "Genesys, NICE CXone, Cisco", risk: "Recall announcement generating 100K calls before routing is configured",
        stack: [{ name: "Genesys Cloud", role: "Primary CCaaS", why: "Recall surge routing activated from pre-built playbooks. VIN-based intent detection routes owners of recalled vehicles to recall-specific messaging before they reach an agent. Reduces agent-handled recall calls by 40-60%.", href: "/vendors/genesys" }],
        pitfall: "NHTSA recall announcements are public — the OEM often has less than 24 hours between internal recall decision and public announcement. If your contact center isn't briefed, IVR isn't updated, and agents aren't trained before the press release hits, 100,000 owners will call agents who know less than the news article. Build a recall readiness playbook: notification content, IVR update, agent briefing, FAQ script, and self-service VIN checker — all deployable within 4 hours."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Proactive recall notification by VIN via mail, email, SMS, and app push","Self-service VIN recall checker on website and mobile app","Connected vehicle in-car support and remote diagnostics","Warranty claim status portal with repair history visibility","Social media management for viral quality complaints and recall concerns"],
        vendors: "Sprinklr, LivePerson, Ada, connected vehicle platforms", risk: "Vehicle owner learning about a safety recall from a news article instead of the OEM",
        stack: [{ name: "Sprinklr", role: "Social CX", why: "Automotive quality issues and recalls go viral on social media. A single TikTok about a brake failure can generate more brand damage than the recall itself. Sprinklr unifies social listening, response, and escalation.", href: "/vendors/digital-engagement" }, { name: "Connected vehicle platform", role: "In-Vehicle Support", why: "Tesla, GM (OnStar), Ford (BlueCruise), and BMW all offer in-car support. The vehicle itself becomes a support channel — sending diagnostic data and enabling remote troubleshooting.", href: "/vendors" }],
        pitfall: "Proactive recall notification is not a legal nicety — NHTSA requires OEMs to notify affected owners by first-class mail. But mail-only notification produces 25-30% completion rates. OEMs that add email, SMS, and app push notifications achieve 50-60% completion. Higher completion rates reduce NHTSA scrutiny, lower recall liability, and protect owners. Multi-channel recall notification isn't optional for responsible OEMs."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["VIN recall lookup bots checking NHTSA and OEM databases","Warranty coverage verification bots by VIN, mileage, and date","Service scheduling bots connecting owners to dealer service departments","Connected vehicle troubleshooting bots with diagnostic data","Owner's manual and feature explanation bots for new vehicle technology"],
        vendors: "Ada, Cognigy, Google CCAI, custom", risk: "Bot stating 'your vehicle is not affected by any recalls' when the VIN database hasn't updated",
        stack: [{ name: "Ada", role: "AI Agent", why: "VIN-based recall check, warranty verification, and dealer locator. Routes warranty disputes and technical complaints to human agents. Handles the high-volume, low-complexity calls that surge during recall events.", href: "/vendors/iva" }],
        pitfall: "VIN recall bots must query the NHTSA recall database AND the OEM's internal recall database — they're not always in sync. A bot that checks NHTSA but not the OEM's pending recalls might miss a just-announced campaign. A bot that checks only the OEM might miss a supplier-level recall affecting multiple brands. Query both databases and present the union of results."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["NHTSA recall notification and completion compliance","Magnuson-Moss Warranty Act compliance for warranty claims","State lemon law compliance varying by jurisdiction","TREAD Act defect reporting requirements","CPSC compliance for non-vehicular consumer products"],
        vendors: "NHTSA compliance, Magnuson-Moss, state lemon laws", risk: "Warranty denial violating Magnuson-Moss and triggering FTC or state AG complaint",
        stack: [{ name: "OEM warranty system", role: "Compliance", why: "Warranty adjudication must comply with Magnuson-Moss — denying a warranty claim requires documented justification, and the OEM bears the burden of proof that the failure isn't covered. Contact center agents making denial decisions must be trained on both the warranty terms and the legal requirements.", href: "/vendors" }],
        pitfall: "Magnuson-Moss Warranty Act prohibits tying warranty coverage to the use of OEM-branded parts or dealer-only service. An agent who says 'your warranty is void because you used aftermarket brake pads' is making an illegal warranty denial. Train every warranty agent on Magnuson-Moss basics — the fine for systemic violation is enterprise-threatening, and the FTC actively enforces."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Recall scheduling workflow connecting owner to dealer with parts availability check","Warranty claim adjudication workflow with goodwill escalation tiers","Connected vehicle OTA update notification and failure resolution workflow","Lemon law buyback/replacement workflow with state-specific requirements","NHTSA complaint documentation workflow capturing required safety data"],
        vendors: "SAP, Oracle, Salesforce, DealerSocket, CDK", risk: "Recall scheduling without parts availability check — owner arrives, parts not in stock",
        stack: [{ name: "SAP (Automotive)", role: "Warranty & Recall", why: "Warranty claims management, recall campaign tracking, and parts logistics. The ERP backbone that determines whether the recall part is available at the dealer before scheduling the appointment.", href: "/vendors" }, { name: "CDK / Reynolds & Reynolds", role: "Dealer Management", why: "DMS integration connecting OEM recall and warranty systems to dealer service scheduling. Without DMS integration, the OEM contact center can't schedule a dealer appointment — they can only tell the owner to call the dealer.", href: "/vendors" }],
        pitfall: "The #1 recall CX failure: OEM notifies owner, owner calls to schedule, owner drives to dealer, dealer says 'we don't have the recall part in stock.' Now the owner is angry, the dealer is embarrassed, and the recall completion rate drops. Build parts-availability-aware scheduling — if the part isn't in stock at the owner's preferred dealer, route to a dealer that has it, or schedule after the part is available."
      },
      { layer: 1, name: "Data Access", capabilities: ["Vehicle master data — VIN, build data, warranty status, recall applicability","Warranty claims history by VIN with repair details and parts used","Connected vehicle telemetry — diagnostic trouble codes, mileage, location","Dealer network data — locations, service capacity, parts inventory","NHTSA complaint and recall databases"], vendors: "SAP, Oracle, Salesforce Mfg Cloud, connected vehicle platforms", risk: "Agent seeing warranty status but not repair history — can't assess if the same issue recurred",
        stack: [{ name: "SAP S/4HANA (Automotive)", role: "ERP", why: "Vehicle master data, warranty claims, parts inventory, and dealer management. The data foundation for every OEM contact center interaction. Real-time access to warranty status by VIN.", href: "/vendors" }, { name: "Connected vehicle platform", role: "Telemetry", why: "Real-time vehicle diagnostic data — DTCs, battery state of health (EV), tire pressure, fluid levels. When an owner calls about a warning light, the agent can see the diagnostic data before the owner describes the symptom.", href: "/vendors" }],
        pitfall: "Connected vehicles generate massive telemetry data — but most OEM contact centers can't access it in real-time. The vehicle sends a DTC to the cloud platform; the cloud platform stores it; but the agent desktop doesn't display it. An owner calling about a check engine light is describing what the OEM already knows digitally. Connect vehicle telemetry to the agent desktop so the agent sees the DTC before the owner finishes explaining. This alone reduces AHT by 2-3 minutes per technical call."
      },
    ],
  },

  "automotive-dealer": {
    name: "Automotive Dealer & Retail", parent: "Manufacturing & Automotive",
    tagline: "BDC operations, service scheduling, sales follow-up, F&I, and CSI management.",
    intro: "Automotive dealer contact centers — typically called BDCs (Business Development Centers) — bridge the gap between the showroom and the service drive. The CX challenge is that the dealer IS the brand experience for most vehicle owners, but dealer contact centers are often undertrained, understaffed, and disconnected from both the OEM and the customer's vehicle data.",
    kpis: [
      { metric: "AHT", avg: "4:30", note: "Short — appointment scheduling and sales follow-up are focused" },
      { metric: "FCR", avg: "72%", note: "Above average — most BDC calls are scheduling or status" },
      { metric: "CSAT (CSI)", avg: "82%", note: "Higher — personal relationship with advisor drives satisfaction" },
      { metric: "Appointment Set Rate", avg: "45%", note: "The BDC-specific metric: % of inbound leads converted to appointments" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["CSI/SSI score tracking by advisor, department, and dealership","Sales lead conversion analytics from BDC through closing","Service appointment show rate and revenue per RO","Recall appointment completion tracking for OEM compliance","Internet lead response time and conversion funnel analytics"], vendors: "DealerSocket, VinSolutions, NICE", risk: "CSI scores declining without connecting to specific BDC behaviors",
        stack: [{ name: "DealerSocket / VinSolutions", role: "Dealer CRM", why: "Lead management, follow-up tracking, and CSI monitoring. The CRM that measures whether the BDC is converting leads and maintaining satisfaction.", href: "/vendors" }],
        pitfall: "OEMs tie dealer incentives to CSI scores — but CSI surveys measure the service experience, not the BDC experience. A BDC agent who sets an appointment brilliantly but the service advisor who handles the visit poorly produces a low CSI that the BDC can't control. Track BDC-specific metrics (appointment set rate, show rate, speed to lead) separately from CSI."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Sales vs service routing separating new vehicle leads from service requests","Internet lead routing with speed-to-response SLA","Service recall routing matching VIN to open campaigns","After-hours routing for service emergencies and sales inquiries","VIP and loyalty routing for high-value repeat customers"], vendors: "NICE CXone, Five9, RingCentral", risk: "Internet lead waiting 4 hours for response while competitors respond in 5 minutes",
        stack: [{ name: "Five9", role: "CCaaS", why: "Right-sized for dealer BDC operations (5-20 agents). Blended inbound/outbound for lead follow-up. CRM integration with DealerSocket and VinSolutions.", href: "/vendors/five9" }],
        pitfall: "Speed to lead is the single most important metric in dealer sales BDC. A study by Lead Response Management found that responding to an internet lead within 5 minutes is 100x more effective than waiting 30 minutes. Most dealer BDCs respond in 2-4 hours — by which time the customer has submitted the same lead to 3 other dealers. Automate instant response with a personalized follow-up call within 10 minutes."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Service appointment scheduling via text, chat, and phone","Sales lead follow-up sequences via email, text, and phone","CSI survey follow-up for dissatisfied customers","Recall notification and appointment scheduling outreach","Service reminder notifications for maintenance milestones"], vendors: "Podium, Kenect, DealerSocket, CDK", risk: "Customers unable to schedule service without calling during business hours",
        stack: [{ name: "Podium", role: "Messaging & Reviews", why: "Text-based communication for dealer service and sales. Review generation for Google and OEM surveys. The messaging layer that modern car buyers expect.", href: "/vendors" }],
        pitfall: "Dealer service scheduling by phone only — 'call us during business hours' — loses 30-40% of service appointments. Customers who can't call during the day (because they're working) defer service or go to an independent shop. Online and text-based scheduling is not a convenience — it's a revenue recovery tool."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Service appointment scheduling bots with real-time advisor availability","Recall check bots by VIN with appointment offer","Vehicle trade-in value estimation bots","Parts availability and pricing bots","Service status bots with estimated completion time"], vendors: "Ada, dealer-specific chatbots", risk: "Bot scheduling an appointment for a recall without confirming parts availability",
        stack: [{ name: "Ada / dealer chatbot", role: "AI Agent", why: "24/7 appointment scheduling, VIN recall lookup, and service FAQ. Captures leads after hours when the BDC is closed — the hours when 40% of online leads are submitted.", href: "/vendors/iva" }],
        pitfall: "Dealer chatbots must integrate with the DMS (CDK, Reynolds & Reynolds) for real-time service capacity. A bot that offers 'Tuesday at 9am' when the service drive is already overbooked for Tuesday creates a no-show or a long wait when the customer arrives. Pull real-time advisor availability and bay capacity from the DMS."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["TCPA compliance for sales and service outreach calls and texts","FTC Safeguards Rule compliance for customer financial data (F&I)","OEM program compliance for recall handling and warranty processes","State-specific advertising and pricing disclosure requirements","Do Not Call and opt-out management for outbound campaigns"], vendors: "DMS compliance modules, TCPA compliance", risk: "TCPA violation from automated service reminder texts without proper consent",
        stack: [{ name: "DMS compliance / TCPA tools", role: "Regulatory", why: "TCPA fines for unconsented text messages and calls are $500-$1,500 per violation. A dealer that sends 10,000 service reminder texts without proper consent faces $5M-$15M in potential liability. Capture consent at point of sale and honor opt-outs in real-time.", href: "/vendors" }],
        pitfall: "The FTC Safeguards Rule (effective 2023) requires dealers to implement comprehensive information security programs for customer financial data — including data handled by the BDC. If BDC agents access customer credit applications, income verification, or payment information, the dealer must have encryption, access controls, and security training in place. Many dealer BDCs are not yet compliant."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Sales lead capture and assignment workflow from website, phone, and walk-in","Service appointment workflow with advisor assignment and bay scheduling","Recall appointment workflow with OEM parts verification","CSI recovery workflow for dissatisfied survey respondents","Equity mining workflow identifying service customers ready for new vehicle purchase"], vendors: "CDK, Reynolds & Reynolds, DealerSocket, Tekion", risk: "Hot lead assigned to a salesperson who's off today — no follow-up until tomorrow",
        stack: [{ name: "CDK Drive", role: "DMS", why: "Dominant dealer management system. Service scheduling, parts inventory, and customer records. The operational backbone the BDC integrates with.", href: "/vendors" }, { name: "Tekion", role: "Cloud DMS", why: "Cloud-native dealer management system challenging CDK. Modern APIs, better integration, and mobile-first design. Growing adoption in progressive dealer groups.", href: "/vendors" }],
        pitfall: "Equity mining — identifying service customers whose trade-in value exceeds their loan balance — is the highest-ROI BDC workflow. A customer who brings their car in for a 30,000-mile service and could trade up to a new model with lower payments should hear from the sales BDC before they leave the service drive. Most dealers run equity mining as a monthly batch report; real-time equity alerts during service visits capture 3-5x more opportunities."
      },
      { layer: 1, name: "Data Access", capabilities: ["DMS — customer records, vehicle history, service appointments, parts inventory","CRM — lead management, follow-up activity, and sales pipeline","OEM portal — recall data, warranty claims, incentive programs","Inventory management — new and used vehicle availability","F&I system — credit applications, payment structures, and aftermarket products"], vendors: "CDK, Reynolds & Reynolds, Tekion, DealerSocket, VinSolutions", risk: "CRM and DMS containing duplicate customer records with conflicting data",
        stack: [{ name: "CDK / Reynolds & Reynolds", role: "DMS Data", why: "Vehicle service history, parts inventory, customer contact information, and financial records. Every BDC interaction requires DMS data.", href: "/vendors" }, { name: "VinSolutions / DealerSocket", role: "CRM Data", why: "Lead status, follow-up history, communication preferences, and sales pipeline. The CRM and DMS must share data — CRM for relationship context, DMS for transactional data.", href: "/vendors" }],
        pitfall: "The dealer data problem: the DMS and the CRM often contain different customer records for the same person. The DMS has the service customer (entered at the service drive); the CRM has the sales lead (entered from the website). Without identity resolution, the BDC doesn't know that the service customer who's in for a 60,000-mile service is the same person who submitted a trade-in inquiry online last week. Deduplicate across DMS and CRM."
      },
    ],
  },

  "industrial-b2b": {
    name: "Industrial & B2B Manufacturing", parent: "Manufacturing & Automotive",
    tagline: "Parts ordering, warranty claims, technical support, field service, and distributor support.",
    intro: "Industrial manufacturing contact centers serve businesses whose production depends on the manufacturer's products. When a CNC machine goes down, a hydraulic pump fails, or a critical assembly part is backordered, the customer's production line stops — costing $10,000-$100,000 per hour. The CX challenge is providing technical expertise and parts logistics with the urgency that production downtime demands.",
    kpis: [
      { metric: "AHT", avg: "12:00", note: "Longest — technical diagnosis, parts identification, and field service coordination" },
      { metric: "FCR", avg: "48%", note: "Very low — parts availability, field service scheduling, and engineering review" },
      { metric: "CSAT", avg: "72%", note: "Below average — downtime frustration overrides service quality" },
      { metric: "Containment", avg: "12%", note: "Very low — technical questions require engineering-level knowledge" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Account profitability analytics connecting service cost to revenue","Mean time to resolve (MTTR) by product line, issue type, and technician","Parts availability and backorder impact on resolution time","Warranty claim trending by product, component, and manufacturing batch","Customer health scoring combining service frequency, NPS, and revenue trend"], vendors: "NICE, Verint, Salesforce Analytics", risk: "Key accounts churning because service degradation wasn't detected early",
        stack: [{ name: "NICE CXone", role: "Analytics", why: "Technical QA scoring evaluating whether agents correctly diagnosed the issue, identified the right part, and escalated when needed. B2B-grade analytics connecting interactions to account health.", href: "/vendors/nice-cxone" }],
        pitfall: "B2B manufacturers track MTTR (mean time to resolve) at the ticket level but not at the account level. An account that opens 15 tickets per quarter with an average 4-day MTTR has a different experience than an account that opens 2 tickets per quarter with a 4-day MTTR. The first account has a chronic product quality issue masquerading as good support performance. Track resolution at the account level to see the real picture."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Production-down emergency routing with immediate escalation to engineering","Named account routing for strategic accounts with dedicated support teams","Product-line routing matching callers to agents trained on specific equipment","Distributor vs end-user routing with different service models","Field service dispatch routing coordinating technician scheduling and parts"], vendors: "Genesys, NICE CXone, ServiceNow", risk: "Production-down emergency waiting in a general support queue",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Priority routing based on account value and issue severity. Production-down calls bypass all queues and reach a senior engineer immediately. Account-based routing ensures strategic accounts always reach their dedicated team.", href: "/vendors/genesys" }],
        pitfall: "Industrial support must have a 'production down' emergency path that's separate from routine support — and accessible 24/7. A customer whose $2M production line is stopped at 2am needs a live engineer, not a voicemail. Staff overnight emergency coverage with senior technical resources, not junior agents. The cost of one overnight engineer is less than the cost of losing one production-down account."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Customer portal with equipment registry, service history, and parts ordering","Proactive maintenance notifications based on equipment runtime and IoT data","Technical documentation library with model-specific manuals and bulletins","Field service scheduling with technician assignment and ETA tracking","Video-assisted remote diagnosis for complex equipment issues"], vendors: "Salesforce, ServiceMax, Glia, Zoom", risk: "Customer unable to find documentation for their specific equipment model/serial",
        stack: [{ name: "Glia", role: "Visual Support", why: "Video-assisted support for complex equipment — the customer shows the technician the equipment via smartphone camera, and the technician guides the diagnosis remotely. Reduces truck rolls by 25-40% for issues that can be resolved with guided customer action.", href: "/vendors/digital-engagement" }],
        pitfall: "Industrial customers call support when equipment fails — but most failures have warning signs visible in operational data (vibration increase, temperature rise, pressure fluctuation). Proactive maintenance notifications based on IoT sensor data prevent failures before they create downtime and support calls. The best support interaction is the one that never happens because the failure was prevented."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Parts identification bots using model, serial, and component description","Warranty coverage verification by serial number and purchase date","Equipment documentation search bots returning model-specific manuals","Service request status bots with field service ETA","Basic troubleshooting bots with step-by-step diagnostic guides"], vendors: "Ada, Cognigy, custom bots", risk: "Bot identifying the wrong part number for a similar but different model",
        stack: [{ name: "Ada", role: "AI Agent", why: "Parts lookup by serial number, warranty verification, and service status. Routes production-down emergencies and complex technical questions to human engineers immediately.", href: "/vendors/iva" }],
        pitfall: "Parts identification bots are powerful but dangerous in industrial manufacturing. A pump impeller that looks identical across 5 model variants but has different dimensions, materials, or pressure ratings will fail catastrophically if the wrong part is installed. Bots must verify model number, serial number, AND revision level before confirming a part number. Add a human confirmation step for safety-critical components."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Product liability compliance for safety-critical equipment","UCC warranty compliance for commercial sales","Export control (ITAR/EAR) for defense and dual-use products","Environmental compliance for hazardous materials in products","ISO 9001 quality management system integration with support"], vendors: "Custom compliance, ERP-embedded", risk: "ITAR-controlled technical data shared with unauthorized foreign national",
        stack: [{ name: "ERP compliance modules", role: "Export Control", why: "SAP and Oracle embed export control screening in parts orders and technical data requests. A support agent shipping a controlled part or sending controlled documentation to a prohibited country creates a federal violation. Automate screening — don't rely on agents to know ITAR.", href: "/vendors" }],
        pitfall: "ITAR (International Traffic in Arms Regulations) controls the export of defense-related products and technical data. If your products include any defense applications, your support agents cannot share technical specifications, troubleshooting procedures, or parts data with foreign nationals without export authorization. This applies to phone calls, emails, and portal access. One violation can result in criminal prosecution and debarment from government contracts."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Parts order fulfillment workflow with inventory check and shipping","Warranty claim adjudication workflow with engineering review for complex claims","Field service dispatch workflow with technician assignment, parts kit, and ETA","RMA (Return Material Authorization) processing workflow","Product quality escalation workflow connecting support to engineering and manufacturing"], vendors: "SAP, Oracle, Salesforce, ServiceMax, IFS", risk: "Field service dispatched without the right parts — technician arrives and can't repair",
        stack: [{ name: "ServiceMax", role: "Field Service", why: "Purpose-built for industrial field service. Technician scheduling, parts kit preparation, work order management, and customer portal. Connects the contact center to field operations.", href: "/vendors" }, { name: "SAP S/4HANA", role: "ERP", why: "Parts inventory, warranty claims, and order management. The operational backbone for industrial support. Real-time parts availability determines whether the agent can promise same-day or next-day delivery.", href: "/vendors" }],
        pitfall: "Field service dispatch without parts verification is the most expensive CX failure in industrial manufacturing. A technician drives 3 hours to the customer site, opens the equipment, discovers the replacement part isn't in the truck, and tells the customer 'I'll need to come back when the part arrives.' The customer's production line stays down for an additional 2-5 days. Build parts-kit verification into every dispatch workflow — confirm the required parts are available and loaded before the technician departs."
      },
      { layer: 1, name: "Data Access", capabilities: ["ERP — parts inventory, BOMs, pricing, and order status","CRM — account management, service history, and installed base","Equipment registry — serial numbers, configurations, and warranty status","Field service system — technician schedules, work orders, and parts kits","IoT platform — equipment telemetry, runtime data, and predictive alerts"], vendors: "SAP, Oracle, Salesforce Manufacturing Cloud, PTC ThingWorx", risk: "Agent seeing the product catalog but not the customer's specific installed configuration",
        stack: [{ name: "SAP S/4HANA", role: "ERP Data", why: "Parts availability, BOMs, warranty status, and order processing. Every industrial support interaction requires ERP data — is the part in stock? Is the warranty active? Has this claim been filed before?", href: "/vendors" }, { name: "Salesforce Manufacturing Cloud", role: "CRM", why: "Account management with installed base tracking. Shows what the customer has, what they've bought, what they've claimed warranty on, and what they're likely to need next.", href: "/vendors/ccaas" }, { name: "PTC ThingWorx", role: "IoT Platform", why: "Connected equipment telemetry. When the customer calls about equipment failure, the agent can see the equipment's operational data — runtime hours, error codes, and performance degradation — before the customer describes the problem.", href: "/vendors" }],
        pitfall: "Industrial support agents need installed base data — not just product catalog data. The customer isn't calling about a generic 'Model X pump.' They're calling about the specific pump with serial #12345, installed in March 2022, running configuration B, with firmware v2.3, in a corrosive environment. Without installed base data, the agent starts every call from zero. Build a serial-number-linked customer equipment registry accessible from the agent desktop."
      },
    ],
  },

  "consumer-electronics": {
    name: "Consumer Electronics & Appliances", parent: "Manufacturing & Automotive",
    tagline: "Product setup, troubleshooting, warranty, returns, and smart home integration.",
    intro: "Consumer electronics contact centers handle the post-unboxing experience — setup, troubleshooting, warranty claims, and returns. The CX challenge is that products are increasingly complex (smart home ecosystems, firmware updates, multi-device interoperability) while customer tolerance for complexity is decreasing. Customers expect Apple-level simplicity from every brand.",
    kpis: [
      { metric: "AHT", avg: "7:00", note: "Moderate — simple setup is quick; interoperability troubleshooting is long" },
      { metric: "FCR", avg: "65%", note: "Below average — firmware issues, compatibility problems, and warranty coordination" },
      { metric: "CSAT", avg: "74%", note: "Driven by product quality first, support quality second" },
      { metric: "Containment", avg: "30%", note: "Setup guides and FAQ automatable; compatibility and warranty need humans" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Product defect trending by SKU, batch, and firmware version","Support cost per product informing design-for-supportability","NPS correlation between support experience and repurchase","Return reason analytics separating defect from user error from buyer's remorse","Knowledge base effectiveness — which articles reduce contact, which don't"], vendors: "NICE, Medallia, Qualtrics", risk: "Product defect invisible until support costs spike 3 months post-launch",
        stack: [{ name: "NICE CXone", role: "Analytics", why: "Product-specific contact reason trending. When a new SKU launches and generates 3x expected support volume, NICE identifies whether the issue is defect (engineering fix), documentation (content fix), or user error (training fix).", href: "/vendors/nice-cxone" }],
        pitfall: "Consumer electronics manufacturers track support cost as an overhead line item, not as a product quality signal. If Product A generates $15 in support cost per unit and Product B generates $3, that's a product design gap worth $12/unit at scale — potentially millions per year. Feed support data into product development to build design-for-supportability into the next generation."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Product-line routing matching callers to agents trained on specific categories","Warranty vs out-of-warranty routing with different service paths","Smart home ecosystem routing for multi-device interoperability issues","Premium support routing for high-end product lines","Returns and exchange routing with policy enforcement"], vendors: "Genesys, NICE CXone, Five9", risk: "Smart home issue requiring expertise across 3 product categories reaching a single-product agent",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Product-line routing with SKU-level agent specialization. Handles the breadth of consumer electronics — from headphones to smart TVs to home security — with appropriate routing to trained specialists.", href: "/vendors/nice-cxone" }],
        pitfall: "Smart home interoperability issues are the fastest-growing and hardest-to-route call type in consumer electronics. 'My smart speaker won't control my smart lights when I'm using my streaming service' involves three product categories, potentially three manufacturers, and three ecosystems. Most routing puts this in a general queue where no single agent knows all three. Build a multi-product escalation team trained across the ecosystem."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Interactive setup guides with video and step-by-step instructions","Firmware update notification and troubleshooting","Product registration with warranty activation","Self-service return and exchange portal","Community forums with peer-to-peer troubleshooting and moderation"], vendors: "Zendesk, Intercom, Ada, community platforms", risk: "Community forum containing incorrect advice that users follow",
        stack: [{ name: "Zendesk", role: "Support Platform", why: "Multi-channel support with strong knowledge base and community forum integration. Good for consumer electronics brands managing high-volume product support across many SKUs.", href: "/vendors" }],
        pitfall: "Firmware updates that break features are the most damaging CX event in consumer electronics — the product worked yesterday, the user didn't change anything, and now it's broken. Proactive notification ('a firmware update is available — here's what it fixes and what may change') gives users control. Silent auto-updates that break functionality generate massive support volume and social media backlash. Let users choose when to update."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Guided troubleshooting bots with product-specific diagnostic trees","Setup and configuration bots with step-by-step instructions","Warranty status verification by serial number or purchase date","Return eligibility bots with policy and restocking fee information","Compatibility checker bots for ecosystem and accessory questions"], vendors: "Ada, Cognigy, custom bots", risk: "Bot troubleshooting a firmware issue with hardware diagnostics — wrong tree entirely",
        stack: [{ name: "Ada", role: "AI Agent", why: "Product-specific troubleshooting, setup guidance, and warranty verification. Handles the high volume of simple questions (setup, compatibility, warranty status) that don't need human agents.", href: "/vendors/iva" }],
        pitfall: "Troubleshooting bots for consumer electronics must distinguish between hardware failure (replace the product), firmware issue (update or roll back), user error (education), and ecosystem incompatibility (can't be fixed — explain limitation). A bot that runs hardware diagnostics when the issue is a firmware bug wastes 10 minutes and frustrates the customer. Start with 'has anything changed recently?' to classify the issue category before diving into diagnostic steps."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Consumer Product Safety Commission (CPSC) compliance for safety defects","FCC compliance for wireless and electronic emissions","State warranty and return policy compliance","EU CE marking and WEEE compliance for international products","Privacy compliance for smart home data collection and usage"], vendors: "CPSC compliance, FCC, custom", risk: "Smart home device collecting data without proper disclosure creating privacy violation",
        stack: [{ name: "Compliance systems", role: "Product Safety", why: "CPSC requires manufacturers to report product safety defects. Contact center agents who receive reports of fires, electric shocks, or injuries must be trained to document these reports and escalate to the safety team immediately.", href: "/vendors" }],
        pitfall: "Smart home devices collect voice recordings, usage patterns, and environmental data. Privacy regulations (CCPA, GDPR, state laws) require disclosure of what's collected and how it's used. When a customer calls and asks 'is my smart speaker recording me?' the agent must provide an accurate, compliant answer — not a reassuring platitude. Train agents on your product's actual data collection practices and provide a clear, honest response."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Product return and exchange workflow with condition assessment","Warranty claim workflow with repair vs replace decision logic","Advanced replacement workflow (send new product before receiving defective)","Product recall notification and replacement workflow","Refurbished/renewed product processing and resale workflow"], vendors: "Salesforce, SAP, Oracle, Zendesk", risk: "Advanced replacement sent without receiving the defective unit back — inventory loss",
        stack: [{ name: "Salesforce Service Cloud", role: "Case Management", why: "Warranty claims, returns, and exchange management. Tracks product serial numbers through the return/replace/refurbish lifecycle.", href: "/vendors/ccaas" }],
        pitfall: "Advanced replacement (sending a new unit before receiving the defective one) is the highest-satisfaction resolution method — the customer gets working equipment immediately. But without a deposit hold or return tracking, 10-15% of customers keep both units. Implement a credit card hold for the replacement value and automatic follow-up if the defective unit isn't returned within 14 days."
      },
      { layer: 1, name: "Data Access", capabilities: ["Product catalog with specifications, compatibility, and firmware versions","Warranty database with serial number registration and coverage status","Inventory management for replacement and exchange stock","Customer profile with purchase history and product registration","Knowledge base with troubleshooting articles and setup guides"], vendors: "SAP, Oracle, Salesforce, Zendesk", risk: "Agent unable to look up warranty status because the customer didn't register the product",
        stack: [{ name: "SAP / Oracle", role: "ERP", why: "Product master data, inventory, and warranty information. The source of truth for 'is this product under warranty?' and 'do we have replacement stock?'", href: "/vendors" }, { name: "Zendesk Guide", role: "Knowledge Base", why: "Product-specific troubleshooting articles and setup guides. Self-service deflection when articles are good; contact driver when articles are missing or wrong.", href: "/vendors" }],
        pitfall: "Product registration rates for consumer electronics are typically 20-30% — meaning 70-80% of customers who call for warranty support can't be verified through the registration database. Build alternative warranty verification: retailer purchase data (Best Buy, Amazon), credit card lookup, or date-code-based warranty (manufacture date + warranty period). Requiring registration to access warranty support alienates the majority of customers."
      },
    ],
  },

  "aerospace-defense": {
    name: "Aerospace & Defense", parent: "Manufacturing & Automotive",
    tagline: "MRO support, parts logistics, AOG emergencies, regulatory compliance, and fleet services.",
    intro: "Aerospace contact centers support aircraft operators whose equipment availability directly affects revenue (airlines) or mission readiness (defense). An Aircraft on Ground (AOG) event costs an airline $50,000-$150,000 per hour in lost revenue. The CX challenge is 24/7 parts availability, regulatory compliance (FAA/EASA), and engineering expertise at a level no other manufacturing sector requires.",
    kpis: [
      { metric: "AHT", avg: "15:00", note: "Longest in manufacturing — parts identification, certification tracing, and AOG coordination" },
      { metric: "FCR", avg: "40%", note: "Lowest — parts sourcing, engineering review, and regulatory verification" },
      { metric: "CSAT", avg: "70%", note: "Driven by parts availability and AOG response time, not interaction quality" },
      { metric: "AOG Response", avg: "2 hrs", note: "Time to locate and ship a critical AOG part — the #1 metric" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["AOG response time tracking — time from request to parts shipment","Parts fill rate analytics by part number and stock location","Warranty and product support cost by aircraft type and operator","Fleet reliability analytics feeding back to design engineering","ITAR/EAR compliance audit trail for technical data distribution"], vendors: "NICE, custom analytics, SAP", risk: "AOG response degradation invisible until operators start sourcing from competitors",
        stack: [{ name: "Custom BI", role: "Aerospace Analytics", why: "Aerospace analytics are unique — AOG response time, parts fill rate, rotable pool utilization, and warranty claim trending by aircraft type. No standard CX analytics tool covers these metrics.", href: "/vendors" }],
        pitfall: "In aerospace, the support experience IS the competitive differentiation. Every airframe and engine manufacturer offers the same product to the same airlines. The manufacturer that answers AOG calls fastest, ships parts overnight, and provides engineering support on weekends wins the fleet support contract. Track AOG response metrics as the primary competitive indicator."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["AOG priority routing — immediate 24/7 escalation to senior support","Product-line routing by airframe, engine, and system","Operator-tier routing based on fleet size and contract level","Engineering escalation routing for technical inquiries beyond parts","ITAR-controlled routing restricting access based on caller nationality"], vendors: "Genesys, Cisco, NICE CXone", risk: "AOG call at 3am reaching voicemail instead of 24/7 support desk",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "24/7 AOG routing with immediate escalation. Operator identification and contract-level routing. Handles the zero-tolerance-for-downtime urgency that aerospace support requires.", href: "/vendors/genesys" }],
        pitfall: "AOG support must be 24/7/365 with zero voicemail. An airline with a grounded 737 at 2am in Dubai doesn't leave a message — they call the competitor. Staff overnight and weekend AOG desks with senior parts specialists who have authority to approve emergency shipments, charter flights for parts delivery, and authorize field repairs. This is not a cost center — it's revenue protection."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["AOG parts request portal with real-time inventory and shipping options","Technical publications access with ATA chapter-organized documentation","Engineering inquiry submission with SLA-tracked response","Fleet management portal with aircraft-specific service history","Proactive service bulletin and airworthiness directive notifications"], vendors: "SAP, IFS, Salesforce, custom portals", risk: "Service bulletins not reaching affected operators in time for compliance",
        stack: [{ name: "IFS", role: "Aerospace & Defense Platform", why: "Purpose-built for aerospace MRO. Parts logistics, work package management, and fleet tracking. The platform that connects support to operations for aerospace manufacturers.", href: "/vendors" }],
        pitfall: "Airworthiness directives (ADs) from FAA/EASA are mandatory compliance actions. OEM service bulletins (SBs) may be recommended but not mandatory — unless referenced by an AD. Your support team must clearly distinguish between mandatory ADs and recommended SBs in every communication. Mixing them up creates operator confusion — either unnecessary grounding (treating an SB as mandatory) or compliance violation (treating an AD as optional)."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Parts cross-reference bots identifying part numbers by description or application","Service bulletin applicability bots by aircraft model and serial number","Warranty eligibility bots with flight-hour and calendar-based verification","Documentation search bots within structured technical publications","Basic troubleshooting bots for common line maintenance issues"], vendors: "Custom, limited commercial", risk: "Bot recommending a part that doesn't have current airworthiness certification",
        stack: [{ name: "Custom / limited AI", role: "Aerospace AI", why: "Aerospace AI must be conservative — an incorrect part identification, wrong torque value, or outdated certification could affect flight safety. AI for parts cross-reference and documentation search; human for all engineering decisions and airworthiness determinations.", href: "/vendors" }],
        pitfall: "Every aerospace part has a traceability chain — manufacturer, batch, certification, and airworthiness status. A parts lookup bot that returns a part number without verifying current airworthiness certification could lead to installation of a part that's been subject to an AD or inspection requirement. AI in aerospace must always return parts data with certification status attached — never a bare part number."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FAA/EASA airworthiness compliance for parts and technical data","ITAR/EAR export control for defense and dual-use aerospace products","AS9100 quality management system compliance","FAA Part 21/145 repair station compliance for MRO operations","Traceability and documentation requirements for every part and repair"], vendors: "FAA/EASA compliance, ITAR, AS9100", risk: "ITAR-controlled data shared with unauthorized party creating federal violation",
        stack: [{ name: "ERP export control", role: "ITAR/EAR Compliance", why: "Automated export screening for every parts order and technical data request. In aerospace, ITAR violations are criminal offenses with prison time. Automate screening — do not rely on agents to know which parts and data are controlled.", href: "/vendors" }],
        pitfall: "ITAR in aerospace is absolute. A support agent who emails a wiring diagram for a military aircraft system to a foreign operator — even an allied NATO country — without an export license has committed a federal crime. Screen every technical data request against ITAR/EAR control lists. Implement system-level controls that prevent export of controlled data, not just training that asks agents to remember the rules."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["AOG parts fulfillment workflow — locate, certify, ship, track","Warranty claim workflow with flight-hour and usage verification","Service bulletin compliance tracking and parts kit distribution","Engineering change order notification and retrofit coordination","Rotable pool management — exchange, repair, and certification workflow"], vendors: "SAP, IFS, Oracle, AMOS", risk: "AOG part shipped without current airworthiness certification documentation",
        stack: [{ name: "SAP (Aerospace & Defense)", role: "ERP", why: "Parts logistics, warranty management, and order fulfillment for aerospace. Handles the unique requirements of serialized, traceable, certified parts that no generic ERP supports.", href: "/vendors" }, { name: "IFS", role: "MRO & Fleet", why: "Maintenance, repair, and overhaul management. Work packages, task cards, and fleet tracking. Connects support to the maintenance planning that operators depend on.", href: "/vendors" }],
        pitfall: "Aerospace parts logistics are uniquely complex: every part is serialized, every transaction requires traceability documentation, and every part must have current airworthiness certification. An AOG parts shipment that arrives without the correct 8130-3 (airworthiness approval tag) can't be installed — the operator is still grounded even though the part is physically present. Ensure certification documentation ships with the part, not in a separate follow-up email."
      },
      { layer: 1, name: "Data Access", capabilities: ["Parts catalog with configuration, interchangeability, and certification","Warranty database with flight-hour and calendar tracking by serial number","Fleet data — operator aircraft, configuration, and service history","Technical publications — AMM, CMM, IPC organized by ATA chapter","Regulatory database — ADs, SBs, and compliance status by aircraft"], vendors: "SAP, IFS, AMOS, Flatirons", risk: "Parts catalog showing superseded part numbers without the current replacement",
        stack: [{ name: "SAP", role: "Parts & Logistics Data", why: "Serialized parts inventory, certification status, and logistics tracking. The data foundation for every AOG response — is the part in stock, is it certified, and how fast can we ship it?", href: "/vendors" }, { name: "Flatirons Solutions", role: "Technical Publications", why: "S1000D and ATA iSpec 2200 technical publications management. When a customer asks 'what's the torque spec for this bolt on a 787 wing root?' the answer is in the structured technical data.", href: "/vendors" }],
        pitfall: "Aerospace parts catalogs contain superseded, obsoleted, and interchangeable part numbers — a single component might have 5 part numbers across different revisions. An agent quoting a superseded part number creates an order that can't be fulfilled with current production parts. Build part number resolution logic that always returns the current, in-production part number with full interchangeability documentation."
      },
    ],
  },

  "food-beverage": {
    name: "Food & Beverage Manufacturing", parent: "Manufacturing & Automotive",
    tagline: "Product quality complaints, allergen inquiries, recalls, retailer support, and consumer hotline.",
    intro: "Food and beverage manufacturer contact centers handle consumer complaints, retailer inquiries, and — most critically — food safety events including allergen contamination, foreign objects, and pathogen contamination. The CX challenge is treating every quality complaint as a potential food safety signal while managing routine consumer feedback and retailer logistics.",
    kpis: [
      { metric: "AHT", avg: "5:00", note: "Shorter — consumer complaints are focused; quality events are detailed" },
      { metric: "FCR", avg: "75%", note: "Above average — most complaints resolved with coupon, replacement, or explanation" },
      { metric: "CSAT", avg: "78%", note: "Above average when complaints are handled with empathy and speed" },
      { metric: "Safety Escalation", avg: "2%", note: "Percentage of complaints that trigger food safety investigation" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Product complaint trending by SKU, production facility, and lot code","Food safety signal detection — clustering of similar complaints","Consumer sentiment by product, flavor, and packaging change","Retailer complaint analytics by retail partner and region","Recall effectiveness — notification reach and product recovery rate"], vendors: "NICE, Medallia, custom QA systems", risk: "Food safety signal buried in routine complaint volume",
        stack: [{ name: "NICE CXone", role: "QA & Trending", why: "Complaint trending that detects when multiple consumers report the same issue (off taste, illness, foreign object) from the same lot code. This is the early warning system for food safety events.", href: "/vendors/nice-cxone" }],
        pitfall: "Food safety events start as individual consumer complaints. Three people calling separately about 'funny-tasting yogurt' from different stores in different states might be three unrelated quality variations — or they might be the first signal of a pathogen contamination affecting an entire production run. Build automated complaint clustering by lot code and symptom. If 3+ consumers report similar symptoms from the same lot code within 48 hours, trigger a food safety investigation automatically."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Food safety priority routing for illness reports and foreign objects","Consumer complaint vs retailer inquiry routing","Product quality routing by category and production facility","Media inquiry routing during recall events","Allergen inquiry routing to trained food safety specialists"], vendors: "Genesys, NICE CXone, Five9", risk: "Consumer reporting illness reaching a general complaint agent instead of food safety",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Keyword detection for food safety language — 'sick,' 'hospital,' 'allergic reaction,' 'glass,' 'metal' — routes immediately to food safety team. Ensures safety-critical complaints never wait in a general queue.", href: "/vendors/nice-cxone" }],
        pitfall: "Every consumer complaint must be screened for food safety signals during intake — not after classification. An agent who classifies 'I found something hard in my cereal' as 'product quality - texture' instead of 'food safety - foreign object' has delayed a potential safety investigation. Train all intake agents to ask: 'Did you or anyone become ill?' and 'Can you describe what you found?' before classifying."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Consumer complaint portal with product and lot code capture","Recall notification via website, social media, and retailer communication","Coupon and replacement product fulfillment for resolved complaints","Allergen information portal with ingredient and production facility data","Social media management for viral product quality complaints"], vendors: "Sprinklr, Zendesk, custom consumer portals", risk: "Recall notification not reaching consumers who don't follow the brand on social media",
        stack: [{ name: "Sprinklr", role: "Social + Consumer", why: "Food quality complaints often go viral on social media before the consumer calls the hotline. A TikTok showing a foreign object in a product generates millions of views in hours. Sprinklr detects, escalates, and manages the response.", href: "/vendors/digital-engagement" }],
        pitfall: "Food recall notifications depend heavily on retailers removing products from shelves and posting in-store notices — but the manufacturer can't control retail execution. Supplement retailer-dependent recall communication with direct consumer notification (email, SMS, social media), FDA recall alert, and media outreach. The more channels, the higher the recovery rate and the lower the liability exposure."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Product information bots (ingredients, allergens, nutrition, sourcing)","Complaint intake bots with lot code and purchase location capture","Coupon and replacement fulfillment bots","Store locator and product finder bots","FAQ bots covering dietary questions, certifications, and sourcing"], vendors: "Ada, Zendesk bots, custom", risk: "Bot providing incorrect allergen information creating health risk",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles product information, complaint intake with lot code capture, and coupon fulfillment. Routes all illness reports and allergen concerns to human food safety specialists immediately.", href: "/vendors/iva" }],
        pitfall: "Allergen information bots must be updated in real-time when formulations change. A bot that says 'this product does not contain tree nuts' when the formulation was recently changed to include almond flavoring could contribute to an allergic reaction. Build a direct data feed from product formulation systems to the bot's allergen database with change alerts and human review before the bot starts serving new allergen data."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FDA/FSIS compliance for food safety complaint documentation","FSMA (Food Safety Modernization Act) preventive controls compliance","Allergen labeling compliance (FALCPA and state requirements)","CPSC reporting for foreign object and contamination complaints","Class I/II/III recall classification and execution compliance"], vendors: "FDA compliance, FSMA, FALCPA", risk: "FDA reportable complaint not escalated to regulatory affairs within required timeline",
        stack: [{ name: "FDA/FSIS compliance systems", role: "Regulatory", why: "Certain consumer complaints (serious illness, hospitalization, death) must be reported to FDA within specific timeframes. Contact center agents must recognize reportable events and escalate immediately to regulatory affairs.", href: "/vendors" }],
        pitfall: "FDA requires food manufacturers to report serious adverse events (hospitalization, life-threatening reactions, death) within 15 business days. The clock starts when the contact center receives the report — not when regulatory affairs reviews it. If an agent receives a report of hospitalization on Monday and doesn't escalate until Friday, you've consumed a third of your reporting window before regulatory affairs even sees it. Build immediate escalation with automated regulatory clock tracking."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Consumer complaint intake workflow with product retention request","Food safety investigation workflow from complaint to root cause","Recall execution workflow — notification, retailer communication, and product recovery","Coupon and product replacement fulfillment workflow","Adverse event reporting workflow to FDA/FSIS with timeline tracking"], vendors: "SAP, Oracle, custom QMS, Salesforce", risk: "Consumer disposing of product before lot code is captured — evidence lost",
        stack: [{ name: "SAP / Oracle QMS", role: "Quality Management", why: "Complaint intake, investigation tracking, and CAPA (Corrective and Preventive Action) management. The system that connects a consumer complaint to a production investigation to a process improvement.", href: "/vendors" }],
        pitfall: "The most important step in food safety complaint handling is asking the consumer to retain the product for testing. A consumer who throws away the 'funny-tasting yogurt' before the manufacturer can test it leaves the investigation without physical evidence. Train agents to say: 'Please keep the remaining product and packaging — we'd like to test it' on every quality complaint, not just the ones that sound serious."
      },
      { layer: 1, name: "Data Access", capabilities: ["Product master data — ingredients, allergens, lot codes, and production facilities","Quality management system — complaints, investigations, and CAPA","Production data — lot traceability from ingredients through packaging","Retailer and distribution data — where products were shipped by lot code","Consumer database — complaint history and product feedback"], vendors: "SAP, Oracle, TraceGains, FoodLogiQ", risk: "Lot code traceability gap preventing identification of affected product scope",
        stack: [{ name: "SAP S/4HANA", role: "ERP & Traceability", why: "Lot code traceability from raw ingredient through finished product through retail distribution. When a food safety event occurs, the first question is 'which lots are affected and where did they ship?' SAP answers both.", href: "/vendors" }, { name: "TraceGains / FoodLogiQ", role: "Supply Chain Traceability", why: "Ingredient and supplier traceability. When a food safety event involves a contaminated ingredient, traceability identifies every finished product that used that ingredient from that supplier lot.", href: "/vendors" }],
        pitfall: "FDA's FSMA Rule 204 (effective 2026) requires additional traceability records for certain foods on the Food Traceability List. Your contact center agents handling complaints about these foods must capture Key Data Elements (KDEs) including lot codes, product descriptions, and purchase locations. If your complaint intake form doesn't capture KDEs, you'll have traceability gaps that FDA will find during inspections. Update complaint intake forms to align with FSMA 204 requirements."
      },
    ],
  },
};

export const getManufacturingSubVertical = (slug) => manufacturingSubVerticals[slug];
export const getAllManufacturingSubVerticalSlugs = () => Object.keys(manufacturingSubVerticals);
