export const manufacturingSubVerticals = {
  "automotive-oem": {
    name: "Automotive OEM", parent: "Manufacturing & Automotive",
    tagline: "Recalls, warranty, connected vehicle support, EV ownership, and brand loyalty.",
    intro: "Automotive OEM contact centers own the post-purchase relationship with every owner, and each recall, warranty claim, and service issue shapes whether that owner buys the brand again. The operating challenge is absorbing recall surges, adjudicating warranty cleanly, and supporting connected vehicle and EV questions, all while the dealer remains the physical point of service.",
    kpis: [
      { metric: "AHT", avg: "[[mfg.sv.automotive-oem.aht]]", note: "VIN lookup, warranty verification, and recall coordination add time" },
      { metric: "FCR", avg: "[[mfg.sv.automotive-oem.fcr]]", note: "Warranty decisions, dealer coordination, and parts availability often need follow-up" },
      { metric: "CSAT", avg: "[[mfg.sv.automotive-oem.csat]]", note: "Driven by recall communication speed and how fair warranty decisions feel" },
      { metric: "Containment", avg: "[[mfg.sv.automotive-oem.containment]]", note: "VIN recall checks automate well; warranty and technical questions need people" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["J.D. Power CSI and SSI tracking tied to contact center interactions","Warranty cost-per-vehicle analytics by model, year, and component","Recall completion rate tracking by campaign and geographic region","Connected vehicle complaint trending by software version and feature","Social media sentiment analysis during recall and quality events"],
        vendors: "NICE, Medallia, J.D. Power, Qualtrics", risk: "Quality trend invisible until warranty costs spike",
        stack: [{ name: "Medallia", role: "CX Analytics", why: "Connects CSI survey data to contact center interaction data. Shows which contact center experiences drive or suppress repurchase intent. OEM-specific CX benchmarking.", href: "/vendors/analytics" }, { name: "NICE Nexidia", role: "Interaction Analytics", why: "Analyzes warranty and recall calls at scale. Identifies which warranty denials create the most escalation and which recall communications reduce follow-up calls.", href: "/vendors/analytics" }],
        pitfall: "OEMs track warranty cost as a financial metric but rarely connect it to CX impact. [[mfg.ex.goodwill]] is cheap retention. Track warranty decisions against repurchase data: the link between warranty denial and brand defection is a metric few contact centers see."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Recall surge routing activating overflow capacity within hours of NHTSA announcement","VIN-based routing matching callers to agents trained on their vehicle platform","Warranty escalation routing with goodwill authority tiers","Connected vehicle/EV routing to technically trained specialists","Dealer escalation routing when the customer's dealer issue requires OEM intervention"],
        vendors: "Genesys, NICE CXone, Cisco", risk: "Recall announcement driving a call surge before routing is configured",
        stack: [{ name: "Genesys Cloud", role: "Primary CCaaS", why: "Recall surge routing activated from pre-built playbooks. VIN-based intent detection routes owners of recalled vehicles to recall-specific messaging before they reach an agent. Takes simple recall questions off the agent queue.", href: "/vendors/genesys" }],
        pitfall: "Once a defect is determined to be safety related, the manufacturer has [[mfg.nhtsa.573]] to file its defect report with NHTSA, and NHTSA posts recall filings publicly. Owner letters can follow up to [[mfg.nhtsa.577]] after that filing, so owners often hear about a recall from the news before their letter arrives. If the contact center is not briefed, the IVR not updated and agents not trained before coverage starts, owners reach agents who know less than the news article. Build a recall readiness playbook: notification content, IVR update, agent briefing, FAQ script, and self-service VIN checker, all deployable within [[mfg.recall.playbook]]."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Proactive recall notification by VIN via mail, email, SMS, and app push","Self-service VIN recall checker on website and mobile app","Connected vehicle in-car support and remote diagnostics","Warranty claim status portal with repair history visibility","Social media management for viral quality complaints and recall concerns"],
        vendors: "Sprinklr, LivePerson, Ada, connected vehicle platforms", risk: "Vehicle owner learning about a safety recall from a news article instead of the OEM",
        stack: [{ name: "Sprinklr", role: "Social CX", why: "Automotive quality issues and recalls go viral on social media. A single video about a brake failure can spread faster than the recall notice. Sprinklr unifies social listening, response, and escalation.", href: "/vendors/digital-engagement" }, { name: "Connected vehicle platform", role: "In-Vehicle Support", why: "GM (OnStar) and several other OEMs offer in-car support. The vehicle itself becomes a support channel, sending diagnostic data and enabling remote troubleshooting.", href: "/vendors" }],
        pitfall: "NHTSA requires OEMs to notify registered owners by first class mail (49 CFR 577.7). A letter reaches only owners at a current address who open it. Adding email, SMS, and app push gives owners more ways to learn of the recall and book the repair, and NHTSA publishes recall completion rates by manufacturer. Track completion by notification channel to see which ones move owners to the service drive."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["VIN recall lookup bots checking NHTSA and OEM databases","Warranty coverage verification bots by VIN, mileage, and date","Service scheduling bots connecting owners to dealer service departments","Connected vehicle troubleshooting bots with diagnostic data","Owner's manual and feature explanation bots for new vehicle technology"],
        vendors: "Ada, Cognigy, Google CCAI, custom", risk: "Bot stating 'your vehicle is not affected by any recalls' when the VIN database hasn't updated",
        stack: [{ name: "Ada", role: "AI Agent", why: "VIN-based recall check, warranty verification, and dealer locator. Routes warranty disputes and technical complaints to human agents. Handles the high-volume, low-complexity calls that surge during recall events.", href: "/vendors/iva" }],
        pitfall: "VIN recall bots must query the NHTSA recall database AND the OEM's internal recall database: they're not always in sync. A bot that checks NHTSA but not the OEM's pending recalls might miss a just-announced campaign. A bot that checks only the OEM might miss a supplier-level recall affecting multiple brands. Query both databases and present the union of results."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["NHTSA recall notification and completion compliance","Magnuson-Moss Warranty Act compliance for warranty claims","State lemon law compliance varying by jurisdiction","TREAD Act defect reporting requirements","CPSC compliance for non-vehicular consumer products"],
        vendors: "NHTSA compliance, Magnuson-Moss, state lemon laws", risk: "Warranty denial violating Magnuson-Moss and triggering FTC or state AG complaint",
        stack: [{ name: "OEM warranty system", role: "Compliance", why: "Warranty adjudication must comply with Magnuson-Moss, and a denial needs documented justification that holds up if the owner challenges it. Contact center agents making denial decisions must be trained on both the warranty terms and the legal requirements.", href: "/vendors" }],
        pitfall: "The Magnuson-Moss Warranty Act prohibits tying warranty coverage to OEM-branded parts or dealer-only service unless those are provided free or the FTC grants a waiver (16 CFR 700.10). An agent who says 'your warranty is void because you used aftermarket brake pads' is making a prohibited warranty denial. Train every warranty agent on Magnuson-Moss basics: the FTC can bring enforcement actions, and owners can sue under the Act."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Recall scheduling workflow connecting owner to dealer with parts availability check","Warranty claim adjudication workflow with goodwill escalation tiers","Connected vehicle OTA update notification and failure resolution workflow","Lemon law buyback/replacement workflow with state-specific requirements","NHTSA complaint documentation workflow capturing required safety data"],
        vendors: "SAP, Oracle, Salesforce, DealerSocket, CDK", risk: "Recall scheduling without parts availability check: owner arrives, parts not in stock",
        stack: [{ name: "SAP (Automotive)", role: "Warranty & Recall", why: "Warranty claims management, recall campaign tracking, and parts logistics. The ERP backbone that determines whether the recall part is available at the dealer before scheduling the appointment.", href: "/vendors" }, { name: "CDK / Reynolds & Reynolds", role: "Dealer Management", why: "DMS integration connecting OEM recall and warranty systems to dealer service scheduling. Without DMS integration, the OEM contact center can't schedule a dealer appointment: they can only tell the owner to call the dealer.", href: "/vendors" }],
        pitfall: "A common recall CX failure: OEM notifies owner, owner calls to schedule, owner drives to dealer, dealer says 'we don't have the recall part in stock.' Now the owner is angry, the dealer is embarrassed, and the recall completion rate drops. Build parts-availability-aware scheduling: if the part isn't in stock at the owner's preferred dealer, route to a dealer that has it, or schedule after the part is available."
      },
      { layer: 1, name: "Data Access", capabilities: ["Vehicle master data: VIN, build data, warranty status, recall applicability","Warranty claims history by VIN with repair details and parts used","Connected vehicle telemetry: diagnostic trouble codes, mileage, location","Dealer network data: locations, service capacity, parts inventory","NHTSA complaint and recall databases"], vendors: "SAP, Oracle, Salesforce Mfg Cloud, connected vehicle platforms", risk: "Agent seeing warranty status but not repair history, can't assess if the same issue recurred",
        stack: [{ name: "SAP S/4HANA (Automotive)", role: "ERP", why: "Vehicle master data, warranty claims, parts inventory, and dealer management. The data foundation for every OEM contact center interaction. Real-time access to warranty status by VIN.", href: "/vendors" }, { name: "Connected vehicle platform", role: "Telemetry", why: "Real-time vehicle diagnostic data: DTCs, battery state of health (EV), tire pressure, fluid levels. When an owner calls about a warning light, the agent can see the diagnostic data before the owner describes the symptom.", href: "/vendors" }],
        pitfall: "Connected vehicles generate massive telemetry data, but most OEM contact centers can't access it in real-time. The vehicle sends a DTC to the cloud platform; the cloud platform stores it; but the agent desktop doesn't display it. An owner calling about a check engine light is describing what the OEM already knows digitally. Connect vehicle telemetry to the agent desktop so the agent sees the DTC before the owner finishes explaining. In practice this can take [[mfg.oem.dtc.aht]] off a technical call."
      },
    ],
  },

  "automotive-dealer": {
    name: "Automotive Dealer & Retail", parent: "Manufacturing & Automotive",
    tagline: "BDC operations, service scheduling, sales follow-up, F&I, and CSI management.",
    intro: "Automotive dealer contact centers, typically called BDCs (Business Development Centers), bridge the gap between the showroom and the service drive. The CX challenge is that the dealer IS the brand experience for most vehicle owners, but dealer contact centers are often undertrained, understaffed, and disconnected from both the OEM and the customer's vehicle data.",
    kpis: [
      { metric: "AHT", avg: "[[mfg.sv.automotive-dealer.aht]]", note: "Appointment scheduling and sales follow-up calls are focused" },
      { metric: "FCR", avg: "[[mfg.sv.automotive-dealer.fcr]]", note: "Scheduling and status calls resolve in one contact more often than repairs or disputes" },
      { metric: "CSAT (CSI)", avg: "[[mfg.sv.automotive-dealer.csat]]", note: "The relationship with the service advisor drives satisfaction" },
      { metric: "Appointment Set Rate", avg: "[[mfg.sv.automotive-dealer.apptset]]", note: "The BDC metric: share of inbound leads converted to appointments" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["CSI/SSI score tracking by advisor, department, and dealership","Sales lead conversion analytics from BDC through closing","Service appointment show rate and revenue per RO","Recall appointment completion tracking for OEM compliance","Internet lead response time and conversion funnel analytics"], vendors: "DealerSocket, VinSolutions, NICE", risk: "CSI scores declining without connecting to specific BDC behaviors",
        stack: [{ name: "DealerSocket / VinSolutions", role: "Dealer CRM", why: "Lead management, follow-up tracking, and CSI monitoring. The CRM that measures whether the BDC is converting leads and maintaining satisfaction.", href: "/vendors" }],
        pitfall: "OEMs tie dealer incentives to CSI scores, but CSI surveys measure the service experience, not the BDC experience. A BDC agent who sets an appointment brilliantly but the service advisor who handles the visit poorly produces a low CSI that the BDC can't control. Track BDC-specific metrics (appointment set rate, show rate, speed to lead) separately from CSI."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Sales vs service routing separating new vehicle leads from service requests","Internet lead routing with speed-to-response SLA","Service recall routing matching VIN to open campaigns","After-hours routing for service emergencies and sales inquiries","VIP and loyalty routing for high-value repeat customers"], vendors: "NICE CXone, Five9, RingCentral", risk: "Internet lead waiting hours for a response while competitors reply within minutes",
        stack: [{ name: "Five9", role: "CCaaS", why: "Right-sized for small dealer BDC teams. Blended inbound/outbound for lead follow-up. CRM integration with DealerSocket and VinSolutions.", href: "/vendors/five9" }],
        pitfall: "Speed to lead is a core dealer sales BDC metric: an online shopper often sends the same inquiry to several dealers, and the first useful reply has the advantage. Automate an instant acknowledgment and a personal follow-up call within [[mfg.dealer.followup]]."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Service appointment scheduling via text, chat, and phone","Sales lead follow-up sequences via email, text, and phone","CSI survey follow-up for dissatisfied customers","Recall notification and appointment scheduling outreach","Service reminder notifications for maintenance milestones"], vendors: "Podium, Kenect, DealerSocket, CDK", risk: "Customers unable to schedule service without calling during business hours",
        stack: [{ name: "Podium", role: "Messaging & Reviews", why: "Text-based communication for dealer service and sales. Review generation for Google and OEM surveys. The messaging layer that modern car buyers expect.", href: "/vendors" }],
        pitfall: "Phone-only service scheduling, 'call us during business hours', loses appointments. Customers who can't call during the working day defer service or go to an independent shop. Online and text scheduling win that revenue back."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Service appointment scheduling bots with real-time advisor availability","Recall check bots by VIN with appointment offer","Vehicle trade-in value estimation bots","Parts availability and pricing bots","Service status bots with estimated completion time"], vendors: "Ada, dealer-specific chatbots", risk: "Bot scheduling an appointment for a recall without confirming parts availability",
        stack: [{ name: "Ada / dealer chatbot", role: "AI Agent", why: "24/7 appointment scheduling, VIN recall lookup, and service FAQ. Captures leads after hours when the BDC is closed, when many online leads arrive.", href: "/vendors/iva" }],
        pitfall: "Dealer chatbots must integrate with the DMS (CDK, Reynolds & Reynolds) for real-time service capacity. A bot that offers 'Tuesday at 9am' when the service drive is already overbooked for Tuesday creates a no-show or a long wait when the customer arrives. Pull real-time advisor availability and bay capacity from the DMS."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["TCPA compliance for sales and service outreach calls and texts","FTC Safeguards Rule compliance for customer financial data (F&I)","OEM program compliance for recall handling and warranty processes","State-specific advertising and pricing disclosure requirements","Do Not Call and opt-out management for outbound campaigns"], vendors: "DMS compliance modules, TCPA compliance", risk: "TCPA violation from automated service reminder texts without proper consent",
        stack: [{ name: "DMS compliance / TCPA tools", role: "Regulatory", why: "Under the TCPA a recipient of an unconsented call or text can recover [[mfg.tcpa.damages]] per violation, and a court can triple it for a willful or knowing violation. [[mfg.ex.tcpa]]. Capture consent at point of sale and honor opt-outs in real-time.", href: "/vendors" }],
        pitfall: "The FTC Safeguards Rule (16 CFR part 314) requires dealers that finance or lease vehicles to run an information security program for customer financial data, including data the BDC handles. If BDC agents access credit applications, income verification, or payment information, the dealer needs encryption, access controls, and security training in place, and a larger security event must be reported to the FTC within [[mfg.ftc.notify]] of discovery."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Sales lead capture and assignment workflow from website, phone, and walk-in","Service appointment workflow with advisor assignment and bay scheduling","Recall appointment workflow with OEM parts verification","CSI recovery workflow for dissatisfied survey respondents","Equity mining workflow identifying service customers ready for new vehicle purchase"], vendors: "CDK, Reynolds & Reynolds, DealerSocket, Tekion", risk: "Hot lead assigned to a salesperson who's off today: no follow-up until tomorrow",
        stack: [{ name: "CDK Drive", role: "DMS", why: "Dominant dealer management system. Service scheduling, parts inventory, and customer records. The operational backbone the BDC integrates with.", href: "/vendors" }, { name: "Tekion", role: "Cloud DMS", why: "Cloud-native dealer management system challenging CDK. Modern APIs, better integration, and mobile-first design. Growing adoption in progressive dealer groups.", href: "/vendors" }],
        pitfall: "Equity mining, identifying service customers whose trade-in value exceeds their loan balance, is a high-value BDC workflow. A customer who brings their car in for a routine mileage service and could trade up to a new model with lower payments should hear from the sales BDC before they leave the service drive. Most dealers run equity mining as a monthly batch report; real-time equity alerts during service visits catch opportunities a monthly batch misses."
      },
      { layer: 1, name: "Data Access", capabilities: ["DMS: customer records, vehicle history, service appointments, parts inventory","CRM: lead management, follow-up activity, and sales pipeline","OEM portal: recall data, warranty claims, incentive programs","Inventory management: new and used vehicle availability","F&I system: credit applications, payment structures, and aftermarket products"], vendors: "CDK, Reynolds & Reynolds, Tekion, DealerSocket, VinSolutions", risk: "CRM and DMS containing duplicate customer records with conflicting data",
        stack: [{ name: "CDK / Reynolds & Reynolds", role: "DMS Data", why: "Vehicle service history, parts inventory, customer contact information, and financial records. Every BDC interaction requires DMS data.", href: "/vendors" }, { name: "VinSolutions / DealerSocket", role: "CRM Data", why: "Lead status, follow-up history, communication preferences, and sales pipeline. The CRM and DMS must share data: CRM for relationship context, DMS for transactional data.", href: "/vendors" }],
        pitfall: "The dealer data problem: the DMS and the CRM often contain different customer records for the same person. The DMS has the service customer (entered at the service drive); the CRM has the sales lead (entered from the website). Without identity resolution, the BDC doesn't know that the service customer who's in for a scheduled service is the same person who submitted a trade-in inquiry online last week. Deduplicate across DMS and CRM."
      },
    ],
  },

  "industrial-b2b": {
    name: "Industrial & B2B Manufacturing", parent: "Manufacturing & Automotive",
    tagline: "Parts ordering, warranty claims, technical support, field service, and distributor support.",
    intro: "Industrial manufacturing contact centers serve businesses whose production depends on the manufacturer's products. When a CNC machine goes down, a hydraulic pump fails, or a critical assembly part is backordered, the customer's production line stops, and every hour it stays down costs the customer output. The CX challenge is providing technical expertise and parts logistics with the urgency that production downtime demands.",
    kpis: [
      { metric: "AHT", avg: "[[mfg.sv.industrial-b2b.aht]]", note: "Technical diagnosis, parts identification, and field service coordination add time" },
      { metric: "FCR", avg: "[[mfg.sv.industrial-b2b.fcr]]", note: "Parts availability, field service scheduling, and engineering review need follow-up" },
      { metric: "CSAT", avg: "[[mfg.sv.industrial-b2b.csat]]", note: "Downtime frustration can outweigh service quality" },
      { metric: "Containment", avg: "[[mfg.sv.industrial-b2b.containment]]", note: "Technical questions need engineering-level knowledge" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Account profitability analytics connecting service cost to revenue","Mean time to resolve (MTTR) by product line, issue type, and technician","Parts availability and backorder impact on resolution time","Warranty claim trending by product, component, and manufacturing batch","Customer health scoring combining service frequency, NPS, and revenue trend"], vendors: "NICE, Verint, Salesforce Analytics", risk: "Key accounts churning because service degradation wasn't detected early",
        stack: [{ name: "NICE CXone", role: "Analytics", why: "Technical QA scoring evaluating whether agents correctly diagnosed the issue, identified the right part, and escalated when needed. B2B-grade analytics connecting interactions to account health.", href: "/vendors/nice-cxone" }],
        pitfall: "B2B manufacturers track MTTR (mean time to resolve) at the ticket level but not at the account level. [[mfg.ex.mttr]]. The first account has a chronic product quality issue masquerading as good support performance. Track resolution at the account level to see the real picture."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Production-down emergency routing with immediate escalation to engineering","Named account routing for strategic accounts with dedicated support teams","Product-line routing matching callers to agents trained on specific equipment","Distributor vs end-user routing with different service models","Field service dispatch routing coordinating technician scheduling and parts"], vendors: "Genesys, NICE CXone, ServiceNow", risk: "Production-down emergency waiting in a general support queue",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Priority routing based on account value and issue severity. Production-down calls bypass all queues and reach a senior engineer immediately. Account-based routing ensures strategic accounts always reach their dedicated team.", href: "/vendors/genesys" }],
        pitfall: "Industrial support must have a 'production down' emergency path that's separate from routine support, and accessible 24/7. A customer whose production line stops at 2am needs a live engineer; a voicemail box loses the account. Staff overnight emergency coverage with senior technical people. Weigh the cost of overnight engineering cover against the revenue at risk in a single production-down account."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Customer portal with equipment registry, service history, and parts ordering","Proactive maintenance notifications based on equipment runtime and IoT data","Technical documentation library with model-specific manuals and bulletins","Field service scheduling with technician assignment and ETA tracking","Video-assisted remote diagnosis for complex equipment issues"], vendors: "Salesforce, ServiceMax, Glia, Zoom", risk: "Customer unable to find documentation for their specific equipment model/serial",
        stack: [{ name: "Glia", role: "Visual Support", why: "Video-assisted support for complex equipment: the customer shows the technician the equipment via smartphone camera, and the technician guides the diagnosis remotely. Avoids a truck roll when guided customer action resolves the issue.", href: "/vendors/digital-engagement" }],
        pitfall: "Industrial customers call support when equipment fails, but most failures have warning signs visible in operational data (vibration increase, temperature rise, pressure fluctuation). Proactive maintenance notifications based on IoT sensor data prevent failures before they create downtime and support calls. A prevented failure removes both the downtime and the support call."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Parts identification bots using model, serial, and component description","Warranty coverage verification by serial number and purchase date","Equipment documentation search bots returning model-specific manuals","Service request status bots with field service ETA","Basic troubleshooting bots with step-by-step diagnostic guides"], vendors: "Ada, Cognigy, custom bots", risk: "Bot identifying the wrong part number for a similar but different model",
        stack: [{ name: "Ada", role: "AI Agent", why: "Parts lookup by serial number, warranty verification, and service status. Routes production-down emergencies and complex technical questions to human engineers immediately.", href: "/vendors/iva" }],
        pitfall: "Parts identification bots are powerful but dangerous in industrial manufacturing. A pump impeller that looks identical across several model variants but has different dimensions, materials, or pressure ratings will fail catastrophically if the wrong part is installed. Bots must verify model number, serial number, AND revision level before confirming a part number. Add a human confirmation step for safety-critical components."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Product liability compliance for safety-critical equipment","UCC warranty compliance for commercial sales","Export control (ITAR/EAR) for defense and dual-use products","Environmental compliance for hazardous materials in products","ISO 9001 quality management system integration with support"], vendors: "Custom compliance, ERP-embedded", risk: "ITAR-controlled technical data shared with unauthorized foreign national",
        stack: [{ name: "ERP compliance modules", role: "Export Control", why: "SAP and Oracle embed export control screening in parts orders and technical data requests. A support agent shipping a controlled part or sending controlled documentation to a prohibited country creates a federal violation. Automate screening: don't rely on agents to know ITAR.", href: "/vendors" }],
        pitfall: "ITAR (International Traffic in Arms Regulations) controls the export of defense-related products and technical data. If your products include any defense applications, your support agents cannot share technical specifications, troubleshooting procedures, or parts data with foreign nationals without export authorization. This applies to phone calls, emails, and portal access. Willful violations are federal crimes (22 U.S.C. 2778(c)), and violations can lead to debarment from government contracts."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Parts order fulfillment workflow with inventory check and shipping","Warranty claim adjudication workflow with engineering review for complex claims","Field service dispatch workflow with technician assignment, parts kit, and ETA","RMA (Return Material Authorization) processing workflow","Product quality escalation workflow connecting support to engineering and manufacturing"], vendors: "SAP, Oracle, Salesforce, ServiceMax, IFS", risk: "Field service dispatched without the right parts: technician arrives and can't repair",
        stack: [{ name: "ServiceMax", role: "Field Service", why: "Purpose-built for industrial field service. Technician scheduling, parts kit preparation, work order management, and customer portal. Connects the contact center to field operations.", href: "/vendors" }, { name: "SAP S/4HANA", role: "ERP", why: "Parts inventory, warranty claims, and order management. The operational backbone for industrial support. Real-time parts availability determines whether the agent can promise same-day or next-day delivery.", href: "/vendors" }],
        pitfall: "Field service dispatch without parts verification is one of the costliest CX failures in industrial manufacturing. [[mfg.ex.dispatch]]. Build parts-kit verification into every dispatch workflow: confirm the required parts are available and loaded before the technician departs."
      },
      { layer: 1, name: "Data Access", capabilities: ["ERP: parts inventory, BOMs, pricing, and order status","CRM: account management, service history, and installed base","Equipment registry: serial numbers, configurations, and warranty status","Field service system: technician schedules, work orders, and parts kits","IoT platform: equipment telemetry, runtime data, and predictive alerts"], vendors: "SAP, Oracle, Salesforce Manufacturing Cloud, PTC ThingWorx", risk: "Agent seeing the product catalog but not the customer's specific installed configuration",
        stack: [{ name: "SAP S/4HANA", role: "ERP Data", why: "Parts availability, BOMs, warranty status, and order processing. Every industrial support interaction requires ERP data, is the part in stock? Is the warranty active? Has this claim been filed before?", href: "/vendors" }, { name: "Salesforce Manufacturing Cloud", role: "CRM", why: "Account management with installed base tracking. Shows what the customer has, what they've bought, what they've claimed warranty on, and what they're likely to need next.", href: "/vendors/ccaas" }, { name: "PTC ThingWorx", role: "IoT Platform", why: "Connected equipment telemetry. When the customer calls about equipment failure, the agent can see the equipment's operational data, runtime hours, error codes, and performance degradation, before the customer describes the problem.", href: "/vendors" }],
        pitfall: "Industrial support agents need installed base data, not just product catalog data. The customer isn't calling about a generic 'Model X pump.' They're calling about the specific pump with serial #12345, installed in March 2022, running configuration B, with firmware v2.3, in a corrosive environment. Without installed base data, the agent starts every call from zero. Build a serial-number-linked customer equipment registry accessible from the agent desktop."
      },
    ],
  },

  "consumer-electronics": {
    name: "Consumer Electronics & Appliances", parent: "Manufacturing & Automotive",
    tagline: "Product setup, troubleshooting, warranty, returns, and smart home integration.",
    intro: "Consumer electronics contact centers handle the post-unboxing experience: setup, troubleshooting, warranty claims, and returns. The CX challenge is that products are increasingly complex (smart home ecosystems, firmware updates, multi-device interoperability) while customer tolerance for complexity is decreasing. Customers judge every brand's setup against the simplest product they own.",
    kpis: [
      { metric: "AHT", avg: "[[mfg.sv.consumer-electronics.aht]]", note: "Simple setup is quick; interoperability troubleshooting is long" },
      { metric: "FCR", avg: "[[mfg.sv.consumer-electronics.fcr]]", note: "Firmware issues, compatibility problems, and warranty coordination need follow-up" },
      { metric: "CSAT", avg: "[[mfg.sv.consumer-electronics.csat]]", note: "Driven by product quality first, support quality second" },
      { metric: "Containment", avg: "[[mfg.sv.consumer-electronics.containment]]", note: "Setup guides and FAQs automate well; compatibility and warranty need people" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Product defect trending by SKU, batch, and firmware version","Support cost per product informing design-for-supportability","NPS correlation between support experience and repurchase","Return reason analytics separating defect from user error from buyer's remorse","Knowledge base effectiveness: which articles reduce contact, which don't"], vendors: "NICE, Medallia, Qualtrics", risk: "Product defect invisible until support costs spike months after launch",
        stack: [{ name: "NICE CXone", role: "Analytics", why: "Product-specific contact reason trending. When a new SKU launches and generates far more support volume than expected, NICE identifies whether the issue is defect (engineering fix), documentation (content fix), or user error (training fix).", href: "/vendors/nice-cxone" }],
        pitfall: "Consumer electronics manufacturers track support cost as an overhead line item, not as a product quality signal. [[mfg.ex.support-cost]]. Feed support data into product development to build design-for-supportability into the next generation."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Product-line routing matching callers to agents trained on specific categories","Warranty vs out-of-warranty routing with different service paths","Smart home ecosystem routing for multi-device interoperability issues","Premium support routing for high-end product lines","Returns and exchange routing with policy enforcement"], vendors: "Genesys, NICE CXone, Five9", risk: "Smart home issue requiring expertise across three product categories reaching a single-product agent",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Product-line routing with SKU-level agent specialization. Handles the breadth of consumer electronics, from headphones to smart TVs to home security, with appropriate routing to trained specialists.", href: "/vendors/nice-cxone" }],
        pitfall: "Smart home interoperability issues are a growing, hard-to-route call type in consumer electronics. 'My smart speaker won't control my smart lights when I'm using my streaming service' involves three product categories, potentially three manufacturers, and three ecosystems. Most routing puts this in a general queue where no single agent knows all three. Build a multi-product escalation team trained across the ecosystem."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Interactive setup guides with video and step-by-step instructions","Firmware update notification and troubleshooting","Product registration with warranty activation","Self-service return and exchange portal","Community forums with peer-to-peer troubleshooting and moderation"], vendors: "Zendesk, Intercom, Ada, community platforms", risk: "Community forum containing incorrect advice that users follow",
        stack: [{ name: "Zendesk", role: "Support Platform", why: "Multi-channel support with strong knowledge base and community forum integration. Good for consumer electronics brands managing high-volume product support across many SKUs.", href: "/vendors" }],
        pitfall: "Firmware updates that break features are among the most damaging CX events in consumer electronics: the product worked yesterday, the user didn't change anything, and now it's broken. Proactive notification ('a firmware update is available: here's what it fixes and what may change') gives users control. Silent auto-updates that break functionality generate massive support volume and social media backlash. Let users choose when to update."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Guided troubleshooting bots with product-specific diagnostic trees","Setup and configuration bots with step-by-step instructions","Warranty status verification by serial number or purchase date","Return eligibility bots with policy and restocking fee information","Compatibility checker bots for ecosystem and accessory questions"], vendors: "Ada, Cognigy, custom bots", risk: "Bot troubleshooting a firmware issue with hardware diagnostics: wrong tree entirely",
        stack: [{ name: "Ada", role: "AI Agent", why: "Product-specific troubleshooting, setup guidance, and warranty verification. Handles the high volume of simple questions (setup, compatibility, warranty status) that don't need human agents.", href: "/vendors/iva" }],
        pitfall: "Troubleshooting bots for consumer electronics must distinguish between hardware failure (replace the product), firmware issue (update or roll back), user error (education), and ecosystem incompatibility (can't be fixed: explain limitation). A bot that runs hardware diagnostics when the issue is a firmware bug wastes the customer's time. Start with 'has anything changed recently?' to classify the issue category before diving into diagnostic steps."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Consumer Product Safety Commission (CPSC) compliance for safety defects","FCC compliance for wireless and electronic emissions","State warranty and return policy compliance","EU CE marking and WEEE compliance for international products","Privacy compliance for smart home data collection and usage"], vendors: "CPSC compliance, FCC, custom", risk: "Smart home device collecting data without proper disclosure creating privacy violation",
        stack: [{ name: "Compliance systems", role: "Product Safety", why: "Manufacturers must report product safety defects to CPSC, which expects a report within [[mfg.cpsc.report]] of having information that reasonably supports it. Contact center agents who receive reports of fires, electric shocks, or injuries must be trained to document these reports and escalate to the safety team immediately.", href: "/vendors" }],
        pitfall: "Smart home devices collect voice recordings, usage patterns, and environmental data. Privacy regulations (CCPA, GDPR, state laws) require disclosure of what's collected and how it's used. When a customer calls and asks 'is my smart speaker recording me?' the agent must provide an accurate, compliant answer, not a reassuring platitude. Train agents on your product's actual data collection practices and provide a clear, honest response."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Product return and exchange workflow with condition assessment","Warranty claim workflow with repair vs replace decision logic","Advanced replacement workflow (send new product before receiving defective)","Product recall notification and replacement workflow","Refurbished/renewed product processing and resale workflow"], vendors: "Salesforce, SAP, Oracle, Zendesk", risk: "Advanced replacement sent without receiving the defective unit back: inventory loss",
        stack: [{ name: "Salesforce Service Cloud", role: "Case Management", why: "Warranty claims, returns, and exchange management. Tracks product serial numbers through the return/replace/refurbish lifecycle.", href: "/vendors/ccaas" }],
        pitfall: "Advanced replacement (sending a new unit before receiving the defective one) is a high-satisfaction resolution: the customer gets working equipment immediately. But without a deposit hold or return tracking, some customers keep both units. Place a card hold for the replacement value and follow up automatically if the defective unit isn't returned within the set window."
      },
      { layer: 1, name: "Data Access", capabilities: ["Product catalog with specifications, compatibility, and firmware versions","Warranty database with serial number registration and coverage status","Inventory management for replacement and exchange stock","Customer profile with purchase history and product registration","Knowledge base with troubleshooting articles and setup guides"], vendors: "SAP, Oracle, Salesforce, Zendesk", risk: "Agent unable to look up warranty status because the customer didn't register the product",
        stack: [{ name: "SAP / Oracle", role: "ERP", why: "Product master data, inventory, and warranty information. The source of truth for 'is this product under warranty?' and 'do we have replacement stock?'", href: "/vendors" }, { name: "Zendesk Guide", role: "Knowledge Base", why: "Product-specific troubleshooting articles and setup guides. Self-service deflection when articles are good; contact driver when articles are missing or wrong.", href: "/vendors" }],
        pitfall: "Many buyers never register their product, so a registration lookup cannot verify warranty for them. Build alternative warranty verification: retailer purchase data (Best Buy, Amazon), credit card lookup, or date-code-based warranty (manufacture date + warranty period). Requiring registration for warranty support turns away every unregistered owner."
      },
    ],
  },

  "aerospace-defense": {
    name: "Aerospace & Defense", parent: "Manufacturing & Automotive",
    tagline: "MRO support, parts logistics, AOG emergencies, regulatory compliance, and fleet services.",
    intro: "Aerospace contact centers support aircraft operators whose equipment availability directly affects revenue (airlines) or mission readiness (defense). An Aircraft on Ground (AOG) event costs an airline revenue and schedule for every hour it lasts. The CX challenge is 24/7 parts availability, regulatory compliance (FAA/EASA), and engineering expertise at a depth few other manufacturing sectors need.",
    kpis: [
      { metric: "AHT", avg: "[[mfg.sv.aerospace-defense.aht]]", note: "Parts identification, certification tracing, and AOG coordination add time" },
      { metric: "FCR", avg: "[[mfg.sv.aerospace-defense.fcr]]", note: "Parts sourcing, engineering review, and regulatory verification need follow-up" },
      { metric: "CSAT", avg: "[[mfg.sv.aerospace-defense.csat]]", note: "Driven by parts availability and AOG response time" },
      { metric: "AOG Response", avg: "[[mfg.sv.aerospace-defense.aog]]", note: "Time to locate and ship a critical AOG part" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["AOG response time tracking: time from request to parts shipment","Parts fill rate analytics by part number and stock location","Warranty and product support cost by aircraft type and operator","Fleet reliability analytics feeding back to design engineering","ITAR/EAR compliance audit trail for technical data distribution"], vendors: "NICE, custom analytics, SAP", risk: "AOG response degradation invisible until operators start sourcing from competitors",
        stack: [{ name: "Custom BI", role: "Aerospace Analytics", why: "Aerospace analytics are unique: AOG response time, parts fill rate, rotable pool utilization, and warranty claim trending by aircraft type. No standard CX analytics tool covers these metrics.", href: "/vendors" }],
        pitfall: "In aerospace, support can decide fleet support contracts. Airframe and engine makers sell to a small set of operators, and the one that answers AOG calls fastest, ships parts overnight, and provides engineering support on weekends has an edge when those contracts come up. Track AOG response metrics as the primary competitive indicator."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["AOG priority routing: immediate 24/7 escalation to senior support","Product-line routing by airframe, engine, and system","Operator-tier routing based on fleet size and contract level","Engineering escalation routing for technical inquiries beyond parts","ITAR-controlled routing restricting access based on caller nationality"], vendors: "Genesys, Cisco, NICE CXone", risk: "AOG call at 3am reaching voicemail instead of 24/7 support desk",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "24/7 AOG routing with immediate escalation. Operator identification and contract-level routing. Handles the zero-tolerance-for-downtime urgency that aerospace support requires.", href: "/vendors/genesys" }],
        pitfall: "AOG support must be 24/7/365 with zero voicemail. An airline with a grounded 737 at 2am in Dubai doesn't leave a message: they call the competitor. Staff overnight and weekend AOG desks with senior parts specialists who have authority to approve emergency shipments, charter flights for parts delivery, and authorize field repairs. Treat it as revenue protection."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["AOG parts request portal with real-time inventory and shipping options","Technical publications access with ATA chapter-organized documentation","Engineering inquiry submission with SLA-tracked response","Fleet management portal with aircraft-specific service history","Proactive service bulletin and airworthiness directive notifications"], vendors: "SAP, IFS, Salesforce, custom portals", risk: "Service bulletins not reaching affected operators in time for compliance",
        stack: [{ name: "IFS", role: "Aerospace & Defense Platform", why: "Purpose-built for aerospace MRO. Parts logistics, work package management, and fleet tracking. The platform that connects support to operations for aerospace manufacturers.", href: "/vendors" }],
        pitfall: "Airworthiness directives (ADs) from FAA/EASA are mandatory compliance actions. OEM service bulletins (SBs) may be recommended but not mandatory, unless referenced by an AD. Your support team must clearly distinguish between mandatory ADs and recommended SBs in every communication. Mixing them up creates operator confusion, either unnecessary grounding (treating an SB as mandatory) or compliance violation (treating an AD as optional)."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Parts cross-reference bots identifying part numbers by description or application","Service bulletin applicability bots by aircraft model and serial number","Warranty eligibility bots with flight-hour and calendar-based verification","Documentation search bots within structured technical publications","Basic troubleshooting bots for common line maintenance issues"], vendors: "Custom, limited commercial", risk: "Bot recommending a part that doesn't have current airworthiness certification",
        stack: [{ name: "Custom / limited AI", role: "Aerospace AI", why: "Aerospace AI must be conservative: an incorrect part identification, wrong torque value, or outdated certification could affect flight safety. AI for parts cross-reference and documentation search; human for all engineering decisions and airworthiness determinations.", href: "/vendors" }],
        pitfall: "Every aerospace part has a traceability chain: manufacturer, batch, certification, and airworthiness status. A parts lookup bot that returns a part number without verifying current airworthiness certification could lead to installation of a part that's been subject to an AD or inspection requirement. AI in aerospace must always return parts data with certification status attached, never a bare part number."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FAA/EASA airworthiness compliance for parts and technical data","ITAR/EAR export control for defense and dual-use aerospace products","AS9100 quality management system compliance","FAA Part 21/145 repair station compliance for MRO operations","Traceability and documentation requirements for every part and repair"], vendors: "FAA/EASA compliance, ITAR, AS9100", risk: "ITAR-controlled data shared with unauthorized party creating federal violation",
        stack: [{ name: "ERP export control", role: "ITAR/EAR Compliance", why: "Automated export screening for every parts order and technical data request. In aerospace, willful ITAR violations are federal crimes (22 U.S.C. 2778(c)). Automate screening: do not rely on agents to know which parts and data are controlled.", href: "/vendors" }],
        pitfall: "ITAR in aerospace is absolute. A support agent who emails a wiring diagram for a military aircraft system to a foreign operator, even an allied NATO country, without an export license has violated ITAR. Screen every technical data request against ITAR/EAR control lists. Implement system-level controls that prevent export of controlled data, not just training that asks agents to remember the rules."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["AOG parts fulfillment workflow: locate, certify, ship, track","Warranty claim workflow with flight-hour and usage verification","Service bulletin compliance tracking and parts kit distribution","Engineering change order notification and retrofit coordination","Rotable pool management: exchange, repair, and certification workflow"], vendors: "SAP, IFS, Oracle, AMOS", risk: "AOG part shipped without current airworthiness certification documentation",
        stack: [{ name: "SAP (Aerospace & Defense)", role: "ERP", why: "Parts logistics, warranty management, and order fulfillment for aerospace. Handles the unique requirements of serialized, traceable, certified parts that no generic ERP supports.", href: "/vendors" }, { name: "IFS", role: "MRO & Fleet", why: "Maintenance, repair, and overhaul management. Work packages, task cards, and fleet tracking. Connects support to the maintenance planning that operators depend on.", href: "/vendors" }],
        pitfall: "Aerospace parts logistics are uniquely complex: every part is serialized, every transaction requires traceability documentation, and every part must have current airworthiness certification. An AOG parts shipment that arrives without the correct FAA Form 8130-3 (Authorized Release Certificate) can't be installed: the operator is still grounded even though the part is physically present. Ensure certification documentation ships with the part, not in a separate follow-up email."
      },
      { layer: 1, name: "Data Access", capabilities: ["Parts catalog with configuration, interchangeability, and certification","Warranty database with flight-hour and calendar tracking by serial number","Fleet data: operator aircraft, configuration, and service history","Technical publications: AMM, CMM, IPC organized by ATA chapter","Regulatory database: ADs, SBs, and compliance status by aircraft"], vendors: "SAP, IFS, AMOS, Flatirons", risk: "Parts catalog showing superseded part numbers without the current replacement",
        stack: [{ name: "SAP", role: "Parts & Logistics Data", why: "Serialized parts inventory, certification status, and logistics tracking. The data foundation for every AOG response, is the part in stock, is it certified, and how fast can we ship it?", href: "/vendors" }, { name: "Flatirons Solutions", role: "Technical Publications", why: "S1000D and ATA iSpec 2200 technical publications management. When a customer asks 'what's the torque spec for this bolt on a 787 wing root?' the answer is in the structured technical data.", href: "/vendors" }],
        pitfall: "Aerospace parts catalogs contain superseded, obsoleted, and interchangeable part numbers: a single component might carry several part numbers across revisions. An agent quoting a superseded part number creates an order that can't be fulfilled with current production parts. Build part number resolution logic that always returns the current, in-production part number with full interchangeability documentation."
      },
    ],
  },

  "food-beverage": {
    name: "Food & Beverage Manufacturing", parent: "Manufacturing & Automotive",
    tagline: "Product quality complaints, allergen inquiries, recalls, retailer support, and consumer hotline.",
    intro: "Food and beverage manufacturer contact centers handle consumer complaints, retailer inquiries, and, most critically, food safety events including allergen contamination, foreign objects, and pathogen contamination. The CX challenge is treating every quality complaint as a potential food safety signal while managing routine consumer feedback and retailer logistics.",
    kpis: [
      { metric: "AHT", avg: "[[mfg.sv.food-beverage.aht]]", note: "Routine complaints are focused; quality events need detailed capture" },
      { metric: "FCR", avg: "[[mfg.sv.food-beverage.fcr]]", note: "Many complaints resolve with a coupon, replacement, or explanation" },
      { metric: "CSAT", avg: "[[mfg.sv.food-beverage.csat]]", note: "Moves with empathy and speed in complaint handling" },
      { metric: "Safety Escalation", avg: "[[mfg.sv.food-beverage.safety]]", note: "Share of complaints that trigger a food safety investigation" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Product complaint trending by SKU, production facility, and lot code","Food safety signal detection: clustering of similar complaints","Consumer sentiment by product, flavor, and packaging change","Retailer complaint analytics by retail partner and region","Recall effectiveness: notification reach and product recovery rate"], vendors: "NICE, Medallia, custom QA systems", risk: "Food safety signal buried in routine complaint volume",
        stack: [{ name: "NICE CXone", role: "QA & Trending", why: "Complaint trending that detects when multiple consumers report the same issue (off taste, illness, foreign object) from the same lot code. This is the early warning system for food safety events.", href: "/vendors/nice-cxone" }],
        pitfall: "Food safety events start as individual consumer complaints. Three people calling separately about 'funny-tasting yogurt' from different stores in different states might be three unrelated quality variations, or they might be the first signal of a pathogen contamination affecting an entire production run. Build automated complaint clustering by lot code and symptom. Set an automatic trigger, such as [[mfg.fb.cluster]], that opens a food safety investigation."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Food safety priority routing for illness reports and foreign objects","Consumer complaint vs retailer inquiry routing","Product quality routing by category and production facility","Media inquiry routing during recall events","Allergen inquiry routing to trained food safety specialists"], vendors: "Genesys, NICE CXone, Five9", risk: "Consumer reporting illness reaching a general complaint agent instead of food safety",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Keyword detection for food safety language, 'sick,' 'hospital,' 'allergic reaction,' 'glass,' 'metal', routes immediately to food safety team. Ensures safety-critical complaints never wait in a general queue.", href: "/vendors/nice-cxone" }],
        pitfall: "Every consumer complaint must be screened for food safety signals during intake, not after classification. An agent who classifies 'I found something hard in my cereal' as 'product quality - texture' instead of 'food safety - foreign object' has delayed a potential safety investigation. Train all intake agents to ask: 'Did you or anyone become ill?' and 'Can you describe what you found?' before classifying."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Consumer complaint portal with product and lot code capture","Recall notification via website, social media, and retailer communication","Coupon and replacement product fulfillment for resolved complaints","Allergen information portal with ingredient and production facility data","Social media management for viral product quality complaints"], vendors: "Sprinklr, Zendesk, custom consumer portals", risk: "Recall notification not reaching consumers who don't follow the brand on social media",
        stack: [{ name: "Sprinklr", role: "Social + Consumer", why: "Food quality complaints often go viral on social media before the consumer calls the hotline. A video showing a foreign object in a product can spread widely within hours. Sprinklr detects, escalates, and manages the response.", href: "/vendors/digital-engagement" }],
        pitfall: "Food recall notifications depend heavily on retailers removing products from shelves and posting in-store notices, but the manufacturer can't control retail execution. Supplement retailer-dependent recall communication with direct consumer notification (email, SMS, social media), FDA recall alert, and media outreach. More channels reach more of the consumers who bought the product."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Product information bots (ingredients, allergens, nutrition, sourcing)","Complaint intake bots with lot code and purchase location capture","Coupon and replacement fulfillment bots","Store locator and product finder bots","FAQ bots covering dietary questions, certifications, and sourcing"], vendors: "Ada, Zendesk bots, custom", risk: "Bot providing incorrect allergen information creating health risk",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles product information, complaint intake with lot code capture, and coupon fulfillment. Routes all illness reports and allergen concerns to human food safety specialists immediately.", href: "/vendors/iva" }],
        pitfall: "Allergen information bots must be updated in real-time when formulations change. A bot that says 'this product does not contain tree nuts' when the formulation was recently changed to include almond flavoring could contribute to an allergic reaction. Build a direct data feed from product formulation systems to the bot's allergen database with change alerts and human review before the bot starts serving new allergen data."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FDA/FSIS compliance for food safety complaint documentation","FSMA (Food Safety Modernization Act) preventive controls compliance","Allergen labeling compliance (FALCPA and state requirements)","Reportable Food Registry submissions for foods likely to cause serious harm","Class I/II/III recall classification and execution compliance"], vendors: "FDA compliance, FSMA, FALCPA", risk: "Possible reportable event not escalated to regulatory affairs in time",
        stack: [{ name: "FDA/FSIS compliance systems", role: "Regulatory", why: "Some consumer complaints can make a food reportable to FDA, with a short clock. Contact center agents must recognize possible reportable events and escalate immediately to regulatory affairs.", href: "/vendors" }],
        pitfall: "Once a manufacturer determines that a food is reportable (in the statute's words, \"a reasonable probability\" of \"serious adverse health consequences or death\", 21 U.S.C. 350f), it must report to FDA's Reportable Food Registry within [[mfg.fda.rfr]]. A dietary supplement maker must send FDA a serious adverse event report within [[mfg.fda.supplement]] of receiving it. Both clocks depend on what the contact center hears first: an agent who logs a hospitalization on Monday and escalates on Friday has spent days the regulatory team needed. Build immediate escalation with automated regulatory clock tracking."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Consumer complaint intake workflow with product retention request","Food safety investigation workflow from complaint to root cause","Recall execution workflow: notification, retailer communication, and product recovery","Coupon and product replacement fulfillment workflow","Adverse event reporting workflow to FDA/FSIS with timeline tracking"], vendors: "SAP, Oracle, custom QMS, Salesforce", risk: "Consumer disposing of product before lot code is captured: evidence lost",
        stack: [{ name: "SAP / Oracle QMS", role: "Quality Management", why: "Complaint intake, investigation tracking, and CAPA (Corrective and Preventive Action) management. The system that connects a consumer complaint to a production investigation to a process improvement.", href: "/vendors" }],
        pitfall: "The most important step in food safety complaint handling is asking the consumer to retain the product for testing. A consumer who throws away the 'funny-tasting yogurt' before the manufacturer can test it leaves the investigation without physical evidence. Train agents to say: 'Please keep the remaining product and packaging: we'd like to test it' on every quality complaint, not just the ones that sound serious."
      },
      { layer: 1, name: "Data Access", capabilities: ["Product master data: ingredients, allergens, lot codes, and production facilities","Quality management system: complaints, investigations, and CAPA","Production data: lot traceability from ingredients through packaging","Retailer and distribution data: where products were shipped by lot code","Consumer database: complaint history and product feedback"], vendors: "SAP, Oracle, TraceGains, FoodLogiQ", risk: "Lot code traceability gap preventing identification of affected product scope",
        stack: [{ name: "SAP S/4HANA", role: "ERP & Traceability", why: "Lot code traceability from raw ingredient through finished product through retail distribution. When a food safety event occurs, the first question is 'which lots are affected and where did they ship?' SAP answers both.", href: "/vendors" }, { name: "TraceGains / FoodLogiQ", role: "Supply Chain Traceability", why: "Ingredient and supplier traceability. When a food safety event involves a contaminated ingredient, traceability identifies every finished product that used that ingredient from that supplier lot.", href: "/vendors" }],
        pitfall: "FDA's Food Traceability Rule (FSMA section 204) requires additional traceability records for foods on the Food Traceability List. Congress directed FDA not to enforce it before [[mfg.fda.ftr]], and FDA says it will comply. Agents handling complaints about these foods should still capture Key Data Elements (KDEs) such as lot codes, product descriptions, and purchase locations, since those records are what an investigation needs. Align complaint intake forms with the rule now."
      },
    ],
  },
};

export const getManufacturingSubVertical = (slug) => (Object.prototype.hasOwnProperty.call(manufacturingSubVerticals, slug) ? manufacturingSubVerticals[slug] : undefined);
export const getAllManufacturingSubVerticalSlugs = () => Object.keys(manufacturingSubVerticals);
