export const telecomSubVerticals = {
  "mobile-wireless": {
    name: "Mobile / Wireless Carriers", parent: "Telecommunications",
    tagline: "Plan changes, billing disputes, device support, network coverage, and retention.",
    intro: "Wireless carrier contact centers operate at subscriber scale in a high-churn market. Billing questions, device support, plan changes, network complaints, and retention calls make up the contact mix. Every interaction either raises churn risk or opens a revenue opportunity, and the operation is built around telling the two apart fast.",
    kpis: [
      { metric: "AHT", avg: "[[tel.sv.mobile-wireless.aht]]", note: "Driven by billing explanations and retention negotiations" },
      { metric: "FCR", avg: "[[tel.sv.mobile-wireless.fcr]]", note: "Multi-system billing, network, and device issues often need a follow-up" },
      { metric: "CSAT", avg: "[[tel.sv.mobile-wireless.csat]]", note: "Moves with billing frustration and network complaints" },
      { metric: "Containment", avg: "[[tel.sv.mobile-wireless.containment]]", note: "Balance checks and plan lookups can be automated; billing disputes need a person" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance",
        capabilities: ["Churn prediction models correlating service interactions with disconnection risk","NPS tracking by plan type, tenure, and interaction reason","Billing complaint root cause analytics by charge category","Network experience correlation: CX data mapped to network quality data","Retention offer effectiveness with save rate and cost-per-save tracking"],
        vendors: "NICE Nexidia, Verint, Medallia, Qualtrics", risk: "Churn climbing without visibility into leading indicators",
        stack: [
          { name: "NICE Nexidia", role: "Interaction Analytics", why: "Analyzes interactions at scale to identify churn signals, billing confusion patterns, and agent behaviors that predict retention success. Offers telecom-specific models.", href: "/vendors/analytics" },
          { name: "Medallia", role: "CX Platform", why: "Connects NPS and CSAT to operational data: network quality, billing events, and tenure. Identifies which customer segments are most at risk and why.", href: "/vendors/analytics" },
        ],
        pitfall: "Carriers track churn rate but not the causes behind it. [[tel.ex.churn-mix]] Track churn drivers at the interaction level: the retention agent who handles the cancel call knows why, but that data rarely makes it into a structured field."
      },
      { layer: 6, name: "Routing & Orchestration",
        capabilities: ["Intent-based routing separating billing, tech support, sales, retention, and fraud","Churn risk scoring routing high-risk callers to retention-skilled agents","Device-specific routing matching callers to agents trained on their device","Network outage IVR intercept preventing redundant calls","MVNO vs postpaid vs prepaid routing with separate service models"],
        vendors: "Genesys, NICE CXone, Avaya, Cisco", risk: "Retention-eligible callers reaching general agents without save authority",
        stack: [
          { name: "Genesys Cloud", role: "Primary CCaaS", why: "Predictive routing using AI to match caller intent, churn risk, and lifetime value to the best-fit agent. Built for very large carrier operations.", href: "/vendors/genesys" },
          { name: "NICE CXone", role: "Primary CCaaS", why: "Combined routing + WEM for large carrier operations. Native workforce management handles scheduling complexity across billing, tech support, and retention teams.", href: "/vendors/nice-cxone" },
        ],
        pitfall: "Outage IVR intercepts are a high-return routing investment for carriers. When a cell tower goes down, subscribers in the area call at once. Without an intercept that says 'we know about a service disruption in your area and expect service back this afternoon,' every one of those calls reaches an agent who can only confirm the outage. Automate outage detection → geographic caller matching → IVR intercept. This one workflow can remove [[tel.outage.share]]."
      },
      { layer: 5, name: "Conversation Management",
        capabilities: ["In-app support integrated with the carrier's mobile app","Social media management for network complaints (Twitter/X, Reddit)","Proactive outage notifications via push, SMS, and email","Digital bill explanation tools with interactive charge breakdown","Device setup and troubleshooting via chat with screen sharing"],
        vendors: "LivePerson, Sprinklr, Ada, Glia", risk: "Network complaints going viral on social without real-time response",
        stack: [
          { name: "Sprinklr", role: "Social + Digital CX", why: "Unified social media management and customer care. Carriers face large volumes of social mentions: Sprinklr surfaces the ones that need action, routes to the right team, and tracks resolution.", href: "/vendors/digital-engagement" },
          { name: "LivePerson", role: "Conversational AI + Messaging", why: "Conversational AI and async messaging let subscribers manage billing and plan changes without calling. Supports Apple Messages for Business.", href: "/vendors/digital-engagement" },
        ],
        pitfall: "Carriers add digital channels (chat, in-app) to reduce call volume but don't give digital agents the same system access as phone agents. If a chat agent can look up billing but can't apply credits, process plan changes, or initiate device replacements, the customer hits a wall and calls anyway. Digital channel agents need full transactional authority, not read-only access."
      },
      { layer: 4, name: "Reasoning & Planning",
        capabilities: ["Bill explanation bots that walk through each line item with context","Plan comparison bots recommending the best plan based on usage","Outage status bots with real-time network data and restoration ETA","Device troubleshooting bots with model-specific guidance","Balance and payment bots with payment arrangement capability"],
        vendors: "Cognigy, Kore.ai, Google CCAI, LivePerson AI", risk: "Bot explaining a bill the customer doesn't believe is correct",
        stack: [
          { name: "Kore.ai", role: "Enterprise IVA", why: "Deep telecom domain coverage: billing, plan changes, outage status, device troubleshooting, and payments. Handles the multi-turn conversations telecom requires.", href: "/vendors/iva" },
          { name: "Google CCAI", role: "AI Platform", why: "Dialogflow CX for intent detection + Agent Assist for real-time agent guidance. Best for carriers with GCP infrastructure and engineering teams.", href: "/vendors/iva" },
        ],
        pitfall: "Bill explanation bots are in high demand in telecom and carry real risk. [[tel.ex.bill]] The bot can explain what the charges are; it cannot explain why they're wrong. Build an escalation path for 'this bill is incorrect' that bypasses the explanation loop and routes to an agent with billing authority."
      },
      { layer: 3, name: "Policy & Guardrails",
        capabilities: ["CPNI (Customer Proprietary Network Information) compliance for all channels","FCC regulatory requirements for service quality and billing transparency","Identity verification preventing SIM swap fraud and account takeover","TCPA consent management for marketing and collections communications","State-specific consumer protection compliance"],
        vendors: "Pindrop, TransUnion, T-Mobile SIM Shield, Syniverse", risk: "SIM swap fraud creating account takeover and regulatory exposure",
        stack: [
          { name: "Pindrop", role: "Voice Auth & Fraud", why: "Passive voice authentication + fraud detection. Detects SIM swap attempts, social engineering, and account takeover in real-time. Relevant for wireless carriers, where SIM changes now carry their own FCC rule.", href: "/vendors/acd-routing" },
          { name: "TransUnion (TruValidate)", role: "Identity Verification", why: "Device-based identity intelligence. Verifies the subscriber's identity using the device they're calling from, reducing reliance on knowledge-based authentication that social engineers defeat.", href: "/vendors" },
        ],
        pitfall: "SIM swap fraud turns the contact center into an attack path. An attacker calls the carrier, impersonates the subscriber, transfers the phone number to a new SIM, and uses it to bypass 2FA on banking and crypto accounts. FCC rules for SIM changes ([[tel.fcc.simswap]]) require secure authentication that does not rely on biographical or account details, keep agents from seeing CPNI until the caller is authenticated, and require staff training on SIM swap fraud; the rule's compliance date is still to be set. Implement device-based identity verification (Pindrop, TransUnion) that doesn't rely on the caller knowing the account holder's mother's maiden name."
      },
      { layer: 2, name: "Workflow Execution",
        capabilities: ["Service activation and provisioning workflow with order fallout management","Plan change workflow with prorated billing and feature migration","Device upgrade workflow with trade-in, financing, and shipping coordination","Retention save workflow with tiered offer authority and approval logic","Trouble ticket workflow routing from contact center to NOC to field ops"],
        vendors: "Amdocs, CSG, Pega, ServiceNow Telecom", risk: "Order fallout: provisioning failures creating 'service not working' calls",
        stack: [
          { name: "Amdocs", role: "BSS/OSS", why: "A major BSS vendor for large carriers. Billing, CRM, ordering, and provisioning. Your CX stack integrates with Amdocs, not the other way around. Everything the agent can do is constrained by what Amdocs allows.", href: "/vendors" },
          { name: "CSG (Ascendon)", role: "BSS Platform", why: "Billing, revenue management, and customer management for carriers. Strong in cable/broadband. Growing in wireless with cloud-native Ascendon platform.", href: "/vendors" },
          { name: "ServiceNow Telecom", role: "Service Operations", why: "Trouble ticket management connecting contact center → NOC → field ops. Order management and service assurance workflows. Bridges the gap between CX and network operations.", href: "/vendors" },
        ],
        pitfall: "Order fallout is a hidden driver of telecom contact volume. A subscriber orders a plan change; the order enters the BSS; the provisioning system fails to activate a feature; the subscriber discovers the next day that their data isn't working. The contact center gets the call, but the root cause is a provisioning failure the agent can't see or fix. Build order fallout monitoring that proactively detects failed provisioning and resolves it before the customer calls."
      },
      { layer: 1, name: "Data Access",
        capabilities: ["BSS integration: billing, subscriber profile, plan details, usage data","OSS integration: network inventory, service status, trouble ticket history","CRM with complete subscriber view across all product lines","Device management system: IMEI, warranty, installment balance, trade-in status","Network quality data: coverage maps, tower status, congestion metrics"],
        vendors: "Amdocs, CSG, Netcracker, Salesforce Communications Cloud", risk: "Agent toggling between many systems to answer one billing question",
        stack: [
          { name: "Amdocs CES", role: "BSS", why: "Customer engagement suite connecting billing, ordering, and CRM. The data foundation for carrier CX. Real-time APIs are improving but many implementations still rely on batch.", href: "/vendors" },
          { name: "Salesforce Communications Cloud", role: "Industry CRM", why: "Telecom-specific data model with subscriber, account, service, and order objects. The CRM layer that unifies BSS/OSS data into an agent-friendly view.", href: "/vendors/ccaas" },
          { name: "Netcracker (NEC)", role: "BSS/OSS", why: "Full-stack BSS/OSS for carriers. Revenue management, partner management, and service fulfillment. Alternative to Amdocs for carriers evaluating modernization.", href: "/vendors" },
        ],
        pitfall: "The telecom agent desktop problem is severe. A wireless carrier agent may need: Amdocs for billing, a CRM for interaction history, a network tool for coverage/outage, a device management system for IMEI/warranty, and an order system for provisioning status, five systems, five logins, five interfaces. Often the investment that matters most is a unified agent desktop that abstracts the BSS/OSS complexity into a single view, ahead of a new CCaaS platform. Salesforce Communications Cloud attempts this but requires deep integration work."
      },
    ],
  },

  "broadband-isp": {
    name: "Broadband / ISP", parent: "Telecommunications",
    tagline: "Service activation, speed complaints, outage management, billing, and technical troubleshooting.",
    intro: "ISP contact centers handle customers who view internet service as a utility: they expect it to work, and they call only when it doesn't. Every inbound call represents a failure: a failure of the network, the billing system, the self-service tools, or the installation process. The CX challenge is resolving technical issues remotely while managing the frustration of customers who feel they're paying for a service that isn't delivered.",
    kpis: [
      { metric: "AHT", avg: "[[tel.sv.broadband-isp.aht]]", note: "Driven by guided technical troubleshooting and escalation" },
      { metric: "FCR", avg: "[[tel.sv.broadband-isp.fcr]]", note: "Speed issues and outages often need dispatch or a network-side fix" },
      { metric: "CSAT", avg: "[[tel.sv.broadband-isp.csat]]", note: "Moves with the service problems that prompt the call" },
      { metric: "Containment", avg: "[[tel.sv.broadband-isp.containment]]", note: "Technical issues need human diagnosis; billing can be automated" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Speed test data correlation with complaint volume and NPS","Technician dispatch analytics: repeat visits, first-visit resolution, and customer rating","Outage impact analytics: affected subscribers, duration, and resulting contact volume","Churn prediction correlated to service quality metrics and complaint history","Installation experience analytics: time to first resolution for new subscribers"], vendors: "NICE, Verint, Calix", risk: "Network quality issues showing up as contact center problems without network data correlation",
        stack: [{ name: "Calix", role: "Subscriber Analytics", why: "Subscriber experience analytics purpose-built for broadband. Correlates network performance data (latency, packet loss, speed) with subscriber behavior and support contacts. ISP-specific, not generic CX analytics.", href: "/vendors" }, { name: "NICE CXone", role: "Contact Center Analytics", why: "Interaction analytics connecting call reasons to network events. When many subscribers in one zip code call about slow speeds, NICE can correlate with network data to identify the root cause.", href: "/vendors/nice-cxone" }],
        pitfall: "ISPs track contact center metrics (AHT, FCR, CSAT) and network metrics (uptime, speed, latency) in separate systems owned by separate teams. The contact center team knows complaints are rising; the network team doesn't see a problem because their monitoring shows uptime within target. The issue: [[tel.ex.uptime]] That is enough to generate a wave of calls. Connect network performance data to CX data in real-time."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Technical tier routing: Tier 1 (reboot/reset) → Tier 2 (diagnostic) → Tier 3 (NOC)","Outage IVR intercept with proactive notification before caller reaches queue","New subscriber priority routing during the first weeks after installation","Dispatch routing coordinating field technician scheduling","Retention routing for customers threatening to switch to competitor"], vendors: "Genesys, NICE CXone, Calix", risk: "Speed complaints reaching Tier 1 staff who can only suggest rebooting the modem",
        stack: [{ name: "Genesys Cloud", role: "Primary CCaaS", why: "Multi-tier routing for ISP operations. Predictive routing can assess whether the caller's issue is likely Tier 1 (solvable by agent) or Tier 2+ (requires escalation) based on caller history and network data.", href: "/vendors/genesys" }],
        pitfall: "ISPs route speed complaints to Tier 1 staff whose only tools are 'have you tried restarting your modem?' and 'let me run a speed test from our end.' If the issue is network-side (congestion, line quality, node capacity), Tier 1 spends time on scripted steps before escalating. Pre-screen speed complaints with automated diagnostics: if the subscriber's modem is reporting normal upstream/downstream but the customer reports slow speeds, skip Tier 1 and route directly to Tier 2."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Proactive outage notifications via SMS, email, and app push","Interactive speed test tools accessible during support interactions","Technician dispatch scheduling with real-time availability windows","Installation tracking with milestone notifications","Self-service modem diagnostics and reset tools"], vendors: "Calix CommandIQ, LivePerson, Ada", risk: "Customers discovering outages by losing service rather than receiving proactive notification",
        stack: [{ name: "Calix CommandIQ", role: "Subscriber Self-Service", why: "Mobile app for broadband subscribers. Self-service network diagnostics, speed tests, device management, and parental controls. Reduces inbound call volume by enabling subscribers to troubleshoot before calling.", href: "/vendors" }],
        pitfall: "ISPs deploy speed test tools but show the customer the speed between the modem and the ISP, not the speed to their device. [[tel.ex.wifi]] Provide a diagnostic that shows both: ISP speed to modem AND WiFi speed to device. This prevents unnecessary truck rolls and Tier 2 escalations."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Modem diagnostics bots pulling real-time signal levels and connectivity","Outage status bots with area-specific restoration ETAs","Bill explanation bots with promotional expiration transparency","Speed test bots comparing provisioned vs actual performance","Appointment scheduling bots for installation and service visits"], vendors: "Cognigy, Ada, Calix AI", risk: "Bot suggesting modem restart when the issue is a network-wide outage",
        stack: [{ name: "Ada", role: "AI Customer Service", why: "Handles billing FAQ, outage status, and appointment scheduling. Integrates with ISP systems for real-time modem diagnostics. Routes technical issues beyond basic troubleshooting to agents with context.", href: "/vendors/iva" }],
        pitfall: "An ISP bot must check for known outages BEFORE starting troubleshooting. If a customer messages 'my internet is down' and the bot says 'let's try restarting your modem' when there's a known outage in their area, the bot has wasted the customer's time and made them angrier. Step 1 for any connectivity bot: check outage database by subscriber location. If outage exists → provide ETA and skip troubleshooting. If no outage → begin diagnostics."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FCC broadband labeling compliance for speed and pricing transparency","CPNI protection for subscriber data across all channels","State net neutrality compliance monitoring (where applicable)","State-specific consumer protection for service level commitments","Data privacy for usage and browsing data"], vendors: "ISP-specific compliance, Pindrop", risk: "FCC broadband label non-compliance creating regulatory action",
        stack: [{ name: "Pindrop", role: "Voice Authentication", why: "Subscriber verification without knowledge-based authentication. Especially important as ISP accounts are targeted for identity theft and unauthorized service changes.", href: "/vendors/acd-routing" }],
        pitfall: "FCC broadband consumer labels ([[tel.fcc.labels]]) require ISPs to show prices, fees, typical speed, and typical latency at every point of sale, and the rule counts sales over the phone as a point of sale. An FCC order published in [[tel.fcc.labels.2026]] changes how label information may be given over the phone; its change to section 8.1(a) waits on an effective date. Train contact center agents on the labels so they can reference them during billing and speed complaints. If an agent quotes a speed or price that differs from the broadband label, you've created a consumer protection issue."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Service activation workflow with modem provisioning and speed validation","Trouble ticket workflow routing from contact center to NOC to field tech","Technician dispatch workflow with scheduling, routing, and completion confirmation","Service upgrade workflow with modem compatibility check and provisioning","Disconnect workflow with retention offer, equipment return, and final billing"], vendors: "CSG, Amdocs, ServiceNow, Salesforce", risk: "Trouble tickets closed without resolution: customer calls back",
        stack: [{ name: "ServiceNow Telecom", role: "Service Operations", why: "Trouble ticket lifecycle management: creation, NOC assignment, field dispatch, resolution, and confirmation. Connects contact center tickets to network operations in one workflow.", href: "/vendors" }],
        pitfall: "ISP trouble tickets have a high 'closed without resolution' rate: the NOC marks the ticket resolved because network metrics look normal, but the subscriber's issue persists. Implement a customer confirmation step before closing any trouble ticket: 'We believe your issue has been resolved. Please confirm your service is working properly.' Without this, repeat calls on the same issue stay high."
      },
      { layer: 1, name: "Data Access", capabilities: ["BSS integration: billing, subscriber account, plan details, promotional status","Network management system: modem signal levels, speed, uptime, errors","Field service management: technician schedules, dispatch status, work orders","Provisioning system: service orders, activation status, fallout tracking","Geographic/plant data: service area maps, node capacity, planned maintenance"], vendors: "CSG, Calix, Salesforce Communications Cloud, NetCracker", risk: "Agent seeing billing data but not network data, can't diagnose technical issues",
        stack: [{ name: "Calix Cloud", role: "Subscriber Network Data", why: "Real-time visibility into each subscriber's modem/ONT performance. Signal levels, speed, WiFi coverage, and connected devices. The agent sees what the network sees: no guessing.", href: "/vendors" }, { name: "CSG", role: "BSS", why: "Billing, subscriber management, and revenue assurance for broadband providers. The financial data source for every billing inquiry.", href: "/vendors" }],
        pitfall: "ISP agents face the classic telecom dual-screen problem: billing data in the BSS and network data in the NMS. A subscriber calling about 'slow internet' needs the agent to check both: is the account in good standing (BSS) and is the modem reporting normal signal levels (NMS)? If the agent can only see one, they either miss a billing-related throttle or miss a legitimate network issue. Unify BSS and NMS data in the agent desktop."
      },
    ],
  },

  "cable-tv": {
    name: "Cable & Pay TV", parent: "Telecommunications",
    tagline: "Package management, billing, equipment, content disputes, and cord-cutting retention.",
    intro: "Cable and pay TV contact centers operate in a declining market. Every interaction is colored by the reality that the customer has alternatives, streaming services that cost less and don't require a call to cancel. The CX challenge is making the service valuable enough to retain and the experience easy enough that customers don't leave out of frustration with the process.",
    kpis: [
      { metric: "AHT", avg: "[[tel.sv.cable-tv.aht]]", note: "Driven by package negotiations and retention conversations" },
      { metric: "FCR", avg: "[[tel.sv.cable-tv.fcr]]", note: "Equipment and billing issues often need a follow-up" },
      { metric: "CSAT", avg: "[[tel.sv.cable-tv.csat]]", note: "Moves with pricing and content changes" },
      { metric: "Containment", avg: "[[tel.sv.cable-tv.containment]]", note: "Package lookups and payments can be automated; retention and disputes need a person" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Cord-cutting risk prediction correlated to usage decline and competitive offers","Package downgrade analytics tracking revenue erosion by segment","Content dispute tracking: channel changes, blackouts, and sports package issues","Retention offer ROI by customer segment, tenure, and package type","Equipment return analytics tracking unreturned equipment and charge disputes"], vendors: "NICE, Verint, Qualtrics", risk: "Revenue erosion from package downgrades invisible until quarterly reports",
        stack: [{ name: "NICE CXone", role: "Analytics & WEM", why: "Combined analytics and workforce management for cable operations managing declining volume while maintaining service levels. Right-sizes the workforce as call volume shifts.", href: "/vendors/nice-cxone" }],
        pitfall: "Cable companies track subscriber count but not subscriber value trajectory. [[tel.ex.cable-downgrade]] Track revenue-per-subscriber trends alongside subscriber counts to see the real picture of your business health."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Retention priority routing for cancel-intent calls with save offers","Equipment troubleshooting routing by device type (set-top box, DVR, modem)","Billing dispute routing separating simple inquiries from complex disputes","Sports blackout and content complaint routing during live events","New subscriber onboarding routing with a white-glove experience in the first months"], vendors: "Genesys, NICE CXone, Avaya", risk: "Cord-cutting callers reaching agents without retention authority",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Intent detection identifies cord-cutting callers before they reach an agent. Routes to retention team with subscriber value and competitive offers visible.", href: "/vendors/genesys" }],
        pitfall: "Cancellation rules for cable come mainly from state law and franchise agreements, so check the ones that apply to you. What the FCC's cable customer service standards do set, and a franchise authority can enforce, is phone access: calls answered within [[tel.fcc.cable.answer]] under normal conditions. Within those rules you can offer retention before the cancel flow. Implement a 'before you cancel, let us review your options' step that presents a tailored offer based on the subscriber's usage and tenure. The offer must be genuine, not a delay tactic, or you create regulatory and reputational risk."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Interactive channel lineup and package comparison tools","Equipment self-service for remote diagnostics and reboot","Proactive notifications for channel changes, pricing updates, and outages","Self-service downgrade and cancel flows meeting state and franchise requirements","Content guide and recommendation based on viewing history"], vendors: "LivePerson, Ada, Sprinklr", risk: "Channel lineup changes communicated poorly, generating complaint spikes",
        stack: [{ name: "LivePerson", role: "Messaging & AI", why: "Async messaging for package management and billing questions. Subscribers can browse channel lineups and compare packages within the chat. Reduces call volume for routine account management.", href: "/vendors/digital-engagement" }],
        pitfall: "Channel lineup changes (dropping a network, adding a sports tier, renegotiating content deals) are a frequent source of subscriber anger. Proactive notification isn't enough: you need a self-service path for affected subscribers to see their options (downgrade, switch packages, get a credit) before they call. If the first time a subscriber learns about a channel change is when they can't find their favorite show, you've already lost the interaction."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Package comparison bots recommending plans based on viewing habits","Equipment troubleshooting bots with remote diagnostic capability","Bill explanation bots with promotional pricing timeline visibility","Outage status bots with area-specific restoration information","DVR and recording management bots"], vendors: "Cognigy, Ada, CSG AI", risk: "Bot recommending a more expensive package when the customer wants to downgrade",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles billing FAQ, equipment reset, and outage status. Package comparison with transparent pricing. Routes retention conversations to human agents with full context.", href: "/vendors/iva" }],
        pitfall: "Cable bots must never upsell a customer who is calling to downgrade or cancel. A subscriber saying 'I want to reduce my package' and receiving a bot response of 'have you considered our Premium package with more channels?' is insulting. Intent detection must distinguish between browse (open to suggestions) and reduce (wants less, not more). Route reduce-intent to a human with downgrade and save offers."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FCC cable customer service standards and state cancellation rules","Subscriber privacy protection for viewing and usage data","Franchise agreement compliance for local programming requirements","Equipment return tracking with fee dispute prevention","Promotional pricing transparency with expiration date visibility"], vendors: "CSG compliance, FCC regulatory", risk: "FCC complaints about cancellation difficulty creating regulatory scrutiny",
        stack: [{ name: "CSG", role: "Billing & Compliance", why: "Cable-specific BSS with promotional pricing management, equipment tracking, and regulatory compliance. Manages the complexity of triple-play billing across video, data, and voice.", href: "/vendors" }],
        pitfall: "Promotional pricing that expires and jumps sharply is a major driver of cable complaints and churn. Your billing system knows when the promo expires, but cable companies often don't proactively notify the customer or offer a new promo before the price jumps. Reach out [[tel.cable.promo.lead]] before expiration with a retention offer, and compare the cost of the discount with the value of the subscriber you would lose."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Package change workflow with prorated billing and channel activation","Equipment swap workflow with shipping, activation, and return tracking","Installation scheduling workflow with technician assignment and window confirmation","Retention workflow with tiered save offers and approval escalation","Service disconnect workflow with equipment return and final billing"], vendors: "CSG, Amdocs, Pega, ServiceNow", risk: "Equipment return tracking failures creating wrongful charge disputes",
        stack: [{ name: "CSG", role: "BSS/Order Management", why: "Widely used for cable billing and order management. Package changes, equipment tracking, and service provisioning. The workflow engine that determines what agents can actually do.", href: "/vendors" }],
        pitfall: "Equipment return tracking is a highly avoidable CX failure. [[tel.ex.equipment]] The local office received the equipment but didn't scan it into the tracking system. The subscriber calls, furious, and the agent has to investigate a process failure. Implement real-time return scanning with subscriber confirmation at the point of return."
      },
      { layer: 1, name: "Data Access", capabilities: ["BSS integration: billing, packaging, promotional pricing, and device inventory","Content management system: channel lineup, VOD catalog, and blackout schedules","Set-top box management: device status, firmware, diagnostics, and DVR storage","CRM with subscriber history, interaction log, and retention offer history","Field service system: technician schedules, truck rolls, and installation status"], vendors: "CSG, Amdocs, Ericsson MediaFirst, Salesforce", risk: "Agent unable to see viewing history or content availability during support",
        stack: [{ name: "CSG", role: "BSS", why: "Cable billing and subscriber management. Package details, promotional pricing, equipment inventory, and service orders. The source of truth for every billing and packaging question.", href: "/vendors" }, { name: "Salesforce Communications Cloud", role: "CRM", why: "Subscriber relationship management unifying BSS data, interaction history, and retention offer tracking. Gives agents the context they need without navigating the BSS directly.", href: "/vendors/ccaas" }],
        pitfall: "Cable agents need to see viewing data to have informed retention conversations. [[tel.ex.viewing]] But viewing data is typically in the content management system, not the agent desktop. Connect set-top box viewing data to the agent CRM so retention agents know which content the subscriber actually values, then build save offers around that content."
      },
    ],
  },

  "enterprise-comms": {
    name: "Enterprise & Business Communications", parent: "Telecommunications",
    tagline: "UCaaS/SD-WAN support, SLA management, provisioning, and account management.",
    intro: "Enterprise telecom contact centers serve business customers whose communications infrastructure is mission-critical. A short voice outage can cost an enterprise customer far more than its monthly bill. The CX challenge is providing B2B-grade support, named account managers, SLA-aware routing, proactive monitoring, while managing a complex portfolio of voice, data, cloud, and managed services.",
    kpis: [
      { metric: "AHT", avg: "[[tel.sv.enterprise-comms.aht]]", note: "Driven by provisioning, SLA discussions, and multi-circuit troubleshooting" },
      { metric: "FCR", avg: "[[tel.sv.enterprise-comms.fcr]]", note: "Enterprise issues often span several circuits, sites, and vendors" },
      { metric: "CSAT", avg: "[[tel.sv.enterprise-comms.csat]]", note: "Shaped by the dedicated support model and account management" },
      { metric: "Containment", avg: "[[tel.sv.enterprise-comms.containment]]", note: "Limited where enterprise customers expect an engineer on the line" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["SLA performance reporting by customer, circuit, and service type","Account health scoring based on ticket volume, SLA misses, and NPS","Revenue-at-risk analytics tied to service quality and contract renewal dates","Technician performance analytics for installation and repair quality","Network performance dashboards shared with enterprise customers"], vendors: "NICE, ServiceNow, Salesforce, custom BI", risk: "SLA misses accumulating without proactive customer communication",
        stack: [{ name: "ServiceNow ITSM", role: "Service Management", why: "Enterprise-grade incident, problem, and change management. SLA tracking with automated escalation. Common in B2B service operations in telecom.", href: "/vendors" }],
        pitfall: "Enterprise customers can weigh SLA reporting as heavily as SLA performance. [[tel.ex.sla-report]] Invest in customer-facing reporting alongside network improvements."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Named account manager routing with full account context","SLA-priority routing escalating tickets approaching SLA breach","Circuit-specific routing matching issues to engineers with relevant expertise","Major incident routing activating war room protocols for enterprise outages","Provisioning and order status routing for complex multi-site deployments"], vendors: "Genesys, Cisco, NICE CXone", risk: "Enterprise customer reaching a consumer-grade support agent",
        stack: [{ name: "Cisco Webex CC", role: "Enterprise CCaaS", why: "Natural fit for carriers selling Cisco UCaaS to enterprise customers. Same platform for internal support operations and customer-facing service. Enterprise networking heritage.", href: "/vendors/cisco" }],
        pitfall: "Enterprise and consumer support must be completely separate operations: separate agents, separate queues, separate SLAs, separate systems. [[tel.ex.ent-queue]] If they do, you'll lose a contract worth more than the entire consumer queue generates in a month."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Customer portal with real-time circuit status and SLA dashboards","Proactive major incident notifications with business impact assessment","Change request management with scheduling and approval workflows","Technical account review meetings with QBR preparation","Escalation management with executive communication templates"], vendors: "ServiceNow, Salesforce, Cisco", risk: "Enterprise customers learning about outages from their own users instead of from you",
        stack: [{ name: "ServiceNow Customer Portal", role: "Self-Service", why: "Enterprise customers manage tickets, view SLA reports, and track orders through a branded portal. Reduces calls for status updates while giving customers the transparency they demand.", href: "/vendors" }],
        pitfall: "Enterprise customers should never learn about a service-affecting issue from their own end users. Proactive notification must be faster than the customer's internal detection. [[tel.ex.noc]] Set a target for automated alerting from NOC → customer, such as [[tel.ent.alert]] from detection."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Circuit status bots with real-time performance data","Order and provisioning status bots with milestone tracking","Billing inquiry bots for enterprise invoicing and usage","Basic troubleshooting bots for SIP, internet, and SD-WAN connectivity","Knowledge base search for enterprise product documentation"], vendors: "Limited use: enterprise expects human expertise", risk: "Bot handling mission-critical outage report instead of immediately escalating",
        stack: [{ name: "Minimal AI recommended", role: "None", why: "Enterprise customers paying for mission-critical services expect an immediate human response to incidents. Deploy AI for order status, invoice lookup, and documentation search, never for incident management. A bot saying 'let me help you troubleshoot' during a major outage does lasting damage to the account relationship." }],
        pitfall: "Enterprise AI should be invisible to the customer and visible to the agent. Use Agent Assist (Google CCAI, NICE) to surface circuit history, SLA data, and recommended troubleshooting steps to the agent in real-time, but keep the customer-facing interaction human. Enterprise customers buy expertise, not automation."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["SLA compliance enforcement with automated credit calculation","CPNI protection for enterprise customer data and traffic patterns","SOC 2 compliance for managed service delivery","Contract terms enforcement for service levels and penalties","Change management policies with customer approval workflows"], vendors: "ServiceNow, custom compliance", risk: "SLA credits not issued proactively: customer must demand them",
        stack: [{ name: "ServiceNow", role: "SLA & Compliance", why: "Automated SLA tracking, breach detection, and credit calculation. When a circuit drops below the committed uptime threshold, the credit should be calculated and communicated proactively, not after the customer demands it.", href: "/vendors" }],
        pitfall: "Enterprise SLA credits are typically issued only when the customer requests them. Proactive credit issuance, notifying the customer of the SLA miss AND the credit amount before they ask, transforms the SLA credit from a complaint into a trust-building moment. [[tel.ex.sla-credit]] That message builds the trust that keeps enterprise accounts."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Multi-site provisioning workflow with project management and milestone tracking","Incident management workflow with severity classification and escalation","Change management workflow with customer approval and implementation scheduling","Contract renewal workflow with usage analysis and proposal generation","Decommission workflow with circuit disconnect and equipment return"], vendors: "ServiceNow, Salesforce, Amdocs Enterprise", risk: "Multi-site provisioning delays cascading across the entire project",
        stack: [{ name: "ServiceNow", role: "Workflow Platform", why: "Incident, change, problem, and project management in one platform. Enterprise telecom workflows are ITIL-aligned, and ServiceNow is widely used for ITIL-based service management.", href: "/vendors" }, { name: "Salesforce", role: "Account Management CRM", why: "Enterprise account management, opportunity tracking, and contract management. The commercial layer that sits alongside the operational layer (ServiceNow).", href: "/vendors/ccaas" }],
        pitfall: "Enterprise provisioning for a multi-site SD-WAN deployment is a project management challenge, not a customer service challenge. But the contact center absorbs the calls when provisioning timelines slip. Build a project portal where the enterprise customer can see real-time provisioning status by site: circuit ordered, equipment shipped, installation scheduled, service tested, cutover complete. Without this, the account manager becomes a human status dashboard."
      },
      { layer: 1, name: "Data Access", capabilities: ["Circuit inventory: all services by customer, site, bandwidth, and SLA tier","Network monitoring: real-time performance for customer-facing circuits","BSS: enterprise billing, contracts, and usage data","Order management: provisioning status for new and changed services","Customer portal: shared data layer between carrier and enterprise customer"], vendors: "Amdocs, Salesforce, ServiceNow, Ciena Blue Planet", risk: "Agent seeing aggregate account data but not circuit-level detail",
        stack: [{ name: "Salesforce Communications Cloud", role: "Enterprise CRM", why: "Account and contract management with service inventory. The relationship layer that connects commercial data (contracts, pricing) with operational data (circuits, SLAs).", href: "/vendors/ccaas" }, { name: "Ciena Blue Planet", role: "Network Inventory", why: "Network inventory and service orchestration for carriers. Maps physical and virtual network assets to customer services. When a customer calls about their MPLS circuit, the agent needs to see what Ciena sees.", href: "/vendors" }],
        pitfall: "Enterprise telecom data spans: CRM (account/contract), BSS (billing), OSS (network), OMS (orders), and ITSM (incidents). An agent answering an enterprise customer needs data from all five. Carriers often integrate only some of these and leave the rest as manual lookups. [[tel.ex.ent-aht]] Unify the data layer and measure how much of the navigation time comes back."
      },
    ],
  },

  "managed-services": {
    name: "Managed Service Providers", parent: "Telecommunications",
    tagline: "NOC support, incident management, SLA reporting, change requests, and multi-vendor coordination.",
    intro: "MSP contact centers operate as extensions of their clients' IT departments. The CX challenge is technical depth, when a client calls about a network issue, the MSP agent must diagnose across multiple vendors, circuits, and technologies. Generic customer service skills are insufficient; MSP support is engineering support with SLA accountability.",
    kpis: [
      { metric: "AHT", avg: "[[tel.sv.managed-services.aht]]", note: "Driven by multi-vendor diagnosis and coordination" },
      { metric: "FCR", avg: "[[tel.sv.managed-services.fcr]]", note: "Issues span several vendors and need coordinated resolution" },
      { metric: "CSAT", avg: "[[tel.sv.managed-services.csat]]", note: "Moves with the technical depth clients receive" },
      { metric: "Containment", avg: "[[tel.sv.managed-services.containment]]", note: "Limited where nearly every contact needs technical judgment" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["SLA performance across all managed clients and service types","Mean time to detect (MTTD) and mean time to resolve (MTTR) by incident type","Multi-vendor performance comparison for carrier and technology partners","Client QBR preparation with trend analysis and improvement recommendations","NOC efficiency analytics: alarm-to-ticket ratio and false positive rate"], vendors: "ServiceNow, LogicMonitor, custom dashboards", risk: "MTTR increasing without visibility into which vendor or process is causing delays",
        stack: [{ name: "ServiceNow ITSM", role: "Service Management", why: "Widely used for MSP operations. Multi-client ITSM with SLA tracking, incident management, and change management. The operational backbone.", href: "/vendors" }, { name: "LogicMonitor", role: "Infrastructure Monitoring", why: "Agentless monitoring across client infrastructure: network, cloud, servers, and applications. The data source for NOC operations and proactive alerting.", href: "/vendors" }],
        pitfall: "MSPs track MTTR (mean time to resolve) but not MTTV (mean time to vendor): the time between incident detection and the moment a third-party vendor is engaged. For multi-vendor issues, [[tel.msp.mttv]] of total resolution time can go to identifying which vendor is responsible and getting them engaged. Reducing MTTV through better diagnostics and vendor escalation can outweigh other operational improvements."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Client-specific routing with custom SLAs and escalation paths","Severity-based routing: P1/P2/P3/P4 with different response targets","Technology-specific routing to engineers by expertise (SD-WAN, UC, security)","After-hours NOC routing with on-call engineer escalation","Multi-vendor coordination routing with carrier and vendor management"], vendors: "ServiceNow, Genesys, ConnectWise", risk: "P1 incident reaching a junior engineer during off-hours",
        stack: [{ name: "ConnectWise", role: "MSP Platform", why: "Purpose-built for MSP operations: ticketing, billing, and remote monitoring. Routing based on client, technology, and severity. Good for SMB-focused MSPs.", href: "/vendors" }],
        pitfall: "MSP severity classification is subjective and inconsistent. One client's 'our internet is slow' is a P3; another client's 'our internet is slow' is a P1 because it's affecting their trading floor. Severity must be defined per client in the SLA, tied to business impact, and enforced by the routing engine. If severity is left to the agent's judgment, high-value clients will be under-prioritized."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Client portal with real-time ticket status and SLA dashboards","Major incident bridge calls with client and vendor participation","Change request management with approval workflow and scheduling","Proactive monitoring alerts with client notification preferences","QBR and reporting delivery through portal and scheduled reviews"], vendors: "ServiceNow, ConnectWise, Datto", risk: "Clients hearing about issues from their own users before the MSP notifies them",
        stack: [{ name: "ServiceNow Portal", role: "Client Self-Service", why: "White-labeled client portal with ticket management, asset inventory, and SLA reporting. Enterprise clients expect self-service visibility; SMB clients appreciate the professionalism.", href: "/vendors" }],
        pitfall: "MSP clients fall into two communication camps: enterprise clients who want portal-based self-service and automated reporting, and SMB clients who want a phone call from a person they know. Using the same communication model for both creates friction: the enterprise client doesn't want a phone call for every P3 ticket, and the SMB client doesn't want to log into a portal to check if their email is fixed. Segment your communication model by client type."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Automated network diagnostics triggered by monitoring alerts","Ticket categorization AI classifying incidents by technology and likely root cause","Knowledge base search for runbook procedures by device and vendor","Automated remediation scripts for common issues (circuit bounce, device restart)","Change risk assessment AI evaluating potential impact of planned changes"], vendors: "ConnectWise AI, ServiceNow AI, custom automation", risk: "Automated remediation executing on a production system without proper change control",
        stack: [{ name: "ServiceNow AI", role: "IT Operations AI", why: "AIOps capabilities for incident classification, assignment, and recommended resolution. Learns from historical ticket data to predict root cause and suggest runbook procedures.", href: "/vendors" }],
        pitfall: "MSPs are eager to automate remediation (auto-restart a device, auto-bounce a circuit) to reduce MTTR. But automated remediation on a client's production system without the client's approval is a contract violation and a trust destroyer. Implement automated diagnostics aggressively but require human approval for automated remediation, at least until the client explicitly opts in to auto-remediation for specific, low-risk actions."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Client SLA compliance tracking with automated breach alerting","Change management policies with client-specific approval requirements","Data privacy controls for multi-tenant MSP environments","SOC 2 and ISO 27001 compliance for managed security services","Vendor SLA enforcement for carrier and technology partner accountability"], vendors: "ServiceNow, custom compliance", risk: "Multi-tenant data leakage between MSP clients",
        stack: [{ name: "ServiceNow", role: "ITSM & Compliance", why: "Multi-tenant architecture ensuring client data isolation. SLA tracking, change approval workflows, and audit trails. The compliance backbone for MSP operations.", href: "/vendors" }],
        pitfall: "Multi-tenant MSP environments create a distinct compliance risk: client A's data must never be visible to client B's users. This extends to the contact center: an agent working on Client A's ticket must not have access to Client B's network diagrams or configuration data. Implement role-based access control by client, not just by function. Regular access audits prevent scope creep."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Incident management workflow: detect, triage, diagnose, resolve, confirm, close","Change management workflow: request, assess risk, approve, implement, verify","Problem management workflow: identify root cause, implement permanent fix","Onboarding workflow for new managed service clients","Vendor escalation workflow with SLA tracking for third-party resolution"], vendors: "ServiceNow, ConnectWise, Autotask (Datto)", risk: "Incident resolution delayed by vendor coordination failures",
        stack: [{ name: "ServiceNow ITSM", role: "ITIL Workflows", why: "Incident, change, problem, and release management in ITIL-aligned workflows. The operational backbone for MSP service delivery, from small to very large client bases.", href: "/vendors" }, { name: "ConnectWise Manage", role: "MSP Operations", why: "Purpose-built for MSP ticketing, project management, and billing. Better for SMB-focused MSPs than ServiceNow. Integrates with ConnectWise Automate for remote monitoring.", href: "/vendors" }],
        pitfall: "MSPs run ITIL-aligned incident management but skip problem management. The result: the same incident recurs monthly because nobody investigates the root cause. A circuit that bounces every few weeks generates a P2 ticket each time, gets resolved by bouncing the router, and generates another P2 ticket a few weeks later. Implement problem management to identify and fix root causes: it's cheaper than managing recurring incidents."
      },
      { layer: 1, name: "Data Access", capabilities: ["Network monitoring platform: real-time device, circuit, and application status","ITSM: ticket history, SLA data, and change records by client","Configuration management database (CMDB): asset inventory and dependencies","Client documentation: network diagrams, runbooks, and contact lists","Vendor portal access: carrier circuits, ISP accounts, and hardware warranty"], vendors: "LogicMonitor, SolarWinds, ServiceNow CMDB, ConnectWise", risk: "CMDB out of date: agent troubleshooting with stale network topology",
        stack: [{ name: "LogicMonitor", role: "Monitoring", why: "Agentless infrastructure monitoring. Network, cloud, and application visibility across all managed clients. The alerting layer that triggers NOC response.", href: "/vendors" }, { name: "ServiceNow CMDB", role: "Asset & Configuration", why: "Configuration items, relationships, and dependencies for every managed client. When an engineer troubleshoots a client's issue, the CMDB shows what's connected to what.", href: "/vendors" }],
        pitfall: "An out-of-date CMDB sends engineers in the wrong direction with confidence. [[tel.ex.cmdb]] Implement automated CMDB discovery (LogicMonitor, ServiceNow Discovery) that continuously updates configuration data from the actual network, not from manual data entry."
      },
    ],
  },

  "fiber-infrastructure": {
    name: "Fiber & Infrastructure", parent: "Telecommunications",
    tagline: "Installation scheduling, construction updates, service activation, and wholesale support.",
    intro: "Fiber and infrastructure providers operate contact centers with a project-based CX model. Customers call about construction timelines, installation scheduling, and service activation: interactions tied to physical construction that takes weeks or months. The CX challenge is managing expectations over long timelines while delivering responsive service for activated customers.",
    kpis: [
      { metric: "AHT", avg: "[[tel.sv.fiber-infrastructure.aht]]", note: "Driven by scheduling and project status calls" },
      { metric: "FCR", avg: "[[tel.sv.fiber-infrastructure.fcr]]", note: "Construction and installation timelines sit outside contact center control" },
      { metric: "CSAT", avg: "[[tel.sv.fiber-infrastructure.csat]]", note: "Moves with construction progress and delays" },
      { metric: "Containment", avg: "[[tel.sv.fiber-infrastructure.containment]]", note: "Service availability checks and status updates can be automated" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Construction project milestone tracking with customer communication triggers","Installation completion rate and first-visit success analytics","Take rate analytics by neighborhood and marketing campaign","Post-activation satisfaction tracking at set intervals after activation","Wholesale partner SLA performance and dispute tracking"], vendors: "NICE, Salesforce, custom BI", risk: "Construction delays creating customer frustration without proactive communication",
        stack: [{ name: "Salesforce", role: "CRM & Project Tracking", why: "Customer lifecycle management from pre-sales interest → construction → installation → activation → ongoing service. The relationship layer that spans the multi-month customer journey.", href: "/vendors/ccaas" }],
        pitfall: "Fiber providers track construction project milestones internally but don't share them with customers who signed up for service. A customer who registered interest many months ago and hasn't heard anything will call, and the agent often can't give a specific timeline because construction data lives in the project management system, not the CRM. Build a customer-facing construction tracker (similar to pizza delivery tracking) showing: design → permitting → construction → splicing → service available."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Pre-sale vs active customer routing with different service models","Installation scheduling routing to dispatch and field operations","Construction inquiry routing to project management teams","Wholesale/carrier routing separating retail and wholesale customers","Service activation routing with real-time provisioning status"], vendors: "Genesys, NICE CXone, 8x8", risk: "Active service issues waiting behind pre-sale construction inquiries",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Right-sized for growing fiber providers scaling from startup to regional carrier. Modular: start with basic routing and add WEM and analytics as subscriber base grows.", href: "/vendors/nice-cxone" }],
        pitfall: "Fiber providers often start with a small contact center handling both pre-sale construction inquiries and active service support. As the subscriber base grows, active service calls (billing, tech support) increasingly compete with construction inquiries. Separate these into distinct routing paths early: the agents who handle 'when will fiber be available on my street?' are not the same agents who troubleshoot ONT failures."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Construction milestone notifications via email and SMS","Installation appointment confirmation with preparation checklist","Service availability checker for address-level fiber coverage","Proactive delay notifications with revised timelines","Referral program communications for neighborhood campaigns"], vendors: "Well Health, Klaviyo, custom notifications", risk: "Customers discovering construction delays only when they call to ask",
        stack: [{ name: "Custom notifications", role: "Project Communications", why: "Fiber construction communication is project-based, not transactional. Standard CX messaging tools send post-interaction surveys; fiber needs milestone-based communications. Providers often build custom notification systems tied to their construction project management.", href: "/vendors" }],
        pitfall: "The gap between 'customer signs up' and 'fiber is available' can run [[tel.fiber.gap]]. During that gap, silence equals churn. Competitors (cable, wireless ISPs) will continue marketing to your signed-up customers. Monthly milestone updates, even if the milestone is 'permitting is still in progress', maintain engagement; track pre-activation cancellations to see the effect."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Service availability bots checking address-level fiber coverage","Installation scheduling bots with technician availability","Construction status bots with project milestone information","Speed test and service health bots for active subscribers","Bill explanation and payment bots"], vendors: "Ada, Calix AI", risk: "Bot reporting incorrect service availability for an address",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles a high-volume inquiry, 'is fiber available at my address?', with real-time GIS data integration. Also handles installation scheduling and billing FAQ for active subscribers.", href: "/vendors/iva" }],
        pitfall: "Address-level availability checking is a critical bot in fiber CX, and an error-prone one. [[tel.ex.lateral]] False positives create installation failures; false negatives lose potential subscribers. Validate your availability data against actual field conditions, not just GIS maps."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["FCC broadband labeling compliance for fiber services","Construction easement and right-of-way communication requirements","Municipal franchise agreement compliance","Customer data privacy for address and location information","Competitive anti-slamming protections during service activation"], vendors: "Regulatory compliance, FCC", risk: "Broadband label non-compliance for new fiber service offerings",
        stack: [{ name: "FCC compliance", role: "Regulatory", why: "Broadband labels, truth-in-billing, and local franchise agreements are the main compliance requirements. Fiber providers often handle compliance internally rather than through specialized vendors." }],
        pitfall: "Fiber overbuilders face particular competitive dynamics: they're building infrastructure in areas already served by cable and wireless. State and local regulations around construction access, pole attachments, and franchise agreements vary wildly. Your contact center agents will receive complaints about construction disruption (torn yards, blocked driveways) that are actually construction policy issues. Build an escalation path to the construction team that gives agents specific, honest timelines for restoration."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Customer registration and interest capture workflow","Installation scheduling workflow with site survey and technician dispatch","Service activation workflow with ONT provisioning and speed validation","Construction-to-service handoff workflow bridging project and operations teams","Wholesale provisioning workflow for carrier and ISP customers"], vendors: "Salesforce, Calix, custom construction management", risk: "Installation scheduled before construction is actually complete at the address",
        stack: [{ name: "Calix", role: "Fiber Operations", why: "Revenue EDGE platform for fiber broadband providers. ONT provisioning, subscriber management, and network analytics. Purpose-built for fiber operations rather than adapted from legacy copper platforms.", href: "/vendors" }, { name: "Salesforce", role: "CRM & Lifecycle", why: "Customer lifecycle from pre-sale interest through construction, installation, activation, and ongoing service. Connects marketing (lead gen) to operations (installation) to service (support).", href: "/vendors/ccaas" }],
        pitfall: "The construction-to-service handoff is a failure-prone workflow in fiber operations. Construction team completes splicing at an address and marks it 'serviceable' in their system. The customer schedules installation. The technician arrives and discovers the drop wasn't actually terminated, or the splice is substandard. The customer waited weeks for the appointment and now has to reschedule. Implement a quality check between construction completion and serviceable status: don't mark an address as available until a technician has verified the drop."
      },
      { layer: 1, name: "Data Access", capabilities: ["GIS/mapping system with address-level fiber availability","Construction project management with milestone and timeline data","ONT/CPE management with provisioning and diagnostic data","BSS for billing, subscriber management, and service orders","Network monitoring for fiber plant health and performance"], vendors: "Calix, Adtran, Salesforce, OSPInsight, Vetro FiberMap", risk: "GIS data showing 'serviceable' for addresses where construction isn't complete",
        stack: [{ name: "Calix Cloud", role: "Fiber Network Data", why: "ONT diagnostics, subscriber network performance, and WiFi analytics. The real-time data source for any 'my internet is slow' interaction with a fiber subscriber.", href: "/vendors" }, { name: "Vetro FiberMap", role: "GIS / Fiber Plant", why: "Fiber network planning and asset management. Maps physical fiber infrastructure to addresses. The data source for 'is fiber available at my address?', a common inquiry for growing fiber providers.", href: "/vendors" }],
        pitfall: "Fiber providers have two distinct customer populations with different data needs: pre-sale prospects wanting availability and timeline information (GIS + construction data), and active subscribers wanting service and billing support (BSS + network monitoring). Fiber providers often build their CX stack for active subscribers and handle pre-sale as an afterthought, even though pre-sale inquiries can be [[tel.fiber.presale]] of contact volume during expansion. Size your data integration for both populations from day one."
      },
    ],
  },
};

export const getTelecomSubVertical = (slug) => (Object.prototype.hasOwnProperty.call(telecomSubVerticals, slug) ? telecomSubVerticals[slug] : undefined);
export const getAllTelecomSubVerticalSlugs = () => Object.keys(telecomSubVerticals);
