export const travelSubVerticals = {
  "airlines": {
    name: "Airlines", parent: "Travel & Hospitality",
    tagline: "Booking changes, cancellations, disruption management, loyalty, and baggage.",
    intro: "Airline contact center volume is set by operations. A normal day is manageable. A storm at a hub strands thousands of passengers at once, and every one of them needs a rebooking. The operating challenge is building capacity, routing, and proactive rebooking for disruption days, because travelers rarely call when flights run on time.",
    kpis: [
      { metric: "AHT", avg: "[[trv.sv.airlines.aht]]", note: "Rebooking, fare differences and multi-leg itineraries drive handle time" },
      { metric: "FCR", avg: "[[trv.sv.airlines.fcr]]", note: "Disruption rebooking often needs follow-up on waitlists and upgrades" },
      { metric: "CSAT", avg: "[[trv.sv.airlines.csat]]", note: "Moves with the disruption experience as much as with service quality" },
      { metric: "Containment", avg: "[[trv.sv.airlines.containment]]", note: "Flight status and simple booking changes can be automated; disruptions keep people involved" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Disruption recovery CSAT tracking by event type and resolution path","Loyalty tier satisfaction segmented by elite status and lifetime value","EU261/DOT compensation compliance monitoring with automated tracking","Agent rebooking quality scoring: were passengers put on the best available option?","Social media sentiment during IROP events correlated with operational response speed"],
        vendors: "NICE Nexidia, Medallia, Qualtrics", risk: "EU261 compliance gaps creating regulatory fines",
        stack: [{ name: "NICE Nexidia", role: "Interaction Analytics", why: "Analyzes disruption calls at scale: detects rebooking errors, missed compensation offers, and escalation patterns. Critical for post-IROP quality review.", href: "/vendors/analytics" }, { name: "Medallia", role: "CX Platform", why: "Real-time passenger sentiment connected to flight operations data. Shows which disruptions create the most loyalty damage and where recovery was effective.", href: "/vendors/analytics" }],
        pitfall: "Airlines measure IROP (irregular operations) performance by operational metrics, rebooking rate, completion factor, delay minutes. They rarely measure IROP CX performance: how the passenger experienced the disruption. [[trv.ex.irop.hold]] Measure both."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["IROP surge routing activating overflow agents and automated rebooking","Loyalty tier routing: elite passengers to dedicated teams with zero-wait SLA","Multi-language routing across global hub airports and booking origins","Fare class-aware routing matching complex ticket rules to trained agents","Proactive rebooking notification replacing inbound calls with outbound solutions"],
        vendors: "Genesys, NICE CXone, Amadeus", risk: "Elite passengers waiting in general queue during disruptions",
        stack: [{ name: "Genesys Cloud", role: "Primary CCaaS", why: "Built to absorb the volume spikes that airline IROPs create. Predictive routing matches passengers to agents by language, loyalty tier, and rebooking complexity.", href: "/vendors/genesys" }, { name: "Amadeus Airline Service Hub", role: "Airline CX Platform", why: "Purpose-built for airline customer service. Integrates directly with the PSS (reservation system) for real-time rebooking, seat assignment, and fare recalculation within the agent desktop.", href: "/vendors" }],
        pitfall: "Automated proactive rebooking is the investment to weigh first. When a flight cancels, the system rebooks affected passengers on the next suitable flight, sends the new itinerary, and routes to an agent only the passengers who reject it. Under the US automatic refund rule a passenger who declines a cancelled or significantly changed flight is owed a refund, so the notice must also offer that choice. Count your own IROP calls before and after to size the effect."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Proactive IROP notifications via app push, SMS, and email with rebooking options","In-app messaging for booking modifications and seat selection","Social media response for real-time disruption complaints (Twitter/X, Instagram)","WhatsApp and messaging for international travelers","Automated boarding pass and itinerary delivery post-rebooking"],
        vendors: "LivePerson, Sprinklr, Amadeus, SITA", risk: "Passengers learning about cancellations from social media before the airline notifies them",
        stack: [{ name: "Sprinklr", role: "Social + Digital CX", why: "Airlines face massive social media volume during disruptions. Sprinklr unifies social listening, response, and care, routing angry tweets to the right team before they go viral.", href: "/vendors/digital-engagement" }, { name: "SITA", role: "Aviation Messaging", why: "Aviation-specific passenger communication platform. Integrates with departure control systems for real-time flight status messaging. Purpose-built for the operational reality of airline CX.", href: "/vendors" }],
        pitfall: "A passenger who learns of a cancellation at the airport has been failed on the most basic obligation. Notice should go out the moment operations decides, and the rules reward it: US carriers must [[trv.dot.notify]] of a cancellation or significant change and of any right to a refund, and under EU261 compensation for a cancellation does not apply when passengers are told [[trv.eu261.twoweeks]] ahead. If your notification system is triggered by departure control rather than operations planning, it notifies too late."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Flight status bots with real-time operational data and connection risk","Rebooking bots offering alternative flights, dates, and routings","Baggage tracking bots with real-time WorldTracer integration","Loyalty point redemption and upgrade request bots","Booking modification bots for date, time, and seat changes"],
        vendors: "Amelia, Cognigy, Ada, [24]7.ai", risk: "Bot rebooking passenger on a connection they can't make due to minimum connect time",
        stack: [{ name: "Amelia (IPsoft)", role: "Conversational AI", why: "Deep travel domain expertise with airline-specific intents, rebooking, upgrade, mileage, baggage. Handles complex multi-leg itinerary modifications. Deployed at major carriers.", href: "/vendors/iva" }, { name: "[24]7.ai", role: "AI Customer Service", why: "Strong airline deployments handling booking modifications, flight status, and loyalty inquiries. Good containment rates for routine travel interactions.", href: "/vendors/iva" }],
        pitfall: "Airline rebooking bots must understand minimum connection times, aircraft type changes (lie-flat to coach is not an equivalent rebook), codeshare rules, and fare class availability. [[trv.ex.connection]] Under the US automatic refund rule a downgrade to a lower class is [[trv.dot.downgrade]], so the passenger can decline it and take a refund. Build airline-specific rebooking logic on top of booking search."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["EU261 compensation rules automated by delay duration, distance, and cause","DOT refund and compensation requirements for US operations","Fare rule enforcement across booking classes, channels, and loyalty tiers","PCI compliance for payment changes and refund processing","GDPR compliance for EU passenger data across global operations"],
        vendors: "Custom policy engines, Amadeus, Sabre", risk: "EU261 compensation not offered proactively, creating regulatory complaints",
        stack: [{ name: "Amadeus / Sabre policy engine", role: "Fare Rules", why: "GDS-embedded fare rules determine what's changeable, refundable, and compensable. The agent desktop must surface these rules in real-time, not require the agent to look them up manually.", href: "/vendors" }],
        pitfall: "EU261 requires the operating carrier to give each passenger it denies boarding or cancels, and each passenger delayed by [[trv.eu261.notice]], a written notice of the compensation and assistance rules. Where that depends on an agent remembering it during an IROP, it gets missed. Automate the eligibility check: when a flight is cancelled or delayed past the thresholds, calculate the compensation band ([[trv.eu261.comp]] by distance) and put it in the passenger notification. Proactive compliance lowers regulatory risk and builds trust."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Automated rebooking workflow triggered by flight cancellation or significant delay","Compensation processing workflow with fare difference, voucher, and cash options","Baggage delay/loss claim workflow with WorldTracer integration","Group booking modification workflow with multi-passenger coordination","Refund processing workflow with fare rule validation and payment reversal"],
        vendors: "Amadeus Altea, Sabre, Navitaire, Salesforce", risk: "Rebooking workflow not accounting for passenger connections downstream",
        stack: [{ name: "Amadeus Altea", role: "PSS", why: "Passenger Service System: the reservation, inventory, and departure control backbone. Every rebooking, cancellation, and modification executes through Altea. Your CX stack integrates with Altea.", href: "/vendors" }, { name: "Sabre SabreSonic", role: "PSS", why: "Alternative PSS powering major carriers. Reservation management, shopping, and fulfillment. Same integration imperative as Amadeus: the PSS constrains what the agent can do.", href: "/vendors" }],
        pitfall: "Airline rebooking workflows must cascade, rebooking passenger A on a new flight may affect their hotel voucher eligibility, their baggage routing, their meal voucher, and their connecting flight at the destination. Most rebooking systems handle the flight change but not the downstream impacts. The passenger is rebooked but their bag goes to the original destination, their hotel voucher wasn't issued, and their connecting flight wasn't updated. Build cascading rebooking that handles the full journey. Bags matter to the rules too: a US domestic checked bag not delivered within [[trv.dot.bag]] of arrival is significantly delayed, and its fee must be refunded."
      },
      { layer: 1, name: "Data Access", capabilities: ["PSS integration: reservations, ticketing, inventory, and fare rules","Flight operations data: real-time status, delays, cancellations, and gates","Loyalty program: tier status, mileage balance, lifetime value, and preferences","Baggage tracking: WorldTracer for delayed, lost, and damaged claims","Revenue management: fare availability, upgrade inventory, and pricing"],
        vendors: "Amadeus, Sabre, Navitaire, SITA", risk: "Agent seeing the reservation but not the operational status of the flight",
        stack: [{ name: "Amadeus Altea / Sabre", role: "PSS Data", why: "The reservation is the core data object. PNR (Passenger Name Record) contains everything: flights, fares, contacts, preferences, and history. Agent desktop must render the PNR in a human-readable format.", href: "/vendors" }, { name: "SITA", role: "Aviation Data", why: "Baggage tracking (WorldTracer), flight messaging (Type B), and airport operations. The operational data layer that sits alongside the commercial PSS layer.", href: "/vendors" }],
        pitfall: "Airline agents toggle between the PSS (reservation), DCS (departure control), loyalty system, baggage system, and operations system. The agent answering 'where's my bag and when's my new flight?' needs data from several of these systems at once. Amadeus's Airline Service Hub and Salesforce's airline solutions aim to unify this, but fragmented desktops remain common. Time the screens and lookups on your own calls to size the gain from a unified desktop."
      },
    ],
  },

  "hotels-resorts": {
    name: "Hotels & Resorts", parent: "Travel & Hospitality",
    tagline: "Reservations, modifications, loyalty tiers, pre-arrival requests, and post-stay resolution.",
    intro: "Hotel contact centers serve three distinct moments: pre-stay (booking, modification, special requests), in-stay (concierge, issues, requests), and post-stay (billing disputes, loyalty, complaints). Each moment requires different agent skills, different system access, and different success metrics. The CX challenge is recognizing which moment the guest is in and routing accordingly.",
    kpis: [
      { metric: "AHT", avg: "[[trv.sv.hotels-resorts.aht]]", note: "Reservations are quick; complaints and modifications take longer" },
      { metric: "FCR", avg: "[[trv.sv.hotels-resorts.fcr]]", note: "Pre-stay requests resolve simply; post-stay disputes need investigation" },
      { metric: "CSAT", avg: "[[trv.sv.hotels-resorts.csat]]", note: "Moves with recognition, in-stay recovery and billing clarity" },
      { metric: "Containment", avg: "[[trv.sv.hotels-resorts.containment]]", note: "Reservation status and loyalty lookups can be automated; service recovery needs people" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Guest satisfaction tracking by property, stay type, and loyalty tier","Post-stay review sentiment correlated to contact center interactions","Revenue-per-call analytics: upsell success on room upgrades and packages","Service recovery effectiveness scoring by complaint type and resolution","Loyalty program engagement analytics tied to contact center touchpoints"],
        vendors: "Medallia, ReviewPro, Qualtrics, NICE", risk: "Negative reviews posted before the hotel has a chance to recover",
        stack: [{ name: "ReviewPro (Shiji)", role: "Hospitality Analytics", why: "Purpose-built for hotels. Aggregates reviews from many review sites, connects to operational data, and identifies which service failures drive the most review damage.", href: "/vendors/analytics" }, { name: "Medallia", role: "Guest Experience", why: "Real-time guest feedback during and after the stay. Alerts the property when a guest is dissatisfied so service recovery can happen before checkout.", href: "/vendors/analytics" }],
        pitfall: "Hotels measure guest satisfaction at checkout or post-stay: too late for service recovery. Real-time satisfaction signals (in-stay surveys, messaging sentiment, app feedback) enable recovery while the guest is still on property. A problem fixed during the stay generates a positive review; the same problem addressed after departure generates an apologetic email and a discounted future stay."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Loyalty tier routing with brand recognition and preference data","Pre-stay vs in-stay vs post-stay routing with different agent pools","Property-specific routing matching callers to agents with local knowledge","Group and event booking routing to specialized sales teams","OTA booking routing separating direct guests from third-party bookings"],
        vendors: "Genesys, NICE CXone, Five9", risk: "Loyal guest treated like a first-time caller during a complaint",
        stack: [{ name: "NICE CXone", role: "CCaaS", why: "Multi-property routing with WEM for managing seasonal staffing across resort locations. Skills-based routing by property type (urban, resort, limited-service) and guest tier.", href: "/vendors/nice-cxone" }],
        pitfall: "Hotel loyalty programs create tiered service expectations, but hotel contact centers often route by call reason alone. A Platinum member calling to resolve a billing error waits in the same queue as a first-time guest making a reservation. [[trv.ex.hotel.tier]] Route by tier first, then by reason."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Pre-arrival messaging with room preferences, early check-in, and special requests","In-stay messaging replacing the front desk phone for service requests","Post-stay follow-up with satisfaction survey and review solicitation","WhatsApp and messaging for international guests","Concierge chat for dining, activities, and transportation"],
        vendors: "ALICE (Actabl), Zingle (Medallia), LivePerson, Ada", risk: "In-stay guest messages not reaching the right hotel team in time",
        stack: [{ name: "Actabl (ALICE)", role: "Hotel Operations", why: "Purpose-built hotel operations platform. Guest messaging, service delivery tracking, and housekeeping coordination. Connects the contact center to on-property operations.", href: "/vendors" }, { name: "Zingle (Medallia)", role: "Guest Messaging", why: "Two-way guest messaging across SMS, WhatsApp, and in-app. Pre-arrival, in-stay, and post-stay communication. Integrates with PMS for guest context.", href: "/vendors" }],
        pitfall: "Hotels deploy guest messaging but route all messages to the front desk, which is already overwhelmed during check-in/out peaks. In-stay service requests (towels, maintenance, concierge) should route to the specific department, not through a front desk bottleneck. Build department-specific routing for guest messages, not a single inbox."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Reservation search and modification bots with real-time availability","Loyalty point balance and redemption bots","Property information bots (amenities, hours, directions, parking)","Pre-arrival request bots (early check-in, late checkout, room preferences)","FAQ bots covering cancellation policies, pet policies, and fees"],
        vendors: "Ada, Cognigy, Quicktext, Asksuite", risk: "Bot confirming a room type that's not actually available",
        stack: [{ name: "Asksuite", role: "Hotel AI", why: "Purpose-built hospitality chatbot and booking engine. Handles reservation inquiries with real-time availability from the PMS. Multi-language. Designed for hotel revenue conversion, not just FAQ deflection.", href: "/vendors/iva" }, { name: "Ada", role: "AI Agent", why: "Handles loyalty lookups, property FAQ, and pre-arrival requests. Routes complex modifications and complaints to human agents with full context.", href: "/vendors/iva" }],
        pitfall: "Hotel booking bots must check real-time PMS availability, not cached inventory. A bot that offers a King Suite that's actually sold out creates a confirmation that the hotel can't honor, resulting in a downgrade at check-in and a furious guest. Integrate directly with the PMS booking engine (Oracle OPERA, Mews, Cloudbeds) for real-time inventory, not a nightly sync."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["PCI compliance for credit card guarantees and payment processing","Cancellation policy enforcement varying by rate type, channel, and loyalty tier","ADA/accessibility compliance for accommodation requests","Guest data privacy (GDPR for EU guests, CCPA for California)","OTA rate parity and commission management compliance"],
        vendors: "PCI compliance, custom policy logic", risk: "Inconsistent cancellation policy application creating guest disputes",
        stack: [{ name: "PMS policy engine", role: "Rate & Policy Rules", why: "The PMS (OPERA, Mews, Cloudbeds) holds the rate and cancellation rules. The agent desktop must surface these rules clearly, is this rate refundable? Is the guest within the cancellation window? What's the penalty?", href: "/vendors" }],
        pitfall: "Hotels sell rooms through many channels (direct website, OTAs, GDS, wholesalers, corporate programs): each with different cancellation policies, rate restrictions, and commission rules. An agent who can't quickly determine which policy applies to this specific booking will either apply the wrong policy (creating financial loss) or default to 'let me check and call you back' (destroying the guest experience). Surface the booking channel and policy in the agent desktop, not buried in the reservation notes."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Reservation creation and modification workflow with availability and pricing","Guest request workflow routing to housekeeping, F&B, or engineering","Service recovery workflow with compensation authority and tracking","Group block management workflow with room list and billing coordination","Loyalty enrollment, tier upgrade, and benefit delivery workflow"],
        vendors: "Oracle OPERA, Mews, Cloudbeds, Salesforce Hospitality", risk: "Service recovery offered inconsistently: one agent gives a free night, another gives nothing",
        stack: [{ name: "Oracle OPERA Cloud", role: "PMS", why: "A widely used PMS in full-service hotels. Reservation, front desk, housekeeping, and billing. Your CX stack integrates with OPERA for every guest-facing interaction.", href: "/vendors" }, { name: "Mews", role: "Cloud PMS", why: "Modern, API-first PMS gaining share in independent and lifestyle hotels. Better integration experience than legacy OPERA for CX technology partners.", href: "/vendors" }],
        pitfall: "Service recovery authority shapes hotel CX more than most settings. If agents must escalate every complaint to a manager for approval, response time stretches from minutes to hours, and the guest posts a negative review in the meantime. Define tiered recovery authority: agents can offer up to $X or Y benefit without approval, supervisors up to $XX, managers above that. Empower agents to resolve in real-time."
      },
      { layer: 1, name: "Data Access", capabilities: ["PMS integration: reservations, room status, guest profile, and billing","Loyalty program database: tier, points, preferences, and stay history","Revenue management system: pricing, availability, and restrictions","Guest profile with preferences, allergies, celebration dates, and past issues","Channel manager: OTA bookings, GDS reservations, and rate parity"],
        vendors: "Oracle OPERA, Mews, Cloudbeds, Amadeus (GDS), Salesforce", risk: "Guest profile fragmented across PMS, loyalty system, and CRM",
        stack: [{ name: "Oracle OPERA", role: "PMS", why: "The reservation and guest data foundation. Current stay, future reservations, past stays, preferences, and billing. Agent needs OPERA data for any guest interaction.", href: "/vendors" }, { name: "Salesforce Hospitality", role: "Guest CRM", why: "Unified guest profile across properties and brands. Connects loyalty data, interaction history, and preferences into a single relationship view.", href: "/vendors/ccaas" }],
        pitfall: "Hotels have a 'guest recognition' problem: the PMS knows the guest as a reservation, the loyalty system knows them as a member number, the CRM knows them as a contact, and the email system knows them as a subscriber. Without identity resolution linking these records, a Platinum member checks in and nobody recognizes them because the front desk sees a PMS record, not a loyalty profile. Unify guest identity across systems."
      },
    ],
  },

  "otas": {
    name: "Online Travel Agencies", parent: "Travel & Hospitality",
    tagline: "Multi-supplier booking support, price disputes, cancellation policies, and trip coordination.",
    intro: "OTA contact centers are intermediaries: they don't operate the flights, hotels, or cars they sell. Every support interaction involves at least two parties (the OTA and the supplier) and often three (OTA, airline, hotel). The CX challenge is resolving problems in systems the OTA doesn't control, with policies the OTA didn't set, for customers who hold the OTA responsible regardless.",
    kpis: [
      { metric: "AHT", avg: "[[trv.sv.otas.aht]]", note: "Multi-supplier coordination drives handle time" },
      { metric: "FCR", avg: "[[trv.sv.otas.fcr]]", note: "Resolution often waits on a supplier the agent does not control" },
      { metric: "CSAT", avg: "[[trv.sv.otas.csat]]", note: "Customers hold the OTA responsible for supplier failures" },
      { metric: "Containment", avg: "[[trv.sv.otas.containment]]", note: "Booking status can be automated; cancellation and refund disputes need people" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Supplier-specific complaint analytics identifying problematic partners","Refund and cancellation dispute volume by booking type and policy","Agent efficiency by supplier system, which supplier systems cause the most friction","Price guarantee claim tracking and competitive monitoring","Customer lifetime value correlation with support experience quality"],
        vendors: "NICE, Qualtrics, custom analytics", risk: "Supplier quality issues invisible until customer complaints aggregate",
        stack: [{ name: "NICE CXone", role: "Analytics & WEM", why: "High-volume OTA operations need combined analytics and workforce management. Identifies which supplier partners generate disproportionate support volume.", href: "/vendors/nice-cxone" }],
        pitfall: "OTAs track CSAT at the interaction level but not at the trip level. A traveler who books a flight, hotel, and car through the OTA might have great interactions with support about each, but their overall trip experience was terrible because the flight was delayed, the hotel overbooked, and the car wasn't available. Track trip-level NPS to understand the full customer experience, not just the support experience."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Booking type routing: flight, hotel, car, package, and multi-component trips","Supplier-specific routing matching agents to suppliers they're trained on","Urgent travel routing for same-day departures and active trips","Refund and dispute routing with policy and authority segmentation","Language routing across global booking origins"],
        vendors: "Genesys, NICE CXone, Amazon Connect", risk: "Package booking issues requiring an agent trained on several supplier systems",
        stack: [{ name: "Amazon Connect", role: "CCaaS", why: "Pay-per-use pricing suits OTA seasonal patterns. Built-in AI capabilities. AWS ecosystem enables custom integrations with multiple supplier APIs simultaneously.", href: "/vendors/amazon-connect" }, { name: "Genesys Cloud", role: "Enterprise CCaaS", why: "For large OTAs needing sophisticated multi-queue routing across booking types, languages, and supplier specializations. Handles the complexity of many supplier routing paths.", href: "/vendors/genesys" }],
        pitfall: "OTA agents must navigate supplier-specific systems: Amadeus/Sabre for airline changes, each hotel chain's extranet for hotel modifications, and car rental systems for vehicle changes. A flight, hotel and car package modification means one system per supplier. Train and route by supplier system expertise, not just by booking type: an agent who knows Amadeus well but can't navigate Hilton's extranet will fail on a package booking that involves both."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Booking confirmation and itinerary delivery across email, app, and messaging","Proactive trip disruption notifications aggregating supplier updates","In-app support with full itinerary context visible to agents","Supplier communication relay: mediating between guest and supplier","Price drop alerts and best-price guarantee claim processing"],
        vendors: "Zendesk, Intercom, LivePerson, Sprinklr", risk: "Supplier policy changes not reflected in OTA customer communications",
        stack: [{ name: "Zendesk", role: "Support Platform", why: "Multi-brand, multi-language support platform with strong workflow automation. Handles the ticket volume and complexity of large OTA operations. Good for managing supplier-related case escalations.", href: "/vendors" }],
        pitfall: "OTAs send booking confirmations with supplier policies (cancellation, check-in time, baggage allowance) at the time of booking. But supplier policies change: the hotel updates its cancellation policy, the airline changes its baggage rules. If the OTA's communication doesn't reflect the current supplier policy, the customer relies on outdated information and the OTA absorbs the complaint. Build dynamic policy retrieval, not static policy snapshots."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Booking status and itinerary bots across all suppliers in the trip","Cancellation and refund eligibility bots with supplier-specific policy logic","Flight status bots with rebooking suggestions for disrupted trips","Hotel and car alternative search bots when original booking is unavailable","FAQ bots covering OTA policies, price guarantees, and loyalty programs"],
        vendors: "Ada, Cognigy, [24]7.ai", risk: "Bot stating a refund policy that differs from the supplier's current policy",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles booking status, cancellation eligibility, and FAQ across all product types. Routes complex multi-supplier issues to human agents with full trip context.", href: "/vendors/iva" }],
        pitfall: "OTA bots face a unique challenge: the cancellation policy is not the OTA's, it's the supplier's. A bot that says 'this booking is non-refundable' must be querying the supplier's current policy, not a cached version. If the supplier has updated their policy to allow free cancellation (as many did during COVID) and the bot still shows 'non-refundable,' the OTA loses the customer's trust and potentially violates consumer protection laws."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Consumer protection compliance varying by booking origin country","PCI compliance for multi-supplier payment processing","Price guarantee and best-price claim validation","Supplier contractual compliance for refund and modification handling","GDPR/privacy compliance for EU travelers across global operations"],
        vendors: "Custom compliance, PCI vendors", risk: "Consumer protection violations from incorrect refund policy application",
        stack: [{ name: "Custom policy engine", role: "Policy Management", why: "OTAs need a policy engine that evaluates: booking origin country (consumer protection), supplier policy (cancellation terms), OTA policy (best-price guarantee), and loyalty status (override rules). OTAs typically build it themselves.", href: "/vendors" }],
        pitfall: "Consumer protection rules vary by country, and each rule sets its own scope. EU Regulation 261/2004 follows the flight's [[trv.eu261.scope]], whatever the traveler's residence: it covers departures from an EU airport, and flights into the EU on an EU carrier. The EU Package Travel Directive covers packages, and a Brazilian customer has protections under the Consumer Defense Code. Your agent handling a cancellation must know which rules apply to this booking. Build jurisdiction-aware policy logic."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Multi-supplier booking modification workflow coordinating changes across all components","Refund processing workflow with supplier refund tracking and customer credit","Trip disruption rebooking workflow across alternative flights, hotels, and cars","Best-price guarantee claim workflow with competitive rate verification","Supplier dispute escalation workflow for unresolved guest complaints"],
        vendors: "Salesforce, custom booking platform, Amadeus, Sabre", risk: "Refund from supplier taking weeks while customer expects immediate credit",
        stack: [{ name: "Amadeus / Sabre", role: "GDS", why: "Flight booking, modification, and cancellation flow through the GDS. OTA agents need GDS access for airline changes: the OTA's own system is a layer on top of the GDS, not a replacement.", href: "/vendors" }],
        pitfall: "OTA refund workflows have a timing mismatch. The rules set clocks travelers can see: a US airline that is merchant of record owes a card refund within [[trv.dot.refund.card]] ([[trv.dot.refund.other]] for other payment), and EU261 sets [[trv.eu261.refund]] for a cancelled flight. A supplier refund can take [[trv.ota.supplier.lag]] to reach the OTA, and the OTA is stuck in the middle. Offer the customer an immediate OTA credit or voucher while the supplier refund processes in the background. This costs working capital but prevents chargebacks (which cost more) and preserves the customer relationship."
      },
      { layer: 1, name: "Data Access", capabilities: ["GDS integration for flight reservations, modifications, and cancellations","Hotel extranet/channel manager connectivity for room bookings","Car rental API integration for reservation management","Customer profile with booking history, preferences, and loyalty","Payment platform for multi-currency, multi-supplier transactions"],
        vendors: "Amadeus, Sabre, Travelport, custom booking platform", risk: "Agent seeing OTA booking data but not supplier-side confirmation status",
        stack: [{ name: "Amadeus/Sabre/Travelport", role: "GDS", why: "Flight content, booking, and modification APIs. The data backbone for every air-related OTA interaction. Real-time PNR access is essential.", href: "/vendors" }, { name: "Custom OTA platform", role: "Booking Engine", why: "Most large OTAs (Booking, Expedia, Trip) run proprietary booking platforms that aggregate GDS, direct hotel connections, and car rental APIs. The agent desktop renders data from this platform.", href: "/vendors" }],
        pitfall: "OTA agents face heavy data fragmentation: flight data in the GDS, hotel data in the hotel's extranet, car data in the rental company's API, and package data in the OTA's own system. A customer calling about a flight+hotel package needs the agent to see both, but the systems are separate. Build a unified trip view that shows all components of the booking in one screen, with status from each supplier's system."
      },
    ],
  },

  "car-rental": {
    name: "Car Rental & Ground Transport", parent: "Travel & Hospitality",
    tagline: "Reservations, vehicle issues, roadside assistance, damage disputes, and loyalty.",
    intro: "Car rental contact centers handle two distinct moments: pre-rental (reservations, modifications, loyalty) and during/post-rental (roadside assistance, damage disputes, billing). The during-rental moment carries the highest stakes: a renter stranded on a highway or dealing with a mechanical issue needs immediate, competent help.",
    kpis: [
      { metric: "AHT", avg: "[[trv.sv.car-rental.aht]]", note: "Reservations are fast; damage disputes are long" },
      { metric: "FCR", avg: "[[trv.sv.car-rental.fcr]]", note: "Reservations resolve on the call; damage disputes need investigation" },
      { metric: "CSAT", avg: "[[trv.sv.car-rental.csat]]", note: "Moves with the counter experience and damage dispute handling" },
      { metric: "Containment", avg: "[[trv.sv.car-rental.containment]]", note: "Reservation changes and loyalty lookups can be automated" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Location-specific satisfaction tracking by branch and region","Damage claim dispute analytics with resolution outcomes","Roadside assistance response time and resolution quality","Upsell conversion analytics for insurance, GPS, and vehicle upgrades","Loyalty program engagement and tier movement analytics"],
        vendors: "NICE, Qualtrics, custom BI", risk: "Branch-level service quality issues invisible at the corporate level",
        stack: [{ name: "NICE CXone", role: "Analytics & QA", why: "Multi-location analytics connecting contact center interactions to branch-level satisfaction. Identifies which locations generate disproportionate complaints.", href: "/vendors/nice-cxone" }],
        pitfall: "Car rental satisfaction is driven by the counter experience (wait time, vehicle availability, upsell pressure) more than the contact center experience. But the contact center absorbs the complaints. Analytics must connect contact center complaint data to specific branch operations. [[trv.ex.car.branch]]"
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Roadside emergency routing with immediate dispatch priority","Reservation vs active-rental vs post-rental routing","Damage dispute routing to trained claims handlers","Loyalty tier routing for elite member priority","Location-specific routing for branch hours and availability"],
        vendors: "Genesys, NICE CXone, Five9", risk: "Roadside emergency calls waiting in the general reservation queue",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Roadside assistance requires instant routing to trained agents with dispatch capability. Genesys handles the urgency-based routing that separates a stranded renter from a reservation change.", href: "/vendors/genesys" }],
        pitfall: "Roadside assistance calls carry the most urgency in car rental: a renter broken down on a highway is in a safety situation. These calls should bypass the IVR and reach a live agent within [[trv.roadside.answer]]. Routing roadside through the same IVR as reservations is a common gap. Build a dedicated roadside number or a single-press IVR escape that guarantees immediate human response."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Reservation confirmation with pickup location, hours, and requirements","Pre-rental digital check-in with license upload and payment verification","Real-time vehicle swap requests via messaging during the rental","Damage reporting with photo upload at vehicle return","Post-rental billing explanation and dispute submission"],
        vendors: "Ada, custom apps, Zendesk", risk: "Damage disputes communicated only by mail weeks after the rental ends",
        stack: [{ name: "Custom mobile app", role: "Renter Experience", why: "Enterprise, Hertz, and Avis all offer mobile check-in, keyless access, and in-app support. The app IS the CX layer for car rental: contact center volume correlates directly with app friction.", href: "/vendors" }],
        pitfall: "Damage charges are a leading source of car rental complaints and chargebacks. A renter who first learns of a damage charge from a card statement weeks after the rental has no context, just a charge. Implement same-day damage notification with photos and a digital dispute submission path, so the renter sees the alleged damage at return. Track your own dispute and chargeback rates before and after."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Reservation creation and modification bots with availability and pricing","Vehicle availability bots by location, class, and date","Loyalty point balance and free rental day bots","FAQ bots covering insurance, fuel policy, driver requirements, and fees","Receipt and invoice request automation"],
        vendors: "Ada, custom bots", risk: "Bot confirming vehicle class that's unavailable at the pickup location",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles reservation search, modification, loyalty lookups, and FAQ. Routes damage disputes and roadside to human agents immediately. Good balance of automation and escalation.", href: "/vendors/iva" }],
        pitfall: "Car rental inventory is not like hotel inventory: it's fluid. A 'full-size sedan' reservation doesn't guarantee a specific vehicle; it guarantees a vehicle class. A bot that says 'your full-size sedan is confirmed' is technically correct but may disappoint the renter who expected a specific car. Set expectations correctly: 'You're confirmed for a full-size sedan or equivalent. Specific vehicle assigned at pickup based on availability.'"
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Insurance and damage waiver disclosure compliance","Age and driver qualification enforcement by jurisdiction","PCI compliance for payment processing and deposits","International rental policy enforcement (cross-border, one-way)","State-specific fee disclosure requirements"],
        vendors: "Custom policy compliance", risk: "Insurance disclosure non-compliance creating consumer protection complaints",
        stack: [{ name: "Custom compliance", role: "Policy Management", why: "Car rental insurance disclosure requirements vary by state and country. The agent must explain CDW/LDW options without pressuring the renter: a fine line between informing and upselling that regulators watch closely.", href: "/vendors" }],
        pitfall: "Car rental counter staff are often compensated on insurance upsell, creating an incentive that conflicts with customer trust. When renters feel pressured into insurance they don't need, they complain to the contact center after the rental. The contact center can't refund the insurance without undermining the branch. Align incentives: reward staff for insurance attachment rate only when the renter keeps the coverage (doesn't dispute it later), not just for selling it."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Reservation workflow with vehicle class, location, and add-on selection","Check-in workflow with license verification, payment, and agreement signature","Vehicle swap workflow during active rental","Damage claim workflow with photo evidence, assessment, and dispute handling","Roadside assistance dispatch workflow with location tracking and ETA"],
        vendors: "Custom fleet management, Salesforce", risk: "Damage claim process running for weeks without status updates",
        stack: [{ name: "Custom fleet/rental platform", role: "Rental Operations", why: "Enterprise (ARM), Hertz, and Avis run proprietary rental management systems. Reservation, fleet, pricing, and damage management in one platform. CX integration connects the contact center to this operational backbone.", href: "/vendors" }],
        pitfall: "Roadside assistance dispatch requires real-time renter location, vehicle identification, and towing/service provider coordination. Car rental roadside is often handled by a third-party roadside network (Agero, AAA). The handoff from the contact center to the roadside provider is where information gets lost: the renter explains the problem to the agent, the agent submits a dispatch, the roadside provider calls the renter to re-confirm details. Implement direct data passing from contact center to roadside dispatch to eliminate the redundant callback."
      },
      { layer: 1, name: "Data Access", capabilities: ["Fleet management system: vehicle inventory, status, and location","Reservation system: bookings, modifications, and pricing","Customer profile with rental history, loyalty tier, and preferences","Damage and claims database with photos and dispute status","Roadside assistance dispatch with provider network and ETA tracking"],
        vendors: "Custom rental platforms, Salesforce", risk: "Agent seeing reservation data but not fleet availability at the pickup location",
        stack: [{ name: "Custom rental platform", role: "Core Operations", why: "Car rental operations run on proprietary platforms built over decades. The contact center integrates with this platform for every interaction: reservations, modifications, damage, and billing.", href: "/vendors" }],
        pitfall: "Car rental agents need real-time fleet visibility, not just reservation data. When a customer calls to modify a reservation to a larger vehicle class, the agent needs to know whether that class is available at that location on that date. Without fleet-level availability (not just reservation inventory), the agent confirms modifications that the branch can't fulfill, creating counter-experience failures."
      },
    ],
  },

  "cruise-lines": {
    name: "Cruise Lines", parent: "Travel & Hospitality",
    tagline: "Booking, shore excursions, onboard services, health protocols, and itinerary changes.",
    intro: "Cruise contact centers manage a long sales cycle: guests often book many months ahead, then customize their trip with dining, excursions, and onboard packages. The CX challenge is keeping guests engaged over a long planning period while handling the operational complexity of a floating hotel with thousands of guests and crew.",
    kpis: [
      { metric: "AHT", avg: "[[trv.sv.cruise-lines.aht]]", note: "Cabins, dining, excursions and packages make bookings long" },
      { metric: "FCR", avg: "[[trv.sv.cruise-lines.fcr]]", note: "Many calls are iterative planning conversations rather than problems to close" },
      { metric: "CSAT", avg: "[[trv.sv.cruise-lines.csat]]", note: "Moves with pre-cruise planning support and embarkation-day problems" },
      { metric: "Containment", avg: "[[trv.sv.cruise-lines.containment]]", note: "Guests planning a high-value trip often want a person to guide them" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Booking conversion analytics from inquiry through deposit through final payment","Pre-cruise engagement scoring predicting onboard spend","Post-cruise satisfaction by ship, itinerary, and cabin category","Travel agent commission and booking channel analytics","Repeat booking and loyalty program performance tracking"],
        vendors: "NICE, Medallia, Qualtrics", risk: "Pre-cruise excitement dropping during the long planning period without engagement",
        stack: [{ name: "Medallia", role: "Guest Experience", why: "Post-cruise survey analytics connecting onboard experience to rebooking likelihood. Identifies which aspects of the cruise experience (dining, entertainment, shore excursions, service) drive the most loyalty.", href: "/vendors/analytics" }],
        pitfall: "Cruise lines measure post-cruise satisfaction but rarely pre-cruise engagement. The months between booking and sailing are where excitement builds or wanes. [[trv.ex.cruise.silence]] Either one erodes the anticipation. Track engagement touchpoints, portal logins, excursion research, dining selections, as leading indicators of satisfaction."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Travel agent vs direct guest routing with different service models","Pre-cruise planning routing to experienced vacation planners","Embarkation-day routing for check-in issues and travel disruptions","Onboard service routing to shipboard guest services","Post-cruise routing for lost items, billing disputes, and rebooking"],
        vendors: "Genesys, NICE CXone", risk: "Travel agent and direct guest queries competing for the same agents",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Handles the complexity of cruise routing, separating travel agent support (B2B, commission-focused) from direct guest support (B2C, experience-focused). Multi-language for international sailings.", href: "/vendors/genesys" }],
        pitfall: "Cruise lines sell a large share of cabins through travel agents, yet contact centers often treat agent calls and guest calls the same. Travel agents have different needs (group bookings, commission inquiries, cabin holds), different system access (agent portal), and different relationship dynamics (B2B partnership). Build a dedicated trade support team with agents trained on the agency relationship, not just the booking system."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Pre-cruise countdown communications building anticipation","Shore excursion booking and modification via web and app","Dining and beverage package selection through digital channels","Embarkation day check-in assistance via messaging","Post-cruise photo, feedback, and rebooking communications"],
        vendors: "Custom cruise app, Medallia, LivePerson", risk: "Pre-cruise communications feeling like upsell rather than excitement-building",
        stack: [{ name: "Custom cruise app/portal", role: "Guest Planning", why: "Royal Caribbean, Carnival, and NCL all run their own apps for pre-cruise planning (excursions, dining, spa), onboard services (daily schedule, chat, ordering), and post-cruise engagement. Planning calls are the volume an app can take on; measure your own planning contacts per booking before and after.", href: "/vendors" }],
        pitfall: "Cruise pre-departure communications walk a fine line between building excitement and pushing upsells. If every email is 'upgrade your beverage package!' and 'don't miss our premium excursions!', guests feel monetized rather than valued. Alternate promotional content with genuine trip preparation: what to pack, port information, embarkation tips, dining recommendations. The goal is anticipation, not anxiety about spending."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Cabin availability and pricing bots with real-time inventory","Shore excursion search and booking bots with port-day scheduling","Dining reservation and package comparison bots","Embarkation document requirement bots (passport, visa, health)","FAQ bots covering dress code, onboard currency, connectivity, and policies"],
        vendors: "Ada, custom bots", risk: "Bot booking excursions that conflict with dining times or other activities",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles cabin search, excursion FAQ, and document requirements. Routes complex multi-cabin group bookings and itinerary changes to human agents. Good for managing the high volume of pre-cruise planning queries.", href: "/vendors/iva" }],
        pitfall: "Cruise planning bots must understand the interconnected nature of the cruise schedule. [[trv.ex.cruise.dining]] Build schedule-aware booking logic that checks for conflicts across excursions, dining, spa, and ship departure times before confirming any activity."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Maritime health and safety compliance for boarding requirements","International travel document verification (passport, visa, vaccination)","Cancellation and refund policy enforcement by booking type and timing","Accessibility accommodation requirements under maritime law","Guest conduct policy enforcement and documentation"],
        vendors: "Custom compliance, maritime law", risk: "Guest denied boarding due to document requirements not communicated clearly",
        stack: [{ name: "Custom compliance system", role: "Maritime & Travel Docs", why: "Cruise documentation requirements vary by itinerary, nationality, and port country. Passport validity, visa requirements, and health documentation must be verified before boarding. Most cruise lines build custom document checkers.", href: "/vendors" }],
        pitfall: "A guest denied boarding because their passport falls short of the validity a port country requires is among the hardest failures in travel to recover from. The guest planned for months, traveled to the port, and was turned away. Proactive document checks at [[trv.cruise.docchecks]] before sailing catch these issues while there is still time to fix them."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Multi-cabin group booking workflow with deposit and payment tracking","Shore excursion booking workflow with capacity and schedule validation","Cancellation and rebooking workflow with penalty calculation","Special occasion package workflow (honeymoon, anniversary, birthday)","Future cruise credit application and redemption workflow"],
        vendors: "Custom cruise reservation system, Salesforce", risk: "Group booking coordination failing across many cabins with different payment schedules",
        stack: [{ name: "Custom reservation system", role: "Cruise Operations", why: "Major cruise lines (Royal Caribbean, Carnival, NCL, MSC) run proprietary reservation systems. Cabin inventory, pricing, dining allocation, and excursion capacity managed in one platform. CX integrates at the API layer.", href: "/vendors" }],
        pitfall: "Future cruise credits (FCCs) issued during COVID became a major operational burden in cruise CX. Complex rules around FCC value, sailing date restrictions, and combinability confused guests and agents alike. Any future disruption that generates mass credits must include a simple, transparent redemption process built into the booking workflow from day one, not bolted on after thousands of guests start calling."
      },
      { layer: 1, name: "Data Access", capabilities: ["Reservation system: cabin, sailing, guests, dining, and packages","Shore excursion inventory with port schedules and capacity","Guest profile with sailing history, preferences, and loyalty tier","Embarkation system: check-in status, document verification, and boarding","Onboard folio: charges, credits, and real-time spending"],
        vendors: "Custom cruise platforms, Fidelio Cruise (Oracle)", risk: "Pre-cruise and onboard systems disconnected: agent can't see what guest booked in port",
        stack: [{ name: "Custom cruise platform", role: "Core Reservation", why: "Each major cruise line operates a proprietary reservation system refined over decades. The contact center agent's entire capability is determined by what this system exposes: bookings, modifications, cancellations, and guest preferences.", href: "/vendors" }, { name: "Fidelio Cruise (Oracle)", role: "Onboard PMS", why: "Onboard property management: cabin assignments, dining, folio management, and guest services. The system that runs the ship. Pre-cruise contact center needs visibility into onboard systems for excursion and dining reservations.", href: "/vendors" }],
        pitfall: "Cruise data spans two worlds: shoreside (reservations, pre-cruise planning, marketing) and shipboard (onboard services, folio, daily operations). When the ship is at sea, connectivity is limited and data sync is delayed. [[trv.ex.cruise.sync]] The data has not synced yet. Build near-real-time sync between shoreside and shipboard systems, especially for time-sensitive bookings."
      },
    ],
  },

  "tours-experiences": {
    name: "Tours & Experiences", parent: "Travel & Hospitality",
    tagline: "Activity booking, schedule changes, weather cancellations, and local guide communication.",
    intro: "Tours and experiences contact centers support travelers in real-time, often in unfamiliar destinations. A customer who booked a snorkeling tour in Cancún and can't find the meeting point needs help within minutes. The CX challenge is providing responsive, multilingual, timezone-spanning support for activities that happen once and can't be repeated.",
    kpis: [
      { metric: "AHT", avg: "[[trv.sv.tours-experiences.aht]]", note: "Booking changes and activity information are simple to handle" },
      { metric: "FCR", avg: "[[trv.sv.tours-experiences.fcr]]", note: "Booking changes resolve on the call; weather cancellations need alternatives" },
      { metric: "CSAT", avg: "[[trv.sv.tours-experiences.csat]]", note: "Moves with day-of responsiveness and weather handling" },
      { metric: "Containment", avg: "[[trv.sv.tours-experiences.containment]]", note: "Booking status and activity information can be automated; day-of changes need people" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Activity satisfaction by experience type, location, and operator","Cancellation and weather impact analytics by season and destination","Operator quality scoring based on guest reviews and complaint patterns","Revenue analytics by destination, season, and booking channel","Guide and operator NPS tracking with performance management"],
        vendors: "Custom analytics, Qualtrics", risk: "Operator quality issues hidden until negative reviews aggregate",
        stack: [{ name: "Custom BI / Looker", role: "Operations Analytics", why: "Tours and experiences analytics are unique: satisfaction varies by weather, guide quality, group size, and seasonality. General CX analytics tools often lack that data model, so platforms tend to build their own.", href: "/vendors" }],
        pitfall: "Satisfaction with tours and experiences swings with weather, guide, and group composition. [[trv.ex.tours.rating]] Track satisfaction at the departure level (specific date and guide) as well as the product level; a single weak guide needs a guide intervention rather than a product change."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Same-day activity routing with immediate response for active travelers","Timezone-aware routing matching callers to agents in appropriate hours","Destination-specific routing to agents with local knowledge","Weather cancellation routing during high-impact events","Operator escalation routing for safety or quality incidents"],
        vendors: "Zendesk, Intercom, NICE CXone", risk: "Traveler needing help early in the local morning reaching an agent in a different timezone",
        stack: [{ name: "Zendesk", role: "Support Platform", why: "Multi-timezone support with structured ticketing. Good for managing the mix of advance bookings and day-of urgent requests across global destinations.", href: "/vendors" }, { name: "Intercom", role: "In-App Support", why: "In-app messaging for mobile-first travelers. Full booking context visible to agents. Good for real-time support during the activity day.", href: "/vendors/digital-engagement" }],
        pitfall: "Tours and experiences support is inherently timezone-fragmented. [[trv.ex.tours.tz]] Follow-the-sun support closes these gaps; a single-timezone team leaves them open. Map your booking destinations against your support hours and staff accordingly."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Booking confirmation with meeting point, time, and preparation instructions","Day-before reminder with weather forecast and what-to-bring guidance","Real-time messaging between traveler and local operator/guide","Weather cancellation notifications with alternative suggestions","Post-experience review solicitation and photo sharing"],
        vendors: "WhatsApp Business, custom messaging, Zendesk", risk: "Traveler unable to reach support or guide on the day of the activity",
        stack: [{ name: "WhatsApp Business", role: "Traveler Messaging", why: "WhatsApp is widely used by international travelers. Meeting point directions, last-minute changes, and real-time guide communication often flow through WhatsApp outside the US.", href: "/vendors" }],
        pitfall: "Meeting point communication is a make-or-break touchpoint for tours and experiences. A traveler who can't find the meeting point misses the tour: a total experience failure. Send the meeting point with GPS coordinates, a photo of the location, and the guide's WhatsApp number [[trv.tours.meeting]] before the start. Static addresses ('in front of the church') are insufficient in unfamiliar destinations."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Activity search and booking bots by destination, date, and interest","Availability check bots with real-time operator inventory","Booking modification and cancellation bots with policy enforcement","Weather-based alternative suggestion bots","FAQ bots covering what to bring, fitness requirements, and cancellation policies"],
        vendors: "Ada, custom bots", risk: "Bot booking an activity that's weather-dependent without weather disclosure",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles booking search, availability checks, and FAQ across destinations. Routes day-of issues and weather cancellations to human agents who can find alternatives.", href: "/vendors/iva" }],
        pitfall: "Weather-dependent activities (snorkeling, hiking, sailing, hot air balloons) have cancellation policies triggered by weather conditions the operator assesses in real-time. A bot that says 'your booking is confirmed' without disclosing 'this activity may be cancelled due to weather with X refund policy' creates false expectations. All weather-dependent bookings must include the weather cancellation policy in the confirmation."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Cancellation policy enforcement varying by operator and activity type","Liability waiver management for adventure and physical activities","Insurance and safety certification verification for operators","Consumer protection compliance across booking jurisdictions","Guide and operator background check and certification tracking"],
        vendors: "Custom compliance", risk: "Safety incident with an unvetted operator creating liability exposure",
        stack: [{ name: "Custom operator management", role: "Safety & Compliance", why: "Viator, GetYourGuide, and Klook all run proprietary operator vetting systems. Safety certifications, insurance verification, and quality standards enforcement. The compliance layer that protects both travelers and the platform.", href: "/vendors" }],
        pitfall: "Tours and experiences platforms face real safety liability. If a platform lists a scuba operator whose equipment fails and a traveler is injured, the platform may share liability even though it didn't operate the tour. Operator vetting (insurance verification, safety certification, incident history) is the compliance foundation. A vetting gap is an existential risk."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Booking workflow with operator confirmation and traveler notification","Weather cancellation workflow with refund or rebooking options","Group booking coordination workflow for families and tour groups","Operator onboarding workflow with vetting, listing, and pricing","Review and quality management workflow with operator feedback"],
        vendors: "Custom platforms, Salesforce", risk: "Weather cancellation refunds taking a week or more during peak season",
        stack: [{ name: "Custom tour platform", role: "Booking Operations", why: "Viator (Tripadvisor), GetYourGuide, Klook, and Airbnb Experiences run proprietary platforms managing operator relationships, inventory, pricing, and booking fulfillment. Contact center agents operate within these platforms.", href: "/vendors" }],
        pitfall: "Weather cancellation surges can overwhelm a tour platform's support capacity. [[trv.ex.tours.weather]] Build automated weather cancellation processing: when a weather event is declared, bulk-cancel affected bookings, auto-refund (or offer credit), and notify travelers before they call."
      },
      { layer: 1, name: "Data Access", capabilities: ["Activity inventory with real-time availability and pricing by operator","Operator database with contact info, certifications, and performance history","Booking platform with reservation status and traveler details","Weather data integration for destination-specific forecasting","Traveler profile with booking history, preferences, and reviews"],
        vendors: "Custom platforms, weather APIs, operator management systems", risk: "Real-time availability not syncing with operator's actual capacity",
        stack: [{ name: "Custom booking platform", role: "Core Data", why: "Tour platforms aggregate inventory from thousands of operators. Real-time availability is the critical data challenge: a small operator might update availability by hand once a day, creating overbooking risk.", href: "/vendors" }],
        pitfall: "Tours and experiences inventory management is fundamentally different from hotels or airlines. A hotel room either exists or doesn't; an airline seat is in a reservation system. A kayak tour's capacity depends on how many kayaks are available, how many guides showed up, and whether the tide is right. Real-time availability from small operators is often a manual phone call, not an API. The gap between 'the system says available' and 'the operator actually has capacity' is a leading source of day-of failures."
      },
    ],
  },
};

export const getTravelSubVertical = (slug) => (Object.prototype.hasOwnProperty.call(travelSubVerticals, slug) ? travelSubVerticals[slug] : undefined);
export const getAllTravelSubVerticalSlugs = () => Object.keys(travelSubVerticals);
