export const utilitiesSubVerticals = {
  "electric-iou": {
    name: "Electric Utilities (IOU)", parent: "Utilities & Energy",
    tagline: "Outage management, billing, service activation, energy efficiency, and storm response.",
    intro: "Electric IOU contact centers face the most extreme volume variability in any industry. A sunny Tuesday generates 3,000 calls; a Category 3 hurricane generates 300,000 in 48 hours. The CX challenge is building for crisis while delivering on everyday service — billing inquiries, start/stop, and energy programs — with agents trained for both.",
    kpis: [
      { metric: "AHT", avg: "7:30", note: "Moderate — billing explanations are long; outage reports are short" },
      { metric: "FCR", avg: "62%", note: "Below average — outages and field work require follow-up" },
      { metric: "CSAT", avg: "72", note: "ACSI score — drops 5-10 points during/after major storms" },
      { metric: "Storm Surge", avg: "10-50x", note: "Most extreme volume variability of any industry" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["J.D. Power satisfaction tracking tied to outage communication quality","Storm response analytics — call volume, wait time, abandonment by storm phase","Bill complaint root cause by rate component and customer segment","Energy efficiency program enrollment and participation analytics","PUC complaint tracking with regulatory response compliance"],
        vendors: "NICE, Verint, J.D. Power, Kubra", risk: "J.D. Power scores declining without understanding which operational failure is causing it",
        stack: [{ name: "NICE Nexidia", role: "Interaction Analytics", why: "Storm-period QA at scale — automated scoring of every outage call even during 50x volume. Identifies agents who provide incorrect restoration estimates or miss safety protocols.", href: "/vendors/analytics" }, { name: "J.D. Power", role: "Satisfaction Benchmarks", why: "Industry standard utility satisfaction measurement. Residential and business studies provide competitive benchmarks. Utilities are ranked and rated publicly — scores affect regulatory perception.", href: "/vendors" }],
        pitfall: "J.D. Power scores for electric utilities are heavily influenced by outage communication — satisfaction is 210 points higher (on 1,000-point scale) when customers receive 5+ outage communications. Most utilities invest in network reliability to improve J.D. Power scores when the faster, cheaper lever is outage communication. Fix the communication before you fix the grid."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Storm IVR intercept with geographic outage status and ETR","Priority routing for wire-down, gas leak, and life-threatening situations","Billing vs outage vs service routing separating call types","High-bill season routing with dedicated bill explanation agents","Medical baseline and life support equipment priority routing"],
        vendors: "Genesys, NICE CXone, Cisco, Avaya", risk: "Life-threatening wire-down call waiting behind billing inquiry during storm",
        stack: [{ name: "Genesys Cloud", role: "Primary CCaaS", why: "Storm routing with geographic caller identification. Matches caller's location to known outage areas and plays area-specific restoration estimates before the caller reaches an agent. Reduces agent-handled storm calls by 40-60%.", href: "/vendors/genesys" }, { name: "NICE CXone", role: "Primary CCaaS", why: "WEM for storm staffing — rapid schedule changes, overtime management, and BPO overflow activation. Handles the workforce side of storm response that Genesys handles on the routing side.", href: "/vendors/nice-cxone" }],
        pitfall: "Wire-down and gas leak calls are life-safety calls that must bypass every queue and reach a trained dispatcher immediately. Most utility IVRs bury the 'downed wire' option 3 levels deep in a menu tree. Build a single-press IVR escape ('Press 1 if you see a downed power line or smell gas') that routes to dispatch with zero wait. This is not a CX decision — it's a safety decision."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Proactive outage notifications via SMS, email, app push, and automated voice","Interactive outage map with real-time restoration status","Bill comparison tools showing month-over-month and year-over-year usage","Payment arrangement self-service with flexible plan options","Energy efficiency program enrollment and rebate tracking"],
        vendors: "Kubra, Notifi (Questline), Bidgely, Ada", risk: "Customers learning about outages by losing power rather than receiving notification",
        stack: [{ name: "Kubra", role: "Utility CX Platform", why: "Purpose-built for utilities. Outage notifications, bill presentment, payment processing, and proactive communications. The standard for utility customer communications.", href: "/vendors" }, { name: "Bidgely", role: "Energy Analytics", why: "AI-powered energy disaggregation — shows customers which appliances drive their bill. Turns 'why is my bill so high?' from a complaint into a self-service discovery. Reduces high-bill calls by 15-25%.", href: "/vendors" }],
        pitfall: "Proactive outage notifications only work if they include an estimated time of restoration (ETR). 'We're aware of an outage in your area' without an ETR generates a call — the customer wants to know when power will be restored. Include ETR in every notification, update it as the estimate changes, and notify again when power is restored. Kubra and utility OMS platforms can automate this end-to-end."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Outage status bots with real-time OMS data and estimated restoration","Bill explanation bots breaking down charges by rate component","Payment arrangement bots with flexible plan creation","Move/start/stop service bots with date scheduling and deposit calculation","Energy efficiency program eligibility bots"],
        vendors: "Cognigy, Ada, Google CCAI", risk: "Bot providing incorrect restoration estimate that the customer relies on",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles outage status (with real-time OMS integration), billing FAQ, payment arrangements, and move/start/stop. Routes high-bill complaints and payment difficulty to human agents with empathy training.", href: "/vendors/iva" }, { name: "Cognigy", role: "Conversational AI", why: "Enterprise-grade IVA with utility-specific intents. Handles the complex bill explanation conversations that require understanding of rate structures, demand charges, and seasonal adjustments.", href: "/vendors/iva" }],
        pitfall: "Outage bots must pull from the OMS (Outage Management System) in real-time — not from a status page that updates every 15 minutes. A customer whose power went out 5 minutes ago calling a bot that says 'no known outages in your area' because the OMS hasn't refreshed destroys trust. Integrate with the OMS event stream, not the OMS status page."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["PUC disconnection rules — winter moratoriums, medical protections, income-based deferrals","Rate case compliance ensuring agents quote current approved rates","CARE/LIHEAP/LIPP payment assistance program eligibility enforcement","Customer data privacy (CPNI equivalent for utilities)","Safety protocols for wire-down, gas odor, and meter access reports"],
        vendors: "Oracle Utilities compliance, PUC-specific", risk: "Disconnecting a customer protected by medical baseline or winter moratorium",
        stack: [{ name: "Oracle CC&B", role: "CIS & Compliance", why: "Customer Information System with embedded disconnection rules, payment program eligibility, and regulatory compliance logic. The system prevents illegal disconnections if configured correctly.", href: "/vendors" }],
        pitfall: "Disconnection rules are the most consequential compliance requirement in utilities. Disconnecting a customer on medical baseline life support equipment can create a fatality. Disconnecting during a winter moratorium creates regulatory violation and public outcry. Your CIS must have hard stops — not soft warnings — that prevent agents from initiating disconnection for protected accounts. This is not a training issue; it's a system design issue."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Outage management workflow — report, verify, dispatch, restore, confirm, notify","Move/start/stop/transfer service workflow with meter reading and deposit","Payment arrangement workflow with regulatory-compliant terms","High-bill investigation workflow with usage analysis and meter verification","Field service dispatch workflow for connects, disconnects, and investigations"],
        vendors: "Oracle Utilities, SAP IS-U, Itron, ServiceNow", risk: "Outage-to-restoration workflow not updating customers at each stage",
        stack: [{ name: "Oracle Utilities (CC&B + WAM + OMS)", role: "Utility Operations", why: "Customer Care & Billing, Work & Asset Management, and Outage Management — the operational trilogy for electric utilities. Your CX stack integrates with all three.", href: "/vendors" }, { name: "ServiceNow", role: "Field Service Management", why: "Coordinates field crew dispatch, work order management, and customer notification. Bridges the gap between the OMS (which knows what's broken) and the customer (who wants to know when it's fixed).", href: "/vendors" }],
        pitfall: "The outage workflow has 6 stages: report → verify → dispatch crew → arrive on site → work in progress → restore power. Most utilities notify customers at stage 1 (we know about it) and stage 6 (power restored). The customer hears nothing for stages 2-5 — which can last 12-72 hours during a major storm. Add notifications at dispatch (crew assigned), arrival (crew on site), and progress (estimated restoration updated). Each notification reduces a callback."
      },
      { layer: 1, name: "Data Access", capabilities: ["CIS — customer account, billing, payment history, rate schedule","OMS — real-time outage status, crew assignment, estimated restoration","MDMS — smart meter data for usage analysis and high-bill investigation","GIS — network topology, service territory mapping, outage area correlation","Field service — work orders, crew location, dispatch status"],
        vendors: "Oracle CC&B, SAP IS-U, Itron, ESRI, Milsoft", risk: "Agent seeing billing data but not outage data — can't answer the #1 question",
        stack: [{ name: "Oracle CC&B", role: "CIS", why: "Customer Information System — the billing, account, and payment foundation. Every billing and payment interaction starts here.", href: "/vendors" }, { name: "Itron", role: "MDMS & Smart Meters", why: "Meter Data Management System. Smart meter data enables high-bill investigation without truck rolls. Agent can see actual usage patterns in 15-minute intervals — proving whether the bill is accurate.", href: "/vendors" }, { name: "ESRI (ArcGIS)", role: "GIS", why: "Geographic Information System mapping the electric network. When a customer reports an outage, GIS maps their location to the affected circuit. Powers the outage map and geographic IVR routing.", href: "/vendors" }],
        pitfall: "The utility agent desktop problem: CIS for billing, OMS for outages, MDMS for meter data, GIS for location, and FSM for dispatch — five systems with five logins. When a customer calls during a storm and says 'my power is out and my bill is too high,' the agent needs OMS (outage status), CIS (billing), and MDMS (usage data) simultaneously. Salesforce Energy & Utilities Cloud attempts to unify this — but most utilities still run fragmented desktops. Prioritize OMS integration above all else — it answers the question customers ask most during the moments they're most frustrated."
      },
    ],
  },

  "natural-gas": {
    name: "Natural Gas", parent: "Utilities & Energy",
    tagline: "Gas leaks, service connections, billing, appliance programs, and safety.",
    intro: "Natural gas contact centers handle a unique duality: routine billing and service calls alongside calls that could involve life-threatening gas leaks. Every contact center agent must be prepared to switch from billing discussion to emergency response protocol in seconds. The CX challenge is maintaining urgency awareness across the entire team at all times.",
    kpis: [
      { metric: "AHT", avg: "6:30", note: "Moderate — routine calls are efficient; safety calls require protocol" },
      { metric: "FCR", avg: "68%", note: "Above utility average — fewer field-dependent issues than electric" },
      { metric: "CSAT", avg: "75", note: "Slightly above electric — fewer outages, more stable service" },
      { metric: "Containment", avg: "28%", note: "Billing and account management automatable; safety calls always human" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Gas odor/leak call response time and disposition tracking","Billing complaint analytics by season and rate structure","Energy efficiency program participation and savings analytics","Safety compliance monitoring for emergency call handling","Customer satisfaction correlated to heating season and rate changes"],
        vendors: "NICE, Verint, J.D. Power", risk: "Gas emergency response time metrics not meeting safety standards",
        stack: [{ name: "NICE CXone", role: "QA & Safety Monitoring", why: "Safety-scored QA for gas emergency calls. Verifies agents follow evacuation scripts, dispatch emergency crews, and provide correct safety instructions. Automated detection of missed safety protocols.", href: "/vendors/nice-cxone" }],
        pitfall: "Gas odor calls have a unique analytics requirement: every call must be reviewed for protocol compliance regardless of outcome. Even if the call turns out to be a false alarm, the agent must have followed the emergency script — tell the caller to evacuate, don't operate switches, don't use phones near the leak. One missed protocol on one call that turns out to be real creates a fatality and a negligence case."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Gas emergency priority routing — immediate dispatch, zero queue","Heating season routing with dedicated teams for no-heat calls","Billing vs service vs emergency routing with safety classification","Appliance repair and maintenance scheduling routing","New construction gas line installation coordination"], vendors: "Genesys, NICE CXone, Cisco", risk: "Gas odor call reaching an agent who doesn't recognize the urgency",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Emergency routing with zero-wait SLA for gas odor and leak calls. IVR keyword detection for safety language ('smell gas,' 'gas leak,' 'gas odor') bypasses the menu and routes to dispatch.", href: "/vendors/genesys" }],
        pitfall: "Gas odor calls must never wait in queue. A customer who smells gas and is told 'your estimated wait time is 4 minutes' might stay on the line — or might hang up and delay reporting a dangerous leak. Implement immediate answer for gas safety calls. If no agent is available, the IVR should provide safety instructions (leave the area, don't use switches) and dispatch automatically based on the caller's address."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Emergency gas safety messaging with evacuation instructions","Proactive cold weather advisories and heating assistance information","Self-service bill payment and payment arrangement portal","Appliance rebate and energy efficiency program enrollment","Construction and new service connection status tracking"], vendors: "Kubra, Ada, utility portals", risk: "Gas emergency instructions buried in a chatbot flow instead of prominently displayed",
        stack: [{ name: "Kubra", role: "Utility Communications", why: "Proactive winter heating advisories, bill notifications, and emergency communications. Gas utilities need proactive communication during cold snaps when demand surges and service interruptions are possible.", href: "/vendors" }],
        pitfall: "Gas utilities must ensure that 'report a gas leak' is the most visible, most accessible action on every digital channel — website, app, IVR, chat. It should never be more than one click/tap/press away. If a customer has to navigate through a billing menu to find the emergency option, the design has failed a safety obligation."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Gas emergency triage bots providing immediate safety instructions","Billing and payment bots for routine account management","Appliance repair scheduling bots","Heating assistance program eligibility bots","Service connection status bots for new construction"], vendors: "Ada, Cognigy", risk: "Bot handling a gas leak report without immediately providing evacuation instructions",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles billing, payments, and scheduling. Critical configuration: any mention of gas odor, leak, or safety immediately exits the bot and routes to a live agent with emergency dispatch capability. The bot's job is to detect safety language and escalate — not to troubleshoot.", href: "/vendors/iva" }],
        pitfall: "A gas utility chatbot must have a hard rule: any message containing safety-related keywords (gas, smell, odor, leak, hissing, explosion) immediately exits the bot flow, provides evacuation instructions, and connects to a live agent with dispatch authority. A bot that says 'I'm sorry, I didn't understand that. Can you rephrase?' in response to 'I smell gas in my kitchen' is a safety failure. Test this scenario monthly."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Pipeline safety compliance (PHMSA/49 CFR 192) for emergency response","PUC disconnection rules with heating season protections","Medical baseline and life support protections for gas heating","Carbon monoxide safety protocols for gas appliance complaints","CARE/LIHEAP payment assistance eligibility and enrollment"], vendors: "PUC compliance, PHMSA", risk: "Emergency response time exceeding pipeline safety regulatory requirements",
        stack: [{ name: "Regulatory compliance systems", role: "Safety & PUC", why: "PHMSA requires gas utilities to respond to gas odor reports within 60 minutes for critical situations. PUC rules govern disconnection, payment assistance, and service quality. Both are non-negotiable.", href: "/vendors" }],
        pitfall: "PHMSA regulations require gas utilities to respond to emergency reports within specific timeframes — typically 60 minutes. The clock starts when the customer calls, not when the crew arrives. If your contact center takes 10 minutes to process the call and dispatch, you've consumed 17% of the response window before a truck moves. Streamline the FNOL-to-dispatch workflow to under 3 minutes."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Gas emergency dispatch workflow — report, triage, dispatch, investigate, resolve","Service connection/disconnection workflow with safety inspection","Heating season no-heat emergency workflow with priority dispatch","Appliance rebate and energy efficiency program enrollment workflow","New construction gas line request and installation scheduling"], vendors: "Oracle Utilities, SAP IS-U, ServiceNow", risk: "No-heat emergency during winter not receiving priority treatment",
        stack: [{ name: "Oracle Utilities", role: "CIS & Operations", why: "Customer billing, service management, and field dispatch for gas operations. Emergency work order creation and priority dispatch integrated with the CIS.", href: "/vendors" }],
        pitfall: "No-heat calls during winter are the gas utility equivalent of power outage calls — the customer has no heating in freezing temperatures. Unlike electric outages (which are network-wide), no-heat calls are usually individual service issues. Each one requires individual diagnosis — is it the meter, the regulator, the pilot light, or an appliance? Build a no-heat triage workflow that dispatches based on symptom, not just a generic service call."
      },
      { layer: 1, name: "Data Access", capabilities: ["CIS — customer account, billing, payment, and rate information","Gas operations system — meter status, pressure, and service line data","Field service management — crew dispatch, work orders, and completion","SCADA — real-time pipeline pressure and flow monitoring","Emergency response database — open investigations, evacuations, and road closures"], vendors: "Oracle CC&B, SAP IS-U, SCADA systems, OSIsoft", risk: "Agent unable to see whether a gas emergency has already been reported for the caller's area",
        stack: [{ name: "Oracle CC&B", role: "CIS", why: "Customer account and billing data. The foundation for every non-emergency gas utility interaction.", href: "/vendors" }, { name: "SCADA integration", role: "Pipeline Operations", why: "Real-time pipeline pressure and flow data. When multiple customers in an area report gas odor, SCADA data can confirm or rule out a pipeline issue — informing whether the response is individual service line or main break.", href: "/vendors" }],
        pitfall: "Gas utility agents need to know if other customers in the same area have already reported a gas odor — because multiple reports from the same area indicate a main break rather than an individual service line issue. A main break requires a different response: more crews, potential evacuation, and coordination with fire department. Build a geographic clustering alert that flags when 2+ gas reports come from the same area within 30 minutes."
      },
    ],
  },

  "water": {
    name: "Water & Wastewater", parent: "Utilities & Energy",
    tagline: "Billing, service quality, conservation, main breaks, and boil-water advisories.",
    intro: "Water utility contact centers handle an essential service with unique public health implications. A boil-water advisory, a main break, or a contamination event creates immediate community concern that goes beyond customer service — it's public health communication. The CX challenge is managing routine billing and service alongside emergency public health messaging.",
    kpis: [
      { metric: "AHT", avg: "5:30", note: "Shorter — simpler billing and fewer rate components than electric" },
      { metric: "FCR", avg: "70%", note: "Above utility average — fewer field-dependent resolutions" },
      { metric: "CSAT", avg: "74", note: "Slightly above average — water is perceived as more essential, less frustrating" },
      { metric: "Containment", avg: "30%", note: "Billing and account changes automatable; water quality requires humans" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Water quality complaint tracking and geographic clustering","Bill complaint analytics correlated to consumption patterns and rate changes","Conservation program participation and water savings tracking","Main break response time and customer communication effectiveness","Public health advisory communication reach and engagement"], vendors: "NICE, J.D. Power, custom BI", risk: "Water quality complaints clustering without public health investigation trigger",
        stack: [{ name: "NICE CXone", role: "QA & Analytics", why: "Geographic clustering of water quality complaints — when 5+ customers in the same area report discolored or odorous water, that's a potential public health event, not 5 individual complaints.", href: "/vendors/nice-cxone" }],
        pitfall: "Water quality complaints must be tracked geographically, not individually. Five customers calling independently about 'brown water' from the same neighborhood isn't five billing issues — it's a potential main break, flushing event, or contamination that requires operations and potentially health department notification. Build geographic complaint clustering into your analytics."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Water emergency routing — main breaks, contamination, and flooding","Water quality complaint routing to operations with sample request","High-consumption alert routing for potential leak investigation","Conservation violation routing during drought restrictions","Boil-water advisory routing with public health messaging"], vendors: "Genesys, NICE CXone, Cisco", risk: "Water contamination report treated as routine complaint",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Emergency routing for water main breaks and contamination reports. Geographic caller identification matches complaints to known infrastructure issues.", href: "/vendors/genesys" }],
        pitfall: "Boil-water advisories require mass outbound communication — every customer in the affected area must be notified. Most water utilities have the outbound notification system but don't have the inbound capacity for the resulting call surge. When 10,000 customers receive a boil-water advisory, 2,000 will call with questions. Staff for the inbound surge, not just the outbound notification."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Boil-water advisory notifications via all available channels","Water quality report sharing with customers requesting their water test results","Conservation program enrollment and rebate tracking","Self-service bill payment and usage monitoring","Main break status updates with restoration timeline"], vendors: "Kubra, custom portals, Ada", risk: "Boil-water advisory reaching only 60% of affected customers",
        stack: [{ name: "Kubra", role: "Utility Communications", why: "Mass notification for water advisories and emergencies. Multi-channel delivery ensuring maximum reach for public health communications.", href: "/vendors" }],
        pitfall: "Water utilities often have the worst customer contact data of any utility type — many customers are renters whose landlord pays the water bill. During a boil-water advisory, the utility can notify the account holder (landlord) but not the resident (tenant) who actually drinks the water. Build a resident notification program that captures contact information for occupants, not just account holders."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Water usage analysis bots identifying potential leaks from consumption spikes","Billing and payment bots for routine account management","Conservation program eligibility bots","Service connection/disconnection scheduling bots","Water quality FAQ bots with appropriate escalation for concerns"], vendors: "Ada, basic IVR", risk: "Bot dismissing a water quality concern that indicates contamination",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles billing, payments, and conservation program enrollment. Routes all water quality complaints to human agents — water quality is a public health concern that bots should never attempt to resolve.", href: "/vendors/iva" }],
        pitfall: "Water quality bots must never reassure a customer that their water is safe. A bot that says 'your water meets all EPA standards' in response to 'my water is brown' is providing health assurance it's not qualified to give. Route every water quality concern to a human agent who can dispatch a sample collection and provide accurate information based on the specific complaint and location."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Safe Drinking Water Act compliance for water quality communication","PUC/water board disconnection and affordability rules","Conservation restriction enforcement during drought declarations","Lead and Copper Rule compliance for customer notification","Cross-connection and backflow prevention program compliance"], vendors: "EPA compliance, state water boards", risk: "Lead notification non-compliance creating public health and legal exposure",
        stack: [{ name: "Regulatory compliance", role: "EPA & State", why: "EPA Lead and Copper Rule revisions require proactive notification to customers with lead service lines. Water utilities must identify, notify, and track these customers — a contact center function.", href: "/vendors" }],
        pitfall: "The revised Lead and Copper Rule (effective 2024) requires water utilities to inventory lead service lines and notify affected customers. Your contact center will receive calls from concerned customers asking 'do I have a lead pipe?' Agents must have access to the service line inventory and provide accurate, non-alarming information. This is a new contact driver that many water utilities haven't staffed or trained for."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Water main break response workflow — report, dispatch, isolate, repair, flush, notify","Service connection/disconnection workflow with meter installation","Leak investigation workflow triggered by consumption spike analysis","Water quality investigation workflow with sample collection and lab testing","Conservation violation workflow with warning and enforcement escalation"], vendors: "Oracle Utilities, SAP, Sensus, Itron", risk: "Main break repair completing without customer restoration notification",
        stack: [{ name: "Oracle Utilities", role: "CIS & Operations", why: "Customer billing, service management, and work order dispatch. Water-specific modules handle consumption analysis, leak detection triggers, and conservation tracking.", href: "/vendors" }],
        pitfall: "Water main breaks require a multi-step customer communication workflow: initial advisory (water service disrupted), updates (crew on site, repair in progress), service restoration (water back on), and quality advisory (flush lines before drinking). Most water utilities communicate steps 1 and 4 but skip steps 2 and 3 — the hours when customers are most anxious. Automate notifications at every stage."
      },
      { layer: 1, name: "Data Access", capabilities: ["CIS — customer account, billing, consumption history","AMI/smart meter data — real-time water consumption and leak detection","GIS — water main mapping, service line inventory, valve locations","SCADA — real-time pressure, flow, and treatment plant data","Water quality database — sample results, compliance status, and advisories"], vendors: "Oracle CC&B, Sensus, Itron, ESRI", risk: "Agent unable to see consumption data to diagnose high-bill or leak complaints",
        stack: [{ name: "Oracle CC&B", role: "CIS", why: "Customer billing and service management. Consumption history for high-bill investigations. Service line records for lead pipe inquiries.", href: "/vendors" }, { name: "Sensus / Itron", role: "AMI & Metering", why: "Smart water meter data with hourly consumption. Enables leak detection — continuous flow at 2am indicates a running toilet or pipe leak. Agents can show customers their usage pattern to explain high bills.", href: "/vendors" }],
        pitfall: "Smart water meters generate leak alerts, but most water utilities don't have a workflow to communicate them to customers proactively. A meter that shows continuous flow for 72 hours almost certainly indicates a leak — which is costing the customer money and wasting water. Proactive leak notification ('our meter indicates you may have a leak — here's how to check') prevents the high-bill complaint call and demonstrates value. The data exists; the communication workflow usually doesn't."
      },
    ],
  },

  "municipal-coop": {
    name: "Municipal & Co-Op Utilities", parent: "Utilities & Energy",
    tagline: "Community-owned service with direct accountability and political visibility.",
    intro: "Municipal and co-operative utility contact centers serve communities that own the utility. City council members, board directors, and community leaders are both governance and customers. The CX challenge is providing professional, consistent service with smaller teams while navigating the political visibility that comes with community ownership.",
    kpis: [
      { metric: "AHT", avg: "6:00", note: "Moderate — community expectations create longer, more personal interactions" },
      { metric: "FCR", avg: "72%", note: "Above average — smaller scale and local knowledge improve resolution" },
      { metric: "CSAT", avg: "78", note: "Higher than IOUs — community ownership creates stronger relationship" },
      { metric: "Containment", avg: "20%", note: "Lower — community expects personal service, not automation" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Community satisfaction surveys tied to board/council reporting","Rate impact communication effectiveness during rate case proceedings","Outage response benchmarking against peer municipal/co-op utilities","Budget impact analytics connecting contact center costs to rate requirements","Community engagement scoring beyond traditional CX metrics"],
        vendors: "NICE, Qualtrics, simple BI", risk: "Board/council receiving customer complaints without contact center context",
        stack: [{ name: "NICE CXone", role: "Right-Sized Analytics", why: "Modular analytics that scales for 10-50 agent municipal operations. Recording, QA, and basic reporting without the enterprise complexity. Cloud-native means no IT infrastructure investment.", href: "/vendors/nice-cxone" }],
        pitfall: "Municipal utility boards and co-op board members receive customer complaints directly — at public meetings, in the grocery store, at church. These complaints bypass the contact center entirely. Build a complaint integration process where board-received complaints are logged in the same system as contact center complaints. Without this, the board sees a distorted view of service quality based on the loudest constituents."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Emergency routing for outage and safety with 24/7 coverage","Community leader routing for council/board members calling about constituent issues","Small-team queue management balancing multi-skill with personalization","After-hours answering service integration with emergency dispatch","Seasonal routing for rate case hearing periods and budget discussions"], vendors: "NICE CXone, 8x8, RingCentral", risk: "After-hours emergency reaching voicemail instead of dispatch",
        stack: [{ name: "8x8", role: "UCaaS/CCaaS", why: "Right-sized for municipal utilities with 5-30 agents. Phone, contact center, and collaboration on one platform. Low cost, easy management, no dedicated IT required.", href: "/vendors" }],
        pitfall: "Small municipal utilities often use answering services for after-hours emergency coverage. The handoff from answering service to utility dispatch is where emergencies get delayed. A customer reports a downed power line at 9pm; the answering service takes a message; the message reaches dispatch at 9:45pm. That's 45 minutes lost. Implement direct dispatch capability for after-hours services — not message-taking."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Community notification for planned outages and rate changes","Self-service bill payment through community-branded portal","Rate case communication with public hearing schedules and testimony","Energy efficiency and rebate program promotion","Community event and program communication"], vendors: "Kubra, simple portals, Ada", risk: "Rate increase communications feeling corporate instead of community-appropriate",
        stack: [{ name: "Kubra", role: "Utility Communications", why: "Bill presentment, payment processing, and notifications scaled for municipal utilities. Community-branded without enterprise complexity.", href: "/vendors" }],
        pitfall: "Rate increase communications at municipal utilities carry political weight that IOU communications don't. An IOU sends a rate increase notice; a municipal utility sends a rate increase notice that becomes a city council agenda item. Frame rate communications with community context — 'this increase funds the water main replacement on Oak Street that the community prioritized' — rather than regulatory language."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Bill payment and account balance bots","Outage status bots with local context","Service connection/disconnection scheduling bots","Rate and program information bots","Office hours and contact information bots"], vendors: "Ada, simple IVR", risk: "Bot interactions feeling impersonal for a community-owned utility",
        stack: [{ name: "Ada / simple IVR", role: "Basic Automation", why: "After-hours self-service for payments, outage reporting, and account balance. Keep daytime interactions human — community utility customers expect to reach a person they might see at the hardware store.", href: "/vendors/iva" }],
        pitfall: "Municipal and co-op utility customers have a fundamentally different relationship with their utility than IOU customers. They're members or constituents, not just customers. A bot that says 'your call is important to us' feels corporate; a person who says 'good morning, this is Sarah at Springfield Electric, how can I help?' feels community. Deploy automation for after-hours and overflow; keep daytime interactions human and personal."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["Municipal code and ordinance compliance for utility operations","Board/council-approved rate and policy enforcement","State PUC or PSC compliance (varies by state for municipals)","Open records and transparency requirements for public entities","Community benefit program eligibility and enrollment compliance"], vendors: "Municipal law, state PUC", risk: "Operating under IOU regulations when municipal exemptions apply (or vice versa)",
        stack: [{ name: "Local regulatory", role: "Municipal Compliance", why: "Municipal utilities may be regulated by the state PUC, the city council, or both — it varies by state and municipality. Your compliance framework must match your specific governance structure.", href: "/vendors" }],
        pitfall: "Municipal utilities face open records requirements that IOUs don't. Customer complaint records, call recordings, and contact center performance data may be subject to public records requests. Train agents with the awareness that their calls could become public record. This isn't a warning — it's a quality motivator."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Service start/stop workflow matching community-specific procedures","Emergency response workflow with local crew coordination","Rate change implementation workflow with community notification","Budget and capital project communication workflow","Community program enrollment and participation tracking"], vendors: "Oracle CC&B, NISC, Cayenta, simple systems", risk: "Community-specific procedures not documented in the workflow system",
        stack: [{ name: "NISC", role: "Cooperative CIS", why: "Purpose-built for electric cooperatives and municipal utilities. Billing, accounting, and customer service on one platform. Designed for the scale and governance model of community-owned utilities.", href: "/vendors" }, { name: "Cayenta (Harris)", role: "Municipal CIS", why: "Utility billing and customer service for municipal utilities. Handles the combined utility billing (electric + water + sewer + trash) common in municipal operations.", href: "/vendors" }],
        pitfall: "Municipal utilities often serve multiple services — electric, water, sewer, and sometimes trash — on one bill. A customer calling about a high bill may be confused about which service caused the increase. Agents need to quickly break down the bill by service and identify which component changed. Combined billing creates combined confusion — train agents on all services, not just one."
      },
      { layer: 1, name: "Data Access", capabilities: ["CIS — customer account across all utility services (electric, water, sewer)","SCADA — real-time system monitoring for generation, distribution, and treatment","GIS — local infrastructure mapping for outage and service territory","Work management — crew scheduling, equipment, and project tracking","Board/council data — approved rates, policies, and capital budgets"], vendors: "NISC, Cayenta, Oracle CC&B, ESRI", risk: "Combined billing data not showing which service drives the complaint",
        stack: [{ name: "NISC", role: "CIS", why: "Dominant in electric cooperatives. Combined billing, member management, and engineering data. Designed for the community utility model.", href: "/vendors" }, { name: "Cayenta", role: "CIS", why: "Municipal utility billing for combined services. Integrates with municipal financial systems for budget reporting and rate case support.", href: "/vendors" }],
        pitfall: "Municipal and co-op utilities often have the oldest infrastructure and the smallest IT budgets. The CIS may be 15-20 years old with limited API capability. Modernizing to NISC or Cayenta is a multi-year project. In the meantime, invest in the agent desktop — even if the underlying CIS is old, a modern agent interface that aggregates CIS, outage, and meter data improves CX without replacing the core system."
      },
    ],
  },

  "renewable-der": {
    name: "Renewable Energy & DER", parent: "Utilities & Energy",
    tagline: "Solar interconnection, battery storage, EV charging, net metering, and distributed energy.",
    intro: "Renewable energy and DER contact centers support the fastest-evolving segment of the utility industry. Customers installing solar panels, battery storage, and EV chargers have technical questions that traditional utility agents aren't trained to answer. The CX challenge is supporting a technically sophisticated customer base navigating interconnection, net metering, and rate optimization — subjects most utility contact centers are unprepared for.",
    kpis: [
      { metric: "AHT", avg: "11:00", note: "Longest in utilities — interconnection and net metering are technically complex" },
      { metric: "FCR", avg: "45%", note: "Very low — interconnection requires engineering review and multi-step approval" },
      { metric: "CSAT", avg: "68", note: "Below average — slow interconnection timelines frustrate solar adopters" },
      { metric: "Containment", avg: "15%", note: "Low — technical complexity requires human expertise" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Solar interconnection timeline tracking against regulatory requirements","Net metering credit accuracy and billing complaint analytics","DER program enrollment and participation analytics","EV charging program adoption and infrastructure utilization","Customer education effectiveness for TOU rates and demand management"],
        vendors: "Custom analytics, Salesforce", risk: "Interconnection delays creating regulatory complaints and solar industry backlash",
        stack: [{ name: "Salesforce Energy & Utilities Cloud", role: "DER CRM", why: "Customer relationship management with DER-specific data objects — solar installations, battery systems, EV accounts, and net metering credits. The CRM layer connecting renewable program data to the contact center.", href: "/vendors/ccaas" }],
        pitfall: "Interconnection timeline is the #1 satisfaction driver for renewable energy customers — and most utilities can't tell customers where their application stands. Build a customer-facing interconnection tracker showing: application received → engineering review → inspection scheduled → meter exchange → interconnected. Each step visible with status and estimated timeline. Without this, every solar customer calls weekly to ask 'where's my interconnection?'"
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Solar interconnection routing to technically trained DER specialists","Net metering billing routing to agents who understand credit calculations","EV charging program routing for residential and commercial programs","Battery storage and demand response program routing","Rate comparison routing for customers evaluating TOU and EV rates"], vendors: "Genesys, NICE CXone", risk: "Solar customer reaching a general agent who can't explain net metering",
        stack: [{ name: "Genesys Cloud", role: "CCaaS", why: "Skills-based routing matching DER inquiries to agents trained on solar interconnection, net metering, and EV rates. These are specialized topics that general utility agents can't handle.", href: "/vendors/genesys" }],
        pitfall: "DER inquiries require a different agent profile than traditional utility calls. A general billing agent can explain a tiered rate structure; a DER agent must explain net metering credits, time-of-use optimization for solar + battery, and interconnection engineering requirements. Staff a dedicated DER team with technical training — don't force general agents to handle these calls."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Solar interconnection application portal with status tracking","Net metering credit visibility in billing portal","EV charging program enrollment and charger rebate tracking","Rate comparison tools for DER customers evaluating TOU options","Educational content on solar, storage, and demand management"], vendors: "Custom DER portals, Ada, Bidgely", risk: "Interconnection applicants with no visibility into their application status",
        stack: [{ name: "Custom DER portal", role: "Interconnection Tracking", why: "Most utilities build custom interconnection portals because no off-the-shelf product handles the complexity of engineering review, inspection scheduling, and meter exchange coordination. The portal IS the CX for solar customers.", href: "/vendors" }, { name: "Bidgely", role: "Energy Analytics", why: "Disaggregated energy analysis showing DER customers their solar production, battery performance, grid consumption, and net metering credits. Turns 'why is my bill still high?' into a self-service discovery.", href: "/vendors" }],
        pitfall: "DER customers are more digitally sophisticated than average utility customers — they researched solar panels, calculated ROI, and chose an installer. They expect a digital-first experience with real-time status tracking. Most utility interconnection processes are manual (engineer reviews drawings, schedules inspection, processes paperwork). The gap between the customer's digital expectation and the utility's manual process creates the frustration. Digitize the interconnection workflow even if the engineering review remains manual."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Interconnection application status bots","Net metering credit calculation bots","EV rate comparison bots","Solar production and consumption analysis bots","Program eligibility bots for rebates and incentives"], vendors: "Ada, custom bots", risk: "Bot providing incorrect net metering credit information",
        stack: [{ name: "Ada", role: "AI Agent", why: "Handles application status, program eligibility, and basic rate comparison. Routes technical interconnection and net metering questions to DER specialists.", href: "/vendors/iva" }],
        pitfall: "Net metering calculations vary by state, utility, and rate schedule — monthly vs annual true-up, retail vs avoided-cost credit, TOU vs flat rate crediting. A bot that says 'you'll receive a credit for your excess solar production' without specifying the credit rate, timing, and true-up period creates billing disputes. Either provide exact, real-time credit information or route to a specialist."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["State interconnection standards and timeline compliance","Net metering policy enforcement by jurisdiction","DER program terms and conditions transparency","EV charging rate and infrastructure compliance","Rate case implications for DER program costs and cross-subsidization"], vendors: "State PUC, custom compliance", risk: "Interconnection timeline violations creating state regulatory complaints",
        stack: [{ name: "State PUC compliance", role: "Regulatory", why: "Interconnection timelines are regulated — many states require utilities to complete residential solar interconnection within 20-30 business days. Exceeding these timelines creates PUC complaints. Track and enforce regulatory timelines.", href: "/vendors" }],
        pitfall: "Net metering policies are changing rapidly — many states are revising net metering from retail-rate crediting to lower rates, adding demand charges for solar customers, or transitioning to 'net billing.' Your contact center agents will receive calls from angry solar customers who were promised one rate structure and are now receiving another. Train agents on the current policy, the transition rules, and the grandfather provisions. This is an active area of regulatory change that generates intense customer emotion."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Solar interconnection application workflow — submit, review, approve, inspect, connect","Net metering enrollment and billing configuration workflow","EV charging program enrollment with equipment rebate processing","Battery storage and demand response program enrollment workflow","Rate schedule change workflow for DER customers switching to TOU"], vendors: "Custom DER systems, Salesforce, Oracle Utilities", risk: "Interconnection application stuck in engineering review for 60+ days",
        stack: [{ name: "Custom interconnection system", role: "DER Operations", why: "Most utilities build or buy interconnection management systems (PowerClerk, Salesforce custom) because their CIS wasn't designed for DER. Application intake, engineering review, inspection scheduling, and meter exchange in one workflow.", href: "/vendors" }, { name: "PowerClerk (Clean Power Research)", role: "Interconnection Platform", why: "Purpose-built interconnection management for utilities. Application processing, engineering review, and program management for solar, storage, and EV. Widely adopted by IOUs.", href: "/vendors" }],
        pitfall: "Interconnection applications get stuck at engineering review because the review queue is first-in-first-out regardless of complexity. A simple 7kW residential rooftop and a complex 500kW commercial installation with battery storage wait in the same queue. Implement complexity-based triage: simple residential interconnections should be fast-tracked with automated review; complex projects should be routed to senior engineers with appropriate timelines."
      },
      { layer: 1, name: "Data Access", capabilities: ["Interconnection management system (application status, engineering review, inspection)","CIS with DER billing — net metering credits, TOU rates, demand charges","AMI/smart meter data — solar production, consumption, and export measurement","GIS — grid capacity, transformer loading, and hosting capacity by circuit","Program management database — rebates, incentives, and participation tracking"], vendors: "PowerClerk, Oracle Utilities, Itron, ESRI, Salesforce", risk: "Agent unable to see solar production data alongside consumption data",
        stack: [{ name: "PowerClerk", role: "Interconnection Data", why: "Application status, engineering review results, and inspection records. The data source for every 'where's my solar interconnection?' call.", href: "/vendors" }, { name: "Itron / AMI", role: "Meter Data", why: "Smart meter data showing both consumption and solar export. When a solar customer asks 'why is my bill still high?' the answer is in the interval data — consumption patterns, production timing, and net metering credit calculation.", href: "/vendors" }],
        pitfall: "DER customers need to see their solar production and grid consumption side by side to understand their bill. Most utility bill presentment shows net consumption but not the components — how much was produced, how much was consumed, how much was exported, and how much credit was applied. Build a DER-specific bill view that shows all four components. Without it, every solar customer's first bill generates a confused call."
      },
    ],
  },

  "energy-retail": {
    name: "Energy Retail / Competitive Supply", parent: "Utilities & Energy",
    tagline: "Plan selection, rate comparison, contract management, and switching.",
    intro: "Competitive energy retail contact centers operate in deregulated markets where customers choose their electricity or gas supplier. Unlike monopoly utilities, competitive retailers can lose customers to competitors overnight. The CX challenge is combining the service reliability expectations of a utility with the sales and retention urgency of a competitive business.",
    kpis: [
      { metric: "AHT", avg: "5:30", note: "Shorter — rate comparison and plan selection are focused conversations" },
      { metric: "FCR", avg: "75%", note: "Above average — most interactions are plan-related and self-contained" },
      { metric: "CSAT", avg: "70", note: "Below average — rate confusion and contract terms create frustration" },
      { metric: "Churn", avg: "25%", note: "High — competitive switching is easy in deregulated markets" },
    ],
    layers: [
      { layer: 7, name: "Analytics & Governance", capabilities: ["Churn prediction correlated to rate competitiveness and contract timing","Enrollment conversion analytics by channel, offer, and customer segment","Retention offer effectiveness — which offers save which segments","Regulatory compliance monitoring for marketing and enrollment practices","Competitive rate monitoring and market position analytics"],
        vendors: "NICE, custom analytics, Salesforce", risk: "Churn accelerating without visibility into competitive rate positioning",
        stack: [{ name: "Custom BI", role: "Market Analytics", why: "Competitive energy retail requires market-specific analytics — rate comparison, margin analysis, and churn prediction tied to contract expiration dates. Standard utility analytics don't cover competitive dynamics.", href: "/vendors" }],
        pitfall: "Energy retailers track churn rate but not churn timing. Most churn happens at contract expiration — the customer's fixed rate ends, they receive a variable-rate bill that's 40% higher, and they switch to a competitor. Proactive renewal outreach 60-90 days before contract expiration with a competitive offer retains 30-40% of at-risk customers. Reactive outreach (after the first variable-rate bill) retains less than 10%."
      },
      { layer: 6, name: "Routing & Orchestration", capabilities: ["Sales vs service routing separating new enrollment from existing customers","Retention routing for customers calling to switch or cancel","Contract renewal routing to agents with re-enrollment authority","Rate comparison routing matching callers to agents who can explain options","Regulatory complaint routing for enrollment and billing disputes"], vendors: "Genesys, NICE CXone, Five9", risk: "Retention-eligible callers reaching sales agents who push new offers instead of addressing concerns",
        stack: [{ name: "Five9", role: "CCaaS", why: "Strong for competitive retail operations with mixed inbound/outbound. Sales dialer for acquisition combined with service routing for existing customers. Good for 50-300 agent operations.", href: "/vendors/five9" }],
        pitfall: "Competitive retailers often combine sales and service in the same contact center — which creates role confusion. A sales agent handling a billing complaint will try to upsell; a service agent handling a retention call won't have offer authority. Separate sales, service, and retention functions with different routing, training, and performance metrics."
      },
      { layer: 5, name: "Conversation Management", capabilities: ["Rate comparison tools showing current plan vs available alternatives","Contract renewal communications with competitive offer presentation","Usage-based plan recommendation using smart meter data","Self-service enrollment and plan switching portal","Regulatory disclosure delivery for TPV and enrollment verification"], vendors: "Custom portals, Ada, Klaviyo", risk: "Rate comparison tools not reflecting actual customer usage patterns",
        stack: [{ name: "Custom enrollment portal", role: "Sales & Service", why: "Competitive retailers live or die by their enrollment experience. Rate comparison, plan selection, and contract execution must be frictionless. Most build proprietary portals because the enrollment experience IS the brand.", href: "/vendors" }],
        pitfall: "Rate comparison tools that show 'estimated monthly cost' based on average usage are misleading. A customer who uses 2,000 kWh in summer and 800 kWh in winter gets a very different bill from a flat-rate plan vs a tiered plan. Use actual historical usage data (from smart meters or utility data exchange) to show the customer their real cost under each plan option. Generic estimates create post-enrollment surprise bills."
      },
      { layer: 4, name: "Reasoning & Planning", capabilities: ["Rate comparison bots using customer usage data","Plan enrollment bots with contract terms and disclosure delivery","Account management bots for payment and billing inquiries","Contract renewal bots with retention offer presentation","Usage analysis bots helping customers optimize their rate plan"], vendors: "Ada, custom bots", risk: "Bot enrolling a customer in a plan that doesn't match their usage pattern",
        stack: [{ name: "Ada", role: "AI Agent", why: "Rate comparison, plan enrollment, and account management. Routes retention conversations to human agents with authority and offer flexibility.", href: "/vendors/iva" }],
        pitfall: "Enrollment bots must deliver regulatory disclosures — many deregulated markets require Third Party Verification (TPV) confirming the customer understands the rate, contract term, and cancellation fee. A bot that enrolls a customer without proper verification creates a regulatory violation. Build TPV-compliant enrollment flows with recorded consent, not just a 'I agree' checkbox."
      },
      { layer: 3, name: "Policy & Guardrails", capabilities: ["PUC/PSC marketing and enrollment practice compliance","Third Party Verification (TPV) for customer enrollment","Slamming and cramming prevention controls","Contract term and early termination fee disclosure requirements","Do Not Call list and TCPA compliance for outbound acquisition"], vendors: "PUC compliance, custom regulatory", risk: "Slamming complaint — customer enrolled without proper consent",
        stack: [{ name: "PUC compliance systems", role: "Regulatory", why: "Deregulated energy markets have strict enrollment rules — TPV, cooling-off periods, and disclosure requirements. Non-compliance results in PUC fines, enrollment reversals, and market suspension.", href: "/vendors" }],
        pitfall: "Slamming (switching a customer's energy supplier without consent) is the most severe regulatory violation in competitive energy retail — it can result in market suspension and criminal penalties. Your enrollment verification process must be bulletproof: recorded TPV, written confirmation, and a cooling-off period. If your sales team is pressured to hit enrollment targets, the temptation to cut verification corners increases. Audit TPV recordings monthly."
      },
      { layer: 2, name: "Workflow Execution", capabilities: ["Customer enrollment workflow with rate selection, TPV, and utility notification","Contract renewal workflow with usage analysis and competitive offer","Plan switch workflow with prorated billing and disclosure","Cancellation workflow with early termination fee calculation","Win-back workflow for recently churned customers"], vendors: "Custom enrollment systems, Salesforce", risk: "Enrollment processing delay causing customer to miss the switch window",
        stack: [{ name: "Custom enrollment platform", role: "Retail Operations", why: "Enrollment processing, utility data exchange (EDI), and customer billing. Most competitive retailers build proprietary systems because the enrollment-to-billing pipeline is their core operational capability.", href: "/vendors" }],
        pitfall: "Enrollment processing depends on data exchange with the local utility (EDI transactions). Processing delays — typically 1-2 billing cycles — create a gap where the customer is enrolled but still receiving bills from their previous supplier. Explain the transition timeline during enrollment: 'Your first bill from us will arrive in approximately 6-8 weeks.' Customers who don't understand the timeline call repeatedly during the gap."
      },
      { layer: 1, name: "Data Access", capabilities: ["Enrollment and customer management system (active customers, contracts, rates)","Utility data exchange (EDI) for meter reads, usage, and billing data","Rate management with current plans, pricing, and competitive intelligence","CRM with customer acquisition source, channel, and campaign data","Payment processing and billing system"], vendors: "Custom retail platforms, Salesforce, EDI providers", risk: "Customer usage data from the utility arriving late or inaccurately",
        stack: [{ name: "Custom retail platform", role: "Core Operations", why: "Enrollment, billing, and customer management purpose-built for competitive retail. Integrates with utility EDI for usage data and settlement.", href: "/vendors" }, { name: "Salesforce", role: "CRM", why: "Customer acquisition and retention management. Tracks enrollment source, contract terms, renewal dates, and churn risk. Essential for competitive analytics.", href: "/vendors/ccaas" }],
        pitfall: "Competitive energy retailers depend on utility-provided meter data (via EDI) for billing accuracy. If the utility sends estimated reads instead of actual reads, the retailer bills on estimates — which creates billing disputes when the actual read arrives and triggers a true-up. Monitor EDI data quality religiously. Estimated reads above 15% of total reads indicate a data quality problem that will generate customer complaints."
      },
    ],
  },
};

export const getUtilitiesSubVertical = (slug) => utilitiesSubVerticals[slug];
export const getAllUtilitiesSubVerticalSlugs = () => Object.keys(utilitiesSubVerticals);
