// Vendor data - structured for profile pages
// Each vendor has: slug, name, category, tier, scores, strengths, weaknesses, bestFit, redFlags, competitors, layers

export const vendors = {
  "genesys": {
    name: "Genesys Cloud CX",
    slug: "genesys",
    category: "Core CX Platforms (CCaaS)",
    categorySlug: "ccaas",
    segment: "Global CCaaS",
    tier: "Strategic Foundation",
    score: 94,
    website: "genesys.com",
    layers: ["5", "6", "7"],
    summary: "The strongest all-around CCaaS platform for enterprise contact centers. Deep omnichannel ACD, intent-driven routing moving toward policy-based orchestration, strong WEM suite, and a growing AI ecosystem. Genesys has the broadest functional footprint in the market and the architecture to support complex, multi-site, multi-region operations.",
    strengths: [
      "Deepest omnichannel routing engine in the market with intent and policy-based capabilities approaching true orchestration",
      "Native WEM suite (WFM, QM, coaching) that competes with standalone WEM vendors — reduces stack fragmentation",
      "Strong journey analytics and real-time dashboards with cross-channel visibility",
      "Mature API ecosystem and AppFoundry marketplace for third-party extensions",
      "Proven enterprise scalability across multi-site, multi-region, regulated deployments",
      "Active AI investment: agent assist, predictive routing, speech/text analytics, and bot platform improving rapidly",
    ],
    weaknesses: [
      "Pricing complexity — multiple SKUs, add-ons, and usage-based components make TCO difficult to predict without detailed scoping",
      "AI capabilities are strong but still modular; full orchestration-layer vision is directional, not fully delivered",
      "Legacy Genesys Engage customers face a meaningful migration lift to Cloud CX — not a simple upgrade path",
      "WEM suite is competitive but may lack the depth of NICE or Verint for organizations with advanced forecasting or QA requirements",
      "Implementation complexity for enterprise deployments still requires experienced partners and meaningful project management",
    ],
    bestFit: "Enterprise contact centers (200+ seats) with omnichannel requirements, complex routing needs, and the budget for a full-suite platform. Strongest in financial services, healthcare, telecom, and government. Organizations that want to consolidate CCaaS + WEM + analytics into fewer vendors.",
    notFit: "SMB or mid-market organizations seeking simple, fast deployment. Teams that need a lightweight digital-first solution. Organizations with primarily chat/messaging volume where a digital engagement platform would be more appropriate.",
    redFlags: [
      "Watch for bundled pricing that looks attractive at signing but escalates with usage-based overages on channels, storage, or API calls",
      "Ensure your implementation partner has specific Genesys Cloud CX experience — Genesys Engage expertise doesn't transfer cleanly",
      "The AI roadmap is ambitious; validate which capabilities are GA vs beta vs roadmap before building your business case around them",
    ],
    competitors: ["NICE CXone", "Five9", "Amazon Connect", "Talkdesk", "Cisco Webex"],
    competitiveContext: "Genesys and NICE CXone are the two strongest enterprise CCaaS platforms. Genesys has the edge in routing sophistication and native WEM integration. NICE has the edge in interaction analytics and QA depth. Five9 competes well on ease of deployment and mid-market value. Amazon Connect wins on AWS-native integration and consumption pricing. Talkdesk is catching up on AI but lacks the enterprise deployment track record.",
  },

  "nice-cxone": {
    name: "NICE CXone",
    slug: "nice-cxone",
    category: "Core CX Platforms (CCaaS)",
    categorySlug: "ccaas",
    segment: "Global CCaaS",
    tier: "Strategic Foundation",
    score: 90,
    website: "nice.com",
    layers: ["5", "6", "7"],
    summary: "The most analytically deep CCaaS platform in the market. NICE CXone combines mature omnichannel routing with the strongest interaction analytics, AI-powered QA (Enlighten), and a comprehensive WEM suite. Following the Cognigy acquisition, NICE is building toward an AI orchestration layer that could redefine how digital and voice interactions are managed.",
    strengths: [
      "Industry-leading interaction analytics — Enlighten AI provides automated QA scoring, sentiment analysis, and behavioral insights at scale",
      "Strongest WEM suite in the CCaaS market (WFM, QM, recording, coaching) — often eliminates the need for standalone WEM vendors",
      "Mature skills-based and behavioral routing with AI-enhanced decisioning",
      "Post-Cognigy acquisition positions NICE as a serious conversational AI orchestration player",
      "Deep compliance and recording capabilities suited for regulated industries",
      "Massive installed base and proven global enterprise scalability",
    ],
    weaknesses: [
      "Platform complexity — the breadth of capabilities means longer implementation timelines and steeper learning curves for admin teams",
      "Integration of Cognigy AI capabilities into the core CXone platform is still in progress — evaluate current state vs roadmap carefully",
      "Pricing tends to be premium; full-suite licensing across WEM + analytics + AI can push TCO above competitors",
      "Digital engagement capabilities are improving but historically voice-centric — pure digital-first organizations may find the UX weighted toward voice workflows",
      "Partner ecosystem for implementation is smaller than Genesys, which can limit options in some regions",
    ],
    bestFit: "Enterprise contact centers that prioritize analytics, QA automation, and workforce optimization. Strongest for financial services, insurance, healthcare, and any vertical where compliance recording and interaction analysis are critical. Organizations looking to consolidate CCaaS + WEM + analytics into a single vendor.",
    notFit: "Digital-first organizations with minimal voice volume. SMB or startup contact centers seeking fast, lightweight deployment. Teams that need maximum flexibility in best-of-breed tool selection — NICE's value proposition is strongest when you buy the full suite.",
    redFlags: [
      "Full-suite pricing can escalate quickly — model your TCO across all modules before committing, especially if you're adding Enlighten AI and advanced WEM",
      "The Cognigy integration roadmap should be validated with specific timelines and GA dates — don't buy based on acquisition announcements alone",
      "Contract terms for enterprise deals can be rigid — negotiate flexibility on seat counts and module adoption phasing",
    ],
    competitors: ["Genesys Cloud CX", "Five9", "Talkdesk", "Verint", "Calabrio"],
    competitiveContext: "NICE and Genesys are the market's two enterprise CCaaS leaders. NICE wins on analytics and QA depth. Genesys wins on routing sophistication and ecosystem breadth. Against Verint and Calabrio, NICE competes directly on WEM — and increasingly wins because WEM is embedded in the CCaaS rather than bolted on. Five9 competes on ease of deployment and mid-market pricing. Talkdesk is a credible challenger on AI but lacks NICE's analytics maturity.",
  },

  "five9": {
    name: "Five9",
    slug: "five9",
    category: "Core CX Platforms (CCaaS)",
    categorySlug: "ccaas",
    segment: "Global CCaaS",
    tier: "Strong Contender",
    score: 78,
    website: "five9.com",
    layers: ["5", "6"],
    summary: "A strong enterprise CCaaS platform that balances capability depth with implementation speed. Five9 has built a reputation for solid skills-based and AI-enhanced routing, good outbound capabilities, and a clean integration story with major CRM platforms. The AI portfolio is growing rapidly, and the platform handles the mid-market to large enterprise range well.",
    strengths: [
      "Balanced platform — strong enough for enterprise complexity, deployable fast enough for mid-market timelines",
      "Excellent outbound and blended contact capabilities — one of the best in the market for organizations with significant outbound volume",
      "Clean CRM integrations (Salesforce, ServiceNow, Zendesk) with pre-built connectors that reduce implementation lift",
      "Growing AI portfolio: IVA, agent assist, workflow automation, and analytics improving quarter over quarter",
      "Strong partner ecosystem for implementation and support across North America",
      "Proven reliability and uptime track record",
    ],
    weaknesses: [
      "WEM capabilities are functional but less mature than Genesys or NICE — complex forecasting or advanced QA scenarios may require a standalone WEM vendor",
      "Interaction analytics are improving but don't match NICE Enlighten or dedicated analytics platforms in depth",
      "International presence is growing but still behind Genesys and NICE for complex multi-region deployments",
      "AI capabilities are directionally strong but newer to market — validate production maturity for your specific use cases",
      "Digital channel depth (messaging, social, in-app) is adequate but less differentiated than digital-first platforms",
    ],
    bestFit: "Mid-market to enterprise contact centers (100–1000+ seats) that need a reliable, well-integrated CCaaS platform without the implementation complexity of Genesys or NICE. Strong for organizations with significant outbound or blended operations. Good Salesforce shops that want tight CRM integration.",
    notFit: "Organizations requiring the deepest possible analytics and QA automation (NICE is stronger). Complex multi-region deployments with local regulatory requirements (Genesys has more global infrastructure). Purely digital-first operations with minimal voice.",
    redFlags: [
      "Evaluate whether Five9's native WEM meets your forecasting and QA requirements or if you'll need to add a standalone vendor — that changes your TCO calculation",
      "AI capabilities are improving rapidly but some features are newer — ask for customer references specifically on the AI features you plan to use",
      "International deployment capabilities should be validated for your specific regions — Five9's strength is North America",
    ],
    competitors: ["Genesys Cloud CX", "NICE CXone", "Talkdesk", "Amazon Connect", "8x8"],
    competitiveContext: "Five9 sits in a strong middle position — more enterprise-capable than Talkdesk or 8x8, faster to deploy than Genesys or NICE. Against Genesys, Five9 trades routing depth for implementation speed. Against NICE, Five9 trades analytics depth for a cleaner mid-market fit. Against Amazon Connect, Five9 offers a more complete out-of-box solution versus Connect's build-it-yourself model. Against Talkdesk, Five9 has more enterprise deployment experience and a more mature outbound engine.",
  },

  "talkdesk": {
    name: "Talkdesk",
    slug: "talkdesk",
    category: "Core CX Platforms (CCaaS)",
    categorySlug: "ccaas",
    segment: "Global CCaaS",
    tier: "Strong Contender",
    score: 75,
    website: "talkdesk.com",
    layers: ["5", "6"],
    summary: "A cloud-native CCaaS platform that has invested heavily in AI and vertical-specific solutions. Talkdesk differentiates through its industry-specific Experience Clouds (Financial Services, Healthcare, Retail) and a strong app ecosystem. The platform is modern, API-first, and appeals to organizations that want a CCaaS vendor with genuine vertical depth.",
    strengths: [
      "Industry-specific Experience Clouds provide pre-built workflows, integrations, and compliance features for financial services, healthcare, and retail",
      "Strong AI investment: agent assist, virtual agents, AI trainer, and workforce management enhanced with ML",
      "Modern cloud-native architecture — clean APIs, good developer experience, and rapid feature releases",
      "AppConnect marketplace with a broad ecosystem of pre-built integrations",
      "Good UX for agent and supervisor interfaces — cleaner than many enterprise competitors",
      "Growing international presence with data residency options in multiple regions",
    ],
    weaknesses: [
      "Enterprise deployment track record is shorter than Genesys, NICE, or Five9 — validate with references at your scale and complexity",
      "WEM capabilities are growing but still maturing — advanced WFM and QA scenarios may require supplemental vendors",
      "Vertical Experience Clouds are a strong differentiator but evaluate how deep the vertical customization goes versus surface-level packaging",
      "Some AI capabilities are newer to market — distinguish between GA features and roadmap items during evaluation",
      "Outbound capabilities are less mature than Five9 for heavy outbound or blended operations",
    ],
    bestFit: "Mid-market to enterprise organizations in financial services, healthcare, or retail that want a CCaaS vendor with genuine vertical understanding. Technology-forward teams that value modern architecture, API flexibility, and rapid innovation cycles. Organizations with 100–500+ seats that want enterprise capability without enterprise implementation complexity.",
    notFit: "The largest enterprise deployments (2000+ seats) with complex multi-region requirements and deep WEM needs — Genesys or NICE may be safer at that scale. Heavy outbound operations. Organizations that need the deepest possible analytics stack built into the platform.",
    redFlags: [
      "Validate the vertical Experience Cloud depth carefully — some vertical features are more mature than others depending on the specific industry",
      "Ask for references at your specific seat count and complexity — Talkdesk's strength is mid-market and growing enterprise, not the largest deployments",
      "AI features are evolving quickly; ensure what you're buying is GA today and perform well in your environment",
    ],
    competitors: ["Genesys Cloud CX", "NICE CXone", "Five9", "Amazon Connect", "RingCentral"],
    competitiveContext: "Talkdesk's strongest position is against mid-market and growing enterprise buyers who value vertical specialization and modern architecture. Against Genesys, Talkdesk trades routing depth and global scale for vertical-specific pre-built workflows and a cleaner UX. Against NICE, Talkdesk trades analytics and WEM depth for implementation speed and developer experience. Against Five9, Talkdesk offers stronger vertical positioning but a less mature outbound engine. Against Amazon Connect, Talkdesk provides a more complete out-of-box experience versus Connect's infrastructure-level flexibility.",
  },

  "amazon-connect": {
    name: "Amazon Connect",
    slug: "amazon-connect",
    category: "Core CX Platforms (CCaaS)",
    categorySlug: "ccaas",
    segment: "Hyperscaler CCaaS",
    tier: "Strong Contender",
    score: 74,
    website: "aws.amazon.com/connect",
    layers: ["5", "6"],
    summary: "AWS's contact center platform takes a fundamentally different approach — consumption-based pricing, deep AWS service integration, and a build-it-yourself architecture that gives engineering-led organizations maximum flexibility. Connect is AI-native with strong hooks into Lex, Bedrock, and the broader AWS ML ecosystem. The tradeoff: you're assembling a contact center from infrastructure components, which means more control and more engineering lift.",
    strengths: [
      "Consumption-based pricing model (pay per minute/message) eliminates per-seat licensing — transformative economics for variable-volume operations",
      "Deep integration with AWS services: Lex (bots), Bedrock (LLMs), Lambda (serverless logic), S3 (storage), and Connect-native features like Contact Lens for analytics",
      "AI-native routing with contact flows and customer profiles that enable sophisticated personalization",
      "Infinite scalability — AWS infrastructure means no capacity planning for spikes",
      "No-code flow builder for contact routing that technical teams can iterate quickly",
      "Strong data accessibility — everything flows through AWS data services for custom analytics and ML",
    ],
    weaknesses: [
      "Requires engineering investment — this is infrastructure that your team builds on. Organizations without strong technical teams will struggle to build what they need",
      "Native WEM capabilities are limited — WFM, QM, and coaching require third-party solutions or custom builds",
      "Out-of-box reporting and dashboards are basic compared to Genesys, NICE, or Five9 — expect to build custom reporting",
      "Supervisor and QA tooling is less mature than purpose-built CCaaS platforms",
      "Professional services ecosystem for Connect is thinner than traditional CCaaS vendors — finding experienced implementation partners can be challenging in some regions",
      "Consumption pricing is attractive but unpredictable — high-volume or long-AHT operations can see costs exceed traditional per-seat models",
    ],
    bestFit: "Technology-forward organizations with strong engineering teams that are already invested in the AWS ecosystem. Variable-volume operations where consumption pricing delivers meaningful savings. Organizations building differentiated CX experiences that require custom AI/ML integration at the infrastructure level.",
    notFit: "Contact centers that need a turnkey, out-of-box solution. Organizations without dedicated engineering resources for ongoing platform development. Teams that require deep native WEM, QA automation, or supervisor tooling without building custom solutions. Operations with consistent high volume where per-seat pricing may be more predictable.",
    redFlags: [
      "Model your consumption costs carefully at realistic volumes, AHT, and growth projections — the per-minute model can surprise at scale",
      "Plan for the total build cost: Connect licensing is cheap but the engineering labor to build your contact center on it is the real investment",
      "Evaluate whether your team can sustain ongoing platform development or if you'll be dependent on external partners for every change",
    ],
    competitors: ["Genesys Cloud CX", "NICE CXone", "Five9", "Talkdesk", "Google CCAI"],
    competitiveContext: "Amazon Connect occupies a unique position — it competes on architecture flexibility and AWS ecosystem depth rather than out-of-box completeness. Against Genesys and NICE, Connect trades turnkey functionality for infrastructure-level control and consumption pricing. Against Five9 and Talkdesk, Connect appeals to a fundamentally different buyer: the CTO with engineering resources who wants to own the architecture. Against Google CCAI, Connect has the more mature contact center platform while Google has stronger conversational AI capabilities.",
  },
};

export const getVendor = (slug) => vendors[slug] || null;
export const getVendorsByCategory = (cat) => Object.values(vendors).filter(v => v.categorySlug === cat);
export const getAllVendors = () => Object.values(vendors);
export const getAllSlugs = () => Object.keys(vendors);
